### ISSUE TITLE
[feature] Implement "I don't have a wallet" UI flows

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/web3modal#1000]
### What problem does this new feature solve?

- Provides guidance to users interacting with web3modal who do not already have a wallet of their own.

### Describe the solution you'd like

- Figma: https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?node-id=3185-47113&t=BZbstyiRC1TrqUS1-0
- Add "I don't have a wallet" button to the bottom of the modal
- Implement new privacy policy / terms popup

#### Currently out of scope

- social / popular wallet view shown in the Figma

**Comment by bkrem** [comment]
cc @0xAsimetriq for context

**Comment by 0xAsimetriq** [comment]
Closing this as context around "I don't have a wallet" is changing completely in v3 / Email sign in work
