### ISSUE TITLE
[bug]  Web3Modal not working on Firefox due to incorrect Content-Security-Policy header

### ISSUE THREAD

**Issue by justraman** [WalletConnect/web3modal#1005]
### Link to minimal reproducible example

https://react-app.walletconnect.com

### Summary

Hey Guys! Thanks for the amazing library. 

We recently launched our NFT marketplace (beta.nft.io). On launch day a user reported that he could not open the WalletConnect modal on the Firefox browser. Upon inspection, I discovered that the problem was due to an incorrectly configured `Content-Security-Policy frame-ancestors` header in the library. 

`https://verify.walletconnect.com/e899c82be21d4acca2c8aec45e893598` This URL returns header `frame-ancestors http://*.localhost http://localhost`, This causes Firefox to block the library from loading due to the restrictive frame-ancestors policy. it should be `frame-ancestors *` or anything less restrictive instead.

I was able to reproduce this on the example site as well `https://react-app.walletconnect.com` , it's not working at all in Firefox. 

<img width="1728" alt="Screenshot 2023-05-04 at 7 03 18 PM" src="https://user-images.githubusercontent.com/25192346/236230290-54f78ccf-eb7c-4308-9ba0-7fb863ec867e.png">

Thank you! 

### List of related npm package versions

@web3modal/standalone

**Comment by 0xAsimetriq** [comment]
Fix is on the way with upstream package
https://github.com/WalletConnect/walletconnect-monorepo/pull/2305

**Comment by 0xAsimetriq** [comment]
@justraman @Trynight  this should now be resolved upstream (no need to change anything).
