### ISSUE TITLE
[bug] Some android devices can't scan the QR code in dark mode 

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#1007]
### Link to minimal reproducible example

https://github.com/AlphaWallet/alpha-wallet-android/issues/3089

### Summary

Taken from https://github.com/AlphaWallet/alpha-wallet-android/issues/3089

Reproduction:

- Go to https://web3modal.com/ click on Connect Wallet button
- Try to scan the QR code with on certain Android devices
- Nothing happens, the QR code just does not get scanned no matter how long I hold the camera to the code

@jakubuid Mentioned:

On some Android wallets the QR code in dark mode is not recognized by a scanner implemented with one of the popular Android lib [ZXing](https://github.com/zxing/zxing).

### List of related npm package versions

-

**Comment by Ian-Bright** [comment]
Can confirm. Metamask mobile does not work in dark mode but works in light mode

**Comment by chadyj** [comment]
@Ian-Bright Can you please let us know Metamask and Android versions?

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by boidushya** [comment]
Able to reproduce this with Samsung S22 Ultra on dark mode

Steps:

1) Go to https://v2-migration-lab.walletconnect.com/wagmi with device/browser theme set to prefer dark mode
2) Click on Connect Wallet
3) QR doesn't scan through Rainbow wallet/Trust Wallet unless brightness is dropped all the way down.

Notes:
- This issue doesn't happen with light mode for me

**Comment by jakubuid** [comment]
FYI Uniswap has its QR code in dark mode: https://interface-git-add-wc-v2-uniswap.vercel.app/#/swap
Can confirm that Metamask is not able to scan it.
MM Android build: https://app.bitrise.io/app/be69d4368ee7e86d/build/f804a7b2-ba13-4f47-a5e5-25096a178df3/artifact/9e1620b52271f6a4/p/8f5617afabfc4833dda2a985cb603bb0

**Comment by chadyj** [comment]
Closing as this will be fixed in https://github.com/WalletConnect/web3modal/issues/1069
