### ISSUE TITLE
[feature] Make --w3m-font-family work for <Web3Button />

### ISSUE THREAD

**Issue by joshlang** [WalletConnect/web3modal#1009]
### What problem does this new feature solve?

Currently, setting `--w3m-font-family` has no effect.  Web3Button is rendered with `Arial` font.

### Describe the solution you'd like

Let me use `--w3m-font-family` to set the font to whatever I want in the <Web3Button />

**Comment by 0xAsimetriq** [comment]
This is already the case i.e. here is preview of customised modal https://lab.web3modal.com/v2Customised

Are these buttons what you were referring too, or is it something else?

<img width="1512" alt="Screenshot 2023-05-09 at 09 42 58" src="https://user-images.githubusercontent.com/3154053/237015531-5f97d4d8-fb1d-4deb-8a88-ab2ac008f57f.png">

**Comment by joshlang** [comment]
Whatttttt the

Yeah.  It works perfectly.

I apologize.

![image](https://github.com/WalletConnect/web3modal/assets/39773384/623a5322-dfa7-4037-9dc4-9bec5aa229bb)

I saw this in Chrome, but didn't see this (at the bottom):
![image](https://github.com/WalletConnect/web3modal/assets/39773384/4f8ed732-1074-4f3e-b30d-182a74169179)

It *IS* showing the correct font.

Once I tried with `monospace` (which isn't such a similar font), it was obvious that it indeed does work.

Sorry for the trouble.
