### ISSUE TITLE
[feature] Expose styling options for modal overlay

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1015]
### What problem does this new feature solve?

- Expose options for overlay color / opacity (i.e. rgb / rgba / hex values etc)
- Allow to dissable overlay
- Allow to manage overlay pointer events

### Describe the solution you'd like

Add new theme variables

**Comment by lm93547** [comment]
Bumping this as I would like to be able to change the text colour independently of the accent colour.

**Comment by darrylyeo** [comment]
+1, it appears we are stuck with `background-color: rgba(0, 0, 0, 0.3);` at the moment.

<img width="1281" alt="Screen Shot 2023-06-15 at 3 15 24 PM" src="https://github.com/WalletConnect/web3modal/assets/13970789/424926e3-3d00-4e67-8b71-85fa7b1fc8b8">

Would be great to have `--w3m-overlay-background-color` and `--w3m-overlay-backdrop-filter` exposed as CSS variables.
