### ISSUE TITLE
[bug] A bug that moves to the App Store when launched on an iPhone SE

### ISSUE THREAD

**Issue by munseunggyumodurich** [WalletConnect/web3modal#1024]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

I tried to connect metaMask from the page https://web3modal.com/ to test it, but even though the app is installed, it is moved to the metaMask app installation link, and there is no response after this. It happens on my iPhone is Iphone Se and the ios version is 16.4.1(a).

### List of related npm package versions

"@wagmi/core": "^0.9.5",
"@web3modal/ethereum": "^2.1.1",
"@web3modal/html": "^2.1.1",
"web3": "^1.8.0",

**Comment by 0xAsimetriq** [comment]
This issue is on MetaMask / iOS side. They are currently using so called universal-links, while majority of other wallets use deep-links. Latter is preferable and MetaMask's next release should start supporting them, thus fixing the issue.
