### ISSUE TITLE
[feature] Improve ux of re-generating pairing when returning back to web3modal

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1025]
### What problem does this new feature solve?

At the moment, we have to re-generate pairing when returning to web3modal from a native app. There is 500ms delay here before that happens. Sometimes, however, this delay is not enough for web3modal to receive possible ACK from a session settlement. We'll likely need to increase this delay, but this creates more room for user to start interacting with web3modal i.e. `retry` button and re-using old session pairing which was already consumed.

### Describe the solution you'd like

Increase delay, but also ensure ui components like retry button are temporarily disabled until new pairing is generated. This should give web3modal more breathing room to receive ACK messages.

**Comment by emzet93** [comment]
The issues seems serious. It's often about 1 - 5 seconds delay between getting back to app and web3modal being closed and connection is established. There is no feedback on UI at all that sth is actually happening and the modal looks exactly the same as before accepting connection in wallet app, so there is pretty big chance that user will interact with modal again, by e.g. pressing "retry".

Is it possible to detect this state after accepting the connection in wallet app and show better feedback in web3modal or/and disable retry button?

**Comment by 0xAsimetriq** [comment]
@emzet93 working on this for upcoming major release, this stuff is a bit tricky, the 5s delay happens when iOS drops websocket connection in safari (because page starts being released from memory). This happens when users spend more time in the native wallet app.

Only way to update ui with new feedback when user gets back is to use focus change listeners on window / tab of the tab and applying it based on some other pre-conditions. Think we'll have good solution for this soon.

**Comment by emzet93** [comment]
@0xAsimetriq thanks for such fast reply! And it makes sense, yeah - I noticed the issue only on iOS safari or when I install it as PWA on iOS. Works instant on iOS chrome indeed.

**Comment by 0xAsimetriq** [comment]
Implemented along other improvements for this scenarion in v3 / alpha
