### ISSUE TITLE
[bug] Web3Modal encounters an initialization failure when attempting to initialize while offline.

### ISSUE THREAD

**Issue by denyshorman** [WalletConnect/web3modal#1026]
### Link to minimal reproducible example

https://stackblitz.com/edit/viem-getting-started-kdtrt9?file=index.ts

### Summary

Steps to reproduce:

```typescript
import { mainnet } from '@wagmi/chains';
import { configureChains, createConfig } from '@wagmi/core';
import { Chain, EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum';
import { Web3Modal, Web3ModalConfig } from '@web3modal/html';

function initialize(): Web3Modal {
  const chains: Chain[] = [mainnet];

  const projectId = 'YOUR_PROJECT_ID';

  const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);

  const wagmiConfig = createConfig({
    autoConnect: true,
    connectors: w3mConnectors({ projectId, version: 1, chains }),
    publicClient,
  });

  const web3ModelConfig: Web3ModalConfig = {
    projectId,
  };

  const ethereumClient = new EthereumClient(wagmiConfig, chains);

  return new Web3Modal(web3ModelConfig, ethereumClient);
}

// 1. Disable the internet connection

// 2. Initialize the web3modal
const web3Modal = initialize(); // Under the hood it fails with the `ChunkLoadError`.

// 3. Restore the connection

// 4. Open the modal
web3Modal.openModal() // modal is not opened and promise is never resolved
```

Please use the link to the reproducible example to confirm.

### List of related npm package versions

@wagmi/core: 1.0.5
@wagmi/chains: 0.2.23
@web3modal/ethereum: 2.4.1
@web3modal/html: 2.4.1
viem: 0.3.27

**Comment by 0xAsimetriq** [comment]
What would you expect to happen instead of error while initialising online? Under the hood, web3modal needs to connect to walletconnect relay and fetch data about wallets, so without internet connection it will not work in general.

**Comment by denyshorman** [comment]
Let's consider this use case:

```typescript
var web3Modal: Web3Modal;

function initializeModal() {
  console.log('before init');
  web3Modal = initialize();
  console.log('after init');
}

async function openModal() {
  console.log('before open');
  await web3Modal.openModal();
  console.log('after open');
}
```

1. User opens a website
2. User loses the internet connection
3. Being offline, user clicks the `initializeModal` button - Web3Modal object is created and returned to a client code without any exceptions (this part works as expected, even if some exceptions are thrown internally).
4. User backs online.
5. User clicks the `openModal` button

Expected behavior: the modal is opened and the console has `before open` and `after open` logs.
Actual behavior: the modal is not opened, the console has only `before open` log.

As we have seen from the behavior above, user is Online and when he/she clicks the `openModal` button, nothing happens. Besides that `await web3Modal.openModal()` neither throws an error nor completes.  
I believe this issue arises during the initialization phase due to network connection errors, and there is no existing retry mechanism in place.

**Comment by luccamordente** [comment]
I'm experiencing the same problems:
* No way to catch the load error; and 
* Trying to open the modal hangs indefinitely.

My understanding is that the load error is related to JS chunks required asynchronously in the package not able to load due to whatever reason. Without a way to catch this kind of error it becomes hard to give feedback to users.

My current workaround was to add a timeout to the `web3Modal.openModal()` call. If it takes too long I suggest the user to refresh the page. 

```ts
await withTimeout(web3Modal.openModal, 5_000, () => {
  setError('This is taking too long. Try refreshing the page.');
});

async function withTimeout(
  operation: () => Promise<void>,
  duration: number,
  onTimeout: () => void,
) {
  const timeout = setTimeout(onTimeout, duration);
  await operation();
  clearTimeout(timeout);
}
```

Not the most elegant, but at least doesn't leave users with a loading spinner.

It would be great to have a more robust process to initialize the modal and catch errors. It doesn't necessarily need to include a retry mechanism, but should allow developers to do it.

**Comment by SergeyVolynkin** [comment]
+1, same issue

**Comment by 0xAsimetriq** [comment]
Thank you for filing a feature request + more details and suggestions. Let's track this in #1344 we are definitely gonna work on improvements around bad or no network conditions in v3.

Meanwhile to unblock you, you could try something like this to reject after 5s

```ts
await Promise.race([
  modal.open(),
  new Promise(reject => setTimeout(reject, 5000))
])
```

**Comment by luccamordente** [comment]
> Thank you for filing a feature request + more details and suggestions. Let's track this in #1344 we are definitely gonna work on improvements around bad or no network conditions in v3.
> 
> Meanwhile to unblock you, you could try something like this to reject after 5s
> 
> ```ts
> await Promise.race([
>   modal.open(),
>   new Promise(reject => setTimeout(reject, 5000))
> ])
> ```

`reject` in the code above is actually the `resolve` function.

I'd recommend actually rejecting the promise instead so you can handle the race more easily:

```ts
try {
  await Promise.race([
    modal.open(),
    new Promise((_resolve, reject) => setTimeout(reject, 5000)),
  ]);
  console.log("Modal opened");
} catch (error) {
  console.log("Modal failed to open");
}
```

**Comment by 0xAsimetriq** [comment]
@luccamordente you are right, updated 👍
