### ISSUE TITLE
I have Coinbase and MetaMask on Chrome but WalletConnect only detects MetaMask

### ISSUE THREAD

**Issue by eriktoor** [WalletConnect/web3modal#1029]
**Describe the bug**
I have Coinbase and MetaMask on Chrome but WalletConnect only detects MetaMask. However if I then get it to detect Coinbase it stops detecting MetMask. 

**SDK Version (if relevant)**
 Next 13.1 
wagma ^0.12.10

**To Reproduce**
1. Click Connect Wallet
2. Wallet Connect Modal Opens 

**Expected behavior**
I expect both Coinbase and MetaMask to be detected but only MetaMask is. 

**Screenshots**

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by ganchoradkov** [comment]
Moving the issue to web3modal's repo
cc @0xAsimetriq

**Comment by 0xAsimetriq** [comment]
Having both will conflict with each outher (on extension level), as coinbase overrides metamask's `window.ethereum` flag. As of now, there is not much we can do besides showing that footer notice to users.

However WalletConnect is collaborating with major wallets and related projects on a new standard that will allow seamless multi ethereum extension support. We hope to get this approved by ethereum community as soon as possible and once it is, web3modal will implement it swiftly

https://ethereum-magicians.org/t/eip-6963-multi-injected-provider-interface-aka-mipi/14076/12
