### ISSUE TITLE
[bug] TypeError: Cannot convert a BigInt value to a number at Math.pow ()

### ISSUE THREAD

**Issue by kenmalibu** [WalletConnect/web3modal#1030]
### Link to minimal reproducible example

https://webgl.alphabettydoodles.io/

### Summary

New react app, fresh install:

npx create-react-app my-app 

npm install @web3modal/ethereum @web3modal/react wagmi viem

node -v                              
v18.16.0

App.js as per documentation:
https://docs.walletconnect.com/2.0/web3modal/react/installation#use-wagmi-hooks

Code base: https://github.com/kenmalibu/ReactWeb3Modal

Issue:

Everything works as expected in localhost development.

npm run build

No errors on build.

When running the build version, after connecting wallet, console displays the following error:

w3m-account-context.ts:64 TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at l (toHex.ts:173:21)
    at param (encodeAbiParameters.ts:211:16)
    at h (encodeAbiParameters.ts:101:12)
    at n.params (encodeAbiParameters.ts:68:25)
    at p (encodeAbiParameters.ts:43:26)
    at c (encodeFunctionData.ts:58:9)
    at readContract.ts:79:20
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    
    
  All subsequent WAGMI contract calls return a status of failure. 
  
  I have only included a fresh version here to make it easier to replicate and report. 
  
  

### List of related npm package versions

    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@web3modal/ethereum": "^2.4.1",
    "@web3modal/react": "^2.4.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "viem": "^0.3.33",
    "wagmi": "^1.0.5",
    "web-vitals": "^2.1.4"

**Comment by 0xAsimetriq** [comment]
I believe this is a known issue in wagmi -> viem, but best ask on their channels to verify, nothing within web3modal scope that we can do here I'm afraid.
