### ISSUE TITLE
Function "approve" of "erc20abi" does not work with Trust wallet browser extension

### ISSUE THREAD

**Issue by burasov-artyom** [WalletConnect/web3modal#1031]
### Link to minimal reproducible example

no

### Summary

Hello. All functions work except "approve"

My code:
```
const publicClient = usePublicClient({
  chainId: config.chainId,
});
const { data: walletClient } = useWalletClient({
  chainId: config.chainId,
});

const token0 = getContract({
  address: address,
  abi: erc20ABI,
  publicClient,
  walletClient,
});

const approveTx = await token0.write.approve({
  account: address,
  args: [addressRouter, amountInMax]
});
```

![изображение](https://github.com/wagmi-dev/wagmi/assets/47752247/d52eaac2-84c1-41f6-b156-aa068201cb53)

There are no errors in the console. I checked other dapp applications, it works correctly.

Tell me please, what could be the reason for this?

### List of related npm package versions

```
"@web3modal/ethereum": "^2.4.1",
"@web3modal/react": "^2.4.1",
"viem": "^0.3.36",
"wagmi": "^1.0.5"
```

**Comment by 0xAsimetriq** [comment]
I would suggest asking viem guys about this, they'll have more context. If it happens only in trust's extension, issue could be with their implementation as well.
