### ISSUE TITLE
[bug]  Ledger Desktop logo 404

### ISSUE THREAD

**Issue by saintmaxi** [WalletConnect/web3modal#1032]
### Link to minimal reproducible example

https://pfp.gangsterallstar.com/

### Summary

In the example, click Connect Wallet to prompt the modal to appear.

The logo for the Ledger Desktop wallet seems to be experiencing a 404 error on the fetch, causing it to display as in the attached image.

<img width="419" alt="LedgerLogo404" src="https://github.com/WalletConnect/web3modal/assets/36748278/6f054957-f6be-4a57-852f-9e28a238e867">

In the console I see the following error:
`GET https://explorer-api.walletconnect.com/v2/logo/lg/58d8f4c8-cf51-4a82-5ce5-56d8a4d24400?projectId=e8c3f6360905ea7d27c22698599cf084 404`

With the response message being `Logo not found for id: 58d8f4c8-cf51-4a82-5ce5-56d8a4d24400`.

### List of related npm package versions

@web3modal/ethereum: "2.3.6"
@web3modal/html: "^2.4.1"
@wagmi/core: "0.10.10"

**Comment by 0xAsimetriq** [comment]
This was fixed in latter versions of the modal. You can also override it via https://docs.walletconnect.com/2.0/web3modal/options#walletimages-optional option (not sure if this is available on version of modal you are using). Also, you should use sme versions of ethereum and html packages.
