### ISSUE TITLE
[bug] Type 'undefined' is not assignable to type 'Element | null'. (@web3modal/react)

### ISSUE THREAD

**Issue by kasparkallas** [WalletConnect/web3modal#1041]
### Link to minimal reproducible example

-

### Summary

Updated my packages (by running `pnpm update --latest") and noticed this:
```
Type error: 'Web3Modal' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.

> 80 |       <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
     |        ^
```
For a reproducible, please provide an easily forkable Codesandbox for bug issuers.

### List of related npm package versions

```
"@web3modal/ethereum": "^2.4.2",
"@web3modal/react": "^2.4.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"@types/react": "^18.2.8",
"typescript": "^5.1.3"
```

**Comment by 0xAsimetriq** [comment]
I ran into this issue myself in web3modal and other projects. Seems to be related to `@types/react` package. What I had to do is delete my `.lock` files and node_modules and re-install everything fresh. That got rid of the ts errors (might need to restart your edditor as well)

**Comment by 0xAsimetriq** [comment]
Closing this for now, let me know if issue persists after doing above.

**Comment by kasparkallas** [comment]
Hey! Just got back to it. Downgraded `@types/react` from `18.2.8` to `18.2.7` and the problem went away. Thanks for your help!

**Comment by 0xAsimetriq** [comment]
Awesome, I got it working without downgrading as well, just had to delete node_modules and package-lock.json file and re-install everything fresh
