### ISSUE TITLE
[quickwin] wallet search

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1042]
### What problem does this new feature solve?

Wallets search quick wins

### Describe the solution you'd like

Updates
• Search bar contents are left aligned
• Typing indicator is brand blue

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4114-49788&t=gsyisLKthX9yo8GY-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/52f2bc71-3e91-4f00-864f-84aa5d107f7d)

**Comment by 0xAsimetriq** [comment]
This was implemented in last release 👍
