### ISSUE TITLE
[quickwin] wallet loading

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1043]
### What problem does this new feature solve?

Wallet loading Quick wins

### Describe the solution you'd like

Updates
• Only one main Retry action
• Universal link as a secondary option, in a link
• Other options exposed underneath

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4230-68596&t=gsyisLKthX9yo8GY-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/cb798d04-d576-4492-9e7f-ef81bb2ca6bb)

**Comment by 0xAsimetriq** [comment]
Implemented in v3
