### ISSUE TITLE
[quickwin] Wallet QR Code

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1044]
### What problem does this new feature solve?

 Wallet QR Code Quick wins

### Describe the solution you'd like

Updates
• Instructions copy updated
• ‘Browser’ replaced by Extension for more clarity and differentiation with ‘Web’
• Btw ‘Web’ mode has been replaced by ‘Webapp’ as well

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4114-49887&t=gsyisLKthX9yo8GY-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/a5516f91-0b54-496f-9c3d-c4e75fabb910)

**Comment by 0xAsimetriq** [comment]
implemented in v3
