### ISSUE TITLE
[quickwin] Account 

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1045]
### What problem does this new feature solve?

Account Quick wins

### Describe the solution you'd like

Updates

• Connected dot blur reduced to 40% opacity
• Connected label aligned in height in his tag
• Copy icon put close to the adress
• Network USD balance stacked to the Crypto one
• Network selection entry point in the Network row
• Recent transaction icon + mabel aligned in height with the previous and following components
• Tx type & Crypto switch to win in space
• Crypto logos horizontally aligned in case of a swap
• Stroke of the colour of the background added around the swapped crypto
• Logout icon moved in header
• Address copied Toast UI designed more away from the Connected Tag one

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4114-49905&t=gsyisLKthX9yo8GY-4

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4114-50001&t=gsyisLKthX9yo8GY-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/baac80f7-e1b9-4371-ba26-053d47165b36)
![image](https://github.com/WalletConnect/web3modal/assets/57009607/c9535c17-976d-4a3e-948a-7a096d98fe70)

**Comment by 0xAsimetriq** [comment]
Won't do this on v2, but we are adding all of these (majority already addressed) in v3
