### ISSUE TITLE
[quickwin] Select Network

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1046]
### What problem does this new feature solve?

Select Network Quick wins

### Describe the solution you'd like

Update
• Search bar added to the network selection, to give the user the opportunity to quickly find which one he wants in case their is a lot more

https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4114-50100&t=gsyisLKthX9yo8GY-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/7d08ba67-8a32-4925-95de-6b682eeeaa2f)

**Comment by 0xAsimetriq** [comment]
Implemented in v3
