### ISSUE TITLE
[bug] lab.web3modal.com disconnect fails with "Error: No matching key. keychain"

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1049]
### Link to minimal reproducible example

https://lab.web3modal.com/with-sign-api/react

### Summary

<img width="862" alt="Screenshot 2023-06-05 at 1 11 49 PM" src="https://github.com/WalletConnect/web3modal/assets/966091/486bfb2b-2286-4eb7-b335-6cd77178d9ca">

Expected behavior: disconnect
Actual behavior: nothing happens

### List of related npm package versions

latest

**Comment by fhermey** [comment]
Hi, what does the error mean and how can I solve it? Any idea? I'm experiencing it, and have no clue how to get around. Appreciate any hint.
