### ISSUE TITLE
[bug] modal shows wrong native chain token

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1054]
### Link to minimal reproducible example

https://lab.web3modal.com/with-wagmi/react

### Summary

Not sure if I can constantly repro
But connect Trust wallet and played around with the namespaces
Noticed that at some point I was on Avalanche but the native token was Matic

![img_4693_720](https://github.com/WalletConnect/web3modal/assets/966091/68346484-1496-4746-9308-5d09d88fea77)

### List of related npm package versions

https://lab.web3modal.com/with-wagmi/react

**Comment by 0xAsimetriq** [comment]
Were not able to reproduce on v2 / v3 uses completely new logic for these, so will close for now.
