### ISSUE TITLE
[feature] WAX Cloud Wallet Integration

### ISSUE THREAD

**Issue by shaffy9633** [WalletConnect/web3modal#1056]
### What problem does this new feature solve?

Hi I want to request or possibly ask if you guys would be integrate WAX Cloud Wallet any time soon? Is there any thing we could do on our end to do this. i.e. fill up a form etc. We are currently using WallectConnect for our website https://www.blumint.com/. Hoping that someone could respond to this ASAP.

### Describe the solution you'd like

Users can connect to the DAPP via WAX Wallet which is one of the options on Web3Modal Auth

**Comment by 0xAsimetriq** [comment]
Wallet teams actually set these up themselves now, to add wax wallet they need to follow project submission guidelines here and get approved by our review team https://docs.walletconnect.com/2.0/cloud/explorer
