### ISSUE TITLE
[quickwin] Improve Search bar

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1058]
### What problem does this new feature solve?

• Add Cancel to the search ; it would give the opportunity user to quickly erase his search without taking to much space as a button
• Make Typing indicator a bit bolder to fit rounded style

### Describe the solution you'd like

Component update here 
https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=6-1530&t=XH3Xef4EiVgJHSzX-4

![image](https://github.com/WalletConnect/web3modal/assets/57009607/f4a9346b-a228-475a-ab7b-5e89658a540f)

**Comment by SAIGANESH-0** [comment]
hi there can someone assign this to me

**Comment by 0xAsimetriq** [comment]
Implemented in v3
