### ISSUE TITLE
[bug] `overflow: hidden` on `html` breaks `position: sticky` elements

### ISSUE THREAD

**Issue by JesseKuntz** [WalletConnect/web3modal#1060]
### Link to minimal reproducible example

https://wagmi.sh/examples/connect-wallet

### Summary

Demo: 

https://github.com/WalletConnect/web3modal/assets/8867651/2604da4b-57cd-4897-9dfc-144f9a2db4a6

Because the modal applies `overflow: hidden` to the `html`, the `position: sticky` elements on the page jump to the top of the page, which is problematic if the page has been scrolled at all.

If the modal applied the `overflow: hidden` to the `body` instead, I believe this problem would be fixed (I say this because we are using the Radix UI Dialog component in our app and it applies `overflow: hidden` to the `body`).

### List of related npm package versions

- "@walletconnect/ethereum-provider": "2.7.8"
- "@walletconnect/ethereum-provider": "2.8.0"
- "@web3modal/standalone": "2.4.3"
- "@walletconnect/modal": "2.4.5"

**Comment by narutodev123** [comment]
Hi Team,
Is there any update on this issue.
