### ISSUE TITLE
Refactor and port feature/web3account code to current release 

### ISSUE THREAD

**Issue by svenvoskamp** [WalletConnect/web3modal#1065]
### What problem does this new feature solve?

To add login with e-mail we need to refactor and port the code from the branch `feature/web3account` to our current release. 

### Describe the solution you'd like

* Create a `w3a controller`
* Create a `w3a util`
* Decouple from `wagmi`
* Implement in latest build

**Comment by 0xAsimetriq** [comment]
Closing this, we won't be porting existing code and likely starting on this from scratch. Older code can still be refferenced.
