### ISSUE TITLE
[quickwin] Success & Error Toasts

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1070]
### What problem does this new feature solve?

These components have been improved and unified

### Describe the solution you'd like

• Their position on Desktop and Mobile : always on the bottom, to be ultimately draggable by user who want to close it before it disappear
• Their Style : Background blur (which is not compatible with React Native) has been replaced by Greys

→ [Figma](https://www.figma.com/file/jjt28S7DTuKxVAYLdb8vmn/Web3Modal?type=design&node-id=4615-98458&t=A11hoPRdDWTaWMNd-4)

![image](https://github.com/WalletConnect/web3modal/assets/57009607/69f55989-e1bf-4751-be75-780899db9dd0)

**Comment by 0xAsimetriq** [comment]
Implemented in v3
