### ISSUE TITLE
[feature] Customizable `font-feature-settings`

### ISSUE THREAD

**Issue by darrylyeo** [WalletConnect/web3modal#1071]
### What problem does this new feature solve?

Web3Modal's `span { font-feature-settings: "tnum", "lnum", "case"; }` rule causes unexpected spacing behavior with some fonts (the `tnum` feature with [Circular](https://lineto.com/typefaces/circular) in this case):

<img width="1290" alt="Screen Shot 2023-06-15 at 3 25 27 PM" src="https://github.com/WalletConnect/web3modal/assets/13970789/621748b0-56d7-4c5e-817e-fce264c1fd4d">
<img width="1290" alt="Screen Shot 2023-06-15 at 3 25 41 PM" src="https://github.com/WalletConnect/web3modal/assets/13970789/50aad81f-6959-416f-aa27-21e35f945a73">

### Describe the solution you'd like

Expose a `--w3m-font-feature-settings` CSS variable or set a more sensible default.

**Comment by 0xAsimetriq** [comment]
Looks like a useful addition 👍 marked as task
