### ISSUE TITLE
[bug] Clear out deeplink choice when qrcode is shown

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1076]
### Link to minimal reproducible example

https://github.com/blocknative/web3-onboard/issues/1780

### Summary

"Clicked" wallet's deeplink choice gets persisted and causes issues when user switches to qrcode pairing / copy uri flow.
We need to Clear out deeplink choice when qrcode is rendered.

### List of related npm package versions
All up to `2.4.7`

**Comment by Adamj1232** [comment]
Thanks @0xAsimetriq! Could this issue related as well : https://github.com/blocknative/web3-onboard/issues/1780 ?

**Comment by L03TJ3** [comment]
Whats the status on this issue?
