### ISSUE TITLE
[bug] relay walletconnect.com refuses valid RPC id

### ISSUE THREAD

**Issue by bitlogik** [WalletConnect/web3modal#1077]
### Link to minimal reproducible example

After sending a valid WS to Opening a WalletConnect v2 client with https://relay.walletconnect.com/, send RPC query :{"jsonrpc":"2.0","id":1,"method":"irn_subscribe","params":{"topic":"d41cc7568d89560a55a04a72ebd3d34364ff474e1447e81f55fece033bd4a1df"}}

### Summary

The relay service replies :
`{"id":1,"jsonrpc":"2.0","error":{"code":-32602,"message":"Request validation error: Invalid request ID"}}`

It works some weeks ago. Now it is broken.
Is there "beyond RPC standard" check on the RPC request id ?
1 is a valid value. The[ official docs](https://docs.walletconnect.com/2.0/specs/servers/relay/relay-server-rpc) uses the "1" value (not as an number, but as a string).

The relay service is still closed source? Else where can we look into it?
is WalletConnect/rpc-proxy the repo for the relay?

### List of related npm package versions

N/A

**Comment by bitlogik** [comment]
We opened this issue https://github.com/WalletConnect/rpc-proxy/issues/170 in rpc-proxy. Not so sure this is the implementation of the relay.walletconnect.com service.

**Comment by 0xAsimetriq** [comment]
This is outside of web3modal project, so I'll close this issue and raise one you opened up on rpc internally.
