### ISSUE TITLE
The console reports an error, and getEnsName is called when web3modal is opened

### ISSUE THREAD

**Issue by rick20220222** [WalletConnect/web3modal#1081]
### Link to minimal reproducible example

https://dev-1.rns.id/nft

### Summary

![screenshot-20230619-151103](https://github.com/WalletConnect/web3modal/assets/100116396/b4f8e0a4-7d60-4a39-8042-429441055f6d)

![screenshot-20230619-151152](https://github.com/WalletConnect/web3modal/assets/100116396/11eea445-acfd-4d8c-90a2-09d7fd7e9d87)

test site: https://dev-1.rns.id/nft

When opening the page, there is this problem in the console, what is the reason for this problem?

### List of related npm package versions

 "@web3modal/ethereum": "^2.4.6",
 "@web3modal/react": "^2.4.6",
 "viem": "^1.0.7",
 "wagmi": "^1.2.0",

**Comment by 0xAsimetriq** [comment]
Preview you provided fails to connect to the relay with
```
Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Unauthorized: origin not allowed)
```

You likely enabled domain allowlisting in your project and this domain is not part of it? So unable to debug this at the moment.

**Comment by rick20220222** [comment]
I added the whitelist and now there is no error.Thx

**Comment by 0xAsimetriq** [comment]
Are you still seeing your original error? I was able to connect fine and am now receiving "chain missmatch error". I believe dapp intends to use goerli, but during connection there is no prompt to switch / change chain. You can set `defaultChain` property on web3modal for that.

**Comment by 0xAsimetriq** [comment]
closing due to innactivity.
