### ISSUE TITLE
[bug] Unable to create instance of WalletConnectModal on ios 15

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1091]
### Link to minimal reproducible example

https://github.com/wagmi-dev/wagmi/issues/2590#issue-1768673199

### Summary

Issue was posted upstream in wagmi, need to investigate and confirm it, then figure out what could be causing it on ios 15.

### List of related npm package versions

@walletconnect/modal

**Comment by ignaciosantise** [comment]
## More info: 
Tested in iOS 15.7.5 and it works good

Console errors from Safari in iOS 15.2:
<img width="1006" alt="Screen Shot 2023-06-23 at 15 26 20" src="https://github.com/WalletConnect/web3modal/assets/25931366/ea963564-8be8-41bb-89b9-435372c32da5">
