### ISSUE TITLE
[feature] EIP-6963 support

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1092]
### What problem does this new feature solve?

[https://eips.ethereum.org/EIPS/eip-6963](EIP-6963) unlocks better way to manage multiple installed extension wallets.

### Describe the solution you'd like

Track progress of the eip and start implementation once it is accepted

**Comment by glitch-txs** [comment]
🤩🤍🔥

**Comment by pitzegluck** [comment]
+++

**Comment by jxom** [comment]
This may be of interest: https://github.com/wagmi-dev/mipd 😄

**Comment by 0xAsimetriq** [comment]
Implemented in 3.0.0-beta.5 as experimental feature, will likely make it into 3.0.1 release
https://github.com/WalletConnect/web3modal/releases/tag/3.0.0-beta.5
