### ISSUE TITLE
[feature] Multilingual Support

### ISSUE THREAD

**Issue by fffedor** [WalletConnect/web3modal#1094]
### What problem does this new feature solve?

Greetings.
Firstly, thank you for the excellent work. I have a need to use web3modal in several languages, I realise that there is very little vocabulary there, but nevertheless.

Is this a possibility now or is it planned in the future?

### Describe the solution you'd like

Additional option

**Comment by 0xAsimetriq** [comment]
Duplicate of https://github.com/WalletConnect/web3modal/issues/627
