### ISSUE TITLE
[bug] Web3modal stuck on loading after redirect from Metamask in iOS

### ISSUE THREAD

**Issue by ShahzaibAyyub** [WalletConnect/web3modal#1095]
### Link to minimal reproducible example

https://www.loom.com/share/91d7ff50dc1a44868e0c746dff44ac03

### Summary

I'm using web3modal react wagmi for my dapp, and due to deep linking issues with iPhone and Metamask, I had to update my Dapp to the latest versions of wagmi, viem, web3modal/ethereum and @web3modal/react. But ran into another major issue in which wallet connection is not picked up after redirect from metamask.

Just 3 days ago it was running fine but got reports from several users that they could not establish a connection from their iPhone to Metamask. Desktop and android version are working fine. I have attached the link to a video reproducing this error. Any help would be greatly appreciated! 

My phone: iPhone 13 Pro Max
iOS: 16.15.1
Metamask version: 7.0.1

### List of related npm package versions

"dependencies": {
    "@web3modal/ethereum": "2.4.7",
    "@web3modal/react": "2.4.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^5.1.3",
    "viem": "1.0.7",
    "wagmi": "1.2.0",
    "web3": "^1.8.2"
  },

**Comment by ShahzaibAyyub** [comment]
Also being reproduced when run this react wagmi example: https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react

**Comment by 0xAsimetriq** [comment]
Does this happen 100% of the time on your end or at random times? Which version of mm do you have installed?

**Comment by ShahzaibAyyub** [comment]
Yes it happens 100% of the times, and my metamask version is latest 7.0.1  @0xAsimetriq

**Comment by 0xAsimetriq** [comment]
@ShahzaibAyyub Where about are you located? Also, I noticed that you are using tuneling via ngrook which can definitely cause issues like this. Can you deploy and re-plicate this issue without it?

**Comment by ShahzaibAyyub** [comment]
Well I have deployed it on an environment and the error is persistent there also (Multiple test users are also reporting it). I used ngrok to test if updating packages to latest might fix this behavior but its still persistent. I can replicate it on my test environment and send a recording if you want to. To reproduce this you can test it out on this example https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react , just make sure you're using an iPhone with latest mm. @0xAsimetriq

**Comment by 0xAsimetriq** [comment]
@ShahzaibAyyub @danyalxahid just did a debugging session for this TL;DR it looks like latest MetaMask is failing when `version: 1` is set. Setting version 2 solves the issue. Also,`2.6.0` of web3modal was just released that completely removes v1 and versioning (v2 only).

Examples above were updated. Let me know if this helps resolve your issues.

**Comment by ShahzaibAyyub** [comment]
@0xAsimetriq changing to version 2 have fixed things for now, will upgrade to 2.6.0 afterwards
