### ISSUE TITLE
switchNetwork from WagmiCore does not work on mobile

### ISSUE THREAD

**Issue by HT-Moh** [WalletConnect/web3modal#1098]
### Link to minimal reproducible example

below

### Summary

Description:
The switchNetwork function should add the network if it does not exist and switch to it. This behavior works correctly on desktops, but when using an iPhone with MetaMask installed (same behavior with trustwallet), the network is not added.

Steps to Reproduce:

Open the index.html file.

1. create `index.html` and add the following code snippet: <w3m-core-button icon='hide'></w3m-core-button> inside the body of 
2. Add `<script type="module" src="'web3modal.js"/>` inside the head tag of `index.html`
3. create `web3modal.js` file and add the code below inside 
4. host the page somewhere and open it on the mobile (iPhone).

```javascript
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";

// import UniversalProvider from "https://unpkg.com/@walletconnect/universal-provider";

import { Web3Modal } from "https://unpkg.com/@web3modal/html";

const { mainnet, polygon, polygonMumbai, avalanche, arbitrum } =
  WagmiCoreChains;
const {
  configureChains,
  createConfig,
  switchNetwork,
} = WagmiCore;

// 1. Define chains
const chains = [mainnet, polygon, polygonMumbai, avalanche, arbitrum];

const projectId = "your_project_id";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, version: 1, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);
const web3modal = new Web3Modal(
  { projectId, walletConnectVersion: 2 },
  ethereumClient
);
web3modal.subscribeModal((newState) => {
  console.log(newState);
});
web3modal.subscribeEvents((newState) => {
  const { name } = newState;
  if (name === "ACCOUNT_CONNECTED") {
    switchNetwork({
      chainId: 80001,
    })
      .then((chain) => {
        console.log(chain);
      })
      .catch((e) => {
       console.error(addError);
      });
  }
  console.log(newState);
});
```

### List of related npm package versions

I am using just html and vanilla javascript and importing the libraries inside the file  `web3modal.js` which is imported on head of index.html as script type module

```javascript
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";

// import UniversalProvider from "https://unpkg.com/@walletconnect/universal-provider";

import { Web3Modal } from "https://unpkg.com/@web3modal/html";
```
Posted on wagmi repo:
https://github.com/wagmi-dev/wagmi/issues/2632

**Comment by 0xAsimetriq** [comment]
Sorry for delayed response. If you use latest wagmi and web3modal packages (you might want to add explicit versioning to your cdn scripts). Calling wagmi's switch network will add new ones to the wallet, but only if they support `wallet_addEthereumChain` method.

I know MetaMask does, not sure about trust wallet. Also note, metamask currently has few issues around chain switching and they are working on next release to address this. If wallet does not support that switch method, it will still switch to a chain if it wass approved during connection (With WalletConnect v2 you connect to multiple chains at once) or will error.

**Comment by TimDaub** [comment]
Just to check: So web3modal itself doesn't have any method that helps to do chain switching, right? That's up to the user to implement using Ethers?

**Comment by glitch-txs** [comment]
We added one 

@svenvoskamp is it out yet?
