### ISSUE TITLE
⚙️ WalletConnect v1 -> v2 migration guide

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1107]
### Summary

WalletConnect v1 protocol has been officially shut down, please see migration guide below for upgrade options
https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview

**Comment by EthanBlockson** [comment]
> If you are using our redesigned Web3Modal (often referred to as Web3Modal v2.0), you are ready to go. Please ensure that you are using a minimum version of **2.6.0**.

> To migrate to WalletConnect v2.0 using wagmi, you need to upgrade **wagmi** to either **0.12.16** if you are using ethers or 1.x.x if you are using viem.

This quote above is not complete. To upgrade for 2.6.0 you need to have @wagmi/core@">=1 and there are lot of [breaking changes](https://wagmi.sh/core/migration-guide#1xx-breaking-changes)...

```
npm ERR! Could not resolve dependency:
npm ERR! peer @wagmi/core@">=1" from @web3modal/ethereum@2.6.0
npm ERR! node_modules/@web3modal/ethereum
npm ERR!   @web3modal/ethereum@"2.6.0" from the root project
npm ERR! 
```

**Comment by 0xAsimetriq** [comment]
@EthanBlockson ty for raising this, will inform our docs team

**Comment by briantate82** [comment]
npm ERR! Could not resolve dependency:
npm ERR! peer @wagmi/core@">=1" from @web3modal/ethereum@2.6.0
npm ERR! node_modules/@web3modal/ethereum
npm ERR!   @web3modal/ethereum@"2.6.0" from the root project

**Comment by 0xAsimetriq** [comment]
Closing now that v3 is stable
