### ISSUE TITLE
[bug] When using Web3Modal to connect on web via mobile wallet, EIP1193 standard is not followed

### ISSUE THREAD

**Issue by Andriy-Kulak** [WalletConnect/web3modal#1111]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

I am noticing that when I use web3modal, if I connect via a browser wallet like metamask, then the EIP 1193 standard is followed where I can see what address is connected via `window.ethereum.selectedAddress` object on browser.
however if a user is using a mobile wallet like wallet connect or rainbow kit to connect to a website on desktop then the EIP 1193 standard is not followed & I cannot use browser window object to understand which wallet is connected.

Steps to reproduce using web3modal on `https://web3modal.com/`
1. Click connect
2. Use a mobile wallet like wallet connect or rainbow wallet via QR code to connect
3. Go to console and type in:`window.ethereum.selectedAddress`. It will be null even though the wallet is connected

Why is this the case & how can I figure out what address is connected without using wagmi?

![Screenshot 2023-06-28 at 11 07 07](https://github.com/WalletConnect/web3modal/assets/12179976/ca9ce0ac-f5c5-406d-942e-3de8af6db62f)

### List of related npm package versions

This isn't version specific. happens on latest versions.

**Comment by 0xAsimetriq** [comment]
There is no mention of `selectedAddress` in [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193) as far as I can see, so will close this issue for now. This could be something specific that only MetaMask adds perhaps?

**Comment by Andriy-Kulak** [comment]
@0xAsimetriq what about `accountsChanged`. This is part of the EIP 1193 standard & doesn't get triggered when I add a wallet via a mobile app like wallet connect or rainbow wallet? Example:

```js
window.ethereum.on('accountsChanged', function (args) {console.log('ethereum yyyyy', args)})
```

**Comment by Andriy-Kulak** [comment]
Reference: https://eips.ethereum.org/EIPS/eip-1193#accountschanged

**Comment by 0xAsimetriq** [comment]
@Andriy-Kulak that's supported, but you don't call it on window, you need to call it on walletconnect provider if you use that
https://docs.walletconnect.com/2.0/web/providers/ethereum#events

window is for injected providers like browser extensions
