### ISSUE TITLE
[docs] provider events on web3modalv2

### ISSUE THREAD

**Issue by 0x0th** [WalletConnect/web3modal#1112]
### Summary

How can I listen to provider events like in v1

https://github.com/WalletConnect/web3modal/tree/V1#provider-events

### Link to the related docs page

https://github.com/WalletConnect/web3modal/tree/V1#provider-events

**Comment by 0xAsimetriq** [comment]
When you use Web3Modal package, you can subscribe to various events via https://wagmi.sh actions or hooks.

When you use WalletConnectModal package with EthereumProvider, you can subscribe to events directly on EthereumProvider https://docs.walletconnect.com/2.0/web/providers/ethereum#events
