### ISSUE TITLE
[bug]  reading filter error in web3modal latest version

### ISSUE THREAD

**Issue by saadqayyum-cyber** [WalletConnect/web3modal#1125]
### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react

### Summary

On launching application with new web3modal integrated, this error appears. This error also appears in example provided by walletconnect
https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'filter')

Call Stack
m.setAccounts
node_modules\@walletconnect\ethereum-provider\dist\index.es.js (1:5395)
m.loadPersistedSession
node_modules\@walletconnect\ethereum-provider\dist\index.es.js (1:7723)
async m.initialize
node_modules\@walletconnect\ethereum-provider\dist\index.es.js (1:6462)
async m.init
node_modules\@walletconnect\ethereum-provider\dist\index.es.js (1:2284)
async WalletConnectConnector.initProvider_fn
node_modules\@wagmi\connectors\dist\walletConnect.js (238:16)

### List of related npm package versions

   "autoprefixer": "10.4.14",
    "eslint": "8.43.0",
    "eslint-config-next": "13.4.7",
    "next": "13.4.7",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "viem": "^1.2.6",
    "wagmi": "^1.3.3"

**Comment by 0xAsimetriq** [comment]
Just ran that example, unable to replicate. Do you have more details on how you got it? Did you tweak the example in any way?

https://github.com/WalletConnect/web3modal/assets/3154053/06d71dfc-0c40-42d1-be7b-daa2d6a33891

**Comment by saadqayyum-cyber** [comment]
The issue was resolved automatically. I believe it was related to Chrome, as it worked fine when I tried it on Microsoft Edge. However, after that, it also started working on Chrome. Additionally, some of the issues were resolved by installing a slightly older version of Next.js. Since I am unable to reproduce the issue anymore, I will be closing this thread
