### ISSUE TITLE
[bug] Reduce search threshold to 1 character

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1144]
### What problem does this new feature solve?

We currently have a threshold of at least 3 chars to be entered into search before kicking off search api request, should be reduced to 1 as we now have wallets with just 2 chars in their names.

### Describe the solution you'd like

Reduce threshold

**Comment by shubhamshd** [comment]
Hi @0xAsimetriq 
I would like to contribute by implementing the suggested changes to the search threshold
I kindly request your permission to proceed with this issue and contribute to the project's improvement. If there are any specific instructions or considerations I should be aware of, please let me know.

Thank you for your time and consideration. I look forward to your response.

**Comment by 0xAsimetriq** [comment]
@shubhamshd Sure thing, the change is minimal with `3` -> `1` here https://github.com/WalletConnect/web3modal/blob/V2/packages/ui/src/views/w3m-wallet-explorer-view/index.ts#L103

We are planning release closer to the end of the week which will include this, but if you manage to open pr before that we can merge 👍

**Comment by shubhamshd** [comment]
Hi @0xAsimetriq  thanks for giving me an opportunity, I have opened and linked a pr for the suggested change, please review!!!
Bear in mind, this is my first ever pr, so pardon me, if anything wrong ☺️
