### ISSUE TITLE
[bug] Unable to connect a wallet with wagmi v1.3.5 and having only one configured chain 

### ISSUE THREAD

**Issue by icedevera** [WalletConnect/web3modal#1150]
### Link to minimal reproducible example

https://github.com/icedevera/web3modal-wagmi-react-example

### Summary

Steps to reproduce from [web3modal wagmi react example](https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react).:
1. Update wagmi to v1.3.5 (latest as of writing).
2. Alter chain array to have only 1 configured chain (e.g. mainnet).
3. Run `npm run dev`.
4. Click connect wallet button.

Expected behavior: WalletConnect prompts to connect to a wallet.
Actual behavior:  WalletConnect is stuck loading with a console error: 
<img width="973" alt="unsupported-chains-error" src="https://github.com/WalletConnect/web3modal/assets/46994386/6e5e3023-256a-4216-b6c1-d5b8052b7f95">

### List of related npm package versions

- wagmi@1.3.5
- viem@1.2.9
- @web3modal/ethereum@2.6.2
- @web3modal/react@2.6.2"

**Comment by 0xAsimetriq** [comment]
This was fixed on wagmi level via https://github.com/wagmi-dev/references/commit/0a57de2a7b0e6ac73208d0d46c541b6db87b0e30 but I don't think wagmi made a release yet, so look out for `1.3.6`. Will ping their team to escalate this 👍

**Comment by icedevera** [comment]
> This was fixed on wagmi level via [wagmi-dev/references@0a57de2](https://github.com/wagmi-dev/references/commit/0a57de2a7b0e6ac73208d0d46c541b6db87b0e30) but I don't think wagmi made a release yet, so look out for `1.3.6`. Will ping their team to escalate this 👍

Oh alright. Thank you 🙏

**Comment by SmartArray** [comment]
As a workaround we can just add another chain to the configuration. For example:

```
const chains = [mainnet, arbitrum /* remove this after bugfix */];
```

**Comment by 0xAsimetriq** [comment]
This was fixed in latest wagmi release

**Comment by SmartArray** [comment]
Thank you @0xAsimetriq and @glitch-txs

**Comment by KINGAVIP** [comment]
@SmartArray Can you provide the solution please that worked for you.

**Comment by SmartArray** [comment]
Upgrade the package
