### ISSUE TITLE
Doesn't connect to Chrome Metamask extension

### ISSUE THREAD

**Issue by sudokey** [WalletConnect/web3modal#1159]
**Describe the bug**
When you click on the metamask icon in the desktop section, a connection via a QR code is shown. It is expected that the connection through the installed extension will work, as on the site https://web3modal.com/.

"@walletconnect/ethereum-provider": "^2.8.6",
"@walletconnect/modal": "^2.5.9",

**Comment by 0xAsimetriq** [comment]
`@walletconnect/modal` Does not support browser extensions or other third party connectors, it is a simple modal to connect external wallets through walletconnect i.e mobile / native desktop apps.

Web3Modal, which you mentioned does support all of this, but requires you to use it with wagmi, as opposed to ethereum-provider.
