### ISSUE TITLE
[bug] Flaky performance on mobile when trying to sign messages

### ISSUE THREAD

**Issue by liron-navon** [WalletConnect/web3modal#1166]
### Link to minimal reproducible example

preview: https://wallet-connect-demo-nine.vercel.app | github: https://github.com/liron-navon/wallet-connect-demo

### Summary

I'm trying to get a user to do 2 things:
1. connect a wallet
2. sign a message

It is part of our verification process, issue is on mobile only, when I open a browser on my phone:
1. I connect using web3modal (the button "Connect wallet") - it always works, metamask is open and there is a connect message.
2. I try to sign the message (with viem, ethers or wagmi) - it only works sometimes, metamask is open, but no signing message.

all the relevant code in the repo is in the file `src/pages/index.tsx`

### devices:
`oppo find x3 lite` | `iphone 13`

### List of related npm package versions

 "@web3modal/ethereum": "^2.6.2"
  "@web3modal/react": "^2.6.2"
  "viem": "^1.2.9"
  "wagmi": "^1.3.7"
  "ethers": "^6.6.2"

**Comment by 0xAsimetriq** [comment]
Similarly to your previous issue, this seems like something to do with MetaMask, as soon as it is open, it is within their realm to receive messages and display prompts or errors. Only idea that comes to mind (and this is something we are working together with metamask on) is that you might be sending sign messages on one chain while metamask wallet is on another.
