### ISSUE TITLE
[bug] When signing messages, sometimes the website is opensea.io

### ISSUE THREAD

**Issue by liron-navon** [WalletConnect/web3modal#1167]
### Link to minimal reproducible example

preview: https://wallet-connect-demo-nine.vercel.app | github: https://github.com/liron-navon/wallet-connect-demo

### Summary

I'm trying to get a user to do 2 things:

1. connect a wallet
2. sign a message

I sometimes get a title in the signing screen on metamask, stating the website "opensea.io" is requesting the signature, which is very confusing...

This signature was requested through the website `wallet-connect-demo-nine.vercel.app` and not `opensea.io`.

All the relevant code in the repo is in the file `src/pages/index.tsx`

### devices:

This happens to me on the phone `oppo find x3 lite`

![Screenshot_2023-07-06-18-34-46-75_3ce871bb60cb313382b75690e63e41d0](https://github.com/WalletConnect/web3modal/assets/18119833/e5f3feb9-11ab-4b51-b7e2-23aaf56d2610)

### List of related npm package versions

"@web3modal/ethereum": "^2.6.2"
"@web3modal/react": "^2.6.2"
"viem": "^1.2.9"
"wagmi": "^1.3.7"
"ethers": "^6.6.2"

**Comment by 0xAsimetriq** [comment]
There is nothing in our codebase setting / falling back to opensea, so I'm not sure why this is happening, could be a cache bug in MetaMask or maybe dapp was setting metadata as opensea during testing?
