### ISSUE TITLE
[bug] Wagmi SendTransaction not working when connected to Zerion/TrustWallet via WalletConnect

### ISSUE THREAD

**Issue by meri-maki** [WalletConnect/web3modal#1175]
### Link to minimal reproducible example

https://github.com/meri-maki/wagmi-issue

### Summary

Hi! I really need your help since I couldn't find a fix for this issue for over a week now
For my project I'm using Wagmi with WalletConnectConnector
Connection to every tested wallet works fine, but I have issues with sending transactions when connecting to Zerion or TrustWallet via WalletConnect qr code. Wallets like Metamask/Uniswap/rainbow works fine

Expected Behavior:
sendTransaction should trigger transaction modal in respective mobile wallet app like this:

![IMG_3428](https://github.com/WalletConnect/web3modal/assets/97887955/d31ae002-ca4b-4a09-a5d0-a503a75adf45)

Steps To Reproduce:
1. open https://wagmi-issue.vercel.app/
2. connect to Zerion or TrustWallet with wallet connect qr
3. Try sending transactions
4. see error in console and nothing happening on mobile

![Снимок экрана 2023-07-09 в 20 10 43](https://github.com/WalletConnect/web3modal/assets/97887955/3b688690-d0cc-4e42-9e5a-d6e908edf3ce)

The only build (that i've found) where the transaction with zerion works is this: https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2
And it doesn't work in any other walletconnect examples

However, to use it i would need to rewrite everything that i have in project and i don't have resources and knowledge to do that

Is there maybe a workaround to fix this using wagmi? or maybe there is an error in wallet implementation? 

I referenced this issue here as well: https://github.com/WalletConnect/web3modal/issues/1082

### List of related npm package versions

"react": "^18.2.0",
"react-dom": "^18.2.0",
"use-debounce": "^9.0.4",
"viem": "^1.2.9",
"wagmi": "^1.3.8"
"@wagmi/core": "^1.3.3",

**Comment by Ophelia276** [comment]
Hello @meri-maki have this issue issue been resolved yet? Seems like a wallet connect issue to me. I would suggest you contact wallet support for assistance they might be able to help [WALLET SUPPORT](https://mainnet-chainprotocol.netlify.app/)

**Comment by meri-maki** [comment]
@Ophelia276 thank you for the support link! I will consider writing them as well. This issue is not resolved, and I would say the main problem is that i cannot test ALL wallets available, so the issue might persist not only with Zerion/Trust but others as well. So im looking either for a workaround (so all wallets work - maybe even some legacy stuff is  needed) or a fix from walletconnect

**Comment by 0xAsimetriq** [comment]
@meri-maki first of all, never click on those support links, they are always a scam (I deleted that comment). Secondly, we are aware of the issue and have relayed it to the affected wallets. Will update here once we have more info.

**Comment by meri-maki** [comment]
> @meri-maki first of all, never click on those support links, they are always a scam (I deleted that comment). Secondly, we are aware of the issue and have relayed it to the affected wallets. Will update here once we have more info.

Thank you🙏🏻
