### ISSUE TITLE
[bug] Injected wallet not being able to integrate with WalletConnect

### ISSUE THREAD

**Issue by carlosper88** [WalletConnect/web3modal#1180]
### Link to minimal reproducible example

https://chrome.google.com/webstore/detail/cobalt-development-build/apkeonngfjnmcggdgdoljjdnkmdmdlno/related

### Summary

After injecting the ethereum methods at window.ethereum, we've been testing with https://lab.web3modal.com/with-wagmi/react. Nevertheless, we're unable to fully connect to WalletConnect. These are the steps:
1. Click on "Connect Wallet"
2. We get the popup with the Cobalt button, indicating it's already installed
<img width="487" alt="Captura de Pantalla 2023-07-10 a las 18 09 58" src="https://github.com/WalletConnect/web3modal/assets/6905975/2245086b-7a6a-4cd3-a163-483e90d0862f">

3. We click the Cobalt button and it starts connecting
<img width="490" alt="Captura de Pantalla 2023-07-10 a las 18 10 16" src="https://github.com/WalletConnect/web3modal/assets/6905975/4d940864-a4dc-4759-9e69-aa73d429ff51">

At this point we expected our wallet to popup, as we're following the connection protocols defined on the EIPs. This has already been tested on other dapps like Remix, where we're able to connect:
1. Popup screen to connect the requesting dapp:
<img width="396" alt="Captura de Pantalla 2023-07-10 a las 18 55 51" src="https://github.com/WalletConnect/web3modal/assets/6905975/a0888f89-f57e-41c6-bd74-3da2ce811e30">

2. Remix indicating wallet is connected and providing address, chain id and balance:
<img width="313" alt="Captura de Pantalla 2023-07-10 a las 18 08 28" src="https://github.com/WalletConnect/web3modal/assets/6905975/8c81d5ec-b400-4241-8305-a6a3d1c75ff7">

3. Cobalt overview screen showing address and balance matching the one provided to Remix
<img width="386" alt="Captura de Pantalla 2023-07-10 a las 18 08 40" src="https://github.com/WalletConnect/web3modal/assets/6905975/d0335df5-e735-48ac-ad57-122769dcfc11">

As you can see, the pure EIP implementation seems to be fine, and we may be missing something related to the WC integration

### List of related npm package versions

No web3 / walletConnect packages are in use currently. As discussed on Slack channels, only with the addition of the EIP methods, wallet connect should be able to connect with our injected wallet.
Library used to send/receive ethereum events:
https://www.npmjs.com/package/emittery

**Comment by 0xAsimetriq** [comment]
Within Web3Modal repo, we are not doing anything special around injected wallets, here most of our logic comes from [wagmi](https://wagmi.sh/).

We use their [injected connector](https://wagmi.sh/react/connectors/injected) for all such wallet interactions, in particular on the loading screen you posted, we call `.connect()` method.

As this works for majority of other extensions, I doubt something is wrong with this connector. Best advice I can give is to check their source at https://github.com/wagmi-dev/references/blob/cf1b48dabbe42a9b71a4965928e5e789b6c656a0/packages/connectors/src/injected.ts and see if something is missing.

**Comment by carlosper88** [comment]
Hi @0xAsimetriq 
Where is it supposed to be set that Injected Connector? At the moment we are doing window.ethereum = {OUR PROVIDER}
I don't see how the injected connector would be exposed to the browser. Should we do window.ethereum = InjectedConnector()? In that case, where would our provider be? window.ethereum.providers?

**Comment by 0xAsimetriq** [comment]
Dapps and modals that use wagmi never interact with `window.ethereum`, instead they call methods on `InjectedConnector ` this is specific to wagmi. As long as everything is set correctly on `window.ethereum` InjectedConnector will pick it up and use it. You don't need to directly do anything with it. The reason I linked it is for you to check how it works and see if anything you are doing might be missing or incompatible.

Try to find differences between other extensions like metamask / brave wallet / phantom / trust etc. as these work as expected and InjectedConnector from wagmi uses them fine. They also don't do anything besides `window.ethereum = {OUR PROVIDER}`. Maybe it depends on when and how you set it? 

Afraid I can't help much here, since I never worked on extension wallets.

**Comment by carlosper88** [comment]
Hi again! We've tested creating a new frontend project that uses the wagmi's `InjectedConnector` and it works just fine (wagmi npm package v1.3.8). So I guess that there must be something on your code that may be banning us from connect.
In particular, this is the part where we're trying to connect, and where we're getting to popup Cobalt
https://github.com/jmontesdeocanuez/testing-wagmi/blob/main/src/app/account.tsx

This is a video where we're running that code. You can also see in the console to the right how we're receiving the `eth_requestAccounts` event in our wallet
https://github.com/WalletConnect/web3modal/assets/6905975/1e551894-0aa7-4b04-9d69-0d6ea2db8191
