### ISSUE TITLE
[bug] Manual wallets do no appear on Android

### ISSUE THREAD

**Issue by darrenvechain** [WalletConnect/web3modal#1187]
### Link to minimal reproducible example

n/a

### Summary

**Expected Behaviour**:
I should see the manually configured mobile wallets on both Android and iOS.

**Actual Behaviour**:
I can only see the manually configured wallets in iOS. Android does not show any.

My `package.json`
```json
"@web3modal/standalone": "^2.3.7",
```

My `walletConnect.ts`
```typescript

import { Web3Modal } from "@web3modal/standalone"

const web3Modal = new Web3Modal({
  walletConnectVersion: 2,
  projectId: DEFAULT_PROJECT_ID,
  standaloneChains: SUPPORTED_CHAINS,
  mobileWallets: [
    {
      id: "my-example-wallet",
      name: "Example",
      links: {
        universal: "https://example.com",
        native: "myapp://com.emaple/",
      },
    },
  ],
  themeVariables: {
    "--w3m-z-index": "99999999",
  },
  walletImages: {
    "my-example-wallet": "/images/logo/my-manual-wallet.png",
  },
})


```

### List of related npm package versions

@web3modal/standalone: ^2.3.7

**Comment by 0xAsimetriq** [comment]
<img width="337" alt="Screenshot 2023-07-12 at 08 48 05" src="https://github.com/WalletConnect/web3modal/assets/3154053/24487c61-7c00-428f-ab9c-208c80263829">

Android doesn't show individual wallets, it has one universal option (button) that applies to all as android devices can handle our `wc://` deeplink by presenting user with native ui that lists all apps that can open it.

**Comment by 0xAsimetriq** [comment]
As a sidenote `@web3modal/standalone` has been deprecated. You likely want to use [@walletconnect/modal](https://docs.walletconnect.com/2.0/web/walletConnectModal/modal/installation) package or `@walletconnect/ethereum-provider`
