### ISSUE TITLE
[bug] 2.7.0 have errors and don't open modal!!

### ISSUE THREAD

**Issue by oleksiivinogradov** [WalletConnect/web3modal#1190]
### Link to minimal reproducible example

mobile.dexgo.app

### Summary

hey-listen.es.js:3 Uncaught (in promise) ReferenceError: process is not defined
    at hey-listen.es.js:3:5

after upgrade this happens

### List of related npm package versions

latest
 import {
        EthereumClient,
        w3mConnectors,
        w3mProvider,
        WagmiCore,
        WagmiCoreChains,
        WagmiCoreConnectors
      } from 'https://unpkg.com/@web3modal/ethereum'

      import { Web3Modal } from 'https://unpkg.com/@web3modal/html'

**Comment by 0xAsimetriq** [comment]
Polyfils were removed in 2.7.0, see https://github.com/WalletConnect/web3modal/releases/tag/2.7.0

Looks like you are using something that requires `process.env`, so you need to add that polyfil manually now
