### ISSUE TITLE
2.7.x Release polyfill guide 

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1192]
### Summary

2.7.0 removed polyfills as per release notes in https://github.com/WalletConnect/web3modal/releases/tag/2.7.0

If you happen to use something that requires these (usually in our cdn bundles), you can reference our previous implementation to see how this is done below. Make sure to polyfill before you import modal packages.
```ts
import { Buffer } from 'buffer'

if (typeof window !== 'undefined') {
  if (!window.Buffer) {
    window.Buffer = Buffer
  }
  if (!window.global) {
    window.global = window
  }
  if (!window.process) {
    window.process = { env: {} }
  }
}
```

**Comment by lbennett-stacki** [comment]
Hi @0xAsimetriq, I've applied this polyfill but still getting this `buffer.constants` is undefined, accessed by pino?

**Comment by 0xAsimetriq** [comment]
Closing now that v3 is stable
