### ISSUE TITLE
same wallet multiple times in modal

### ISSUE THREAD

**Issue by SumiBisht** [WalletConnect/web3modal#1194]
I can see same wallet twice and thrice in the modal:
<img width="387" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/40060905/7638cd44-31c3-4829-a4d6-61c401f92ed6">

And how do i automatically reconnect when I refresh the page currently its getting disconnected on refreshing, I am using ethereum-provider, any help will be appriciated.

**Comment by 0xAsimetriq** [comment]
@SumiBisht I don't see any duplicates in above screenshot, and issue template for `Bug` report was not respected, so I'll be closing this for now, feel free to re-open with further details and proper issue template.

**Comment by SumiBisht** [comment]
Please check now. I can't show two at a time bcz the distance between the
recurring items is more than what can be seen, you just closed this for the
sake of closing please address it there are multiple instances of same
wallet I will post video.

**Comment by 0xAsimetriq** [comment]
@SumiBisht I see no duplicates on https://web3modal.com

Make sure you run latest version and don't initialise modal more than one time (I think this could be the issue you are facing thats causing this behavior).
