### ISSUE TITLE
Can't connect in Trust Wallet browser #2

### ISSUE THREAD

**Issue by meri-maki** [WalletConnect/web3modal#1204]
For me with wagmi 1.3.8 it's still not working (updating wagmi to and viem to latest didn't help)
https://github.com/meri-maki/wagmi-issue

https://wagmi-issue.vercel.app/

https://github.com/WalletConnect/web3modal/assets/97887955/5405b6d0-c57f-4448-96af-46fe643f4bcb

_Originally posted by @meri-maki in https://github.com/WalletConnect/web3modal/issues/1048#issuecomment-1637044841_

**Comment by 0xAsimetriq** [comment]
Closing this one as issue template was not filled out. However I did try to replicate and didn't have any issues, so few ideas:

1. Update to latest TrustWallet version
2. Check for internet conenction to be stable / disable any network affecting apps or vpns
3. From your video looks like Trust wallet was already on some broken state / error screen, could be an issue on their end where they don't handle conenctions on that particular screen maybe.


https://github.com/WalletConnect/web3modal/assets/3154053/d7e0c2ff-8fc9-4bbd-8e4e-888d1bff9039
