### ISSUE TITLE
Can you add crossorigin to the img tags? [feature] 

### ISSUE THREAD

**Issue by dataexcess** [WalletConnect/web3modal#1206]
### What problem does this new feature solve?

I am building a website which requires COEP to be set to 'require-corp' since I need to use SharedArrayBuffer.
However, because of this all the images in the web3modal are not loading. Adding 'crossorigin' to the img's would fix this.

### Describe the solution you'd like

add the attribiute 'crossorigin' to all the imgs

**Comment by 0xAsimetriq** [comment]
@dataexcess Can you expand on your issue and what exactly you'd like to be added to the image tag? My understanding is that `crossorigin="anonymous` is applied to all image tags by default. If you are using strict [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) policies, you will need to allow our image endpoint in your configuration, which should allow them to be loaded?

**Comment by dataexcess** [comment]
I have a script that's using a worker to load a wasm file. I need SharedArrayBuffer to be able to make all of this work. As far as I know (maybe I don't understand it fully) in order to enable SharedArrayBuffer the COEP needs to be set to 'require-corp':

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy

The problem is that setting this in my app (nuxt 3) also blocks all other resources - except if they are marked with crossorigin

**Comment by 0xAsimetriq** [comment]
I see, so I assume other bits like our websocket relay / data fetching via explorer api work fine? I can look into this for you, but in that case, could you give me a concrete example of what needs to be added to the `img` tag for it to work? (ideally if you could test it on your end as well first).

**Comment by dataexcess** [comment]
All the rest is working perfectly! yes.
I just literally added the word 'crossorigin' inside the img tag in google chrome dev and the images start appearing... 

Please have a look and it would be awesome if you can make this work :). Somebody else at the nuxt-security github told me to contact the owners of the 3th party code (you) and had this to say:

"Having a crossorigin prop in the image is a good practise in general so I recommend to do that." 

So, I believe it can do no harm and is good practice anyway? But I'm no expert.

Thank you!

**Comment by 0xAsimetriq** [comment]
Awesome, ty for extra details, I will mark this as a task 👍

**Comment by dataexcess** [comment]
> Awesome, ty for extra details, I will mark this as a task 👍 Meanwhile you can probably write a small script to loop over all images within our web-compoennt `w3m-modal` and add it, so things work while we add on our end

Haha yes that's what I'm trying to do now but I'm kind of stuck 😂. Is there a callback available that I can use when the modal opens? Since I cannot add the script onpage load since obviously the images are not there yet since the modal is not there.

**Comment by dataexcess** [comment]
I'm trying but it's difficult because it is a shadow-element? I cannot use getElementById() it seems.
Anyways I will keep searching

**Comment by dataexcess** [comment]
Let me know if there's a specific branch I could test on to help you once you get to it :)
