### ISSUE TITLE
@walletconnect/modal cannot detect the metamask chrome-wallet

### ISSUE THREAD

**Issue by wenglk** [WalletConnect/web3modal#1207]
**Describe the bug**
When I connect the wallet using the modal generated by @web3modal/html, the system can detect Metamask web-wallet. 
But when I connect the wallet with the modal box generated by @walletconnect/modal, the system cannot detect Metamask web-wallet.

**SDK Version (if relevant)**
@walletconnect/ethereum-provider@2.9.0
@walletconnect/modal@2.5.9
@web3modal/html@^2.4.7

**To Reproduce**
```
// use @web3modal/htm
    const chains = [TestChain];
    const projectId = import.meta.env.VITE_APP_PROJECTID;

    const { publicClient } = configureChains(chains, [
        w3mProvider({ projectId }),
    ]);
    const wagmiConfig = createConfig({
        autoConnect: true,
        connectors: w3mConnectors({ projectId, chains }),
        publicClient,
    });
    const ethereumClient = new EthereumClient(wagmiConfig, chains);
    const web3modal = new Web3Modal({ projectId }, ethereumClient);
    web3modal.openModal();
```
![53f5d3e90d21d7a8aaa743fe69e804f](https://github.com/WalletConnect/walletconnect-monorepo/assets/50406113/4dc2c86a-5dfd-4348-8e85-79b70e5424b4)

```
    // use @walletconnect/modal
    const provider = await EthereumProvider.init({
        projectId: import.meta.env.VITE_APP_PROJECTID,
        chains: [1],
        showQrModal: true,
    });
    await store.providerSelect.connect();
    await store.providerSelect.enable();
```
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/50406113/5651b993-2705-40f0-af2a-0441e4dda5d8)

**Expected behavior**
The modal generated by walletconnect/modal also detects metamask web-wallet

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [114.0.5735.199]

**Comment by 0xAsimetriq** [comment]
`@walletconnect/modal` does not support following features:

1. Extension wallets (like one you mentioned)
2. Account view
3. Chain view
4. Custom ui elements like buttons
5. Third party connectors

All of these are features of `web3modal` https://docs.walletconnect.com/2.0/web/about-web3modal which is not compatible with simple ethereum-provider and requires wagmi.
