### ISSUE TITLE
@walletconnect/modal Cannot find module 'packages/modal-core/dist/_types/src/controllers/ModalCtrl' or its corresponding type declarations, Angular 16

### ISSUE THREAD

**Issue by KornOse** [WalletConnect/web3modal#1211]
Iam trying to migrate Walletconnect v1 to v2 in my Angular dapp but i have issues with two specific imports in @walletconnect/modal
`import("packages/modal-core/dist/_types/src/controllers/ModalCtrl").OpenOptions`
`import("packages/modal-core/dist/_types/src/types/controllerTypes").ModalCtrlState`
[error in node_modules/@walletconnect/modal/dist/_types/src/client.d.ts](https://i.stack.imgur.com/VUJpm.png)

error message is:
`Cannot find module 'packages/modal-core/dist/_types/src/controllers/ModalCtrl' or its corresponding type declarations.`

There is packages folder in modal repository ([here](https://github.com/walletconnect/modal)), however when i download package via npm the structure of files is somewhat different: [structure of files in node_modules](https://i.stack.imgur.com/faUGK.png) That is why it cannot find the path. I dont know if iam doing something wrong or its bug on walletconnect side.

Iam using:
- @angular/cli                    16.1.4
- typescript                      5.1.6

- Angular CLI: 16.1.4
- Node: 19.6.0
- Package Manager: npm 9.4.0

and i have latest @walletconnect packages:
- "@walletconnect/ethereum-provider": "^2.9.0",
- "@walletconnect/modal": "^2.6.0",

When i change the imports to: `import("../../../../modal-core/dist/_types/src/controllers/ModalCtrl").OpenOptions` or change the type to `any` everything works (to do that i need to create fork of the repository etc...)

[link to stackoverflow](https://stackoverflow.com/questions/76705138/walletconnect-modal-cannot-find-module-packages-modal-core-dist-types-src-con)

**Comment by 0xAsimetriq** [comment]
I think only way around this will be to set [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) option in your tsconfig.

**Comment by KornOse** [comment]
It is a bit of a workaround but yea, this does solve my problem i dont get the error anymore. Thanks for the answer.

**Comment by playground** [comment]
Hi @0xAsimetriq @KornOse, is there an Angular example that I can look at?

**Comment by glitch-txs** [comment]
@playground not at the moment, but feel free to make one and add it into [awesome-walletconnect repository](https://github.com/WalletConnect/awesome-walletconnect)
It should work using the [JavaScript package](https://docs.walletconnect.com/web3modal/javascript/about)
