### ISSUE TITLE
Meta Mask: Unrecognized chain ID

### ISSUE THREAD

**Issue by gameblock1** [WalletConnect/web3modal#1214]
### Link to minimal reproducible example

https://bridge.arbitrum.io/?l2ChainId=42170
Note: This website is not mine. I randomly figured out the same error happens when adding network in it.
### Summary

Hi
```
<Web3Modal
        projectId={projectId}
        ethereumClient={ethereumClient}
        defaultChain={arbitrumNova}
        chainImages={{
          42_170: ArbitrumNovaLogo,
        }}
    />
```

as seen above, I have set `defaultChain` to `arbitrumNova`. So when the user connects through MetaMask and if the user doesn't have Nova chain already, MetaMask asks to add that chain and then asks to switch to that. It's all ok but the following error is thrown in the console:
![image](https://github.com/WalletConnect/web3modal/assets/139673933/36c18aea-fa1f-4bdb-a668-0ed51d4e9364)

You can reproduce this using the website I have added its link.
Try by removing Nova chain from MetaMask first, then connect your wallet and from top of website choose Arbitrum Nova.

### List of related npm package versions

latest

**Comment by gameblock1** [comment]
I am testing with https://web3modal.com/ and I get the same error in Console,

![image](https://github.com/WalletConnect/web3modal/assets/139673933/0894702f-bd3c-4d27-840a-75baf1f22e34)
My MetaMask version: `10.33.1`
My Chrome version: `114.0.5735.199 (Official Build) (64-bit)`

**Comment by 0xAsimetriq** [comment]
Wait, so what's the issue? This is correct flow for chains that are not in your mm extension, you have to click approve (this is for beforementioned wallet_addEthereumChain method) and afterwards switch.

Also this error is thrown by metamask's extension not web3modal, so I'll close the issue for now (but the error is correct, you do have to add / approve new chain details first.)

**Comment by gameblock1** [comment]
Well if this error is expected, shouldn't it be caught by the modal in this process?

**Comment by 0xAsimetriq** [comment]
It is not propagated to modal (if it was you'd see connection failed error). Honestly it should be an "info" or "warn" log on metamask's side probably.

**Comment by gameblock1** [comment]
Thanks for the response.
By the way, what are those warnings in the image? There are a lot of them!
