### ISSUE TITLE
[bug] - Can't connect to coin98 wallet

### ISSUE THREAD

**Issue by fachryadhitya** [WalletConnect/web3modal#1221]
### Link to minimal reproducible example

https://share.cleanshot.com/FrvQWdTM

### Summary

Hi there! Good day to all of you!

First of all, thanks for creating this library. It's great, and I love using it in my project.

I'm currently facing an issue where I can't connect to the Coin98 wallet. I scanned the QR code from my app, but nothing happened afterwards.

Here is a screen recording: https://share.cleanshot.com/FrvQWdTM

When I click on Coin98, I scan the QR code, and the connection request appears on my phone, but nothing happens after I click 'Accept Connection'.

### List of related npm package versions

 "@wagmi/core": "^1.2.0",
    "@walletconnect/web3-provider": "^1.8.0",
    "@web3modal/ethereum": "^2.4.5",
    "@web3modal/html": "^2.4.5",

**Comment by 0xAsimetriq** [comment]
Nothing looks out of the ordinary, but I'd recommend this:

1. Remove `@walletconnect/web3-provider` (this is not needed in web3modal wagmi, are you using it for anything in particular?)
2. Update to latest web3modal versions (remove `^` from your package.json just in case to use strict versions)
3. Test with another wallet, does that work? If so, it could be an issue with coin98 wallet not supporting some of your proposed chains maybe.

**Comment by fachryadhitya** [comment]
I've upgraded to 2.7.0 and now I'm having this issues, also I have read the docs whether or not something is changed, but I've followed everything on it, 
<img width="400" alt="CleanShot 2023-07-20 at 13 09 45@2x" src="https://github.com/WalletConnect/web3modal/assets/58819726/65fb91d0-2337-406a-9a0c-bf043361ad43">

**Comment by 0xAsimetriq** [comment]
This happens when you have missmatch in wagmi / modal versions, try again via deleting you .lock file and re-installing. Alternatively this could mean that you are calling some modal functions that are not documented / before modal is initialized.

**Comment by fachryadhitya** [comment]
ok now I can open the modal but still can't connect to coin98, so you believe it's the error from their side?

**Comment by 0xAsimetriq** [comment]
Could be, do you see any error logs on dapp side after attempting to connect, usually wallets should send an error code and a message if something went wrong. Also some wallets had issues reading that "white on black" qrcode, on android phones, however now that you are updated to latest versions, you should always have "black on white".

Other than this, likely an issue on coin98 side.

**Comment by fachryadhitya** [comment]
Ok after upgrading, I can connect to it, thanks man!

**Comment by fachryadhitya** [comment]
sorry actually I still have problem with connecting directly with the coin98 app, it works with QR but when doing directly from their app, I just got 'Tap open to continue' and a loading screen, nothing is happened.. @0xAsimetriq

**Comment by fachryadhitya** [comment]
oh actually, when I click on "coin98" on mobile, it directs me to metamask rather than coin 98, is there a possible bug there?

https://github.com/WalletConnect/web3modal/assets/58819726/9d065a90-223e-43e4-833e-d2c409328b20

**Comment by 0xAsimetriq** [comment]
I just looked at their data in https://cloud.walletconnect.com and they have set wrong deeplink i.e. they added `wc://` instead of `coin98://` (or whatever theirs is). We'll reach out to them, but after that it depends how fast they resolve the issue. Will close this, as it is not web3modal related / wallet needs to fix their data.
