### ISSUE TITLE
[feature] Allow to select the particular wallet on Android

### ISSUE THREAD

**Issue by icedevml** [WalletConnect/web3modal#1228]
### What problem does this new feature solve?

Hello WalletConnect Team!

I have noticed that right now the Web3Modal has a different behavior depending on the smartphone platform where it was launched.

**How Web3Modal looks like on iPhone Safari:**
![image](https://github.com/WalletConnect/web3modal/assets/6976513/9896b58e-2cf8-4517-8208-ec74eddc828d)

**How Web3Modal looks like on Android Chrome:**
![image](https://github.com/WalletConnect/web3modal/assets/6976513/40ada629-d6a1-4fac-b1c7-2094171971f9)

The difference is that on iPhone the user could choose the exact wallet application he wants to use. The picker's user interface is similar to the one that is available on the Desktop.

On the other hand, Android only has a single `[Select Wallet]` button that would invoke the special `wc://...` URI. Then, the Android operating system would look for installed applications that claim to support that URI. The behavior is as follows:
* If none is installed, the button would not do anything;
* If only one compatible application is installed, it will be opened immediately;
* If multiple compatible applications are installed, the system would ask the user to pick the particular application to use;

The current behavior on Android would only allow to choose wallet apps that are already installed and are available in the form of a native application. As of the current state, it would not be possible to choose any wallet that is implemented purely in a form of a standard web application. There are many ways a wallet could operate without any native app:
* by keeping private keys in localStorage or Crypto API;
* by letting user scan the QR code with the private key from the "paper wallet";
* by connecting with the hardware device straight from the browser, using Web Bluetooth API or WebUSB API;

As an example, it wouldn't be possible to pick your [react-wallet demo app](https://react-wallet.walletconnect.com/) only on Android platform, even if that app would theoretically be listed on WalletConnect Cloud or would be listed manually by the dApp's developer in the modal's configuration.

### Describe the solution you'd like

My proposal is to add additional small button in the Web3Modal on Android, like that:

![image](https://github.com/WalletConnect/web3modal/assets/6976513/9bc89b98-85ec-43bc-9dc7-87eac568c05e)

The additional button would cause the modal to fall back to the standard app picker like on the Desktop or iPhone platforms.

Not only this would allow to pick wallet applications that are purely web based on Android, this small feature would also let the user to pick the particular wallet native application in case when there are issues with the operating system's picker (e.g. the user has unintentionally clicked "Remember my choice" and picked the wrong app).

Kindly please let me know if you would find such a feature useful in Web3Modal. If you agree, I could prepare the appropriate Pull Request to the project in order to implement that feature.

**Comment by 0xAsimetriq** [comment]
This will very likely be the case for our v3 release 👍

**Comment by 0xAsimetriq** [comment]
Implemented in v3 alpha
