### ISSUE TITLE
rpc link chainstacklabs for Mumbai is not working anymore

### ISSUE THREAD

**Issue by HT-Moh** [WalletConnect/web3modal#1232]
### Link to minimal reproducible example

easy to reproduce

### Summary

The rpc link for Mumbai is not working anymore [matic-mumbai.chainstacklabs.com](https://matic-mumbai.chainstacklabs.com/) it this cause the whole App to be slow. I think the new rpc is `https://rpc-mumbai.maticvigil.com/` 

https://github.com/wagmi-dev/wagmi/issues/2810

### List of related npm package versions

wagmi

**Comment by HT-Moh** [comment]
Yes agree the network calls are all failing for chainstacklabs only, however, with the following configuration I have it working but slow because first, it uses chainstacklabs, if it does not work it falls back it use polygon-mumbai.g.alchemy.com

![image](https://github.com/WalletConnect/web3modal/assets/34759569/8eb55f8d-b536-4c26-af69-3d011de4d4da)

**Comment by 0xAsimetriq** [comment]
Closing as it is not web3modal related, I suggest to open pr in wagmi to update default rpc or override it in your config.

**Comment by HT-Moh** [comment]
Workaround just use Alchemy and remove publicProvider() and everything works
```javascript
const { publicClient } = configureChains(chains, [
  // publicProvider(),
  alchemyProvider({ apiKey: "your key" }),
  // infuraProvider({ apiKey: "your key" }),
  w3mProvider({ projectId }),
]);
```
