### ISSUE TITLE
[bug] Safepal wallet not working about sign_message

### ISSUE THREAD

**Issue by hoangphuc36006** [WalletConnect/web3modal#1234]
### Link to minimal reproducible example

.....

### Summary

hi sir , i have problem with safepal wallet sign message , it not working
it okay with trust wallet + metamark on sign message ...
please check it sir 

1. connect wallet by web3modal 
2. click button to call sign message 
3. work on trust wallet + metamark but not working on safepal wallet
 
Sorry about my english ..

### List of related npm package versions

@web3modal/ethereum@2.7.0
@web3modal/html@2.6.2
@WagmiCore

**Comment by 0xAsimetriq** [comment]
I'm afraid we can't do anything about this on our end, so your best bet is to contact safepal team. As a sidenote, make sure to update your html package to latest one, so you have same version as ethereum.
