### ISSUE TITLE
[feature] E2E Functional Mock for non-happy-path

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1247]
Idea: use a functional mock of our wallet SDK to test some non-happy path scenarios including:
* wallet not responding within timeout
* wallet sending bad format
* complex permutations of accepted namespaces

**Comment by JonathanConn** [comment]
@arein What do you think about implementing web3wallet into our test-automation api?

I was planning on doing this in the future, and it would take me the same amount of time. Two birds, one stone

**Comment by da748** [comment]
Let's connect with thresholds and bind the company and the power supply unit to create a custom pack in

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JonathanConn** [comment]
Waiting for v3 example project that will replace lab

**Comment by arein** [comment]
Closing in favor of #1582
