### ISSUE TITLE
[bug] Hello when is web3modal going to update to latest v2.9.2 of walletconnect provider? thanks!

### ISSUE THREAD

**Issue by chusla** [WalletConnect/web3modal#1253]
### Link to minimal reproducible example

https://web3plugins.bubbleapps.io/version-test/web3modal

### Summary

looks like web3modal is still using out of date walletconnect version.  There are critical fixes in latest v2.9.2 that should be incorporated into web3modal.

### List of related npm package versions

https://github.com/WalletConnect/web3modal/blob/V2/package-lock.json

     "dependencies": {
        "@coinbase/wallet-sdk": "^3.6.6",
        "@ledgerhq/connect-kit-loader": "^1.1.0",
        "@safe-global/safe-apps-provider": "^0.17.1",
        "@safe-global/safe-apps-sdk": "^8.0.0",
        "@walletconnect/ethereum-provider": "2.9.0",
        "@walletconnect/legacy-provider": "^2.0.0",
        "@walletconnect/modal": "2.5.9",
        "@walletconnect/utils": "2.9.0",
        "abitype": "0.8.7",
        "eventemitter3": "^4.0.7"

**Comment by 0xAsimetriq** [comment]
This is coming from upstream wagmi depencency, will need to be updated there.
