### ISSUE TITLE
Unable to transfer using sendTransaction in IOS

### ISSUE THREAD

**Issue by souravsoftwareer** [WalletConnect/web3modal#1260]
### Link to minimal reproducible example

https://github.com/WalletConnect/react-native-examples/tree/main/dapps/v2Explorer

### Summary

I am getting issue in transfer. it is working fine in Android no issue at all.But in IOS transfer is not happening it gives following error
![1691561989231 (1)](https://github.com/WalletConnect/web3modal/assets/8158259/01486695-931d-44ca-888b-452c5c0ddfd3)

### List of related npm package versions

info Fetching system and libraries information...
System:
OS: macOS 13.3
CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
Memory: 1.51 GB / 32.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 17.0.0
path: ~/.nvm/versions/node/v17.0.0/bin/node
Yarn:
version: 1.22.19
path: /usr/local/bin/yarn
npm:
version: 8.1.0
path: ~/.nvm/versions/node/v17.0.0/bin/npm
Watchman: Not Found
Managers:
CocoaPods:
version: 1.12.1
path: /Users/john/.rvm/rubies/ruby-2.7.6/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 22.4
- iOS 16.4
- macOS 13.3
- tvOS 16.4
- watchOS 9.4
Android SDK: Not Found
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.9971841
Xcode:
version: 14.3/14E222b
path: /usr/bin/xcodebuild
Languages:
Java:
version: 17.0.7
path: /usr/bin/javac
Ruby:
version: 2.7.6
path: /Users/john/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.72.1
wanted: 0.72.1
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false

**Comment by 0xAsimetriq** [comment]
Does this happen in every ios wallet or (I believe it is trust in the screenshot?)

**Comment by ignaciosantise** [comment]
Hey @souravsoftwareer let's talk in the other issue you created -> https://github.com/WalletConnect/react-native-examples/issues/91
