### ISSUE TITLE
undefined .split at ens_split

### ISSUE THREAD

**Issue by gmixoulis** [WalletConnect/web3modal#1269]
### Link to minimal reproducible example

https://codesandbox.io/s/recursing-waterfall-gfdprj?file=/src/index.js

### Summary

I encountered an error when updating the code of my application, specifically related to the integration of Web3Modal and a newer version of a library called "wagmi". Despite updating the "wagmi" code, I didn't make any changes to the Web3Modal code, which resulted in a runtime error. The error message I'm getting is as follows:

index.js:1143 TypeError: Cannot read properties of undefined (reading 'split')
    at ens_split (index.js:732:1)
    at ens_normalize (index.js:682:1)
    at normalize (normalize.js:13:1)
    at A.fetchEnsAvatar (chunk-LAFZBYO7.js:2440:1)
    at Object.fetchProfile (index.js:43:1)
    at kt.fetchProfile (index.js:1141:1)
    at new kt (index.js:1123:1)
    at TemplateInstance._clone (lit-html.js:636:1)
    at ChildPart._commitTemplateResult (lit-html.js:913:1)
    at ChildPart._$setValue (lit-html.js:793:1)
    
    Steps to Reproduce
Update the application code, including the "wagmi" library, to a newer version.
Do not make any changes to the Web3Modal integration code.
Run the application and attempt to use Web3Modal.
Code Snippet

// ... (other imports)
import {
  EthereumClient,
  w3mProvider,
  w3mConnectors,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { WagmiConfig, createConfig, configureChains } from "wagmi";
// ... (other imports)

// ... (other code)

// Web3Modal setup
const projectId = process.env.REACT_APP_WALLET_CONNECT;

const conditional_chain =
  process.env.REACT_APP_ENV === "DEV" ? [mainnet, goerli] : [mainnet];

const { chains, publicClient } = configureChains(conditional_chain, [
  w3mProvider({ projectId, stallTimeout: 1_000 }),
  // ... (other providers)
  publicProvider(),
]);

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

// ... (other code)

// Web3Modal component
<Web3Modal
  themeVariables={{
    "--w3m-font-family": "Helvetica"

  }}
  themeMode={"dark"}
  projectId={projectId}
  ethereumClient={ethereumClient}
/> 

Expected Behavior
The application should run without any errors, and the Web3Modal integration should work as intended.

Actual Behavior
The error described above is thrown when using Web3Modal, specifically when attempting to access properties that are expected to be available in the Web3Modal code.

Additional Information
It appears that the error is related to the integration between Web3Modal and the "wagmi" library, possibly due to differences in versions or compatibility issues. I suspect that the error is arising from the fetchProfile function call in the Web3Modal code.

I would appreciate assistance in resolving this issue or guidance on any necessary changes to the Web3Modal integration to ensure compatibility with the updated "wagmi" library.

Please use your own projectid and infura api key.

Thank you for your help!

### List of related npm package versions

    "@web3modal/ethereum": "2.2.2",
    "@web3modal/react": "2.2.2",
    "viem": "^1.6.0",
    "wagmi": "^1.3.10",
    "react-app-rewired": "^2.2.1",

**Comment by 0xAsimetriq** [comment]
I believe `2.5.x` are the earliest versions of web3modal that will work with wagmi 1.x (if possible always use latest). Api around ens fetches changed when wagmi 0.12.x transitioned to v1, you are seeing errors associated tho this.
