### ISSUE TITLE
[bug] Connexion with Coinbase wallet on mobile doesn't work

### ISSUE THREAD

**Issue by csurbier** [WalletConnect/web3modal#1277]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Hi,

When trying to scan the QRCode from the coinbase wallet mobile app, it doesn't work. It is working fine with other wallets (metamask or ledger). I have the same issue with your "Connect Wallet" button on your main website : https://web3modal.com/

my config code:
`const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    ...w3mConnectors({ chains, version: 2, projectId }),
    new WagmiCoreConnectors.CoinbaseWalletConnector({
      chains,
      options: {
        appName: "My demo",
      },
    }),
  ],
  publicClient,
});`

### List of related npm package versions

 "@wagmi/core": "^1.3.8",
 "@walletconnect/modal-sign-html": "^2.6.0",
 "@web3modal/ethereum": "^2.7.1",
 "@web3modal/html": "^2.7.1",

**Comment by 0xAsimetriq** [comment]
Coinbase uses proprietary connection method, so scanning WalletConnect qr will not work. You seem to have already added their connector, so upon clicking on it, you should be presented with coinbases sdk view and their own qr code. That one will work.

**Comment by csurbier** [comment]
thanks for the answer. clicking on the coinbase connector doesn't work either with a javascript error : 
typeError: CoinbaseWalletSDK is not a constructor

**Comment by 0xAsimetriq** [comment]
Likely something wrong with this bit then `new WagmiCoreConnectors.CoinbaseWalletConnector`

**Comment by csurbier** [comment]
it's the same with your doc : https://docs.walletconnect.com/2.0/web3modal/html/wagmi/custom-wallets
:( 


const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    ...w3mConnectors({ chains, projectId }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: "wagmi demo",
      },
    }),
  ],
  publicClient,
});

**Comment by 0xAsimetriq** [comment]
Just noticed, there is mix of use cases, needs to be one or the other, besides this any wagmi connector is supported in `web3modal` packages.

```
"@walletconnect/modal-sign-html": "^2.6.0",

Or

"@web3modal/ethereum": "^2.7.1",
"@web3modal/html": "^2.7.1",
```

**Comment by csurbier** [comment]
ok thanks will have a look

**Comment by csurbier** [comment]
same. Found the issue :  https://github.com/coinbase/coinbase-wallet-sdk/issues/343
