### ISSUE TITLE
[bug] connection handling for "all wallets"

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1285]
### Link to minimal reproducible example

See screenshot and text

### Summary

1) No user feedback when websocket cannot be established

Repro steps:
a - open https://web3modal-laboratory-v3.vercel.app/
b - disable network
c - open "all wallets"

Expected behavior: error message that connection cannot be established
Actual behavior: nothing happens

<img width="1728" alt="Screenshot 2023-08-21 at 12 38 21 PM" src="https://github.com/WalletConnect/web3modal/assets/966091/22df5eca-91e3-42f4-85d5-c3843be794f4">

Relates to https://github.com/WalletConnect/web3modal/issues/1264

### List of related npm package versions

current

**Comment by 0xAsimetriq** [comment]
Closing in favor of #932
