### ISSUE TITLE
[bug] connecting handling for QR code

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1287]
### Link to minimal reproducible example

See below

### Summary

Repro steps:
a - open https://web3modal-laboratory-v3.vercel.app/
b - disable network
c - open "WalletConnect"

Expected behavior: QR code is NOT shown but error message is shown
Actual behavior: QR code shows with NO indication of a failure

End-users will not be able to connect here

<img width="1728" alt="Screenshot 2023-08-21 at 12 42 47 PM" src="https://github.com/WalletConnect/web3modal/assets/966091/ede335d7-db18-4bb1-8026-1a52b8fd4332">

### List of related npm package versions

latest

**Comment by mabsattar** [comment]
Hi, i would like to work on this, can you please assign me
