### ISSUE TITLE
[bug] Weak network / offline handling

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1289]
### Link to minimal reproducible example

See below

### Summary

Repro steps:
a - connect wallet to https://lab.web3modal.com/with-wagmi/react
b - disable network
c - click "Sign Message"

Actual behavior: button not greyed out and no error message
Expected behavior: button greyed out and failure message if there is no `ACK` within X seconds or if the `ACK` is `false` with an error message

<img width="1728" alt="Screenshot 2023-08-21 at 12 46 34 PM" src="https://github.com/WalletConnect/web3modal/assets/966091/1e62bce0-dab7-4992-ab22-d83c52c74014">

### List of related npm package versions

v2 latest

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin
