### ISSUE TITLE
[feature] Add peer metadata to Web3Modal

### ISSUE THREAD

**Issue by trevormil** [WalletConnect/web3modal#1298]
### What problem does this new feature solve?

Currently, there is no option to use Web3Modal with the peer metadata from Web3Wallet. For example, the [docs](https://docs.walletconnect.com/2.0/web3wallet/wallet-usage) initiate it like the code snippet below.

As a result, connecting with Rainbow Wallet (and I am sure other wallets too) results in a blank icon and a connect message from "Unknown Dapp".

```import { Core } from '@walletconnect/core'
import { Web3Wallet } from '@walletconnect/web3wallet'

const core = new Core({
  projectId: process.env.PROJECT_ID
})

const web3wallet = await Web3Wallet.init({
  core, // <- pass the shared `core` instance
  metadata: {
    name: 'Demo app',
    description: 'Demo Client as Wallet/Peer',
    url: 'www.walletconnect.com',
    icons: []
  }
})```

### Describe the solution you'd like

 It would be nice if dApps could define their peer metadata, so they can brand the connections. So for example, if I had a dApp named "Dapp ABC", when I connect to Rainbow via WalletConnect, it would say "Dapp ABC" wants to connect.

**Comment by glitch-txs** [comment]
This can be done already through wagmi's connector, @0xAsimetriq maybe we could add it as an option to the defaultWagmiConfig fn as well?

**Comment by 0xAsimetriq** [comment]
Shipped in beta.5 https://github.com/WalletConnect/web3modal/releases/tag/3.0.0-beta.5
