### ISSUE TITLE
[bug] `EthereumClient` dose not work with web3js client

### ISSUE THREAD

**Issue by BeroBurny** [WalletConnect/web3modal#1300]
### Link to minimal reproducible example

https://codesandbox.io/s/web3modal-bug-kt583w?file=/src/App.js

### Summary

Using Web3js provider throw error `p.client(...).getDefaultChain is not a function`

note you need to provide your own variables for `projectId` and `provider`

### List of related npm package versions

* @web3modal/ethereum
* @web3modal/react
* web3

**Comment by 0xAsimetriq** [comment]
Right now v2 web3modal works with wagmi/viem only. We are making progress on cross-client compatibility in v3. Meanwhile something like https://docs.walletconnect.com/2.0/advanced/walletConnectModal/about could be used with web3
