### ISSUE TITLE
Document a UMD/SRI example [feature/docs]

### ISSUE THREAD

**Issue by fulldecent** [WalletConnect/web3modal#1305]
### What problem does this new feature solve?

The current examples with CDN (https://docs.walletconnect.com/2.0/web3modal/html/wagmi/installation#add-packages-cdn) do not support SRI. That means it makes you vulnerable to tampering of the files from the CDN (WANGMI).

### Describe the solution you'd like

Please also include an example which uses UMD supporting SRI. (The `integrity="sha256-ZgF78GrWmXH9wGSheWLlf5NCPdDaVPM+jYF5Pg0LwT4=" crossorigin="anonymous"` you see on Bootstrap and many other places.)

Here is a misguide attempt at starting this for my project.

I don't know where I'm going with this. And so I would appreciate documentation on this path.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Hi</title>
  <link rel="stylesheet" href="assets/main.css">
  <script src="https://cdn.jsdelivr.net/npm/ethers@6.7.1/dist/ethers.umd.min.js" integrity="sha256-ZgF78GrWmXH9wGSheWLlf5NCPdDaVPM+jYF5Pg0LwT4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@walletconnect/ethereum-provider@2.10.0/dist/index.umd.js" integrity="sha256-rM0h9J2B4+s6RJelZKsSCiprdJi3Ret46ZwVj4YNRW8=" crossorigin="anonymous"></script>

</head>
<body>
  <article class="lead">
    <h1>Send a 1 ETH tip</h1>
    <button id="buy" type="button" class="btn btn-lg">Connect</button>
  </article>
  <script>
document.getElementById("buy").addEventListener("click", async function() {
  const provider = await global["@walletconnect/ethereum-provider"].EthereumProvider.init({
    projectId: '262de461149a3d0a834baf5a0d19924d', // required
    chains: [1], // required
    // showQrModal: true // requires @walletconnect/modal
  })  

/*
    const wcProvider = new WalletConnectProvider({
      infuraId: "YOUR_INFURA_ID" // Replace with your Infura Project ID
    });
    await wcProvider.enable();
    provider = new ethers.Web3Provider(wcProvider);

  try {
    const signer = await provider.getSigner();
    const txResponse = await signer.sendTransaction({
      to: "0x0000000000000000000000000000000000000000",
      value: ethers.parseEther("0"),
    });
  } catch (err) {
    console.error(err);
  }
  */
});
  </script>

</body>
</html>
```

**Comment by fulldecent** [comment]
I understand that unpkg is the preferred CDN, and I'm happy to use them if they can properly use SRI.

At the moment I cannot find the correct UMD file on unpkg. Tried looking at:

https://unpkg.com/@web3modal/html@2.7.1/umd

**Comment by bores32** [comment]
+1

Would be really cool to have a UMD file for @web3modal/html

Or some guidance on how we can generate it ourselves and make it work with the example above.

We are forced to use V1 until there is a solution for this.

**Comment by glitch-txs** [comment]
closing in favor of https://github.com/WalletConnect/web3modal/issues/1354 let's move the discussion there. Thanks! :)
