### ISSUE TITLE
Add publishing to jsDelivr

### ISSUE THREAD

**Issue by fulldecent** [WalletConnect/web3modal#1307]
### Link to minimal reproducible example

https://www.jsdelivr.com/package/npm/web3modal

### Summary

jsDelivr does not see the current version of web3modal and thousands of people (according to stats on that page) are accessing the old versions thinking they are the latest.

Please update how the package is published so that jsDelivr sees the latest version.

I understand that another CDN is the "preferred" CDN. However the documentation here does not say "don't use other CDNs".

Also I'll note that the preferred CDN does not support SRI and UMD so this is why I am trying to use jsDelivr.

### List of related npm package versions

1.9.2

**Comment by 0xAsimetriq** [comment]
There are multiple cdn providers, so it will be hard for us to document all of them. But all of the work the same i.e. package just needs to be published to npm. Here is how to import one of web3modal packages as per their esm guides

```
https://cdn.jsdelivr.net/npm/@web3modal/html/+esm
```

So just replace unpkg we have in docs with this. Package you referenced `https://www.jsdelivr.com/package/npm/web3modal` is for older version and will remain that as few other people host their servers and run on old modal still.

**Comment by fulldecent** [comment]
Thank you for the reference to the correct page. I see the issue was that I was accessing `[web3modal](https://www.jsdelivr.com/package/npm/web3modal)` which was deprecated in favor of `@web3modal/html`.

It seems the old package was deprecated correctly, as [shown on NPM](https://www.npmjs.com/package/web3modal).

However, unfortunately, when viewed on the jsDelivr website, it is not shown as deprecated. I [reported this issue to them](https://github.com/jsdelivr/jsdelivr/issues/18525).

---

As for SRI, I would like to move that to a separate issue.

**Comment by fulldecent** [comment]
All notes about published so that it can be used in the browser with UMD + SRI are at https://github.com/WalletConnect/web3modal/issues/1305
