### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by PabloFMM** [WalletConnect/web3modal#1319]
### Link to minimal reproducible example

Conecting Safe L2 Optimism to Maniforld with WalletConect

### Summary

Conecting Safe L2 Optimism to Maniforld with WalletConect

It seems that Manifold isn’t currently integrated with the safe and cannot be added as a custom safe app. It would be best to contact them and share the notion link above

No new updates on this yet, you can try adding the dapp as a custom app if it’s compatible with safe apps: [Add a custom Safe App | Safe Help Center 1](https://help.safe.global/en/articles/40859-add-a-custom-safe-app)

You can check the link below for the latest update from the team on the issue:

[https://safe-global.notion.site/safe-global/WalletConnect-v2-update-Issues-and-solutions-for-smart-wallets-3fc32fad6af4485fa5823eaebd486819](url)

![image](https://github.com/WalletConnect/web3modal/assets/9748498/25324812-6efd-4127-8ed4-6005da74015b)

### List of related npm package versions

NA

**Comment by 0xAsimetriq** [comment]
Ty for reporting, this is something we are tracking on a protocolo level at `walletconnect-monorepo` repository, so will close here.
