### ISSUE TITLE
[bug]  Does Web3Modal v3 have to rely on React?

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1322]
### Link to minimal reproducible example

[https://docs.walletconnect.com/2.0/web3modal/v3/vue/about](https://docs.walletconnect.com/2.0/web3modal/v3/vue/about
)
[https://docs.walletconnect.com/2.0/web3modal/v3/html/about](https://docs.walletconnect.com/2.0/web3modal/v3/html/about)

### Summary

When `Vue` does not use react, an error will be reported when running Web3Modal v3.0.0 ` Could not resolve "react"`
Vue不使用React时，运行Web3Modal v3.0.0 会报错 ` Could not resolve "react"`

When `html` runs Web3Modal v3.0.0, an error message ` Could not resolve "react"`
html 运行 Web3Modal v3.0.0 会报错 ` Could not resolve "react"`

Does Web3Modal v3 have to rely on React?
Web3Modal v3必须依赖React吗？

### List of related npm package versions

``` json
{
	"name": "Web3Modal-V3",
	"private": true,
	"version": "0.0.0",
	"type": "module",
	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"preview": "vite preview"
	},
	"dependencies": {
		"vue": "^3.3.4",
		"@wagmi/core": "^1.4.1",
		"@web3modal/wagmi": "3.0.0-alpha.6",
		"viem": "^1.10.8"
	},
	"devDependencies": {
		"@vitejs/plugin-vue": "^4.2.3",
		"vite": "^4.4.5"
	}
}
```

**Comment by 0xAsimetriq** [comment]
This is something we will address on our end for next alpha release, you shouldn't need to do anything extra once it is fixed 👍

**Comment by hhun** [comment]
``` json
{
	"name": "Web3Modal-V3",
	"private": true,
	"version": "1.0.0",
	"type": "module",
	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"preview": "vite preview"
	},
	"dependencies": {
		"vue": "^3.3.4",
		"@wagmi/core": "^1.4.1",
		"@web3modal/wagmi": "3.0.0-alpha.8",
		"viem": "^1.10.8"
	},
	"devDependencies": {
		"@vitejs/plugin-vue": "^4.2.3",
		"vite": "^4.4.5"
	}
}
```
Using `3.0.0-alpha.8`  will still report an error `Could not resolve "react"`
使用 `3.0.0-alpha.8` 依然会报错 `Could not resolve "react"`

请问要怎么解决这个问题？
Please tell me how to solve this problem？

**Comment by 0xAsimetriq** [comment]
@hhun could you create a sandbox with minimal reproduction where this error can be investigated please

**Comment by 0xAsimetriq** [comment]
I've released alpha.9 with an updated import for one of the dependencies that could've needed `react`. Can you please try it out. Here is simple vue project where I was able to run it with no issues (make sure to add your project id in App.vue):

https://stackblitz.com/edit/vitejs-vite-jekevf?file=src%2FApp.vue

**Comment by hhun** [comment]
> I've released alpha.9 with an updated import for one of the dependencies that could've needed `react`. Can you please try it out. Here is simple vue project where I was able to run it with no issues (make sure to add your project id in App.vue):
> 
> https://stackblitz.com/edit/vitejs-vite-jekevf?file=src%2FApp.vue

After using `npm install` to initialize the project, using `yarn dev` **will not report an error**
After using `yarn install` to initialize the project, using `yarn dev` **will report an error**

I don’t know if it’s because `yarn` is not compatible with `peerDependencies`

**Comment by 0xAsimetriq** [comment]
It most probably is, especially if you are not using latest yarn.

**Comment by hhun** [comment]
> It most probably is, especially if you are not using latest yarn.

I'm using v1.22.19, is the latest version

**Comment by 0xAsimetriq** [comment]
I believe yarn v1 is no longer maintained? They are on versin 3 or 4 now probably on their new packages.

**Comment by vitusha-rat** [comment]
I'm using yarn v3 and face same problems

**Comment by glitch-txs** [comment]
Hi @vitusha-rat , could you try adding this to the package.json file?

```
"optionalDependencies": {
    "react": ">=17",
    "react-dom": ">=17"
  },
```

**Comment by hhun** [comment]
After adding `optionalDependencies` in `package.json`, it can run normally.

``` json
	"optionalDependencies": {
		"react": ">=17",
		"react-dom": ">=17",
		"typescript": ">=5.0.4"
	}
```

**Comment by hhun** [comment]
@vitusha-rat 
After adding `optionalDependencies` in `package.json`, it can run normally.

``` json
	"optionalDependencies": {
		"react": ">=17",
		"react-dom": ">=17",
		"typescript": ">=5.0.4"
	}
```

**Comment by vitusha-rat** [comment]
@hhun @glitch-txs 
Thanks! Works now:)

**Comment by yucheng-Li** [comment]
@xzilja It is not work for me in vue2, has any other method solve it?

**Comment by glitch-txs** [comment]
@yucheng-Li feel free to open a new issue stating your problem or a GitHub discussion, you can tag me there too, thanks!
