### ISSUE TITLE
[bug] Chrome version lower than v 111 does not support color mix syntax

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1323]
### Link to minimal reproducible example

[https://web3modal-laboratory-v3.vercel.app](https://web3modal-laboratory-v3.vercel.app/)/

### Summary

Chrome version lower than v 111 does not support color mix syntax
Chrome 版本低于v111不支持 color-mix 语法

### List of related npm package versions
**Web3modal v3**

Chrome v100
![Chrome v100](https://github.com/WalletConnect/web3modal/assets/19625243/da58788d-84eb-4df0-9654-e91f957713a0)

Chrome v111
![Chrome v111](https://github.com/WalletConnect/web3modal/assets/19625243/78d40041-9bd5-486a-b201-77b3a0448959)

**Comment by 0xAsimetriq** [comment]
Should be fixed in alpha.8, let me know if you are still seeing this issue (make sure to install dependencies fresh)
