### ISSUE TITLE
[usage] Web3Modal connect/disconnect not working on Next.js App Router

### ISSUE THREAD

**Issue by ogous** [WalletConnect/web3modal#1328]
### Link to minimal reproducible example

https://web3modal-bug.vercel.app/

### Summary

Hi guys,

I have encountered a bug that effects actions like connect and disconnect on Next.js App Router. It only happens when navigating to any other page after app initialization.

Reproduction steps:

V1:
- Navigate to second page
- Try to connect with Web3Button

V2:
- Connect your wallet with Web3Button
- Navigate to second page
- Try to disconnect

In above scenarios connect/disconnect actions do nothing, normal should be triggered events `ACCOUNT_CONNECTED` and `ACCOUNT_DISCONNECTED` are not emitted. If you refresh the page, only then you can see you are already connected/disconnected, but ofcourse it breaks UX entirely. 

Important note it is only happens in builded app, not happening in dev mode. So I created a minimal example to see it on production mode.

Code repo is here: https://github.com/ogous/web3modal-bug

### List of related npm package versions

  "@web3modal/ethereum": "^2.7.1",
  "@web3modal/react": "^2.7.1",
  "next": "^13.4.19",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
   "viem": "^1.10.4",
   "wagmi": "^1.4.1"

**Comment by 0xAsimetriq** [comment]
I think issue is in  `<WalletConnectProvider>`, it is probably rendered multiple times and re-creates wagmi clients multiple times, which leads to incorrect internal states. If you move wagmi config and ethereum client initialisation outside of your components (up to app root) where they only get created once, it should help resolve the issue.

**Comment by ogous** [comment]
@0xAsimetriq thanks for your insight.

It was really reinitialization of wagmi & ethereum client. Because Next.js App Router, unlike Page Router, seperates server and client components and ship less js code on pages, rerenders every client component on route change, no matter where you put it. And context providers have to be client components like Wagmi Provider. So initialized client should be persisted in useState in Next.js App Router or injected from somewhere else that is not reinitialized.

It could help a basic example on Docs for Next.js App Router, like [this one](https://tanstack.com/query/v4/docs/react/guides/ssr#using-the-app-directory-in-nextjs-13).

**Comment by mlenser** [comment]
@ogous how did you solve this issue?

**Comment by guotie** [comment]
same question, how to solve? @ogous

**Comment by guotie** [comment]
I think I solve this question.

Before:
```
"use client";

import { goerli, mainnet } from "viem/chains";
import { createWeb3Modal, defaultWagmiConfig } from "@web3modal/wagmi/react";
import { WagmiConfig } from "wagmi";

// 1. Get projectId
const projectId = "xxxxxxxx";

function WalletProvider({ children }: { children?: React.ReactNode }) {
  // 2. Create wagmiConfig
  const modalConfig = {
    name: "xxxx",
    description: "xxxx",
    url: "https://web3modal.com",
    icons: ["https://avatars.githubusercontent.com/u/37784886"],
  };
  
  const chains = [goerli, mainnet];
  const wagmiConfig = defaultWagmiConfig({
    chains,
    projectId,
    metadata: modalConfig,
  });
  createWeb3Modal({ wagmiConfig, projectId, chains });
  console.log("web3 modeal created");

  return <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>;
}

export default WalletProvider;
```


After:

```
"use client";

import { goerli, mainnet } from "viem/chains";
import { createWeb3Modal, defaultWagmiConfig } from "@web3modal/wagmi/react";
import { WagmiConfig } from "wagmi";

// 1. Get projectId
const projectId = "xxxxxxxx";

  // 2. Create wagmiConfig
  const modalConfig = {
    name: "xxxx",
    description: "xxxx",
    url: "https://web3modal.com",
    icons: ["https://avatars.githubusercontent.com/u/37784886"],
  };
  
  const chains = [goerli, mainnet];
  const wagmiConfig = defaultWagmiConfig({
    chains,
    projectId,
    metadata: modalConfig,
  });
  createWeb3Modal({ wagmiConfig, projectId, chains });
  console.log("web3 modeal created");

function WalletProvider({ children }: { children?: React.ReactNode }) {
  return <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>;
}

export default WalletProvider;
```

**Comment by da748** [comment]
Automatic connect with three holds and bind the company and the power supply unit and create a custom design website for all in one pack
