### ISSUE TITLE
A better UX with individually named walletes

### ISSUE THREAD

**Issue by miohtama** [WalletConnect/web3modal#134]
I run some in-house user testing with Web3modal this week with technically-sawy audience who are new to a blockchain. 

This is the biggest issue: Users do not understand "WalletConnect" and naming a protocol is too technical for them. They go to App Store and try to find "WalletConnect".

Instead, I suggest one actually has the logos and names of invididual wallets on the selector. Clicking any of them would then just open the same WalletConnect QR code.

**Comment by pedrouid** [comment]
This is very similar to issue #127 but I think this should be handled on the WalletConnect QR Code modal instead or as a helper page on WalletConnect's website.

That way it doesnt need to maintain or curate a list on the Web3Modal itself which feels very opinionated

**Comment by miohtama** [comment]
I agree with your sentiment. It is a tricky political question to maintain the list. I am happy to take the first stab after there is a rough consensus on how the list is maintained and user.

We could still populate Web3modal choices from the list directly - esp. if the developer chooses to do so. We basically need a database of three items (WalletConnect supported flag, logo, name). Maybe toss in the download links for the additional better user experience for users who do not yet have a wallet installed.

**Comment by pedrouid** [comment]
My main concern with configuring a list by the developer is that it adds overhead to support WalletConnect, the less required options the better. We could perhaps make it configurable but optional. But even then I feel like this is a WalletConnect issue and not a Web3Modal issue.

The Web3Modal issue here is to suggest downloading apps in case the user doesnt have an of the wallets

**Comment by miohtama** [comment]
Would you agree if I just create this list with wallet logos and put into WalletConnect repo? I will add an example how to integrate with Web3modal. Then developers can do whatever they want this list, to choose either to use WalletConnect protocol link or populate the list with wallet logos.

**Comment by pedrouid** [comment]
Fair enough, sounds good!

**Comment by hackyguru** [comment]
All the feedback from this thread is addressed in W3MV2. Thank you :)
