### ISSUE TITLE
[feature] jump to  `Trust Wallet` will not enter the `wallet connection page`

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1340]
### What problem does this new feature solve?

When opening the d app of `Web3Modal V3` in the browser that comes with the mobile phone system

When you jump to `other crypto wallets` from the mobile browser,  **will** enter the  `wallet connection page`.

When you jump to `Trust Wallet` from the mobile browser, **will not** enter the  `wallet connection page`.

### Describe the solution you'd like

I don’t know if it is a V3 problem or Trust Wallet app that causes this problem.

**Comment by 0xAsimetriq** [comment]
Could you provide more explanation on this one please, not entirely sure I am following. Maybe a video showing correct / incorrect flows?

**Comment by 0xAsimetriq** [comment]
Closing as inn-active, for some further ideas: If something is not working within the wallet, there is not much we can do and issue should be reported to Trust.
