### ISSUE TITLE
[feature] The interface is not available in mainland China

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1341]
### What problem does this new feature solve?

> verify.walletconnect.com
relay.walletconnect.com
rpc.walletconnect.com

Mainland China cannot access these interfaces normally.
The reason is that the data center IP used by walletconnect.com is blocked in mainland China.
If you nest a layer of CDN, the original data center IP will be hidden and will not be blocked.

### Describe the solution you'd like

Can you add parameters to set these domain names?

It is best to add `walletconnect.com` all domain name and a layer of `CloudFlare` cdn, And hide the data center IP,In this way, mainland China can normally access the WalletConnect API

**Comment by 0xAsimetriq** [comment]
Yep we are aware and working on `.org` fallbacks. I believe verify and relay should already have them in place and rpc.walletconnect.com / api.web3modal.com will get them soon.

**Comment by hhun** [comment]
It is best not to use the domain `api.web3modal.com`. I am afraid that `web3modal.com` will also be blocked, That's even worse,

You can use `rpc.walletconnect.org` or other domain

**Comment by 0xAsimetriq** [comment]
We added fallbacks for `api.web3modal.com` and `rpc.walletconnect.com` to `.org` (relay and verify should fall back on another sdk level). Let me know if you are still experiencing issues with this. Available in beta.3

**Comment by fawaikuangtutu** [comment]
hi @xzilja , I'm using @web3modal/wagmi 5.0.6, still facing this issue.
