### ISSUE TITLE
[feature] add `{timeout: 5000}` option for `web3Modal.open()` async function

### ISSUE THREAD

**Issue by SergeyVolynkin** [WalletConnect/web3modal#1344]
### What problem does this new feature solve?

The `walletConnectModal.open()` may get stuck in an infinite load in case some external wallet connect dependencies fail to load (rough example described here: https://github.com/WalletConnect/web3modal/issues/1026#issuecomment-1726344438)

So we would want to allow `walletConnectModal.open()` to timeout and allow users to retry action (maybe including re-loading failed-to-load assets and APIs)

### Describe the solution you'd like

```tsx
const walletConnectModal = useWeb3Modal();
await walletConnectModal.open({timeout: 5000}) // 5s timeout
```

**Comment by glitch-txs** [comment]
This is done by Wagmi's WalletConnectConnector, maybe we can improve it there
