### ISSUE TITLE
[feature] introduce configuration to disable(or minimize) `localStorage` use (`QuotaExceededError`)

### ISSUE THREAD

**Issue by SergeyVolynkin** [WalletConnect/web3modal#1345]
### What problem does this new feature solve?

Hi WalletConnect team,

When using `@web3modal/react` the `wc@2:core:0.3//history`(and other `wc@2` keys) seems to save quite a lot of records to LocalStorage. I've been using WalletConnect for just a few days and can see almost 3,000 records in LocalStorage.

In production we receive quite a bit of Sentry errors that users run out of localStorage space:
![image](https://github.com/WalletConnect/web3modal/assets/34238697/9289506a-93fb-41b5-ae83-aed528736957)

previous discussions on the issue: 
- https://github.com/WalletConnect/walletconnect-monorepo/issues/3513
- https://github.com/orgs/WalletConnect/discussions/3566#discussioncomment-6980511

### Describe the solution you'd like

(A)
Switch to a more appropriate Web API to store larger amounts of data, e.g. [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) instead of localStorage (which is only 5MB, ref: https://web.dev/storage-for-the-web/)

(B)
Provide the flag to lower localStorage usage (or cleanup on certain threshold)
```tsx
 <Web3Modal
    projectId={…}
    /*… */
    limitedLocalStorageUse={true}
 />
```

**Comment by SergeyVolynkin** [comment]
Follow-up question: is it safe to implement a mechanism in the app code to cleanup WalletConnect local-storage items when the app reaches the `localStorage` limit, will it break `WalletConnect` internal assumptions about the data it has persisted to `localStorage`?

**Comment by glitch-txs** [comment]
how could you share your Wagmi version?

**Comment by SergeyVolynkin** [comment]
> @glitch-txs  how could you share your Wagmi version?

```
// package.json
"viem": "^1.7.0",
"wagmi": "^1.3.10"
```

```
// versions resolved in yarn.lock

viem@^1.0.0, viem@^1.7.0:
  version "1.7.0"
  resolved "https://registry.yarnpkg.com/viem/-/viem-1.7.0.tgz#9d6fbdb4c7db2ef31fe5344fb8fc3b9103ae3225"
  integrity sha512-S4SclYe0Oca6TuPh2YPI3BzfC7a4UvN7TRDCWwpoVNnu9+4z2hqCZhW+6aF1yufgSwdezNsF14vztE/P4eMdBw==

wagmi@^1.3.10:
  version "1.3.10"
  resolved "https://registry.yarnpkg.com/wagmi/-/wagmi-1.3.10.tgz#100aeaecf7a030e9e91118d366a734ec30c56551"
  integrity sha512-MMGJcnxOmeUZWDmzUxgRGcB1cqxbJoSFSa+pNY4vBCWMz0n4ptpE5F8FKISLCx+BGoDwsaz2ldcMALcdJZ+29w==
```

**Comment by glitch-txs** [comment]
could you try updating Wagmi to the latest version (1.4.2 or higher)?
This will update the WalletConnectConnectors dependencies as we've done already some improvements on this

**Comment by SergeyVolynkin** [comment]
Ack, thank you @glitch-txs, I will bump the deps to be the following:
```
"viem": "^1.11.0",
"wagmi": "^1.4.2"
```

And will monitor Sentry if the error rate drops in our environments

**Comment by SergeyVolynkin** [comment]
Should we keep this feature request open, the (A) proposal to use `IndexedDB API` instead of `localStorage`? Is it something WalletConnect team looks into? Google engineering teams (from https://web.dev/storage-for-the-web/) recommend using  `IndexedDB API` instead of `localStorage`

**Comment by 0xAsimetriq** [comment]
Better localStorage management should result  in fewer if not entirely no errors on latest wagmi version, so I will close this one for now. Also, you might still see a few of these due to older localStorage entries, but errors should fade away once these expire and are cleaned up. We are also doing more work on this, but in https://github.com/WalletConnect/walletconnect-monorepo if you want to keep an eye on this. IndexDB is indeed one of the things we are looking into.

**Comment by SergeyVolynkin** [comment]
Ack, thank you for helping to resolve this @0xAsimetriq @glitch-txs
