### ISSUE TITLE
[bug] Page content still shifting when Modal is opened

### ISSUE THREAD

**Issue by pauldemarco** [WalletConnect/web3modal#1347]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

1. Open the landing page for v3 (https://web3modal.com/)
2. Click the "CONNECT WALLET" button at the top right
3. Notice how the page contents shift when the modal opens.

I am testing with a Chrome browser on the desktop.

Previous issue from beta3: https://github.com/WalletConnect/web3modal/issues/1343

### List of related npm package versions

3.0.0-beta.4

**Comment by 0xAsimetriq** [comment]
Replied in previous issue https://github.com/WalletConnect/web3modal/issues/1343#issuecomment-1728880972
