### ISSUE TITLE
[feature] V3 Vue + wagmi SyntaxError: does not provide an export named 'IJsonRpcProvider'

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1349]
### What problem does this new feature solve?

> Uncaught (in promise) SyntaxError: The requested module '/v132/@walletconnect/jsonrpc-utils@1.0.8/es2022/jsonrpc-utils.mjs' does not provide an export named 'IJsonRpcProvider'

### Describe the solution you'd like

``` js
import { createWeb3Modal, defaultWagmiConfig } from 'https://esm.sh/@web3modal/wagmi?bundle'
import { mainnet } from 'https://esm.sh/@wagmi/core/chains?bundle'

// 1. Define constants
const projectId = 'YOUR_PROJECT_ID'

// 2. Create wagmiConfig
const chains = [mainnet]
const wagmiConfig = defaultWagmiConfig({ chains, projectId, appName: 'Web3Modal' })

// 3. Create modal
const modal = createWeb3Modal({ wagmiConfig, projectId, chains })

modal.open()

**Comment by glitch-txs** [comment]
Hi could you share a minimal reproducible example of this issue?

**Comment by 0xAsimetriq** [comment]
You forgot to add `beta` tag to web3modal dependency, here is a working example
https://github.com/WalletConnect/web3modal/blob/V3/examples/html-wagmi/main.js

**Comment by hhun** [comment]
> You forgot to add `beta` tag to web3modal dependency, here is a working example https://github.com/WalletConnect/web3modal/blob/V3/examples/html-wagmi/main.js

Still reporting an error: `Uncaught (in promise) SyntaxError: The requested module '/v132/@walletconnect/jsonrpc-utils@1.0.8/es2022/jsonrpc-utils.mjs' does not provide an export named 'IJsonRpcProvider'`
``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Web3Modal V3</title>
</head>
<body>

<w3m-button></w3m-button>
<w3m-network-button></w3m-network-button>
<w3m-connect-button></w3m-connect-button>
<w3m-account-button></w3m-account-button>

<button id="open-connect-modal">Open Connect Modal</button>
<button id="open-network-modal">Open Network Modal</button>

</body>

<script type="module">
import { arbitrum, mainnet } from 'https://esm.sh/@wagmi/core/chains?bundle'
import { createWeb3Modal, defaultWagmiConfig } from 'https://esm.sh/@web3modal/wagmi@beta?bundle'

// 1. Create projectId
const projectId = 'YOUR_PROJECT_ID'

// 2. Create wagmiConfig
const chains = [mainnet, arbitrum]
const wagmiConfig = defaultWagmiConfig({ chains, projectId, appName: 'Web3Modal' })

// 3. Create modal
const modal = createWeb3Modal({ wagmiConfig, projectId, chains, themeMode: 'light' })

// 4. Trigger modal programaticaly
const openConnectModalBtn = document.getElementById('open-connect-modal')
const openNetworkModalBtn = document.getElementById('open-network-modal')

openConnectModalBtn.addEventListener('click', () => modal.open())
openNetworkModalBtn.addEventListener('click', () => modal.open({ view: 'Networks' }))
</script>

</html>
```

**Comment by hhun** [comment]
@0xAsimetriq @glitch-txs 

Still reporting an error: `Uncaught (in promise) SyntaxError: The requested module '/v132/@walletconnect/jsonrpc-utils@1.0.8/es2022/jsonrpc-utils.mjs' does not provide an export named 'IJsonRpcProvider'`
``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Web3Modal V3</title>
</head>
<body>

<w3m-button></w3m-button>
<w3m-network-button></w3m-network-button>
<w3m-connect-button></w3m-connect-button>
<w3m-account-button></w3m-account-button>

<button id="open-connect-modal">Open Connect Modal</button>
<button id="open-network-modal">Open Network Modal</button>

</body>

<script type="module">
import { arbitrum, mainnet } from 'https://esm.sh/@wagmi/core/chains?bundle'
import { createWeb3Modal, defaultWagmiConfig } from 'https://esm.sh/@web3modal/wagmi@beta?bundle'

// 1. Create projectId
const projectId = 'YOUR_PROJECT_ID'

// 2. Create wagmiConfig
const chains = [mainnet, arbitrum]
const wagmiConfig = defaultWagmiConfig({ chains, projectId, appName: 'Web3Modal' })

// 3. Create modal
const modal = createWeb3Modal({ wagmiConfig, projectId, chains, themeMode: 'light' })

// 4. Trigger modal programaticaly
const openConnectModalBtn = document.getElementById('open-connect-modal')
const openNetworkModalBtn = document.getElementById('open-network-modal')

openConnectModalBtn.addEventListener('click', () => modal.open())
openNetworkModalBtn.addEventListener('click', () => modal.open({ view: 'Networks' }))
</script>

</html>
```

**Comment by 0xAsimetriq** [comment]
Looks like a type import from downstream dependency, besides error log in console, everything is working on my end, so you can probably ignore for now. Will try to find this in our walletconnect-monorepo to see if we can silence.

**Comment by hhun** [comment]
> Looks like a type import from downstream dependency, besides error log in console, everything is working on my end, so you can probably ignore for now. Will try to find this in our walletconnect-monorepo to see if we can silence.

Due to this problem, the wallet cannot be connected

Clicking `WalletConnect` cannot display the QR code
Clicking `MetaMask` cannot connect to MetaMask

**Comment by 0xAsimetriq** [comment]
I see, will need to look into this and talk to a relevant team. Looks like esm.sh cdn can't properly bundle some walletconnect dependencies

**Comment by hhun** [comment]
@0xAsimetriq 
Is there a solution to this problem?

**Comment by 0xAsimetriq** [comment]
Not as of now, we removed cdn support for now until we resolve. CDN bundlers like unpkgk / jsondeliver / esm.sh run into issues, so best advice for now is to set up a bundler like https://vitejs.dev locally, build bundle that you need and use that (upload to your server). But we will try to resolve CDN support as soon as possible

**Comment by jzsjiale** [comment]
> Not as of now, we removed cdn support for now until we resolve. CDN bundlers like unpkgk / jsondeliver / esm.sh run into issues, so best advice for now is to set up a bundler like https://vitejs.dev locally, build bundle that you need and use that (upload to your server). But we will try to resolve CDN support as soon as possible

May I ask if this problem has been resolved now? Thank you!

**Comment by wcldyx** [comment]
> Not as of now, we removed cdn support for now until we resolve. CDN bundlers like unpkgk / jsondeliver / esm.sh run into issues, so best advice for now is to set up a bundler like https://vitejs.dev locally, build bundle that you need and use that (upload to your server). But we will try to resolve CDN support as soon as possible

Hello, I've also encountered this issue and it's been causing me a lot of distress. Could you please update on any progress or solutions regarding this? I'm genuinely struggling with it and it's making me feel quite down. Thank you for your time and assistance!
