### ISSUE TITLE
[bug] run `yarn install` in `vue`, then run `yarn dev`, Will report an error: `Could not resolve "react"`

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1350]
### Link to minimal reproducible example

https://docs.walletconnect.com/2.0/web3modal/v3/vue/about

### Summary

run `yarn install` in **vue**, then run `yarn dev`, Will report an error: `Could not resolve "react"`

### List of related npm package versions
yarn install
![微信截图_20230921234232](https://github.com/WalletConnect/web3modal/assets/19625243/068ac752-3bb4-4704-8e5c-06b93122e5c7)

yarn dev
![360截图20230921235041473](https://github.com/WalletConnect/web3modal/assets/19625243/5f5b9c3c-f9ba-4fb5-8861-426a33262604)

**Comment by glitch-txs** [comment]
Hi, if you're using yarn could you try adding this to the package.json file?

```
"optionalDependencies": {
    "react": ">=17",
    "react-dom": ">=17"
  },
```

**Comment by hhun** [comment]
After adding `optionalDependencies` in `package.json`, it can run normally.
``` json
	"optionalDependencies": {
		"react": ">=17",
		"react-dom": ">=17",
		"typescript": ">=5.0.4"
	}
```

**Comment by yucheng-Li** [comment]
> After adding `optionalDependencies` in `package.json`, it can run normally.
> 
> ```json
> 	"optionalDependencies": {
> 		"react": ">=17",
> 		"react-dom": ">=17",
> 		"typescript": ">=5.0.4"
> 	}
> ```

Are you use vue2 ?

**Comment by glitch-txs** [comment]
we don't recommend using `optionalDependencies` anymore, and this should be fixed without any workaround needed in the latest version.
