### ISSUE TITLE
[bug] Keplr web app 404

### ISSUE THREAD

**Issue by kopeboy** [WalletConnect/web3modal#1351]
### Link to minimal reproducible example

https://wallet.keplr.app/wc?uri=wc%3Aa57224773c86672ca2a71fd75af055448656ec32d0db11671377a9c6b6b2193c%402%3Frelay-protocol%3Dirn%26symKey%3D064013dca6a9ffeaafde6d6b22259b19c3a10db365b96b4e58880928e3caeac5

### Summary

At https://web3modal.com/ select all wallets > Keplr > Webapp > Open link > 404

Keplr is the main wallet for 50+ Cosmos chains so would be great to have working integration..

### List of related npm package versions

What used in your live implementation at https://web3modal.com/

**Comment by 0xAsimetriq** [comment]
Thank you for reporting, I just tested and it indeed leads to 404, but more so it doesn't look like kepler has a web wallet, so this data is probably incorrect, looks like they have mobile and extension? Kepler themselves will need to update their data on https://cloud.walletconnect.com to fix these issues. I'll close the issue for now, will all see if we have contact with them to try and speed this up.
