### ISSUE TITLE
ClientCtrl has no client set

### ISSUE THREAD

**Issue by musexiliangcheng** [WalletConnect/web3modal#1353]
exports.RouterCtrl = W;
var k;
var f = {
    ethereumClient: void 0,
    setEthereumClient: function setEthereumClient(e) {
      k = e;
    },
    client: function client() {
      if (k) return k;
      throw new Error("ClientCtrl has no client set");
    }
  },

我不知道是出了什么问题，项目无法打开
I don't know what is the problem, the project can not open

**Comment by 0xAsimetriq** [comment]
Can you provide details about packages and versions used / codesandbox reproduction (minimal) please. Usually this happens when you create wagmi instance inside a render loop i.e. inside react component as opposed to creating it once at the top level of your app.

**Comment by musexiliangcheng** [comment]
creating it once at the top level of your app? What does that mean

**Comment by musexiliangcheng** [comment]
> 您能否提供有关所使用的软件包和版本/codesandbox 复制（最小）的详细信息。通常，当您在渲染循环内（即在 React 组件内）创建 wagmi 实例时，而不是在应用程序的顶层创建一次，就会发生这种情况。

creating it once at the top level of your app? What does that mean,        Where to create？

**Comment by 0xAsimetriq** [comment]
Outside of reacts render loop, if you make small codesandbox (other similar repro), I can have a look and see how you implemented it atm.

**Comment by 0xAsimetriq** [comment]
@musexiliangcheng were you able to resolve this issue with suggestions above / by upgrading to v3?

**Comment by 0xAsimetriq** [comment]
Closing as innactive, feel free to provide extra context when available.

**Comment by SashaDesigN** [comment]
Having the same one issue when launch locally with Svelte App

**Comment by glitch-txs** [comment]
@SashaDesigN could you share an MRE? (public repo / code sandbox)
