### ISSUE TITLE
[feature] Set qrcode view into "loading" state when user scans it

### ISSUE THREAD

**Issue by xzilja** [WalletConnect/web3modal#1355]
### What problem does this new feature solve?

Currently dapp shows no feedback to user once qrcode is scanned (not approved or rejected yet). We can improve ux here by  bumping it into "loading" state.

### Describe the solution you'd like

We can extend standard wagmi methods and hook into walletconnect provider to listen for `1101` reply on our websocket (meaning that user has scanned qrcode) and set qr view into such loading state.

**Comment by glitch-txs** [comment]
is this possible? sounds like a low level implementation?
