### ISSUE TITLE
[bug] [v3] wallet is listed but it's not on featuredWalletIds

### ISSUE THREAD

**Issue by obernardovieira** [WalletConnect/web3modal#1360]
### Link to minimal reproducible example

https://utils-git-feature-web3modal-v3-ipct.vercel.app

### Summary

I've only included 2 wallets on `featuredWalletIds` but coinbase wallet is listed. Then added it to `excludeWalletIds` but still appears.
I've also tried with other wallets, to see if I could find any problem, but nothing so far. Why is coinbase wallet always listed? I don't want to list it.

### List of related npm package versions

"@wagmi/core": "1.4.2",
"@web3modal/wagmi": "3.0.1",
"viem": "1.12.2",
"wagmi": "1.4.2"

**Comment by 0xAsimetriq** [comment]
Coinbase is a trickier one, all options related to ids mostly manipulate wallets we fetch from our api i.e. https://walletconnect.com/explorer I know coibase is in there, but it is also a default connector in web3modal v3. To remove it you can reference this section of docs https://docs.walletconnect.com/2.0/web3modal/react/about#implementation you will see tabs for `default` and `custom` options, you are interested in replicating whats in custom, but removing `CoinbaseConnector` from there.

Hope this helps.
