### ISSUE TITLE
web3 modal v3 account view(overlay screen) causing ui to flicker

### ISSUE THREAD

**Issue by ethdev279** [WalletConnect/web3modal#1364]
web3 modal v3 account view(overlay screen) causing ui to flicker when there is a constant update to ui. I think this was due to improper zindex?

https://github.com/WalletConnect/walletconnect-monorepo/assets/45661693/4764425a-3ac2-4072-9701-109cf2d0aa12

_Originally posted by @ethdev279 in https://github.com/WalletConnect/walletconnect-monorepo/discussions/3722_

**Comment by 0xAsimetriq** [comment]
@ethdev279 do you by any chance have a link to live demo of this and additional details like which browser / os is used? Definitely looks weird, you can try to set higher z-index for modal via options https://docs.walletconnect.com/web3modal/react/theming#themevariables and see if it solves it, but it feels like there is something else causing this issue on that page to be honest.

**Comment by ethdev279** [comment]
Tried with modal z-index but that didnt work. Here is the MRE: https://stackblitz.com/edit/stackblitz-starters-wrqnsn?file=app%2Fcomponents%2FWeb3Provider.js Try hovering on the edges of modal or try switching network from account view and then move cursor away. you'll notice the issue.

**Comment by 0xAsimetriq** [comment]
Ty for reproduction, still not seeing any issues. Which os / browser are you using (I've tested on macOS - Chrome / Firefox / Safari). Do you see similar issue on https://web3modal.com ?

**Comment by ethdev279** [comment]
Yes. Its there as well. PFA

 I'm on windows and chrome 117.0.5938.132

https://github.com/WalletConnect/web3modal/assets/45661693/89fe0f6e-6391-4e51-a9e7-82ec43511678

**Comment by glitch-txs** [comment]
Hi @ethdev279 let's follow this one up on the [open discussion](https://github.com/orgs/WalletConnect/discussions/3722#discussioncomment-7142366) so we avoid duplications. Thanks! :)
