### ISSUE TITLE
[feature] V3 How can I obtain the WalletConnect QR code?

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1366]
### What problem does this new feature solve?

V3 How can I obtain the WalletConnect QR code?

### Describe the solution you'd like

Obtain the WalletConnect QR code to customize the UI

**Comment by 0xAsimetriq** [comment]
This is not a feature of web3modal, but you can achieve it on your own (it is hard).

Web3modal is built on top of `@web3modal/ui` package which contains all of these web-components (including qrcode) https://gallery.web3modal.com/?path=/docs/composites-wui-qr-code--docs

You can use this component and generate qrcode data using wagmi, here is how we generate it (you grab WalletConnect connector and listen for uri event)
https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/src/client.ts#L137-L152

Closing this issue, as this is out of scope for web3modal i.e. it's meant to be used as a drop in sdk with customization availabre through options, for something more custom, you'd likely need to build out your own solution, that said we will be extending customization options over time.
