### ISSUE TITLE
[feature] Get <wallet> button update

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1367]
### What problem does this new feature solve?
@kacperoak  @ignaciosantise @quetool @svenvoskamp end of last week we iterated with @Ilja to add the stores button on desktop and make wallet mobile apps & extensions linked for users of this device too (full discussion [here](https://walletconnect.slack.com/archives/C03QE6HUT38/p1695738340824729)). 

### Describe the solution you'd like

To support the app on 2 stores case we created an universal [Get the app entry](https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal?type=design&node-id=9960-163100&mode=design&t=DErlYejocTw9Q8jo-4). Please update :pray::skin-tone-3:
![image](https://github.com/WalletConnect/web3modal/assets/57009607/c0cf4602-113c-4c09-85ee-4e4dc73affe5)
![image](https://github.com/WalletConnect/web3modal/assets/57009607/a4176619-1715-4447-a465-a3c55897c2c5)

**Comment by ignaciosantise** [comment]
@dianeben is the whole component pressable? or only the "Get >" button?

**Comment by svenvoskamp** [comment]
Has been implemented, so closing
