### ISSUE TITLE
[bug] Safari on macOS and iOS prevents opening a custom wallet's `webapp_link`

### ISSUE THREAD

**Issue by freeatnet** [WalletConnect/web3modal#1368]
### Link to minimal reproducible example

https://github.com/freeatnet/web3modal-safari-webapp-blocked

### Summary

Safari (macOS 13.6, iOS 16.4 and 17.0) blocks attempts to open an external link in a new tab/window with `window.open(link, '_blank')`.

**Steps to reproduce:**
1. Bootstrap a WalletConnect-enabled app (or clone the repro repo).
2. Add a custom wallet with a webapp link, e.g.,
```diff
createWeb3Modal({
  wagmiConfig,
  projectId,
  chains,
+  customWallets: [
+    {
+      id: "webapp-wallet",
+      name: "Webapp Wallet",
+      webapp_link: "https://some-domain.xyz/",
+    },
+  ],
});
```
3. Run the app (`yarn dev` in the repro app).
4. Visit the website, http://localhost:3000
5. Click "Connect Wallet", select the custom wallet
6. Observe the WalletConnect modal display a loader state ([image](https://github.com/WalletConnect/web3modal/assets/138289/3d227115-c8f5-4d98-94bf-92eabaea3989)).
7. When nothing happens, click "Open".

**Expected:** the webapp link is opened.
**Observed:**
* On iOS, the link doesn't open, and Safari provides no feedback to the user.
* On macOS, the link doesn't open, and Safari briefly flashes "Pop-up Window Blocked"

**Additional triage:**
1. This issue appears specific to the `w3m-connecting-wc-web` component opening the link in a new window. If the custom wallet specifies a `mobile_link` instead of a `webapp_link`, the target URL is opened as expected; however, it is opened in the current tab with no (documented) way to redirect the user back to the original app.
2. Replacing the button with a link (`<a href=${CoreHelperUtil.formatUniversalUrl(this.wallet.webapp_link, this.uri).redirect} target="_blank">`) allows the webapp link to be opened normally. It appears that Safari only blocks `window.open(uri, '_blank')` calls and doesn't have an issue with the specific redirect URI.

### List of related npm package versions

```{
	"@types/node": "18.15.11",
	"@types/react": "18.0.31",
	"@types/react-dom": "18.0.11",
	"@web3modal/wagmi": "3.0.2",
	"eslint": "8.37.0",
	"eslint-config-next": "13.2.4",
	"next": "13.2.4",
	"react": "18.2.0",
	"react-dom": "18.2.0",
	"typescript": "5.0.4",
	"viem": "^1.13.1",
	"wagmi": "^1.4.2"
}
```

**Comment by 0xAsimetriq** [comment]
Looks like this is new in macOS / iOS 17. I think your suggestion to use link here is the way to go, we'll add in next release 👍

**Comment by freeatnet** [comment]
@glitch-txs could I get an update, please?

**Comment by glitch-txs** [comment]
This should be fixed in the latest version, feel free to reopen if the issue persists.
