### ISSUE TITLE
[bug] UI on iOs 14

### ISSUE THREAD

**Issue by r0kan** [WalletConnect/web3modal#1370]
### Link to minimal reproducible example

no

### Summary

Hello, we have decided to migrate to the new version of web3modal, but the UI in our web application is displaying incorrectly on devices running iOS 14 and older versions of Android. Is this expected behavior, or will you be adapting the layout for devices that do not support certain CSS features (such as flex-gap)?
![IMG_7F30FEA53215-1](https://github.com/WalletConnect/web3modal/assets/11544432/9934c747-ddcb-4412-b0cc-c7f14466c523)
<img width="460" alt="Screenshot 2023-10-03 at 16 33 10" src="https://github.com/WalletConnect/web3modal/assets/11544432/1a08f903-3568-4958-a672-83e8531ab135">
<img width="459" alt="Screenshot 2023-10-03 at 16 33 18" src="https://github.com/WalletConnect/web3modal/assets/11544432/18bb8ce4-5c44-4b8a-b5c9-b06502f4b265">
<img width="464" alt="Screenshot 2023-10-03 at 16 33 29" src="https://github.com/WalletConnect/web3modal/assets/11544432/1c81418f-c4a7-42e0-9f12-ca1b3beb9e88">

### List of related npm package versions

"@web3modal/wagmi": "3.0.2"

**Comment by 0xAsimetriq** [comment]
Right now we are trying to support latest ios 15.x version and up, if you see some issues there please post them so we can have a look.
