### ISSUE TITLE
[bug] wallet api returns 403 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#1375]
### Link to minimal reproducible example

no need as you can take your example from docs 

### Summary

When trying to use just simple example from the documentation i get 403 from `https://api.web3modal.com/getWallets`. 

### List of related npm package versions

    "viem": "^1.15.3",
    "wagmi": "^1.4.3",
    "@web3modal/wagmi": "^3.0.2",

**Comment by 0xAsimetriq** [comment]
It means that `projectId` was not set or got banned.

**Comment by pociej** [comment]
@0xAsimetriq yes indeed but here comes the question. How to run web3modal on localhost if projectId needs domain verification.

**Comment by 0xAsimetriq** [comment]
Domain verification is not required, but definitely encouraged for production deployments. You can create development and production projects (different projectid's).
