### ISSUE TITLE
[bug] Allow users to switch to supported chain in single chain setups

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#1377]
### Link to minimal reproducible example

n/a

### Summary

Noticed in v3 that if my wallet is connected to unsupported chain, I couldn't been able to switch to supported chain from acccount view. I was able to switch in v2 but not in v3. this is happening only when I have single chain in supported chains list in wagmi config.

![Screenshot 2023-10-06 163543](https://github.com/WalletConnect/walletconnect-monorepo/assets/45661693/1b374755-5b46-4cc0-af30-7bd956205c48)

### List of related npm package versions

n/a

**Comment by spider9375** [comment]
in v2 when prompted to sign message there used to be a switch chain. In v3 this is no longer the case. I hope this gets addressed as well

**Comment by 0xAsimetriq** [comment]
@spider9375 that is part of wagmi's sign message action not web3modal, you can provide specific chain to that method.

**Comment by spider9375** [comment]
@0xAsimetriq  https://wagmi.sh/core/actions/signMessage there is no chain that can be provided for this specific method

**Comment by 0xAsimetriq** [comment]
Ah, do you even need to switch chain for this one? Signature is deprived from same private key no matter which chain the user is on, I think that's why they don't have it there.

I was thinking in terms of connect method, when you connect and user selects say arbitrum in web3modal, but their wallet is on ethereum, then they will be prompted to switch the network.

And other methods that actually need to be chain specific have option to pass chainId i.e. https://wagmi.sh/core/actions/writeContract#chainid-optional

**Comment by spider9375** [comment]
I pass only mainnet as chain for configureChains and createConfig. But in my app I can connect and then sign while in Linea network in my metamask mobile app.

I was using WalletConnectSignClient v2 CDN and signing with the .request method would prompt in the metamask app to switch chains. Now i don't get this behavior with the web3modal and wagmi signMessage
