### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Awais994** [WalletConnect/web3modal#1378]
### Link to minimal reproducible example

 const wagmiConfig = defaultWagmiConfig({ chains, projectId });  // 3. Create modal createWeb3Modal({   wagmiConfig,   projectId,   chains,   themeMode: "light", });

### Summary

Modal not work properly on mobile when i am use contracts buy functions.

### List of related npm package versions

3.0.2

**Comment by glitch-txs** [comment]
Hi, could you share more details on the issue? do you have any public repo that showcase the issue?

Let's reopen once we have more details.

**Comment by Awais994** [comment]
yes, i am sharing you link
https://test-qtaxi-presale.netlify.app/

**Comment by glitch-txs** [comment]
Thanks, could you please open a GitHub discussion with the following information?
https://github.com/orgs/WalletConnect/discussions/3457

Thanks!

**Comment by Awais994** [comment]
Done.
