### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#1379]
### Link to minimal reproducible example

I would suggest to remove this step or create some playground as creating reproduction involves creating projectId. 

### Summary

Ledger live does not work. If I choose ledger live from list of wallets it redirects to the [404](https://www.ledger.com/ledger-live/download/wc?uri=wc%3A9e1c8582a8b64d843f0c7d6a97ec5022ebdccd9414be57892368bec0c7fb20c2%402%3Frelay-protocol%3Dirn%26symKey%3Df0a8f7d9be08853fcbd4f2f8b0cf17bc41896ec1231537a467b0ba9bfba6e878). 

### List of related npm package versions

    "@web3modal/wagmi": "^3.0.2"

**Comment by 0xAsimetriq** [comment]
Looks like ledger provided invalid details, will contact our team to look at this.
