### ISSUE TITLE
Metamask included twice as metamask and browserwallet 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#1380]
### Link to minimal reproducible example

...

### Summary

This maybe more UX glitch then bug per se, however it produces really strange experience. If user has metamask plugin Installed ( i guess it touches other browser wallets too) then on the list of suggested connection both metamask and browser wallet (which on click behaves as metamask) are rendered. Also different badges are displayed Metamask is 'Recent' and browser wallet is 'Installed'.  Look at the attached screenshot. 
<img width="405" alt="Screenshot 2023-10-09 at 08 55 06" src="https://github.com/WalletConnect/web3modal/assets/3854675/e9cf6b97-0194-410d-97b9-145866bb4077">

### List of related npm package versions

    "@web3modal/wagmi": "^3.0.2",

**Comment by 0xAsimetriq** [comment]
Just had a stab at this, we actually can't de-cople these at the moment as only way to do this would be based on `window.ethereum.isMetaMask` flag. This flag is set and overriden a lot by other extensions so we risk removing metamask incorrectly.

That said, next release of web3modal introduces EIP6963 support (https://github.com/WalletConnect/web3modal/pull/1365) which will improve the situation, I believe metamaks is about to support is as well, so we will eventually remove "Browser Wallet" option all together once top ~20 extensions adopt this (we are close)

**Comment by victorpavlenko** [comment]
<img width="444" alt="image" src="https://github.com/WalletConnect/web3modal/assets/5157416/7aae3e9d-8f72-4125-8d22-90f6898797c6">
@0xAsimetriq I have 3 of them lol

Btw I use 3.1.0 but still
In my case I need to connect 

```
 const connectors = [
      new MetaMaskConnector({ chains }),
      new InjectedConnector({ chains, options: { shimDisconnect: true } }),
      new WalletConnectConnector({ chains, options: { projectId, showQrModal: false } }),
      new CoinbaseWalletConnector({ chains, options: { appName: metadata.name } })
    ];
```

last one without image came from here: **new MetaMaskConnector({ chains })** but I need this button for my case 

Any suggestion how to remove this one ?

**Comment by 0xAsimetriq** [comment]
Remove `InjectedConnector` (Browser wallet) and exlude metamask's wallet id if you need to only use MetaMaskConnector

**Comment by victorpavlenko** [comment]
Thanks for `InjectedConnector`
<img width="465" alt="image" src="https://github.com/WalletConnect/web3modal/assets/5157416/e0b2249a-564c-45f7-8334-9fa899f88955">

Yes I try it already but still, another one there
`excludeWalletIds: ["c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96"]`

**Comment by glitch-txs** [comment]
That one is from MetaMask connector, you can remove it actually.

I highly recommend adding EIP6963Connector instead, it will detect installed wallets automatically.

**Comment by victorpavlenko** [comment]
@glitch-txs 

<img width="456" alt="image" src="https://github.com/WalletConnect/web3modal/assets/5157416/5342fd29-8a17-4590-8744-ca82ebcc446d">

Not really I need it to have this button^ 
will try EIP6963 thanks

**Comment by glitch-txs** [comment]
If you're using a wagmi connector and would like to add an image you can use this option
https://docs.walletconnect.com/web3modal/react/options#connectorimages

**Comment by victorpavlenko** [comment]
@glitch-txs It didn't work, I still think it's a bug...

**Comment by glitch-txs** [comment]
@victorpavlenko instead of `metamask` the key needs to be `metaMask`

cc @0xAsimetriq maybe we can get some lowercase function to avoid this confusion here 🤔
