### ISSUE TITLE
Named export 'WebSocket' not found. The requested module 'ws' is a CommonJS module, which may not support all module.exports as named exports. [bug] 

### ISSUE THREAD

**Issue by abdullahmehboob20s** [WalletConnect/web3modal#1383]
### Link to minimal reproducible example

Install "npm install @web3modal/wagmi wagmi viem" in Nextjs 13 and wrap your App with <WagmiConfig>....

### Summary

I installed web3Modal "npm install @web3modal/wagmi wagmi viem" as described in [documentation](https://docs.walletconnect.com/web3modal/react/about). After wrapping my whole app in 

    <WagmiConfig config={config}>
              ...................other code
    </WagmiConfig>
    
    
I am keep getting this error

![image](https://github.com/WalletConnect/web3modal/assets/64467248/b7c772df-5fe0-47d3-bc08-f42cf9c67891)

this is my package.json

`{
  "name": "verse",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build && next export",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@crossmint/client-sdk-react-ui": "^1.1.0-alpha.0",
    "@wagmi/core": "^1.4.2",
    "@web3-react/core": "^8.2.2",
    "@web3modal/wagmi": "^3.0.0",
    "axios": "^1.5.0",
    "daisyui": "^2.43.0",
    "ethers": "^6.7.1",
    "next": "12.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "sharp": "^0.31.1",
    "sweetalert2": "^11.7.28",
    "swiper": "^8.3.2",
    "tailwind-merge": "^1.14.0",
    "viem": "^1.16.0",
    "wagmi": "^1.4.3",
    "web3": "^1.7.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.8",
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.2.4"
  }
}
`

to reproduce this
Install "npm install @web3modal/wagmi wagmi viem" in Nextjs 13 and wrap your App with <WagmiConfig>....

### List of related npm package versions

"dependencies": {
    "@crossmint/client-sdk-react-ui": "^1.1.0-alpha.0",
    "@wagmi/core": "^1.4.2",
    "@web3-react/core": "^8.2.2",
    "@web3modal/wagmi": "^3.0.0",
    "axios": "^1.5.0",
    "daisyui": "^2.43.0",
    "ethers": "^6.7.1",
    "next": "12.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "sharp": "^0.31.1",
    "sweetalert2": "^11.7.28",
    "swiper": "^8.3.2",
    "tailwind-merge": "^1.14.0",
    "viem": "^1.16.0",
    "wagmi": "^1.4.3",
    "web3": "^1.7.1"
  },

**Comment by glitch-txs** [comment]
This seems to be unrelated to Web3Modal 🤔

Could you share a public repository/sandbox that we can run and reproduce this issue?
Also why are you using web3-react? Thanks!
