### ISSUE TITLE
[bug]  Module not found: Can't resolve '@web3modal/wagmi/react'

### ISSUE THREAD

**Issue by samartsevigor** [WalletConnect/web3modal#1384]
### Link to minimal reproducible example

-

### Summary

<img width="342" alt="Снимок экрана 2023-10-10 в 11 12 56" src="https://github.com/WalletConnect/web3modal/assets/63883555/f2a88b35-3544-4b2b-877d-ba24c9a7dcec">

> 

<img width="289" alt="Снимок экрана 2023-10-10 в 11 13 11" src="https://github.com/WalletConnect/web3modal/assets/63883555/5b881115-8b8c-41e5-8a2d-5ef5876e52e2">
>
<img width="649" alt="Снимок экрана 2023-10-10 в 11 13 28" src="https://github.com/WalletConnect/web3modal/assets/63883555/cc3f90fe-6ba1-4f0c-b0bc-2371ced08480">
>
<img width="973" alt="Снимок экрана 2023-10-10 в 11 13 48" src="https://github.com/WalletConnect/web3modal/assets/63883555/3d205409-d32b-40b4-b49f-13bbb3b1e7bc">

Tried deleting the node_modules folder and reinstalling the packages, but the issue is not resolved.

### List of related npm package versions

    "@web3modal/wagmi": "^3.0.2"

**Comment by samartsevigor** [comment]
> Please provide more complete / minimal reproduction in codesandbox or as git repo. Hard to tell from current info what's causing this.

https://codesandbox.io/s/nice-glade-7fmmkd?file=/src/App.js

**Comment by 0xAsimetriq** [comment]
Thank you for repro, you will need to update to wagmi 1.x and viem 1.x (wagmi 0.x also doesn't work with viem as far as I know). That should resolve the issue.

**Comment by samartsevigor** [comment]
I have these versions locally:
"viem": "^1.16.2",
"wagmi": "^1.4.3",

But in CodeSandbox, there are no such versions available for a proper demonstration.

**Comment by samartsevigor** [comment]
@0xAsimetriq Is this compatible with Webpack 4?

**Comment by glitch-txs** [comment]
Could you set up a public repository with a minimal example? Something we can run and test

**Comment by 0xAsimetriq** [comment]
@samartsevigor I think it should be, only thing I'm not certain about is if webpack 4 supports `exports` field in package.json i.e. this https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/package.json#L11

Other than this, you need to be on latest babel to support es6 features (or add appropriate babel loaders for things like optional chaining / nullish coalescing etc.)

**Comment by simondlr** [comment]
fwiw, experiencing the same issue and trying to debug why it happens. When I drop react from the URI and use only 

```import { createWeb3Modal, defaultWagmiConfig } from '@web3modal/wagmi';```

it works... But, I'm experiencing other issues elsewhere that I'm busy debugging. At least I'm not getting a "module not found" anymore. And wagmiConfig is properly initialised after using defaultWagmiConfig.

Using 
wagmi: 1.4.2
viem: 1.10.13
web3modal/wagmi: 3.1.0

**Comment by simondlr** [comment]
Okay, update on above. It turns out @samartsevigor suspicions were correct. Exports in package.json don't work work webpack v4. I used an old create-react-app that used webpack v4. When bumping to latest versions, it works and properly imports it.

fwiw, I use craco to add Babel transpilers and not react-app directly.
"@craco/craco": "^7.1.0",
"react-scripts": "^5.0.1",
