### ISSUE TITLE
[bug] No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by AlexBHarley** [WalletConnect/web3modal#1385]
### Link to minimal reproducible example

https://github.com/AlexBHarley/web3modal-error

### Summary

I've run into a few errors now trying to convert a Rainbowkit application into a web3modal 3.0 one. The latest error, which can be reproduced in the linked repo is `Error: No QueryClient set, use QueryClientProvider to set one`.

I just followed the instructions in the [Getting Started](https://docs.walletconnect.com/web3modal/react/about) guide.

### List of related npm package versions

- Node 16
- pnpm 8.6.6
- wagmi ^1.4.3
- @web3modal/wagmi ^3.0.2

**Comment by 0xAsimetriq** [comment]
This is not an error from web3modal, looks like something from react-query / wagmi, I'd try checking with them.
