### ISSUE TITLE
[bug] Only first network really works, otherwise: Requested chains are not supported

### ISSUE THREAD

**Issue by dzek69** [WalletConnect/web3modal#1387]
### Link to minimal reproducible example

https://github.com/dzek69/bug-walletconnect

### Summary

So I just followed the tutorial:
https://docs.walletconnect.com/web3modal/react/about

And when using Trust or Ledger wallets via WalletConnect I can only connect to the network that is specified in the `chains` array as the first one.

So let's say I want to support mainnet + bsc, if I set it up like this:
```
const chains = [mainnet, bsc]
```

then I can only connect to the mainnet, trying to use a BSC wallet in Trust app leads to `Unknown error` in the app and `Requested chains are not supported` in the browser console

BUT

I can set the array like that:
```
const chains = [bsc, mainnet]
```

and now I can connect the BSC wallet in the Trust app, but the mainnet one does not work.

This is confirmed to be a problem with Trust wallet and Ledger wallet with Ledger Live app (unfortunately I don't have this device for my own, so I cannot test on demand), it does not happen with MetaMask when connecting via Wallet Connect.

I'm using Trust app on Android from the Play Store.

### List of related npm package versions

@web3modal/wagmi: 3.1.0
viem: 1.16.2
wagmi: 1.4.3

**Comment by 0xAsimetriq** [comment]
As you mentioned, this is a wallet specific issue where Ledger and Trust need to update their implementation (I assume we are talking Trust's extension here? As their mobile wallets should work ok). Our team is in contact with them, hopefully we can resolve soon.

**Comment by glitch-txs** [comment]
Hi, Trust is working fine on our end. Could you elaborate on what you mean by
"trying to use a BSC"?
Please add reproduction steps 🙏

**Comment by dzek69** [comment]
@0xAsimetriq As I mentioned in original message - I'm using Trust mobile app on Android, from a Play Store, so it is updated.

@glitch-txs by "trying to use a BSC wallet in Trust app" I mean I go to Settings (bottom right icon), then Wallet (first option), then I add new one - I was importing it using `I already have a wallet`, then I search for "BNB" and I select "BNB Smart Chain" and I give my mnemonic pass phrases. Then I select this wallet again in the Settings -> Wallet:

![image](https://github.com/WalletConnect/web3modal/assets/4936805/ee2531bc-9e6d-4028-86f4-255347a18146)

It will only work if `chains = [bsc, mainnet]`, but then the first wallet does not work

**Comment by glitch-txs** [comment]
Because you're adding a new wallet (key + address) that wasn't specified nor approved in the session proposal

**Comment by dzek69** [comment]
I don't understand, sorry. I'm not switching the wallet during an existing session. I try to create new session each time I switch wallet.

And the first wallet only works with `chains = [mainnet, bsc]` and 2nd one only works with `chains = [bsc, mainnet]`.
