### ISSUE TITLE
[bug] Bitget wallet is not detected

### ISSUE THREAD

**Issue by m00n620** [WalletConnect/web3modal#1389]
### Link to minimal reproducible example

https://web3modal.com

### Summary

Bitget Wallet(formerly Bitkeep) is not being detected in web3modal V3. I believe it's because current web3modal is checking `window.ethereum.isBitKeep` instead of `window.bitkeep.ethereum`.

### List of related npm package versions

"@web3modal/wagmi": "^3.0.2"

**Comment by glitch-txs** [comment]
This is not planned for v3, we are moving towards [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) instead. Actually the last version of v3 already supports EIP-6963 which will detect your wallet if (it's installed) automatically and it's going to be shown on top of the modal. I would highly suggest integrating the protocol.
Some major wallets already support this EIP and we have a dapp for testing it. https://github.com/WalletConnect/EIP6963

**Comment by Server-mtx** [comment]
import { useAppKitWallet, AppKitWalletButton } from "@reown/appkit-wallet-button/react";
const { isReady, isPending, connect } = useAppKitWallet({})
connect("tokenpocket");    Unable to function properly
show Not Detected
