### ISSUE TITLE
[feature] V3 How to use `Tron network` ? Please write a detailed example

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1392]
### What problem does this new feature solve?

V3 How to use `Tron network` ?

### Describe the solution you'd like

Please write a detailed example
Preferably a `vue` example

.
---

https://react-app.walletconnect.com/
https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2

This example uses V2

And using  `Tron network`  requires two clicks, which is a bit troublesome to operate.

**Comment by 0xAsimetriq** [comment]
Is tron an evm based chain? If so, it should be exactly the same as interacting with mainnet for example, you might need to create a custom chain config for wagmi though (see wagmi docs). If it is not and evm chain, it is not possible to use it with Web3Modal at this time. We have another product that interacts with more low level walletconnect sdk's like `@alletconnect/universal-provider` called WalletConnectModal if you want to try it https://docs.walletconnect.com/web3modal/about#walletconnectmodal
