### ISSUE TITLE
[bug] No such file or directory

### ISSUE THREAD

**Issue by samartsevigor** [WalletConnect/web3modal#1393]
### Link to minimal reproducible example

-

### Summary

<img width="1334" alt="Снимок экрана 2023-10-13 в 04 24 14" src="https://github.com/WalletConnect/web3modal/assets/63883555/13e1346d-d281-4891-94a3-b51d65017d6b">
<img width="331" alt="Снимок экрана 2023-10-13 в 04 24 39" src="https://github.com/WalletConnect/web3modal/assets/63883555/41411dee-8c74-4111-b063-1106313f4109">

I'm using Create-react-app and getting the following error. Can you provide a solution?

### List of related npm package versions

"viem": "^1.16.4",
"wagmi": "^1.4.3",
"@web3modal/wagmi": "^3.1.0"

**Comment by glitch-txs** [comment]
Hi create-react-app has been deprecated and it's no longer maintained. Consider using Vite + React or a Metaframeworks instead 🙏

**Comment by samartsevigor** [comment]
@glitch-txs 
I have a large project, and migrating to Vite will bring significant problems and time loss.

**Comment by 0xAsimetriq** [comment]
Issue is not so much create-react-app but more of it's dependency on webpack / babel. Both wagmi and web3modal use modern build setups (es modules, named exports in package json etc.) I think create-react-app requires extra configuration in webpack and babel to get these working, but as it is no longer maintained they didn't add these.

What Glitch suggested is the best way forward, if you remain on cra you are likely not gonna be able to use new tooling like viem, w3m, wagmi etc.
