### ISSUE TITLE
[bug] useWeb3ModalEvents disconnect events are not emitted on Version 3

### ISSUE THREAD

**Issue by ogous** [WalletConnect/web3modal#1394]
### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal/assets/47118973/6b136fd1-f941-4915-b2dc-b34680138f93

### Summary

import {  useWeb3ModalEvents } from '@web3modal/wagmi/react'
const events = useWeb3ModalEvents()

When listening events through subscribe or with useWeb3ModalEvents, every other events like "modal open/close", "connect success", or click events are emitted normally, but not any disconnect events. When disconnect button clicked through modal, there is no disconnect success/error event, only modal close event is triggered.

What I expect is 'DISCONNECT_SUCCESS' event should be triggered. Version 2 was working like that.

### List of related npm package versions

"react": "18.2.0",
"next": "13.5.4",
"@web3modal/wagmi": "3.1.0"

**Comment by ogous** [comment]
I realized CONNECT_SUCCESS event is not triggered also when scanning QR code through mobile device wallets. It works when connected with browser extensions.

**Comment by 0xAsimetriq** [comment]
Yep, this is an actual bug, seems to happen due to 2 events being published quickly one after another i.e. events you mentioned are almost always followed by `MODAL_CLOSE` event, which is what listeners pick up. Will investigate and push fix 👍

**Comment by ogous** [comment]
Thanks for the quick response @0xAsimetriq. useWeb3ModalEvents is very useful for implementing off-chain or some syncing features etc., it can also help developers to add it to docs.

**Comment by 0xAsimetriq** [comment]
@ogous Definitely, also let me know if you can think of other useful events. We implemented bare minimum in first release with idea of expanding them based on user needs.

**Comment by ogous** [comment]
@0xAsimetriq existing events cover everything in our use-cases for now. I am pleased to let you know if I found anything can be enhanced.

**Comment by SlinkyPotato** [comment]
A temporary workaround is to track `MODAL_CLOSE` and then check for the value of account. 

```typescript
this.modal.subscribeEvents((event: EventsControllerState) => {
      console.log('event', event.data);
      switch (event.data.event) {
        case 'CONNECT_SUCCESS':
          this.isConnected = true;
          this.account = getAccount();
          break;
        case 'DISCONNECT_SUCCESS':
          this.isConnected = false;
          this.account = null;
          break;
        case 'MODAL_CLOSE':
          if (!getAccount().address) {
            this.isConnected = false;
            this.account = null;
          }
      }
    });
```

It's not ideal but it should satisfy the criteria for checking `DISCONNECT_SUCCESS`

**Comment by glitch-txs** [comment]
you can use wagmi hooks to track the user connection

**Comment by SlinkyPotato** [comment]
As in react hooks? I'm using Angular.

**Comment by ethan-auroria** [comment]
Would like to chime in here as well. It is beneficial to have proper events for important state changes. I would like to also request for `CONNECT_SUCCESS` to be fired after successful reconnect (wallet was connected and page reloaded).

And wagmi hooks are not the answer because some projects do not use React.

**Comment by glitch-txs** [comment]
you can subscribe to wagmi account changes, etiher with hooks or actions

**Comment by ernesck** [comment]
Any example of how to use wagmi's watchAccount on vue? Looks like 
`const wagmiConfig = defaultWagmiConfig({ chains, projectId, metadata })`
as config doesn't get accepted in watchAccount function.

**Comment by ethan-auroria** [comment]
For those who are still struggling, I have found the answer: use the following functions imported from `@wagmi/core`: `watchNetwork`, `watchAccount`, `watchPublicClient`, `watchWalletClient`. Call them right after creating the modal, pass in your callbacks. When the client disconnects, the `onWalletClientChanged` should be called with an `undefined` wallet object.

```javascript
const modal = createWeb3Modal({ wagmiConfig, projectId, chains });

// call the unwatch functions when your component is destroyed.
const unwatchNetwork = watchNetwork(onNetworkChanged);
const unwatchAccount = watchAccount(onAccountChanged);
const unwatchPublicClient = watchPublicClient({}, onPublicClientChanged); // define chain id?
const unwatchWalletClient = watchWalletClient({}, onWalletClientChanged);

// do your event handling here.
function onNetworkChanged(data: GetNetworkResult) {}
function onAccountChanged(data: GetAccountResult) {}
function onPublicClientChanged(data: GetPublicClientResult) {}
function onWalletClientChanged(data: GetWalletClientResult) {}
```

**Comment by ernesck** [comment]
> For those who are still struggling, I have found the answer: use the following functions imported from `@wagmi/core`: `watchNetwork`, `watchAccount`, `watchPublicClient`, `watchWalletClient`. Call them right after creating the modal, pass in your callbacks. When the client disconnects, the `onWalletClientChanged` should be called with an `undefined` wallet object.
> 
> ```js
> const modal = createWeb3Modal({ wagmiConfig, projectId, chains });
> 
> // call the unwatch functions when your component is destroyed.
> const unwatchNetwork = watchNetwork(onNetworkChanged);
> const unwatchAccount = watchAccount(onAccountChanged);
> const unwatchPublicClient = watchPublicClient({}, onPublicClientChanged); // define chain id?
> const unwatchWalletClient = watchWalletClient({}, onWalletClientChanged);
> 
> // do your event handling here.
> function onNetworkChanged(data: GetNetworkResult) {}
> function onAccountChanged(data: GetAccountResult) {}
> function onPublicClientChanged(data: GetPublicClientResult) {}
> function onWalletClientChanged(data: GetWalletClientResult) {}
> ```

Exactly what I was looking for, thanks!

**Comment by bjmvercelli** [comment]
> you can use wagmi hooks to track the user connection

So it isn't a bug as @xzilja said?
