### ISSUE TITLE
How to implement createWeb3Modal() function in Nextjs 13 [bug] 

### ISSUE THREAD

**Issue by abdullahmehboob20s** [WalletConnect/web3modal#1395]
### Link to minimal reproducible example

add createWeb3Modal() in layout.js file in Nextjs 13

### Summary

I am using Nextjs 13 and set up everything written in [docs](https://docs.walletconnect.com/web3modal/react/about). But i am stuck on this [point](https://docs.walletconnect.com/web3modal/react/about#implementation) where I am having to put `createWeb3Modal({ wagmiConfig, projectId, chains })` in my layout.js file. I am receiving this error again and again. And this is the only I am getting. Please help me fix it.

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/64467248/59bccc38-75e3-490d-8fef-9062c0fd39cb)
 

### List of related npm package versions

  "dependencies": {
    "@crossmint/client-sdk-react-ui": "^1.1.0-alpha.0",
    "@wagmi/core": "^1.4.2",
    "@web3-react/core": "^8.2.2",
    "@web3modal/wagmi": "^3.1.0",
    "axios": "^1.5.0",
    "daisyui": "^2.43.0",
    "ethers": "^6.7.1",
    "next": "^13.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "sharp": "^0.31.1",
    "sweetalert2": "^11.7.28",
    "swiper": "^8.3.2",
    "tailwind-merge": "^1.14.0",
    "viem": "^1.16.5",
    "wagmi": "^1.4.3",
    "web3": "^1.7.1"
  },

**Comment by 0xAsimetriq** [comment]
Closing as a duplicate / continuation in #1386

**Comment by abdullahmehboob20s** [comment]
I was able to solve this by Making a `Web3ModalProvider` component which looks like below
```javascript
"use client";

import { WagmiConfig } from "wagmi";
import { config, projectId, chains } from "utils/wagmiConfig";
import { createWeb3Modal } from "@web3modal/wagmi/react";
import NonSSRWrapper from "./NonSSRWrapper";

createWeb3Modal({
  wagmiConfig: config,
  projectId,
  chains,
});

export default function Web3ModalProvider({ children }) {
  return (
    <NonSSRWrapper>
      <WagmiConfig config={config}>
        {children}
      </WagmiConfig>
    </NonSSRWrapper>
  );
}
```

and then wraping my whole app into `Web3ModalProvider` component, Now my `layout.js` file is looking like this
```javascript
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider>
          <Layout>{children}</Layout>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
```
