### ISSUE TITLE
[feature] - More Configuration

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1398]
### What problem does this new feature solve?

-

### Describe the solution you'd like

- [ ] Allow to hide "All Wallets" button (only on desktop).
- [ ] Tokens config to allow override native cryptocurrency images. Solves https://github.com/WalletConnect/web3modal/issues/1406
- [ ] Custom chain images must be shown in all views (when the user is connected and switches to that chain) - not only on the Networks View. Solves https://github.com/WalletConnect/web3modal/issues/1405

**Comment by 0xAsimetriq** [comment]
Could you expand on last 2 points please

**Comment by glitch-txs** [comment]
I'll reopen an issue with the first item alone, as we have already other opened issues for the rest of features.
