### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by cityflysky** [WalletConnect/web3modal#1399]
### Link to minimal reproducible example

can not disconnect

### Summary

https://github.com/WalletConnect/web3modal/assets/109882297/c57a9dc5-9616-42b2-9d8a-7c132b017881

### List of related npm package versions

"@web3modal/wagmi": "^3.1.0",

**Comment by 0xAsimetriq** [comment]
No title, no actionable reproduction in here to understand the issue, please create a new one and provide as much info (repos / code samples etc) as you can, to help us debug this.
