### ISSUE TITLE
[bug] Connection declined Connection can be declined if a previous request is still active

### ISSUE THREAD

**Issue by cityflysky** [WalletConnect/web3modal#1400]
### Link to minimal reproducible example

Connection declined Connection can be declined if a previous request is still active

### Summary

![image](https://github.com/WalletConnect/web3modal/assets/109882297/68aac047-69a6-4271-bd98-6ad06d5a5c1d)

### List of related npm package versions

    "@wagmi/core": "^1.4.2",
    "@web3modal/wagmi": "^3.1.0",

**Comment by 0xAsimetriq** [comment]
No reproduction, MetaMask worked fine for me just now on web3modal.com

**Comment by MickWang** [comment]
same issue here.
<img width="364" alt="image" src="https://github.com/WalletConnect/web3modal/assets/6647774/07395663-0976-4ace-904e-fa488a281360">
