### ISSUE TITLE
[docs] Can you help me write an example of connecting `Web3Model V3` to the `TRON network`?

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1401]
### Summary

@glitch-tx

能不能帮我写一个 Web3Model V3 连接波场网络的例子？
Can you help me write an example of connecting `Web3Model V3` to the `TRON network`?

https://react-app.walletconnect.com/ 这个例子太复杂看不懂
https://react-app.walletconnect.com/ This example is too complicated to understand

code
---
``` js
import { defaultWagmiConfig, createWeb3Modal } from '@web3modal/wagmi/vue'

import { mainnet, bsc } from '@wagmi/core/chains'
import { tron } from '@/utils/chains'

const chains = [mainnet, bsc, tron]
const projectId = WALLET_CONNECT_PROJECT_ID

const wagmiConfig = defaultWagmiConfig({ chains, projectId })
createWeb3Modal({
	wagmiConfig,
	chains,
	projectId,
	defaultChain: mainnet
})
```
希望能用这种方式连接，这样代码看起来更直观。
Hopefully it can be connected this way so the code looks more intuitive.

**Comment by glitch-txs** [comment]
Tron is not supported by Wagmi because it has different protocols of communication with the web. So it's not possible at the moment.

**Comment by hhun** [comment]
@glitch-txs 
Please tell me how `tron` ​​in this example of https://react-app.walletconnect.com/ connects to `WalletConnect`?

**Comment by glitch-txs** [comment]
It's using Sign API
https://github.com/WalletConnect/web-examples/blob/main/dapps/react-dapp-v2/src/chains/tron.ts

You can also make it work with universal-provider 
https://docs.walletconnect.com/advanced/providers/universal

**Comment by hhun** [comment]
@glitch-txs 

Error reporting: `Unsupported chains. connect() requiredNamespaces, chains must be defined as "namespace:chainId" e.g. "eip155:1": {...} in the namespace key OR as an array of CAIP-2 chainIds e.g. eip155: { chains: ["eip155:1", "eip155:5"] }`

**How to solve this problem?**

How to generate `client` and `pairingTopic`?

``` js
const projectId = WALLET_CONNECT_PROJECT_ID

//  Initialize the provider
const provider = await UniversalProvider.init({
	logger: 'info',
	relayUrl: 'wss://relay.walletconnect.com',
	projectId: projectId,
	metadata: {
		name: 'React App',
		description: 'React App for WalletConnect',
		url: 'https://walletconnect.com/',
		icons: ['https://avatars.githubusercontent.com/u/37784886']
	},
	client: undefined // optional instance of @walletconnect/sign-client
})

//  create sub providers for each namespace/chain
await provider.connect({
	namespaces: {
		eip155: {
			chains: ['eip155:1', 'eip155:80001'],
			methods: ['eth_sendTransaction', 'eth_signTransaction', 'eth_sign', 'personal_sign', 'eth_signTypedData'],
			events: ['chainChanged', 'accountsChanged'],
			rpcMap: {
				1: 'https://rpc.walletconnect.com?chainId=eip155:1&projectId=' + projectId,
				80001: 'https://rpc.walletconnect.com?chainId=eip155:80001&projectId=' + projectId
			}
		},
		tron: {
			chains: ['tron:0x2b6653dc'],
			methods: ['tron_signTransaction', 'tron_signMessage'],
			events: [],
			rpcMap: {
				'0x2b6653dc': 'https://api.trongrid.io'
			}
		},
		pairingTopic: 'c4f80c8fd9ba77aace71f958dbe84954044a1693fcc866a224b3cab15613bdde', // optional topic to connect to
		skipPairing: false // optional to skip pairing ( later it can be resumed by invoking .pair())
	}
})
```

**Comment by glitch-txs** [comment]
hi, could you open an issue in the [monorepo](https://github.com/WalletConnect/walletconnect-monorepo) for this?
