### ISSUE TITLE
[bug] Next.js webpack errors because of missing documentation

### ISSUE THREAD

**Issue by dirtycajunrice** [WalletConnect/web3modal#1408]
### Link to minimal reproducible example

https://web3modal.justfixit.dev/

### Summary

Web3Modal uses 3 libraries that cause repeated and annoying webpack errors in Next.js. This is resolvable by adding this snippet of code to the documentation for Next.js users:
```js
// Path: next.config.js
const nextConfig = {
  webpack: (config) => {
    config.externals.push(
      "pino-pretty",
      "lokijs",
      "encoding"
    );
  return config;
}
```

### List of related npm package versions

https://github.com/dirtycajunrice/web3modal-bug-examples-2023-10-21/blob/9269c51dfe95d7ec2a5e0efebd3fb3923c9b79f1/package.json#L11-L19
```json
  "dependencies": {
    "@web3modal/wagmi": "^3.1.0",
    "next": "13.5.6",
    "react": "^18",
    "react-code-blocks": "^0.1.4",
    "react-dom": "^18",
    "viem": "^1.16.6",
    "wagmi": "^1.4.5"
  },
```

**Comment by nftchance** [comment]
Thanks for documenting this -- Saved me a lot of frustration.
