### ISSUE TITLE
[bug] MetaMask mobile wallet connects successfully with unsupported chain (displays 'Chain 1")

### ISSUE THREAD

**Issue by meri-maki** [WalletConnect/web3modal#1415]
### Link to minimal reproducible example

https://github.com/meri-maki/useSwitchNetwork

### Summary

I have a project that should only work with certain chains ```[polygon, arbitrum, bsc, sepolia]```
When I connect my mobile Matamask wallet (either with WalletConnect or from list of wallets on mobile) with Etherium chain selected, it connects with no errors

Web3Modal Network button displays it as 'Chain 1'

![Снимок экрана 2023-10-23 в 21 19 43](https://github.com/WalletConnect/web3modal/assets/97887955/ade61208-83ed-47f9-9a4b-70f18e5b3361)

This is very confusing behavior... How is it possible for Metamask to even connect to the unsupported chain?

This can be replicated on local host with min rep example

### List of related npm package versions

		"@web3modal/wagmi": "^3.1.0",
		"viem": "^1.16.2",
		"wagmi": "^1.4.3"

**Comment by glitch-txs** [comment]
MetaMask will connect to the chain you have opened in the mobile wallet app not the website

**Comment by meri-maki** [comment]
@glitch-txs is there any way around it...? Why it's displayed as "Chain 1"?

**Comment by meri-maki** [comment]
The one fix I found is to declare ```defaultChain```, but we would like to avoid this behavior

**Comment by meri-maki** [comment]
@glitch-txs do you think it's reasonable to mention this issue on wagmi? or is this issue exclusive to mm mobile wallet, and there is nothing we can do?

**Comment by glitch-txs** [comment]
you can open an issue in MetaMask mobile repository, it's on their end only.

**Comment by da748** [comment]
Automatic connect with three holds and bind the company and the power supply unit and create a custom design website for all in one pack
