### ISSUE TITLE
[feature] Implement the Ability to Create Custom Chain Buttons

### ISSUE THREAD

**Issue by fahimfaisaal** [WalletConnect/web3modal#1420]
### Discussed in [3771](https://github.com/orgs/WalletConnect/discussions/3771)

<div type='discussions-op-text'>

<sup>Originally posted by **fahimfaisaal** October 11, 2023</sup>
I need some help with integrating two custom buttons in my application. These buttons will allow users to connect their Ethereum and Polygon wallets seamlessly. I'm using the `useWeb3Modal` hook to open a modal for wallet connections, but I'm encountering a few challenges.

Here's the problem I'm facing:

1. **Default Chain Issue:** By default, the `useWeb3Modal` hook sets the first chain from the chains array or the `defaultChain` property. This behavior doesn't suit my use case, as I want users to be able to select a dedicated network only after clicking the corresponding button.

2. **Undefined Network:** I've tried to use the `useSwitchNetwork` hook to switch to a dedicated network, but it's showing me "undefined" before the user is connected to a wallet. This creates a usability issue as users should be able to choose their network at the time of connecting the wallet.
</div>

## What I Want:

I'm looking for a solution that allows users to connect their Ethereum and Polygon wallets by simply clicking the respective buttons with the dedicated chain name, rather than having to go through a separate network selection step. i.e. `open({ view: 'Networks' })`.

**Comment by da748** [comment]
Automatic connect with three holds and bind the company and the power supply unit and create a custom design website for all in one pack

**Comment by meri-maki** [comment]
You can use wagmi ```useConnect``` hook and pass ```connect({chainId: number})``` to each button
https://wagmi.sh/react/hooks/useConnect

**Comment by fahimfaisaal** [comment]
> You can use wagmi `useConnect` hook and pass `connect({chainId: number})` to each button https://wagmi.sh/react/hooks/useConnect

Yes, I can but for that I have to remove `web3modal` and build own custom modal, right?

**Comment by meri-maki** [comment]
@fahimfaisaal yes, if you use ```useConnect``` you don't need ```web3modal```
There is another way though
You can use  ```<w3m-account-button />``` along with ```<w3m-connect-button />```
This way you can define the chain BEFORE coonecting wallet with connect button
like in the example below
https://web3modal.com/

**Comment by fahimfaisaal** [comment]
> @fahimfaisaal yes, if you use `useConnect` you don't need `web3modal` There is another way though You can use `<w3m-account-button />` along with `<w3m-connect-button />` This way you can define the chain BEFORE coonecting wallet with connect button like in the example below https://web3modal.com/

But according to the [docs](https://docs.walletconnect.com/web3modal/react/components) I didn't see any kind of chainId or chain option out there.

**Comment by meri-maki** [comment]
@fahimfaisaal ```<w3m-network-button />``` is what you need to look at
It's hard to explain, since I don't know exactly what are your needs
Implement ```<w3m-network-button />``` and see what it does

**Comment by meri-maki** [comment]
@fahimfaisaal you are either using ```<w3m-network-button />``` or remove web3modal at all and build everything woth ```wagmi``` alone
