### ISSUE TITLE
[feature] show a popup when connected to wrong network

### ISSUE THREAD

**Issue by wslyvh** [WalletConnect/web3modal#1422]
### What problem does this new feature solve?

You can configure the supported chains as part of your Web3ModalClientOptions.
But there's no feedback whenever I connect or switch to an unsupported network.
Which often breaks or leads to errors.

### Describe the solution you'd like

I suggest to automatically show a popup/modal, whenever you connect or switch to an unsupported network.
The modal should provide a warning, but also show a list of supported networks to easily switch.

Example
![image](https://github.com/WalletConnect/web3modal/assets/25974464/5b3f6375-c92a-48bb-96c9-81746c204c69)

**Comment by glitch-txs** [comment]
You can still use wagmi hooks to subscribe to network changes, they also have a boolean for supported networks.
 Also imo forcing a popup without direct user action might be a bit abrupt for some

**Comment by meri-maki** [comment]
Network switch can only be detected with ```useNetwork``` hook, which doesn't support ```onSuccess``` and ```onError``` (in comparison to ```useSwitchNetwork```)
In the last few days I have experienced some bugs with MetaMask - ```chain.unsupported``` returns wrong value (connecting to supported chain and seeing ```unsupported: true```)

So I have to write huge useEffect that detects chain.id and compare it to the array of supported chain...

Also there is a need to build fallback UI when unsupported chain is detected...

**Comment by glitch-txs** [comment]
Added in v4 👍

**Comment by wslyvh** [comment]
@glitch-txs is it possible to make this configurable? There are a lot of use-cases that do not require to automatically pop up and can actually be quite annoying :sweat_smile:
