### ISSUE TITLE
[feature] Web3Modal v3 - Callback on session approval (QR code)

### ISSUE THREAD

**Issue by Spxc** [WalletConnect/web3modal#1427]
### What problem does this new feature solve?

Using the latest version: https://docs.walletconnect.com/web3modal/ it dosent seem like the lib knows when a user really connects. It works fine using Metamask in Chrome, but not using a Mobile wallet.

### Describe the solution you'd like

A solution to listen for the connection/session. And if it's approved on the mobile wallet, run callback. User can then do whatever they want in this function. This was a function on prior versions.

**Comment by glitch-txs** [comment]
hi, are you using wagmi or ethers? could you also share the steps to reproduce? have you tried this on [labs](https://lab.web3modal.com/)?

**Comment by Spxc** [comment]
> hi, are you using wagmi or ethers? could you also share the steps to reproduce? have you tried this on [labs](https://lab.web3modal.com/)?

Hi,
Sorry forgot to mention. I'm using Wagmi fro the contracts etc. And Web3Modal on the dApp end. Web3Modal seems to be working fine when using the Metamask extension (the modal auto-closes). Using Metamask on mobile the QR modal never closes and the user has to refresh the page in order for the session to be set (and states updated). 

I'm currently using the `useWaitForTransaction()` callback for fetching the state of sent transactions, and it would be optimal if one would be able to do the same for connecting and disconnecting. ex `useWaitForApproval()`.

layout.tsx:
```
const chains = [mainnet, sepolia]
const projectId: any = process.env.PROJECT_ID

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })])

const wagmiConfig = createConfig({
    autoConnect: true,
    connectors: w3mConnectors({ projectId, chains }),
    publicClient
  })

const ethereumClient = new EthereumClient(wagmiConfig, chains)

return (
      <>
         <WagmiConfig config={wagmiConfig}>
              {children} // Includes the <Web3Button /> component
            </WagmiConfig>
            <Web3Modal 
              themeVariables={{ '--w3m-accent-color': '#315FF6' }}
              projectId={projectId} 
              ethereumClient={ethereumClient}
              defaultChain={sepolia}
            />
      </>
)
```

Also a sidenote, there is missing documentation on how to set the metadata config using v2 and `createConfig` from wami as far as i can see. There is only an example for the `defaultConfig`.

All the transactions and deployments works, it's just the connecting which seems a bit off. I may have missed the documentation, but i wasent able to figure it out. But as far as i can see, there is no way to catch a connect or a disconnect.

**Comment by glitch-txs** [comment]
Could you try upgrading to v3? v2 is no longer maintained https://docs.walletconnect.com/web3modal/upgrade
Also you should use wagmi's hooks, you can use [useAccount](https://wagmi.sh/react/hooks/useAccount) to check when the user is connected

**Comment by Spxc** [comment]
> Could you try upgrading to v3? v2 is no longer maintained https://docs.walletconnect.com/web3modal/upgrade Also you should use wagmi's hooks, you can use [useAccount](https://wagmi.sh/react/hooks/useAccount) to check when the user is connected

Upgraded to v3 (thought it was v3.2, error on my end).
Using: `const accountEvents = useAccount()` to fetch the account changes, works, but only using injected wallets. Using the QR code and WC, the modal now closes, but no event is triggered from `useAccount()`

**Comment by glitch-txs** [comment]
Could you provide a Minimal Reproducible Example?

**Comment by Spxc** [comment]
`layout.tsx`

```
  const accountEvents = useAccount()

  const wagmiConfig = defaultWagmiConfig({ chains, projectId, metadata })
  createWeb3Modal({ 
    wagmiConfig, 
    projectId, 
    chains
  })

useEffect(() => {
        if (!accountEvents.address) {
            onConnectionChange(null)
            console.log("Disconnected:", accountEvents)
            return
        }
        onConnectionChange(accountEvents)
        console.log("Connected:", accountEvents)
    }, [accountEvents])

  return(<WagmiConfig config={wagmiConfig}>...</WagmiConfig>)
  
```

**Comment by glitch-txs** [comment]
> dosen't fire at all on account changes, before reload.

Are you using app dir router?

**Comment by Spxc** [comment]
Not sure about "app dir router", but if you're thinking about the App Router in Next13/14, yes :)

**Comment by glitch-txs** [comment]
could you share a MRE?
