### ISSUE TITLE
[docs] Vite 将 `@web3modal` 或者 `@walletconnect` 单独打包会报错

### ISSUE THREAD

**Issue by hhun** [WalletConnect/web3modal#1428]
### Summary

Vite 将 `@web3modal` 或者 `@walletconnect` 单独打包会报错
> Uncaught ReferenceError: Cannot access 'o' before initialization at _web3modal-d7874689.js:1

`vite.config.js` 的 `rollupOptions` 配置
``` js
	rollupOptions: {
		plugins: [],
		output: {
			manualChunks(id) {
				if (id.includes('node_modules')) {
					const packageName = id.toString().split('node_modules/')[1].split('/')[0]
					if (['@wagmi', '@web3modal', '@walletconnect', '@coinbase', '@metamask', 'viem'].includes(packageName)) {
						return '_web3modal'
					}
					switch (packageName) {
						case 'validator':
							return '_' + packageName // 单独打包
							break
						default: // 合并打包
							return '__vendor'
							break
					}
				}
			},
			chunkFileNames: 'static/chunk/[name]-[hash].js', // 引入文件名的名称
			entryFileNames: 'static/entry/[name]-[hash].js', // 包的入口文件名称
			assetFileNames: 'static/[ext]/[name]-[hash].[ext]' // 资源文件像：字体、CSS、图片等
		}
	},
```
请问这个问题怎么解决？
web3modal不能使用CDN应该也是这个问题造成的

**Comment by 0xAsimetriq** [comment]
Closing due to lack of description. Do you have live preview or full github repo where this error is thrown? By the looks of it you are using custom bundling of multiple packages, so a lot of things could be causing this. Please open an issue with extended information.
