### ISSUE TITLE
[feature] Improve "Try Again" logic on ios when deeplink is canceled

### ISSUE THREAD

**Issue by xzilja** [WalletConnect/web3modal#1429]
### What problem does this new feature solve?

When users cancel native ios prompt for deeplink, ios goes into state where all further prompts are invalid until user refreshes the browser. We could improve on handling this.

### Describe the solution you'd like

- Checking if user left the dapp or not (flag on window visibility event changes)
- If user has left the dapp, we assume that they wen't to wallet successfully, in which case "Try Again" remains as a deeplink
- If user has not left the dapp, we assume that user canceled native deeplink prompt and should reload the window

**Comment by subhod-i** [comment]
Hey team, the problem persists on IOS with the latest library v5.1.6. Any updates?  I see this has been closed as completed.
