### ISSUE TITLE
"Failed to execute 'setItem' on 'Storage'" [bug]

### ISSUE THREAD

**Issue by alexanderpehlivanov** [WalletConnect/web3modal#1430]
### Link to minimal reproducible example

// Libraries import { useWeb3Modal, useWeb3ModalState } from "@web3modal/wagmi/react"; import { useAccount } from "wagmi";

### Summary

{context: 'client'}
 "Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//keychain' exceeded the quota."

### List of related npm package versions

"@web3modal/wagmi": "^3.2.0"
"wagmi": "^1.4.5"
"viem": "^1.18.0"

**Comment by glitch-txs** [comment]
Hi @alexanderpehlivanov  were you able to fix this?

**Comment by alexanderpehlivanov** [comment]
@No I just opened another one

**Comment by alexanderpehlivanov** [comment]
@glitch-txs This is the problem with the disappearing connection view that was mentioned a while ago. I moved this bug to https://github.com/WalletConnect/web3modal/issues/1431. If you want we can get on call and I can show you how to reproduce it.

**Comment by JohnathanWhite** [comment]
also experiencing this
