### ISSUE TITLE
[bug] Can not switch to Goerli

### ISSUE THREAD

**Issue by zhangjing28** [WalletConnect/web3modal#1432]
### Link to minimal reproducible example

https://github.com/zhangjing28/bridge-wallet-connect-demo

### Summary

**Steps to Reproduce**
* Click "connect wallet" to open wallet connect modal
* Click "Wallet Connect" in popup and using Metamask app to scan the qrcode
* Click "switch to goerli"

**Detail Error Message**
```Uncaught (in promise) SwitchChainError: An error occurred when attempting to switch chain.
Details: {"code":-32602,"message":"May not specify default MetaMask chain."}
Version: viem@1.18.1

### List of related npm package versions

```
{
  "name": "bridge-wallet-connect-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@web3modal/wagmi": "^3.2.0",
    "next": "14.0.1",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^1.18.1",
    "wagmi": "^1.4.5"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}

**Comment by glitch-txs** [comment]
hi, can you try importing them from 'viem/chains' ?

`import * as allChains from "viem/chains";`

**Comment by zhangjing28** [comment]
> hi, can you try importing them from 'viem/chains' ?
> 
> `import * as allChains from "viem/chains";`

Thanks for you quick reply, but it's not working. Got the same error as before

**Comment by kolirt** [comment]
> > hi, can you try importing them from 'viem/chains' ?
> > `import * as allChains from "viem/chains";`
> 
> Thanks for your quick reply, but it's not working. Got the same error as before

any solutions?

**Comment by glitch-txs** [comment]
Please upgrade to Viem v2
