### ISSUE TITLE
[bug] copy address success in local dev but. failed when deployed to server

### ISSUE THREAD

**Issue by guotie** [WalletConnect/web3modal#1436]
### Link to minimal reproducible example

diffucult to reproduce

### Summary

In local dev, when i copy the address from modal, it success.

But when I deploy to server, the copy failed with:

```
Failed to copy
```

Then, I found this link:  https://stackoverflow.com/questions/69438702/why-does-navigator-clipboard-writetext-not-copy-text-to-clipboard-if-it-is-pro

they say:

```
Because the navigator.clipboard.writeText method returns a promise and your code does not wait for its result.
```

so, I think the copy code should be 
```
navigator.clipboard.writeText(val).then(....)
```

### List of related npm package versions

3.1.0

**Comment by 0xAsimetriq** [comment]
Can you copy it on https://web3modal.com ?

1. If yes, then do you have a preview of your deployment where this issue happens?
2. If no, can you provide browser / device details?

Awaiting this is not necessary

**Comment by jordaniza** [comment]
Hi, I am having a similar issue, but this is persistent on all mobile devices using Sveltekit.

On desktop, no problem, on mobile "failed to copy" when hitting the copy button to the right of "scan the code"

**Comment by li460930736** [comment]
![image](https://github.com/WalletConnect/web3modal/assets/56672001/2064757a-a27f-45f5-b93f-76c311f648eb)
same, local dev success, product failed

**Comment by li460930736** [comment]
"@wagmi/core": "^1.4.12",
"@web3modal/wagmi": "^3.5.2",
"use-wagmi": "^0.4.9",
"viem": "^1.21.0",
my version
