### ISSUE TITLE
[bug] when cancelling metamask's connections and click retry, the notification will be popup 'address in invalid'

### ISSUE THREAD

**Issue by Ernest5663** [WalletConnect/web3modal#1437]
### Link to minimal reproducible example

N/A

### Summary

**Only Mobile physical device is triggerable**, desktop or responsive isn't able to trigger this.

Using Device: 
- iPhone 12 Pro, iOS 17.0

Ways to trigger: 
- Connect wallet using Metamask
- When 'Open this page in "MetaMask"?' popup comes out, click Cancel
![IMG_2469](https://github.com/WalletConnect/web3modal/assets/49939314/56d5cd0b-378b-4c5f-9c23-d5872289b75e)

- Click Try Again on the modal
- A popup 'Safari cannot open the page because the address is invalid.' will be show and keep, ways only to solve is to reload whole page.

![IMG_2470](https://github.com/WalletConnect/web3modal/assets/49939314/d10584d8-bf2d-457b-8ad1-412b25c52f1a)

### List of related npm package versions

"@headlessui/react": "^1.7.17",
    "@nanostores/persistent": "^0.9.1",
    "@nanostores/react": "^0.7.1",
    "@types/node": "20.5.9",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "@uniswap/widgets": "^2.59.0",
    "@web3modal/wagmi": "^3.2.0",
    "autoprefixer": "10.4.15",
    "axios": "^1.6.0",
    "classnames": "^2.3.2",
    "downloadjs": "^1.4.7",
    "eslint": "8.48.0",
    "eslint-config-next": "13.4.19",
    "firebase": "^10.5.2",
    "html-to-image": "^1.11.11",
    "lightweight-charts": "^4.1.1",
    "lodash": "^4.17.21",
    "nanostores": "^0.9.4",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-toastify": "^9.1.3",
    "react-tooltip": "^5.21.6",
    "recharts": "^2.9.1",
    "sass": "^1.69.5",
    "sortablejs": "^1.15.0",
    "ua-parser-js": "^1.0.37",
    "viem": "^1.18.1",
    "wagmi": "^1.4.5"

**Comment by PigCharid** [comment]
我的问你跟你的差不多

**Comment by PigCharid** [comment]
我的问题和你差不多，解决了么

**Comment by 0xAsimetriq** [comment]
This is limitation of iOS native system that we have no control over. However, we have few ideas on how to improve this and are tracking them here https://github.com/WalletConnect/web3modal/issues/1429 (closing this issue in favor of existing feature-request)
