### ISSUE TITLE
[bug] duplicate Metamask shown when selecting provider

### ISSUE THREAD

**Issue by Ernest5663** [WalletConnect/web3modal#1438]
### Link to minimal reproducible example

N/A

### Summary

- Two Metamask shown when selecting wallets

Mobile: 
![File](https://github.com/WalletConnect/web3modal/assets/49939314/31864128-0f19-4157-a63c-e649955c0b87)

Desktop:
![Screenshot 2023-11-02 at 17 59 32](https://github.com/WalletConnect/web3modal/assets/49939314/fc10d952-5a47-4f51-8b88-e6be3c457bf6)

### List of related npm package versions

"@headlessui/react": "^1.7.17",
    "@nanostores/persistent": "^0.9.1",
    "@nanostores/react": "^0.7.1",
    "@types/node": "20.5.9",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "@uniswap/widgets": "^2.59.0",
    "@web3modal/wagmi": "^3.2.0",
    "autoprefixer": "10.4.15",
    "axios": "^1.6.0",
    "classnames": "^2.3.2",
    "downloadjs": "^1.4.7",
    "eslint": "8.48.0",
    "eslint-config-next": "13.4.19",
    "firebase": "^10.5.2",
    "html-to-image": "^1.11.11",
    "lightweight-charts": "^4.1.1",
    "lodash": "^4.17.21",
    "nanostores": "^0.9.4",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-toastify": "^9.1.3",
    "react-tooltip": "^5.21.6",
    "recharts": "^2.9.1",
    "sass": "^1.69.5",
    "sortablejs": "^1.15.0",
    "ua-parser-js": "^1.0.37",
    "viem": "^1.18.1",
    "wagmi": "^1.4.5"

**Comment by glitch-txs** [comment]
hi, ca you share your configuration?

**Comment by Ernest5663** [comment]
const wagmiConfig = createConfig({
    autoConnect: true,
    connectors: [
      new WalletConnectConnector({ chains, options: { projectId, showQrModal: false, metadata } }),
      new EIP6963Connector({ chains }),
      new MetaMaskConnector({ chains }),
      new CoinbaseWalletConnector({
        chains,
        options: {
          appName: metadata.name,
        },
      }),
    ],
    publicClient,
  })

  createWeb3Modal({ wagmiConfig, projectId, chains, themeMode: 'dark' })

im migrating from v2 to this, thanks

**Comment by glitch-txs** [comment]
You don't need the MetaMask connector anymore, you can remove it, Web3Modal should detect when MetaMask is installed and will be shown automatically
