### ISSUE TITLE
[feature]  - Add disconnect function to Ethers5

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1439]
### What problem does this new feature solve?

There's no function to disconnect the wallet for custom buttons.

### Describe the solution you'd like

We can add the disconnect function in this hook `useWeb3ModalAccount`

```ts
const { address, chainId, isConnected, disconnect } = useWeb3ModalAccount()

disconnect()
```
or

```ts
const { open, close, disconnect } = useWeb3Modal()

disconnect()
```

**Comment by vadimchilinciuc** [comment]
sorry guys ,can you add olso support fo javascript ,for disconect olso ?
// im using its this way 
import {createWeb3Modal} from '@web3modal/ethers5';

Last question is this already in production ? its possible to use this feature? 
Thanks a lot ,
Vadim Chilinciuc

**Comment by glitch-txs** [comment]
@vadimchilinciuc for JavaScript it will be `modal.disconnect()`. This will be on production in the next minor
