### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by alexanderpehlivanov** [WalletConnect/web3modal#1441]
### Link to minimal reproducible example

QR Code is not showing

### Summary

When you click to connect with the QR code it shows skeleton loading but is infinite. The QR code is not shown in the end. 

### List of related npm package versions

"@web3modal/wagmi": "^3.2.0",

**Comment by 0xAsimetriq** [comment]
Everything works as expected on https://web3modal.com and https://lab.web3modal.com

This issue doesn't have enough context for us to debug it. Feel free to open new one with expanded details (preview link where you see the issue, browser / device details, are any vpns used etc..)
