### ISSUE TITLE
[feature] onConnect callback needed

### ISSUE THREAD

**Issue by guotie** [WalletConnect/web3modal#1442]
### What problem does this new feature solve?

I want do something when the wallet was connect, so if expose onConnect callback, I think it is very useful

### Describe the solution you'd like

I want do something when the wallet was connect, so if expose onConnect callback, I think it is very useful

**Comment by glitch-txs** [comment]
You can use useAccount and trigger a useEffect on address changes

https://wagmi.sh/react/hooks/useAccount
