### ISSUE TITLE
[feature] - Allow to override WalletConnect logo and name button

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1446]
### What problem does this new feature solve?

Some devs might want to add only a few wallets on the modal and remove the WalletConnect logo and name since not all users know what it is
e.g. from https://github.com/orgs/WalletConnect/discussions/3874#discussioncomment-7468106
![image](https://github.com/WalletConnect/web3modal/assets/66949816/7bbbce50-c382-4e45-b297-52c590745bf5)

### Describe the solution you'd like

- Allow to override WalletConnect logo and name button
- Or allow to remove it completely. Some featured wallets support both extension and WalletConnect protocol, so adding them a featured would be enough.

**Comment by chadyj** [comment]
> Allow to override WalletConnect logo and name button

That's the solution, but what is the problem?

**Comment by glitch-txs** [comment]
> That's the solution, but what is the problem?

That's not customizable
