### ISSUE TITLE
[feature] `"Terms of Service"` and `"Privacy Policy"` footer links should be of color `--w3m-accent`

### ISSUE THREAD

**Issue by SergeyVolynkin** [WalletConnect/web3modal#1447]
### What problem does this new feature solve?

In WalletConnect modal v3 footer links are not changing color when `--w3m-accent` is set

### Describe the solution you'd like

Given `--w3m-accent` is set to purple 

Expected (links takes `--w3m-accent` color):
<img width="391" alt="Screenshot 2023-11-03 at 19 03 50" src="https://github.com/WalletConnect/web3modal/assets/34238697/03aecb4f-aee8-4233-ac4d-e505bf165562">

Current WalletConnect modal version (links are gray):
<img width="382" alt="Screenshot 2023-11-03 at 19 02 55" src="https://github.com/WalletConnect/web3modal/assets/34238697/ba45e356-9c54-491f-ba67-ac5f18cdfa1f">

**Comment by 0xAsimetriq** [comment]
This is not intended by current designs, so will be closing the issue. We will re-visit once some more core features of web3modal are complete and work starts on extended theming.
