### ISSUE TITLE
[feature] Allow for more configurability in the "Connect Wallet" UI

### ISSUE THREAD

**Issue by SergeyVolynkin** [WalletConnect/web3modal#1449]
### What problem does this new feature solve?

Currently, it is not possible to configure which options exactly available to the user in the "Connect Wallet" UI. 

### Describe the solution you'd like

Allow 

```ts
 createWeb3Modal({
      displayBrowserWalletOption: false,
      displayWalletConnectOption: false,
      // … other options
    });
```

So that it is possible to configure a UI with options like this:
<img width="373" alt="image" src="https://github.com/WalletConnect/web3modal/assets/34238697/dc6eb473-2aeb-4536-8c78-5484eaf6135e">

Vs. current UI:
<img width="373" alt="image" src="https://github.com/WalletConnect/web3modal/assets/34238697/c844d025-3aae-4616-a928-efdfa81118c9">

**Comment by arein** [comment]
@SergeyVolynkin valid request - for our understanding - can you explain why you don't want the QR code option? On Desktop (which is where your screenshot is from, this might break some use-cases)

**Comment by SergeyVolynkin** [comment]
Hi @arein!

This is partially due to our requirement to only allow only `RFC 6979`-compatible. (i.e. signature should be the same for the same exact payload) wallets. We are building an exchange, so accidentally allowing users to Sign-In with non-stable-signature Wallets will result in users won't be able to Sing In (when they try to sign in a second time from scratch) (and they'll need to call chain contracts directly to withdraw funds).

I filed the https://github.com/orgs/WalletConnect/discussions/3866 issue-discussion . If my understanding is correct, setting the `excludeWalletIds` / `includeWalletIds` does not protect from users onboarding with any wallet
(the https://github.com/orgs/WalletConnect/discussions/3866 still has no response, maybe you would know how to best restrict down to `RFC 6979`-compatible wallets)
