### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by PigCharid** [WalletConnect/web3modal#1450]
### Link to minimal reproducible example

no

### Summary

After the Little Fox Wallet cuts the chain, if I use wagmi's disconnect to disconnect and then reconnect because the chain is not supported, I cannot connect to the normal chain.

### List of related npm package versions

"dependencies": {
    "@davatar/react": "^1.11.1",
    "@headlessui/react": "^1.7.17",
    "@web3modal/wagmi": "^3.2.0",
    "classnames": "^2.3.2",
    "ethers": "^5.7.2",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.11.0",
    "react-router-dom": "^6.18.0",
    "react-toastify": "^9.1.3",
    "react-use": "^17.4.0",
    "viem": "^1.18.4",
    "wagmi": "^1.4.5"
  },

**Comment by 0xAsimetriq** [comment]
Can't help with this one, because there is not enough info to even understand what the issue is. Feel free to re-open with title, better description / some reporduction.
