### ISSUE TITLE
MetaMask Option not working on Firefox

### ISSUE THREAD

**Issue by Zimtente** [WalletConnect/web3modal#1451]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Hey,

The MetaMask wallet option isnt able to find Extension even though its installed (fresh Firefox installation without any extra addons)

![image](https://github.com/WalletConnect/web3modal/assets/27185649/494aa284-21a7-432a-a0dc-7c87a612722b)

Steps to reproduce:
1) Go to https://web3modal.com/
2) Click on "Connect Wallet" (blue button at the top)
3) MetaMask option should state "Installed" isnt - when clicking on the option it only leads to "Get the Addon"

### List of related npm package versions

these are from my personal project - not sure what the actual  https://web3modal.com/ website uses... but same situation on my local build.

  "@wagmi/connectors": "^3.1.3",
    "@web3modal/wagmi": "^3.2.0",
    "viem": "^1.18.4",
    "wagmi": "^1.4.5",

**Comment by glitch-txs** [comment]
@0xAsimetriq is this because of RDNS ? They only launched 6963 on chrome

**Comment by 0xAsimetriq** [comment]
This will be resolved once MetaMask adds EIP6963 support on all browsers (Browser Wallet option should work for now). They indicated that this is coming very soon.
