### ISSUE TITLE
 There was a problem with the linking step.

### ISSUE THREAD

**Issue by PigCharid** [WalletConnect/web3modal#1453]
### Link to minimal reproducible example

https://github.com/PigCharid/wcWeb3modalTest

### Summary

There was a problem with the linking step. I monitor the wallet's chain-cutting action in the program. If the chain that is switched is not a chain that I support, I use wagmi's disconnect hook to disconnect. But when I reconnected, I couldn't connect, and I didn't switch back to the chain I supported in the wallet first. If I refresh the page and reconnect, the link will be cut off normally and then linked again.

### List of related npm package versions

{
  "name": "wcmodaltest",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@web3modal/wagmi": "^3.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "^1.18.4",
    "wagmi": "^1.4.5"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}

**Comment by arein** [comment]
@PigCharid can you please add repro steps?

**Comment by PigCharid** [comment]
npm  i
npm run dev


Derek ***@***.***>于2023年11月6日 周一17:12写道：

**Comment by glitch-txs** [comment]
@PigCharid could you add repro steps like this:

Example:
1. open the modal
2. Connect by QR code with Trust Wallet
3. Do X...
etc

**Comment by PigCharid** [comment]
@glitch-txs  @areinHere is the steps.
1. Click Connect to use Metamask to connect to the wallet
2. Use Metamask to switch the network to any network except sepola
3. My program monitors network changes, but I do not support sepolia, so it automatically disconnects. Click Connect Wallet again to connect, and find that you cannot switch back to sepolia and then connect.
4. Refresh the web page and continue to click on the wallet link. Metamsk will switch to Sepolia and the link will be successful.
I want to be able to switch Metamask's network back to Sepolia normally in step 3, but it doesn't seem to work.
