### ISSUE TITLE
Safe Wallet redirecting to a 404

### ISSUE THREAD

**Issue by Zimtente** [WalletConnect/web3modal#1455]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Hey,

I tested the "Safe" option of your modal but by clicking on "Webapp" tab - it directs me to a 404 not found page.

Steps to reproduce:

Go to https://web3modal.com/
Click on "Connect Wallet" (blue button at the top)
Click "All Wallets"
Click on "Safe" then "Webapp" 
Click on "Open" (link)
Leads to: https://app.safe.global/wc?uri=wc%3A006a77707b44492cd54376fd68b1adb75fec9b1cf114d62bb0704aef7257b0bd%402%3Frelay-protocol%3Dirn%26symKey%3De87e96b1bc31d3c829087a35c7361536d392da33c1c2aa585c4eae12c142d767

which shows this:

![image](https://github.com/WalletConnect/web3modal/assets/27185649/a353f0c8-dc72-46ed-a33c-0b2c33a8e84d)

Doing it "manually" by Copying the link (pairing code) and then just pasting it into the pairing code field in the https://app.safe.global/ app works.

### List of related npm package versions

these are from my personal project - not sure what the actual https://web3modal.com/ website uses... but same situation on my local build.

"@wagmi/connectors": "^3.1.3",
"@web3modal/wagmi": "^3.2.0",
"viem": "^1.18.4",
"wagmi": "^1.4.5",

**Comment by arein** [comment]
I've reported this to Safe.

**Comment by arein** [comment]
@Zimtente Safe told me the fix is scheduled to go live on Wednesday (Nov 8).

**Comment by Zimtente** [comment]
okay thank you @arein !

**Comment by 0xAsimetriq** [comment]
Closing this on our end, for progress please reference
https://github.com/safe-global/safe-wallet-web/pull/2747
