### ISSUE TITLE
[feature] Vanilla JS implementation (for Django)

### ISSUE THREAD

**Issue by pmosse** [WalletConnect/web3modal#1457]
### What problem does this new feature solve?

Be able to integrate Wallet Connect anywhere

### Describe the solution you'd like

An example on how to integrate Web3modal with just javascript, like this example which is outdated:

https://github.com/WalletConnect/web3modal-vanilla-js-example

**Comment by glitch-txs** [comment]
we don't support CDN at the moment, you can keep track of the following issue for updates https://github.com/WalletConnect/web3modal/issues/1354
