### ISSUE TITLE
[feature] introduce `includeWalletIdsStandards` configuration for `createWeb3Modal` (filter out incompatible to required standards wallets)

### ISSUE THREAD

**Issue by SergeyVolynkin** [WalletConnect/web3modal#1461]
### What problem does this new feature solve?

Hi WalletConnect team,

In our dApp we require the connected ethereum wallet to be `RFC 6979`-compatible. (i.e. signature should be the same for the same exact payload). We are building an exchange, so accidentally allowing users to Sign-In with non-stable-signature Wallets will result in users won't be able to Sing In (when they try to sign in a second time from scratch) (and they'll need to call chain contracts directly to withdraw funds).

But there is currently no easy way to block the non-`RFC 6979`-compatible wallets from WalletConnect options. _(The `includeWalletIds` currently can be used, but it is a manual process of finding all the `RFC 6979`-compatible and "allowlisting" them.)_

For more context on the issue:
> … If a user uses a random temporary key k wallet[i.e. non `RFC 6979`-compatible], then when the user closes the browser or switches browsers, the user may have no permission to operate on dApp using the same L1 wallet.
Although it is possible to recover assets through Ethereum Key Authentication, the process is complicated and is likely beyond the capabilities of the average user.
(source: https://blog.safeheron.com/blog/insights/safeheron-originals/enhancing-security-on-mpc-wallet-dydx-connections#risk-of-asset-loss-for-users-of-wallets-utilizing-random-temporary-key-k)

### Describe the solution you'd like

Introduce `includeWalletIdsStandards` prop that in similar to the [WalletConnect web explorer](https://walletconnect.com/explorer?type=wallet&chains=eip155%3A1&eip6963=true) way will filter out incompatible wallets from `includeWalletIds`

```ts
createWeb3Modal({
  includeWalletIdsStandards: {
    RFC6979: true,
  },
  // … other options
});
```
<img width="400" alt="image" src="https://github.com/WalletConnect/web3modal/assets/34238697/1e86b1a4-6e51-4ad2-83e8-128257564dd1">

**Comment by SergeyVolynkin** [comment]
Created after https://github.com/orgs/WalletConnect/discussions/3866 discussion

**Comment by 0xAsimetriq** [comment]
This is interesting proposal 👍 we'll need to check with our data team to see if it is good enough for us to provide this (there is a risk of not showing a wallet here because they didn't fill out standards field for their project for example). If data for this is good, we could ship

**Comment by SergeyVolynkin** [comment]
Thank you @0xAsimetriq, if we won't be able to add feature in near future due to higher priorities, 

- Question 1: would it be possible to somehow get a list of wallets with non-stable signatures, so we can use `excludeWalletIds` to block them
- Question 2: is it a correct assumption that most of the WalletConnect-provided wallets are already `RFC 6979`-compatible (with stable signatures), so risk of user singing with a non-stable signature is low?

**Comment by ccamrobertson** [comment]
@SergeyVolynkin I see this was closed; as a non-RFC 6979 compliant wallet, we too are curious about ensuring we are blocked from dapps that require RFC 6979 compliance. Was another resolution reached?

**Comment by SergeyVolynkin** [comment]
@ccamrobertson one option is to ask for two signatures during first time wallet connection, then remember the given address is compliant (client-side in IndexedDB, LocalStorage)

**Comment by ccamrobertson** [comment]
@ccamrobertson that's certainly good practice on the dapp side, however, apart from RFC 6979 compliance (infeasible for us at the moment) there doesn't seem like much can be done on our [wallet] side.

Maybe a canonical list of dapps who require RFC 6979 compliance and a corresponding list of wallets that do not support it?
