### ISSUE TITLE
[feature] Add support for different or custom address icons.

### ISSUE THREAD

**Issue by destructioneth** [WalletConnect/web3modal#1465]
### What problem does this new feature solve?

We are currently restricted to a metallic ball looking icon.
![image](https://github.com/WalletConnect/web3modal/assets/7505068/30e73144-752f-4afe-86be-52f6584d993d)

### Describe the solution you'd like

It would be nice if we had other options, or even better, allow us to set a custom component alltogether.
![image](https://github.com/WalletConnect/web3modal/assets/7505068/3fa4ad3d-a00d-49f2-add6-744d3944a5d8)

**Comment by glitch-txs** [comment]
Useful library: https://github.com/bpierre/blo
