### ISSUE TITLE
[bug] Mobile Browser <-> Crypto.com | Defi Wallet switch is broken.

### ISSUE THREAD

**Issue by Destrian** [WalletConnect/web3modal#1466]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Steps to reproduce:

1. Open a browser like Chrome or Brave on an Android device with the Crypto.com | Defi Wallet app installed.
2. Navigate to any website / dapp with the web3modal and tap on Connect Wallet.
3. Tap on the Crypto.com | Defi Wallet option.
4. The system will switch to the Defi Wallet as expected, but will not actually connect. Instead, it will switch to the app and do nothing.

Adding the Crypto.com | Defi Wallet ID from the explorer to includeWalletIds does not fix the issue.

Opening the website on the Defi Wallet browser itself works. Every other feature works as expected.

Only happens on Android devices. On IOS everything works as expected.

### List of related npm package versions

"@web3modal/wagmi": "^3.2.1"

**Comment by glitch-txs** [comment]
I was able to reproduce it, we'll try to contact them

**Comment by arein** [comment]
@Destrian crypto.com confirmed the fix will be released on Monday. Closing this ticket

**Comment by Destrian** [comment]
That's actually awesome. Looking forward to it!
