### ISSUE TITLE
[feature] Update Light Theme Modal Background Colour on Native

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1472]
### What problem does this new feature solve?

While testing Web3Modal native on light mode, I noticed modal backgrounds where not `#FFFFFF` (and that should be)
Conscious it was confusing in our Design System to have Dark background in 125 and Light in 100, I updated the `Light/Background/125` to #FFFFFF in our Core Library, so that we can have full white modal backgrounds.

@ignaciosantise @quetool @kacperoak @radeknovis could we update in next releases ? 🙏 

### Describe the solution you'd like

https://www.figma.com/file/VKp2Ni4kc1nDaYx6pPPSCF/Core-Library?type=design&node-id=158-443&mode=design&t=TDigKbtLAzOCNKCS-4

- [x] Flutter
- [x] React Native
- [ ] iOS
- [ ] Android

**Comment by quetool** [comment]
This is done for Flutter since a while! :)
