### ISSUE TITLE
[bug] Welcome Back Metamask Modal is showing on 2nd+ load the app Vue 3 Vite TS Composition API without click on connect Wagmi button

### ISSUE THREAD

**Issue by TetianaMolchanova** [WalletConnect/web3modal#1473]
### Link to minimal reproducible example

https://github.com/TatyanaMolchanova/Metamask-Welcome-Back-Issue

For project working, please, add actual const projectId = 'Enter ID of Your Project Here'

Here is the video of the issue - https://youtube.com/shorts/ZpHGs9B3aMU?si=GIuiWuznKEENlOhE

### Summary

When usinig default code from https://docs.walletconnect.com/web3modal/vue/about with Wagmi on very first login in metamask it works as expected.

But if I close the all browser tabs or reload computer and open app again I see opened Welcome Back Modal Metamask also I don't click on the Connect Button it's always opened.

This behavior is not expected. Because it's expected that Metamask Modal is activated on click on it.

`npm install @web3modal/wagmi @wagmi/core viem`

`<script setup>
  import { createWeb3Modal, defaultWagmiConfig } from '@web3modal/wagmi/vue'
  import { mainnet, arbitrum } from 'viem/chains'

  // 1. Get projectId
  const projectId = 'YOUR_PROJECT_ID'

  // 2. Create wagmiConfig
  const metadata = {
    name: 'Web3Modal',
    description: 'Web3Modal Example',
    url: 'https://web3modal.com',
    icons: ['https://avatars.githubusercontent.com/u/37784886']
  }

  const chains = [mainnet, arbitrum]
  const wagmiConfig = defaultWagmiConfig({ chains, projectId, metadata })

  // 3. Create modal
  createWeb3Modal({ wagmiConfig, projectId, chains })
</script>

<template>
    <w3m-connect-button />
</template>
`

### List of related npm package versions

{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@wagmi/core": "^1.4.6",
    "@web3modal/wagmi": "^3.2.1",
    "viem": "^1.19.1",
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}

**Comment by glitch-txs** [comment]
can you try clearing local storage?

**Comment by TetianaMolchanova** [comment]
Yes, you are right, clearing local storage solved this issue.
`onMounted(() => {
    localStorage.clear();
    }
}`

Thank you.

**Comment by glitch-txs** [comment]
I think this happens usually on locahost when you run another project and connect/disconnect, etc. and Web3Modal stored your status as "connected" when you've been disconnected in another project runnning in the same port, so this shouldn't happen in production.
