### ISSUE TITLE
[bug] defaultWagmiConfig ovewrites rpcUrls 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#1480]
### Link to minimal reproducible example

-----

### Summary

The way of integration with wagmi overwrites provided rpcUrls https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/src/utils/provider.ts#L73. Is there reason to use thos particural rpcUrls? Do wallet connect use some specific methods that are not available on other nodes ? 
If answer is yes I think documentation should provide explanation. If not then IMO defaults should act like defaults, which generally mean values that will be used when no value is provided rather then overwite valid input. 

### List of related npm package versions

 -----

**Comment by glitch-txs** [comment]
Defaults are covered by the public provider, they share the same url

**Comment by pociej** [comment]
@glitch-txs look here https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/src/utils/provider.ts#L71-L86
