### ISSUE TITLE
[bug] Mobile MetaMask is not responding to the request for a network change action

### ISSUE THREAD

**Issue by thyoondev** [WalletConnect/web3modal#1481]
### Link to minimal reproducible example

.

### Summary

Mobile MetaMask is not responding to the request for a network change action.

I made a network change request with the following code.

```ts
walletConnectProvider.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: HEX_CHAIN_ID }],
      });
```

Network change requests aren't coming through on mobile MetaMask when the action is triggered. 
How long might it take to fix this bug?

### List of related npm package versions

@web3modal/ethers5

**Comment by glitch-txs** [comment]
can you share steps to reproduce and a MRE?

**Comment by thyoondev** [comment]
@glitch-txs 

1. Connect your mobile MetaMask to the WalletConnect QR code.
2. If the network is different, execute the network change function below.
3. The network change modal does not appear in the mobile MetaMask.

```ts
walletConnectProvider.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: HEX_CHAIN_ID }],
      });
```


- MRE
```ts
export const oasys = {
  chainId: 248,
  name: 'Hub-Mainnet',
  currency: 'OAS',
  explorerUrl: 'https://explorer.oasys.games',
  rpcUrl: 'https://rpc.mainnet.oasys.games/',
};
```


```ts
import { createWeb3Modal, defaultConfig } from '@web3modal/ethers5';

const chains = [oasys];

const ethersConfig = defaultConfig({
  metadata: {
    name: 'example name',
    description:
      'example description',
    url: 'https://example.com',
    icons: ['https://example.com'],
  },
  defaultChainId: 248,
  enableEIP6963: false,
  enableInjected: false,
  enableCoinbase: false,
  rpcUrl: 'https://rpc.mainnet.oasys.games/',
});

export const walletConnectModal = createWeb3Modal({
  ethersConfig,
  projectId,
  chains,
  themeMode: 'dark',
  defaultChain: oasys,
  includeWalletIds: [
    '37aacf1e6bf6793c892e42c3f7623a61d9ffcb4337010804cc3193c4d596cf5c',
  ],
  excludeWalletIds: ['c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96'],
});

walletConnectModal.subscribeProvider(
  ({ provider, providerType, address, chainId, isConnected }) => {
    if (isConnected) {
      provider$.next(provider);
    } 
  }
);
```

Transactions other than network changes are successful.
Additionally, when directly connected via ethers.js instead of WalletConnect, the provider shows the network change modal successfully on mobile MetaMask.

**Comment by thyoondev** [comment]
@glitch-txs Could you please provide an update on this matter?

**Comment by glitch-txs** [comment]
hi, you should fallback into `wallet_addEthereumChain`. So the chain you want to switch to can be added into the sesion proposal, once this is done you'll be able to switch internally in the dapp, and this will show up in MetaMask when triggering a transaction request.

**Comment by thyoondev** [comment]
@glitch-txs hello. Thank you for answer! 
I didn't understand this very well, could you explain it in a little more detail?

**Comment by glitch-txs** [comment]
try `wallet_switchEthereumChain` if it fails then request `wallet_addEthereumChain` if it gets accepted then call `wallet_switchEthereumChain` again.

When switching fails it mean the chain is not in the session metamask uses wallet_addEthereumChain to update the session with the requested chain
