### ISSUE TITLE
Why does login show derek.wc.ens?

### ISSUE THREAD

**Issue by NatPDeveloper** [WalletConnect/web3modal#1486]
**Describe the bug**
Login shows derek.wc.ens for any wallet or provider. 

**SDK Version (if relevant)**
 - Whatever https://web3modal.com/ is running

**To Reproduce**
1. Go to https://web3modal.com/
2. login with any wallet

**Expected behavior**
Display the address logged in with.

**Screenshots**

![Screenshot from 2023-11-20 09-00-14](https://github.com/WalletConnect/walletconnect-monorepo/assets/34429364/165e4736-08c9-4787-b8c9-342ac2662a92)

**Desktop (please complete the following information):**
 - All Desktop OS's

**Additional context**
Please confirm as soon as possible this is not a hack.

**Comment by chris13524** [comment]
Thanks for reporting, this is not a hack and was a faulty deploy to our ENS resolution API. We've updated our status page: https://status.walletconnect.com/incidents/l56lqvvn6msk
