### ISSUE TITLE
[bug] - MetaMask is triggered on reload when it's manually disconnected

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1488]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Steps to Reproduce:

1. Click button.
2. Connect with injected MetaMask via Web3Modal.
3. Disconnect from site using MetaMask UI (not Disconnect button in modal).
4. Reload page, observe eager connection.

### List of related npm package versions

'@web3modal/wagmi': latest

**Comment by abdullahmehboob20s** [comment]
Yes, same is happening for me

**Comment by danielmedvec** [comment]
The way i solved it is by removing the wagmi.connectedRdns from localstorage that wagmi adds.  


    import { useAccount, useDisconnect } from "wagmi";
```
   
    const { address } = useAccount();
    const { disconnect } = useDisconnect();

    useEffect(() => {
        if (address === undefined) {
            disconnect();
            removeLocalStorage()
        }
    }, [address])
    
     const removeLocalStorage = () => {
        localStorage.removeItem('wagmi.connectedRdns');
    }
```

**Comment by SlinkyPotato** [comment]
I'm seeing the same issue, alternatively I tested this with the new ethers v6 and I'm not seeing it there.

**Comment by SlinkyPotato** [comment]
Hi Enes, 

So the PR is written in such a way that the auto connect variable is defaulted to true but allows it to be false for the same function. 

My first thought on a specific scenario is when security is the utmost important. For single page transactions that do not require refresh this might be ideal. 

I guess giving options to devs is where my headspace is at.

**Comment by glitch-txs** [comment]
hi @SlinkyPotato you can set this in the custom config option, this is more of a feature request imo and doesn't fix the issue stated here for devs that want to use the  autoConnect feature
