### ISSUE TITLE
[bug] TypeError: Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by YVeselovskyi** [WalletConnect/web3modal#1495]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Open the console on the main website and there will be an error in fetchBalance, the same is happening on my websites. 

### List of related npm package versions

  "@wagmi/core": "^1.4.2",
  "@web3modal/wagmi": "^3.0.1"

**Comment by philogicae** [comment]
Same problem here since few minutes, on both dev and prod environments

**Comment by danielmedvec** [comment]
Same problem here...

**Comment by glitch-txs** [comment]
We're looking into it

**Comment by 10yearslottery** [comment]
Same here

**Comment by glitch-txs** [comment]
Should be fixed by now, thanks @chris13524 🙌

**Comment by YVeselovskyi** [comment]
> Should be fixed by now, thanks @chris13524 🙌

I still see this error in https://web3modal.com/ console
