### ISSUE TITLE
[bug] - Handle errors from Blockchain API

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1498]
### Link to minimal reproducible example

none

### Summary

There was an issue https://github.com/WalletConnect/web3modal/issues/1495#event-11038150207
when the Blockchain API wasn't properly working, Web3Modal should fallback into another provider or return something that doesn't hurt the performance.

### List of related npm package versions

@web3modal/wagmi: latest

**Comment by arein** [comment]
`Handle` for me just means properly show them to the end-user. If Blockchain API is down we cannot fail over. Bad luck. We fail over in Blockchain API but it's a bottleneck by design.

**Comment by enesozturk** [comment]
> ...fallback into another provider or return something that doesn't hurt the performance

@glitch-txs can you elaborate on this a bit more, please? Handling errors depends on what the error is. The issue https://github.com/WalletConnect/web3modal/issues/1495 seems like we shouldn't be silently handling that error in my opinion. It's something we should throw error and should never happen.

I'll still be checking the Blockchain API calls that can be improved tho

**Comment by enesozturk** [comment]
@glitch-txs Understood, let me double-check our calls to see what we can do to improve this, seems like there is no action item
