### ISSUE TITLE
[bug] When I connect wallet, it didn't get exact chain id. And when I send transaction, it doesn't redirect to wallet automatically.

### ISSUE THREAD

**Issue by fhrryDeveloper** [WalletConnect/web3modal#1505]
### Link to minimal reproducible example

https://fairlotto.io

### Summary

Hello, Support team.
How are you today?
I am using web3modal on my react project. I have integrated web3modal on my project and it is good working on pc. But when I open my website on mobile, it shows some errors.
1. When I connect wallet, it didn't get exact chain id.  (So I got wrong network message(I made it base on chain id))
2. When I send transaction after connect wallet, it doesn't redirect to wallet automatically. I should go to my wallet manually to sign it.
Please check these problems and give me a solution. Thanks in advance.

### List of related npm package versions

"@web3modal/wagmi": "^3.1.0",
"wagmi": "^1.3.9",
"web3": "^1.9.0"

**Comment by glitch-txs** [comment]
Web3js is currently not supported by Web3Modal.

**Comment by fhrryDeveloper** [comment]
> Web3js is currently not supported by Web3Modal.

what do you mean? It is good working on pc. 
Also I am using web3modal provider. Also it works on another project sometimes. Not working on mobile

**Comment by fhrryDeveloper** [comment]
Hey @glitch-txs 
Why no update?

**Comment by glitch-txs** [comment]
hi @fhrryDeveloper wagmi only work with Viem, share a MRE if possible but as I said, web3js is currently not supported
