### ISSUE TITLE
[bug] It reports  "Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'"

### ISSUE THREAD

**Issue by hdhmail2000** [WalletConnect/web3modal#1506]
### Link to minimal reproducible example

[bug] It reports  "Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'"

### Summary

To install it, you can run: npm install --save @web3modal/wagmi/vue
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

### List of related npm package versions

latest

**Comment by 0xAsimetriq** [comment]
This is operating system level error, we are not able to help here I'm afraid. I suggest to look this up online, check if you are accessing that file correctly and it has necessary permissions.

**Comment by hdhmail2000** [comment]
Why use "C:\DumpStack.log.tmp" file? 
Where can I change the path
Thank you

**Comment by 0xAsimetriq** [comment]
I'm actually not aware of what this file is. Within our repo (and dependencies that we use) nothing seems to be using this. From file name it seems like some sort of log dump, perhaps from a build tool you might be using or some other process that is running?

**Comment by glitch-txs** [comment]
could you share a minimal reproducible example?

**Comment by ProximaCA** [comment]
same problem
