### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by BeycanDeveloper** [WalletConnect/web3modal#1509]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/elegant-ardinghelli-n53nwj?file=%2Fsrc%2Findex.mjs%3A18%2C10

### Summary

If you use the network switching feature during the connection process and reject the network switching instead of accepting it, everything will work fine at first.

However, when you try the connection for the second time, the network switching screen appears, but w3m does not wait for the response from the wallet and terminates the process by giving the warning in the picture below.

![image](https://github.com/WalletConnect/web3modal/assets/50718965/1fba671c-dad2-4555-a777-3d0d4c0a889a)

When you press connect for the first time and reject it on the change screen, it will be written to the console as "Error". When you press connect for the second time, before you do anything, a warning will appear as shown in the picture below. Therefore, from now on, no action will be taken by the user whether you approve or reject it. Because it has already been received as rejection.

![image](https://github.com/WalletConnect/web3modal/assets/50718965/4be835e6-ecab-4c59-8fea-b4121c81e591)

### List of related npm package versions

"@wagmi/core": "^1.4.7"
"@web3modal/wagmi": "^3.3.2"
"viem": "^1.19.9"

**Comment by 0xAsimetriq** [comment]
This error is not coming from w3m, looks like wallet itself is throwing it, we are just reacting to the error. I'd suggest checking with wallet owners.

**Comment by BeycanDeveloper** [comment]
If this is not a problem in w3m then it is also in viem. Because when I try it with metamask's own "wallet_switchEthereumChain" method, it sends it again even though I reject the switch request every time.

Because when I reject it, it returns an answer. That's why I can get an answer every time.

What kind of problem do you think it could be? Should I port this to viem?

Because I already get the switchChain method from wagmi and it is from viem.

What do you think could be the problem here? When we reject metamask's request to switch its "wallet_switchEthereumChain" method and resubmit it later. A replacement screen appears again. However, once we cancel the change screen, Viem opens again, but it returns the error message I mentioned directly, not the response from the wallet.

I hope I could explain.

**Comment by BeycanDeveloper** [comment]
Yes, you are right, I should move this to wagmi or viem repo. Thanks.
