### ISSUE TITLE
[bug] lab.web3modal.com WAGMI example lost sign message button

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#1512]
### Link to minimal reproducible example

https://lab.web3modal.com/library/wagmi/

### Summary

There is no sign message button on https://lab.web3modal.com/library/wagmi/ but there is on https://lab.web3modal.com/library/ethers/

### List of related npm package versions

Latest

**Comment by glitch-txs** [comment]
it shows up for me 🤔 
![image](https://github.com/WalletConnect/web3modal/assets/66949816/12bc484b-c713-45c9-b80a-b4ac34939f3c)

**Comment by chris13524** [comment]
Ah, looks like it's dependent on the connected state, but the Ethers one is not. These should match in behavior

**Comment by glitch-txs** [comment]
Ahh right, it should show up when connected only

**Comment by svenvoskamp** [comment]
Closing this one, as ethers has the same behaviour as wagmi now
