### ISSUE TITLE
[bug]  All wallets still displayed even if there is 0 additional wallet 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#1519]
### Link to minimal reproducible example

-----

### Summary

<img width="473" alt="Screenshot 2023-11-30 at 10 52 09" src="https://github.com/WalletConnect/web3modal/assets/3854675/9b128ce8-0eb6-4db5-8c64-d1b4e72bfba2">

### List of related npm package versions

---

**Comment by pociej** [comment]
@0xAsimetriq I would need this to be done soon. If you agree that hiding 'all wallets' when there is 0 wallets to show is desirable behaviour I can make PR.

**Comment by pociej** [comment]
@0xAsimetriq thx for reply, teah i know I can tweak it but would definietly prefer not to have final sollution based on tweaks. So plan is that for now I will tweak, and create PR, once PR will be merged everything will be great :)

**Comment by glitch-txs** [comment]
PR opened
https://github.com/WalletConnect/web3modal/pull/1499

**Comment by pociej** [comment]
@glitch-txs great !
