### ISSUE TITLE
hooks for customWallets & account view modal

### ISSUE THREAD

**Issue by BeycanDeveloper** [WalletConnect/web3modal#1520]
### What problem does this new feature solve?

1 - customWallets

 In my project, I receive payments via address transfer. In other words, the user can pay directly to the address without connecting to any wallet. However, I have to show it with the Web3 modal option. I tried the customWallets value in the link below, but since there is no hook, I cannot get an action when clicked. I think it would be nice to add a hook here.

https://docs.walletconnect.com/web3modal/javascript/options#customwallets

2 - account view modal

I think a hook to add HTML to the place I marked in the image below would be great. As I said, I receive payments with web3modal in my project. However, I have something like this in mind. The user will first connect to the wallet, then I want to list the available tokens in the wallet one under the other, just like the network change button. Then, when one of them is clicked, I want to start the transfer process with web3modal.

![image](https://github.com/WalletConnect/web3modal/assets/50718965/1adbfba2-40f3-4a39-99e8-51a1cc88ea5f)

### Describe the solution you'd like

What I mentioned above will not actually disrupt the general structure and will only be something that people can make extra additions to if they want it.

**Comment by glitch-txs** [comment]
Hi @BeycanDeveloper thanks for bringing this up!

> pay directly to the address without connecting to any wallet

May I ask which service are you using for this?

**Comment by BeycanDeveloper** [comment]
Actually, what I'm talking about right now is 1. I made the event using event subscriptions. It would also be better if you also send the id data for SELECT_WALLET in event subscriptions.

But I can't do anything about the account view modal. Actually, I think I can add HTML to the related field by accessing the hidden DOM with js. But for the moment, I am waiting for a more stable solution from your side.

**Comment by BeycanDeveloper** [comment]
Also, with this method, I assume that we have our own private wallet and we added it together with the customWallets property. Let's say we did the connection process when you clicked using event subscriptions in the way I'm doing right now. So how do we set this for the entire w3m? Such as the connected network and account information.

**Comment by glitch-txs** [comment]
We'll consider it for the future refactor, closing as I'm doing some clean up 👍

**Comment by BeycanDeveloper** [comment]
@glitch-txs does this exist in the new appkit?
