### ISSUE TITLE
[bug] - Wallet is not opened when using Telegram in-app browser on iOS

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1530]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

- go to telegram and paste https://web3modal.com/ in some random chat
- selecte any wallet, it won't open on iOS
- workaround suggested here: https://github.com/orgs/WalletConnect/discussions/3986

### List of related npm package versions

latest

**Comment by kandrukKV** [comment]
I have a simple Telegram bot with this code that just opens the telegram web app:

```
const TelegramBot = require('node-telegram-bot-api');
const token = 'MY_TOKEN';
const bot = new TelegramBot(token, {polling: true});

bot.on('message', async (msg) => {
    const chatId = msg.chat.id;

    const text = msg.text;

    if (text === '/start') {
        await bot.sendMessage(chatId, 'Inline btn', {
            reply_markup: {
                inline_keyboard: [
                    [{ text: 'Open',  web_app: {url: 'https://main--bejewelled-daffodil-333813.netlify.app'}}]
                ]
            }
        });
    }
  });
```

Telegram Web App has simple code:
