### ISSUE TITLE
[feature] Retrieving selected connector

### ISSUE THREAD

**Issue by ennioVisco** [WalletConnect/web3modal#1531]
### What problem does this new feature solve?

When supporting multiple connectors for writing transactions with Wagmi, we need to be able to connect to the wallet, to retrieve a `walletClient` (via the `connect` method in `@wagmi/core`). 
In doing so, we must select the appropriate connector, but we currently have no way to know the one the user selected in Web3Modal.

I'm currently using Web3Modal in `vue`.

### Describe the solution you'd like

I'd like to have a `useConnector` composable that retrieves the selected connector.

**Comment by ennioVisco** [comment]
> This is already handled internally, you shouldn't use the connect function. Once the user is connected you can use this https://wagmi.sh/core/actions/getWalletClient

so it's bugged because I get undefined when I run `getWalletCllient()`

**Comment by ethan-auroria** [comment]
@glitch-txs What is the right way to use `getWalletCllient()`? The only optional parameter it accepts is `chainId`. And indeed I get `undefined` after calling the function.

**Comment by glitch-txs** [comment]
If the wallet is not connected it's going to be undefined.

**Comment by ethan-auroria** [comment]
Even when `getWalletClient()` is called after `MODAL_LOADED` event, it is still undefined. The wallet was connected in a previous session.

**Comment by ethan-auroria** [comment]
I get valid result if I listen for `CONNECT_SUCCESS` event and only call `getWalletClient()` after that, but clearly it only work for one scenario which is right after connecting to a wallet. Subsequent page loads with the wallet already connected result in `undefined`.

**Comment by glitch-txs** [comment]
This is an issue on the wagmi side, try adding a setTimeout to delay the call a little bit on page load.

We'll upgrade to Wagmi v2 this week

**Comment by ethan-auroria** [comment]
Thank you. Adding a timeout of about 500ms after `MODAL_LOADED ` event seems to do the trick. Perhaps it would be nicer to have a new event that indicates the client is ready.

**Comment by glitch-txs** [comment]
This is fixed in Wagmi v2 with a new flag I think

https://wagmi.sh/react/api/connectors/injected#unstable-shimasyncinject

**Comment by ethan-auroria** [comment]
> This is fixed in Wagmi v2 with a new flag I think
> 
> https://wagmi.sh/react/api/connectors/injected#unstable-shimasyncinject

There are some questions remain:

1. The wagmi feature you cited appear to only affects the shim client, i.e. MetaMask browser extension. How does that help with other clients, for example when I connect to a wallet on my phone?
2. Suppose that it can fix the issue, what is the new recommended way to obtain the client, is it by calling `getWalletClient` directly after `createWeb3Modal`?

**Comment by glitch-txs** [comment]
Curious why are you using that function?

Did you experience this issue on other connectors?

If this persists in v2 we should open an issue in the Wagmi repo

**Comment by ethan-auroria** [comment]
I just started using walletconnect, and so far it appears to be the only way for me to work with the account, to initiate a sign request or transfer. Is there a better option?

**Comment by glitch-txs** [comment]
If you're using Web3Modal + Wagmi an easier way is to use hooks or actions.

For example if you're using React you can use this hook for signing:
https://1.x.wagmi.sh/react/hooks/useSignMessage

For other frameworks you can use core actions: 
https://1.x.wagmi.sh/core/actions/signMessage

**Comment by ethan-auroria** [comment]
> If you're using Web3Modal + Wagmi an easier way is to use hooks or actions.
> 
> For example if you're using React you can use this hook for signing: https://1.x.wagmi.sh/react/hooks/useSignMessage
> 
> For other frameworks you can use core actions: https://1.x.wagmi.sh/core/actions/signMessage

Yeah that works, thank you.
Not sure if I have ever seen it in the docs. Wagmi docs also do not help as they do not explain the nature of this function, that it uses a hidden global value stashed somewhere.

**Comment by glitch-txs** [comment]
they use Zustand internally, which is a global store library
