### ISSUE TITLE
[feature] Add Networks to Activity

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1535]
### What problem does this new feature solve?

We would like to add networks to Activity to give a better context on chains to UX
Discussion [here](https://walletconnect.slack.com/archives/C03QE6HUT38/p1701418669880399)

Please add the network box on Tx thumbnails instead of transaction status icons, and move them on the left of the title (check the size which is bigger than before to fit the row title)

Thank you 🙏 

cc @enesozturk 

### Describe the solution you'd like

https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?type=design&node-id=13206-356025&mode=design&t=GmayUlFLNhcbQY7D-4
![image](https://github.com/WalletConnect/web3modal/assets/57009607/c5f4a419-fb37-45f2-8a6d-b5ffb56aefe4)

**Comment by chadyj** [comment]
There are legibility issues with some icons, such as this one @dianeben 
This doesn't seem so readable or intuitive, especially when there are different chains?

<img width="21" alt="Screenshot 2023-12-08 at 14 29 21" src="https://github.com/WalletConnect/web3modal/assets/116099/de70b810-77da-4966-b9b1-e2afe7b68620">

**Comment by dianeben** [comment]
@chadyj this is the official Cosmos Hub Icon, which is less accessible with his grey background. We could trick and use the Cosmos Asset logo as here which is more accessible:
![image](https://github.com/WalletConnect/web3modal/assets/57009607/15f7aaba-a26f-492f-b9c6-46a7c15bd9c3)

I won't recommend it though, because it won't be consistent with the network official branding, and we can't do a special treatment for each network logo. We should consider that Network indicator is an extra info and not the main one, and if we face some networks logo less accessible it's not a major issue

**Comment by glitch-txs** [comment]
hi, has this been resolved?
