### ISSUE TITLE
[feature] Why appear 2 options when I send transaction after wallet connected?

### ISSUE THREAD

**Issue by fhrryDeveloper** [WalletConnect/web3modal#1536]
### What problem does this new feature solve?

![image](https://github.com/WalletConnect/web3modal/assets/72539001/554c279f-c50b-4a0a-b3d0-e02a5ab45b14)
Please check above image.
This is the screen when I send transaction after wallet connected. I think this modal doesn't need. It is because wallet already connected and transaction confirm must happen on connected wallet. If there is already solution for it, please let me know. Thanks in advance.

### Describe the solution you'd like

Please remove "choose activity" modal and go to metamask wallet directly.
![image](https://github.com/WalletConnect/web3modal/assets/72539001/7c060401-a4af-4d22-be7d-84b0f25f8980)

**Comment by glitch-txs** [comment]
This is a MetaMask issue with their deeplink, should report to them
