### ISSUE TITLE
[bug] Scan the QR code using the mobile wallet app

### ISSUE THREAD

**Issue by dangdang02** [WalletConnect/web3modal#1545]
### Link to minimal reproducible example

'All Wallets' and scanning the QR code with the phone

### Summary

Scan the QR code using the mobile wallet app.
WalletConnect QR CODE
Everything works fine after the connection.

However, when selecting the wallet in 'All Wallets' and scanning the QR code with the phone, the browser displays the following prompt. Additionally, an infinite loop of the following content occurs, with a very fast recurrence rate. Within a few seconds, the webpage is inundated with endless requests:
WebSocket connection to 'wss://www.walletlink.org/rpc'
This leads to the webpage crashing."

-----------------------------------------

RxWebSocket.js:41 WebSocket connection to 'wss://www.walletlink.org/rpc' failed: Insufficient resources
@ RxWebSocket.js:41
Observable2._trySubscribe @ Observable.ts:239
Observable2.subscribe @ Observable.ts:221
TakeOperator2.call @ take.ts:73
Observable2.subscribe @ Observable.ts:215
innerSubscribe @ innerSubscribe.ts:112
MergeMapSubscriber2._innerSub @ mergeMap.ts:155
MergeMapSubscriber2._tryNext @ mergeMap.ts:148
MergeMapSubscriber2._next @ mergeMap.ts:128
Subscriber2.next @ Subscriber.ts:100
FilterSubscriber2._next @ filter.ts:102
Subscriber2.next @ Subscriber.ts:100
Notification2.observe @ Notification.ts:48
DelaySubscriber2.dispatch @ delay.ts:104
AsyncAction2._execute @ AsyncAction.ts:128
AsyncAction2.execute @ AsyncAction.ts:116
AsyncScheduler2.flush @ AsyncScheduler.ts:65
setInterval
AsyncAction2.requestAsyncId @ AsyncAction.ts:78
AsyncAction2.schedule @ AsyncAction.ts:71
Scheduler2.schedule @ Scheduler.ts:68
AsyncScheduler2.schedule @ AsyncScheduler.ts:49
DelaySubscriber2._schedule @ delay.ts:124
DelaySubscriber2.scheduleNotification @ delay.ts:140
DelaySubscriber2._next @ delay.ts:145
Subscriber2.next @ Subscriber.ts:100
FilterSubscriber2._next @ filter.ts:102
Subscriber2.next @ Subscriber.ts:100
SkipSubscriber2._next @ skip.ts:45
Subscriber2.next @ Subscriber.ts:100
TapSubscriber2._next @ tap.ts:126
Subscriber2.next @ Subscriber.ts:100
Subject2.next @ Subject.ts:71
BehaviorSubject2.next @ BehaviorSubject.ts:44
webSocket.onclose @ RxWebSocket.js:51

### List of related npm package versions

Web3Modal v3
@web3modal/ethers5 ethers@5.7.2

**Comment by glitch-txs** [comment]
this is a Coinbase issue, are you using Coinbase wallet? could you detail the steps to reproduce the issue?
