### ISSUE TITLE
[bug] Misleading unconnected state with MetaMask

### ISSUE THREAD

**Issue by enesozturk** [WalletConnect/web3modal#1547]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

When the connected wallet is MetaMask, sometimes the w3m shows the unconnected state in the first loading of my dApp. 

### Reproduction

- Open web3modal.com
- Connect with MetaMask
- Open new tab > open web3modal.com again. 
- Repeat opening a new tab several times.

At some point. The w3m will be showing an unconnected state. This is not happening with the other wallets. Tried with the following so far:

- WalletConnect
- CoinBase
- Rainbow
- Zerion

### Notes

It's the same for the `ethers` lib. Not only related to `wagmi`. So high possible the problem is on the MetaMask side. 

Lets use this issue to follow the problem.

**Comment by tomiir** [comment]
Seems related to this issue on MM side: 
https://community.metamask.io/t/provider-not-getting-connected/27309/10

**Comment by glitch-txs** [comment]
issue related to old EIP6963Connector - should work in Wagmi v2
