### ISSUE TITLE
[feature] Email login - UI fixes

### ISSUE THREAD

**Issue by dianeben** [WalletConnect/web3modal#1551]
### What problem does this new feature solve?

![image](https://github.com/WalletConnect/web3modal/assets/57009607/4c6fa5da-e62d-4919-b753-1b84ddcc8e66)
![image](https://github.com/WalletConnect/web3modal/assets/57009607/ae76b7cc-04b9-4f86-ad57-311d10801b94)
![image](https://github.com/WalletConnect/web3modal/assets/57009607/45770743-4202-4505-858c-6586b27bfd38)

### Describe the solution you'd like

Noticed 3 components to polish in the email login flow:
• [Header](https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?type=design&node-id=4829-112701&mode=design&t=7bQqUBueQ4IbRf9j-4) that should be 64px height
• [Email Input](https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?type=design&node-id=4571-75954&mode=design&t=7bQqUBueQ4IbRf9j-4) chevron that should be centered in height
• [Email Input Loader ](https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?type=design&node-id=11081-153105&mode=design&t=7bQqUBueQ4IbRf9j-4)that should be 14px size, with 18px padding right

cc @WalletConnect/javascript-team @svenvoskamp

**Comment by sajadvilsin-cmyk** [comment]
> @sajadvilsin-cmyk
