### ISSUE TITLE
[feature] Have a style prop to pass into <w3m-button>

### ISSUE THREAD

**Issue by suhelClamp** [WalletConnect/web3modal#1572]
### What problem does this new feature solve?

Having to solely rely on the theme variables is too restrictive to dapps that have a certain UI style.

Also the current solution I see is to create a custom `WallectConnectModal`, but that is too much work for a simple connect button.

### Describe the solution you'd like

I would simply like to be able to pass a style props component to the `<w3m-button>` or another solution would be to attach a unique id to all the components rendered, so that the user can style them accordingly using plain old css.

**Comment by glitch-txs** [comment]
Hi, you can pass them to the createWeb3Modal function or to the custom theme hooks/actions from the modal. Feel free to repoen if this is not useful.
