### ISSUE TITLE
[feature] Request to add a feature for disabling ENS name resolutio

### ISSUE THREAD

**Issue by dangdang02** [WalletConnect/web3modal#1573]
### What problem does this new feature solve?

Request to add a feature for disabling ENS name resolutio

### Describe the solution you'd like

Request to add a feature for disabling ENS name resolution. I don't use the Ethereum mainnet and don't need to retrieve ENS names. I prefer not to communicate with URLs for obtaining ENS names.

**Comment by arein** [comment]
Is this coming from centralization concerns aka you don't want to rely on an external party for this?

Or do you dislike name services in the first place?

**Comment by glitch-txs** [comment]
current issue: ENS call in ethers is hard-coded for ethereum mainnet

**Comment by glitch-txs** [comment]
If you're still experiencing this issue please create a new one as we have integrated a new ticketing system, thanks!
