### ISSUE TITLE
[bug] upgrade to 3.5 error

### ISSUE THREAD

**Issue by CjoyHome** [WalletConnect/web3modal#1584]
### Link to minimal reproducible example

https://github.com/CjoyHome/next-wallet-connect-demo

### Summary

An error occurred when I upgraded version 3.4.0 to 3.5.0
![image](https://github.com/WalletConnect/web3modal/assets/26813427/86d39f0f-3185-4b5c-aae8-2fb1608832fe)
![image](https://github.com/WalletConnect/web3modal/assets/26813427/26ff2c0e-755f-4e2c-b7fd-9dfbfa444d67)

### List of related npm package versions

`  
"@metamask/detect-provider": "^1.2.0",
    "@walletconnect/modal": "^2.6.2",
    "@web3modal/ethers5": "^3.5.0",
    "ethers": "^5.7.2",
    "keccak256": "^1.0.6",
    "merkletreejs": "^0.3.9",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-bootstrap": "^2.4.0",
    "react-dom": "18.1.0",
    "react-intl": "^6.4.2",
    "web3": "^1.7.3"`

**Comment by CjoyHome** [comment]
@glitch-txs If you have time, please help me take a look, thank you

**Comment by glitch-txs** [comment]
The issue seems to be related to the React and Next version, could you try updating it?
This worked for me: https://github.com/CjoyHome/next-wallet-connect-demo/pull/1

**Comment by CjoyHome** [comment]
This is not inconvenient to upgrade, there is no error in 3.4.0, is it not backward compatible

**Comment by glitch-txs** [comment]
Let's wait for @svenvoskamp to look into this

**Comment by CjoyHome** [comment]
ok,thanks

**Comment by glitch-txs** [comment]
hi @CjoyHome are you still experinecing this issue?
