### ISSUE TITLE
[bug] Modal appears below website

### ISSUE THREAD

**Issue by oracle-eth** [WalletConnect/web3modal#1585]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

The modal appears below the site content and is stuck to the left.

### List of related npm package versions

web3modal

**Comment by oracle-eth** [comment]
![Screenshot 2023-12-19 032858](https://github.com/WalletConnect/web3modal/assets/90863965/af760a5f-2660-47e2-944c-201acec12510)

**Comment by glitch-txs** [comment]
Unable to repro
