### ISSUE TITLE
[bug] Angular "@web3modal/ethers5": "^3.5.1" Errors from node_modules dependencies

### ISSUE THREAD

**Issue by thedarkknight197** [WalletConnect/web3modal#1598]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/wallet-connect-p8sdrm

### Summary

I am following this documentation because there isn't an angular section: https://docs.walletconnect.com/web3modal/javascript/about

But after adding imports in my component, angular don't compile and throw many errors based on node_modules dependencies.

I have replicated the issues in the sandbox in the link on the top.

The code is in src/app/app.component.ts

Build at: 2023-12-21T09:37:18.083Z - Hash: cff064b867c1f41e - Time: 5084ms

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@ethersproject/json-wallets/lib.esm/crowdsale.js depends on 'aes-js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@ethersproject/json-wallets/lib.esm/keystore.js depends on 'scrypt-js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@ethersproject/keccak256/lib.esm/index.js depends on 'js-sha3'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@ethersproject/providers/lib.esm/base-provider.js depends on 'bech32'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@ethersproject/sha2/lib.esm/sha2.js depends on 'hash.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@walletconnect/jsonrpc-http-connection/dist/esm/http.js depends on 'cross-fetch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@walletconnect/jsonrpc-utils/dist/esm/env.js depends on '@walletconnect/environment'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@walletconnect/relay-auth/dist/esm/api.js depends on '@stablelib/ed25519'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@web3modal/common/dist/esm/src/utils/DateUtil.js depends on 'dayjs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@web3modal/common/dist/esm/src/utils/DateUtil.js depends on 'dayjs/plugin/relativeTime.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@web3modal/common/dist/esm/src/utils/DateUtil.js depends on 'dayjs/plugin/updateLocale.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@web3modal/ethers5/dist/esm/src/utils/defaultConfig.js depends on '@coinbase/wallet-sdk'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/ubuntu/IdeaProjects/t-rex-solution/node_modules/@web3modal/ui/dist/esm/src/utils/QrCode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Error: node_modules/@web3modal/core/dist/types/src/utils/TypeUtil.d.ts:1:39 - error TS2307: Cannot find module '@web3modal/wallet' or its corresponding type declarations.

1 import type { W3mFrameProvider } from '@web3modal/wallet';
                                        ~~~~~~~~~~~~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:3:42 - error TS2307: Cannot find module '@web3modal/siwe' or its corresponding type declarations.

3 import type { Web3ModalSIWEClient } from '@web3modal/siwe';
                                           ~~~~~~~~~~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:20:11 - error TS2430: Interface 'Web3ModalState' incorrectly extends interface 'PublicStateControllerState'.
  Types of property 'selectedNetworkId' are incompatible.
    Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.
      Type 'number' is not assignable to type '`${string}:${string}`'.

20 interface Web3ModalState extends PublicStateControllerState {
             ~~~~~~~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:33:5 - error TS2416: Property 'getState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '() => { selectedNetworkId: number | undefined; open: boolean; }' is not assignable to type '() => { open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }'.
    Call signature return types '{ selectedNetworkId: number | undefined; open: boolean; }' and '{ open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }' are incompatible.
      The types of 'selectedNetworkId' are incompatible between these types.
        Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.

33     getState(): {
       ~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:37:5 - error TS2416: Property 'subscribeState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '(callback: (state: Web3ModalState) => void) => () => void' is not assignable to type '(callback: (newState: PublicStateControllerState) => void) => () => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Types of parameters 'newState' and 'state' are incompatible.
        Type 'Web3ModalState' is not assignable to type 'PublicStateControllerState'.

37     subscribeState(callback: (state: Web3ModalState) => void): () => void;
       ~~~~~~~~~~~~~~


Error: node_modules/@web3modal/scaffold-utils/dist/types/src/EthersTypesUtil.d.ts:1:39 - error TS2307: Cannot find module '@web3modal/wallet' or its corresponding type declarations.

1 import type { W3mFrameProvider } from '@web3modal/wallet';
                                        ~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.

### List of related npm package versions

"@web3modal/ethers5": "^3.5.1",
"ethers": "^5.7.2",

**Comment by glitch-txs** [comment]
Can you try running `npm install @web3modal/wallet`

**Comment by thedarkknight197** [comment]
Same issue

**Comment by thedarkknight197** [comment]
I have also added @web3modal/siwe 

Now have:

```
Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:20:11 - error TS2430: Interface 'Web3ModalState' incorrectly extends interface 'PublicStateControllerState'.
  Types of property 'selectedNetworkId' are incompatible.
    Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.
      Type 'number' is not assignable to type '`${string}:${string}`'.

20 interface Web3ModalState extends PublicStateControllerState {
             ~~~~~~~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:33:5 - error TS2416: Property 'getState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '() => { selectedNetworkId: number | undefined; open: boolean; }' is not assignable to type '() => { open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }'.
    Call signature return types '{ selectedNetworkId: number | undefined; open: boolean; }' and '{ open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }' are incompatible.
      The types of 'selectedNetworkId' are incompatible between these types.
        Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.

33     getState(): {
       ~~~~~~~~


Error: node_modules/@web3modal/ethers5/dist/types/src/client.d.ts:37:5 - error TS2416: Property 'subscribeState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '(callback: (state: Web3ModalState) => void) => () => void' is not assignable to type '(callback: (newState: PublicStateControllerState) => void) => () => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Types of parameters 'newState' and 'state' are incompatible.
        Type 'Web3ModalState' is not assignable to type 'PublicStateControllerState'.

37     subscribeState(callback: (state: Web3ModalState) => void): () => void;
       ~~~~~~~~~~~~~~




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✖ Failed to compile.


```

**Comment by glitch-txs** [comment]
if you're using Angular make sure to add `"skipLibCheck": true` in the tsconfig.json file

**Comment by thedarkknight197** [comment]
Now is working, please someone update the documentation!!!
(And add also this information for Angular it is still used)

**Comment by glitch-txs** [comment]
I'm not familiar with Angular but if you feel like we'd welcome some example [here](https://github.com/WalletConnect/web-examples) :D

**Comment by thedarkknight197** [comment]
@glitch-txs in doc is missing also:  @web3modal/siwe
I am not in falling in love with React and its ecosystem

**Comment by glitch-txs** [comment]
we have a SIWE section
![image](https://github.com/WalletConnect/web3modal/assets/66949816/010497bd-87c6-4452-a69f-95ab87fe5fe1)

**Comment by glitch-txs** [comment]
should be peer and optional

**Comment by thedarkknight197** [comment]
when i compiled following https://docs.walletconnect.com/web3modal/javascript/about etherscan v5 is required

**Comment by thedarkknight197** [comment]
@glitch-txs : is missing only wise and it not compile :D 
https://codesandbox.io/p/devbox/wallet-connect-p8sdrm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqf0dt3r00092869nsusp7y9%2522%252C%2522sizes%2522%253A%255B59.39779474130619%252C40.60220525869381%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqf0dt3r00022869cegcc5fu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqf0dt3r00072869o7gk7gvn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqf0dt3r00082869opdljsgr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqf0dt3r00022869cegcc5fu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqf0dt3r00012869ckpnr264%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqf0dt3r00022869cegcc5fu%2522%252C%2522activeTabId%2522%253A%2522clqf0dt3r00012869ckpnr264%2522%257D%252C%2522clqf0dt3r00082869opdljsgr%2522%253A%257B%2522id%2522%253A%2522clqf0dt3r00082869opdljsgr%2522%252C%2522activeTabId%2522%253A%2522clqf0fk79003l2869x4q327uj%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clqf0fk79003l2869x4q327uj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clqf0nn9n00n12869yy2cgkjf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqf0dt3r00072869o7gk7gvn%2522%253A%257B%2522id%2522%253A%2522clqf0dt3r00072869o7gk7gvn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqf0dt3r000328696xc7a3sx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clqf0hftv00be2869tgk9ujde%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqf0hfv605vjeelxcb2i5itx%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqf0dt3r000328696xc7a3sx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by thedarkknight197** [comment]
with "skipLibCheck": true is working now
