### ISSUE TITLE
[bug] Arbitrum image should be updated

### ISSUE THREAD

**Issue by enesozturk** [WalletConnect/web3modal#1648]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

The Arbitrum network's image should be updated to a recent one: https://arbitrumfoundation.notion.site/arbitrumfoundation/Arbitrum-Brand-Kit-48751dc5e03240a5872496283f088f79?p=6014e69d7b574f378a50f5ee678495d3&pm=c

### List of related npm package versions

```json
"@web3modal/core": "3.5.0"
```

**Comment by enesozturk** [comment]
> was this resolved? @enesozturk 

I don't think it is. We'll need to update the image in our bucket. I could remind it to @bkrem tomorrow. Remember Chad shared the latest icons with us.

**Comment by bkrem** [comment]
@enesozturk if you send me the exact asset in question I can add it to our Cloudflare Images bucket and then help whitelist it on api.web3modal.com as a public image 👍

**Comment by bkrem** [comment]
@enesozturk think we can close? Looks like this shipped in `v4.0.0`

**Comment by enesozturk** [comment]
@bkrem Exactly, this is fixed, closing.
