### ISSUE TITLE
How to override z-index of modal?

### ISSUE THREAD

**Issue by 0xTimepunk** [WalletConnect/web3modal#165]
I am using react-financial-charts (https://github.com/reactivemarkets/react-financial-charts) and the following happens:

![image](https://user-images.githubusercontent.com/45543880/83782265-7ca1dd80-a687-11ea-8507-a3280734d496.png)

I cannot select the wallets where the chart is being drawn (some elements appear even in front of the web3modal). Do you think I can solve this by overriding the z-index? If so what is the appropriate css class to override? Thank you

**Comment by pedrouid** [comment]
Interesting, that could be useful. Theme is used for colors only... I will leave this issue open to include other overrides in the future but for now it would be best to just target it with a stylesheet

**Comment by j-mars** [comment]
> Interesting, that could be useful. Theme is used for colors only... I will leave this issue open to include other overrides in the future but for now it would be best to just target it with a stylesheet

That's what I will do. Thanks!

**Comment by mkdir01** [comment]
Any updates on this?

**Comment by Xh0st** [comment]
![popup](https://user-images.githubusercontent.com/16942479/125702263-d98920c7-ef00-45fc-b855-49b940226e37.jpg)
Any updates?? How to solve this?

**Comment by Xh0st** [comment]
> > Interesting, that could be useful. Theme is used for colors only... I will leave this issue open to include other overrides in the future but for now it would be best to just target it with a stylesheet
> 
> That's what I will do. Thanks!
> (closed by mistake)

How did you solved ?

**Comment by rafinskipg** [comment]
Please, z-index of 2 is not enough. Allow people to override it

**Comment by giovas94** [comment]
Hi @Xh0st  @rafinskipg,

You just need to add the z-index in the modal calss in your global css file, like this:

`
.web3modal-modal-lightbox {
  z-index: 10 !important;
}
`

**Comment by 70nyIT** [comment]
Understand the trick of the class, but being able to override zIndex keeps the code much more clean. +1 for me for this feature!

**Comment by mhjey** [comment]
Please make it z-Index editable out of the box

**Comment by nicolas-zozol** [comment]
Adding js code to maintain and document when css nails it is not a good idea.

`.web3modal-modal-lightbox.web3modal-modal-lightbox { z-index: 10; }`  mays work without the `!important` addition.

**Comment by GorgeousPuree** [comment]
Such a small feature, but would keep code cleaner.
+1 from me.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Comment by carlosrsabreu** [comment]
For those who are struggling with this, just add this to your CSS:

````
body {
  --w3m-z-index: 1500;
}
````

**Comment by mqklin** [comment]
There is also a documented way: https://docs.walletconnect.com/web3modal/v2/javascript/wagmi/theming#themevariables
```
const web3Modal = new Web3Modal({
  themeVariables: {{
    '--w3m-z-index': 1500,
  }}
})
```

**Comment by kaifirschau** [comment]
@mqklin that worked perfectly for me. Thanks!
