### ISSUE TITLE
[bug] @web3modal/ethers5@3.5.1 has broken dependency

### ISSUE THREAD

**Issue by wwhchung** [WalletConnect/web3modal#1650]
### Link to minimal reproducible example

N/A

### Summary

@web3modal/ethers5@3.5.1 references "@web3modal/siwe" "3.5.0-6a05dc24" as an optional depedency, which does not exist. 

You can reproduce this simply by trying to do:
yarn add @web3modal/ethers5@3.5.1

### List of related npm package versions

@web3modal/ethers5@3.5.1

**Comment by glitch-txs** [comment]
Thanks for reporting, closing in favor of https://github.com/WalletConnect/web3modal/issues/1653
