### ISSUE TITLE
[bug] back button after switching chain broken

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#1655]
### Link to minimal reproducible example

https://web3modal-laboratory-git-360-alpha1-walletconnect1.vercel.app/library/wagmi-email/

### Summary

1. Connect email wallet
2. Click account
3. In account modal switch chain
4. Click back button

Expected bheavior: something happens
Actual behavior: noting happens

https://github.com/WalletConnect/web3modal/assets/966091/0cc17b10-1995-4d90-8f45-5539781aec92

### List of related npm package versions

-

**Comment by tomiir** [comment]
Closing this as it's resolved by #1662
