### ISSUE TITLE
Getting error when without disconnect user is coming to the dapp then it is giving address and isConnected true in useAccount.[bug] 

### ISSUE THREAD

**Issue by narutodev123** [WalletConnect/web3modal#1663]
### Summary

Getting this error user comes to the page without disconnect and does not enter password in the metamask. How to handle this scenario.

![image](https://github.com/WalletConnect/web3modal/assets/87875485/dcea5dd7-6cc0-4132-af6e-26c512b2bd84)

### List of related npm package versions

"@web3modal/wagmi": "^3.4.0",
"viem": "^1.19.11",

**Comment by glitch-txs** [comment]
Please update to Wagmi v2
