### ISSUE TITLE
[feature] Hook for Returning Wallet Information

### ISSUE THREAD

**Issue by remibeaufils** [WalletConnect/web3modal#1665]
### What problem does this new feature solve?

**Issue:**
I'm facing a challenge in identifying which wallet the user has chosen to connect. I've explored the documentation and codebase but couldn't find a solution.

**Description:**
In the context of our application, we use web3modal, and it would be immensely beneficial to retrieve information about the user's chosen wallet during the connection process. This information is crucial for improving user experience and our analytics.

**Background:**
During previous discussions here https://github.com/orgs/WalletConnect/discussions/4027, it was recommended that a dedicated hook be introduced to handle these connections and return relevant wallet information seamlessly.
--> This feature request aligns with the feedback from these discussions, aiming to address the identified gap by proposing the implementation of a specialized hook for retrieving wallet information within the Web3Modal repository.

Thank you for your assistance!

### Describe the solution you'd like

For now I am able to get that information when the user connects through WalletConnect.
But not when the user connects directly with a wallet, eg MetaMask.

I would like to implement the recommendation made by @glitch-txs in the following discussion: https://github.com/orgs/WalletConnect/discussions/4027#discussioncomment-7935554.

The suggestion is to introduce a dedicated hook in the Web3Modal repository for returning wallet information:
> I think we could build a hook for this, could you open an issue in Web3Modal repository for this? we could abstract WalletConnect & EIP-6963 connections into a hook that returns the wallet information or even in the events hook

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by Nazeeh21** [comment]
Can someone assign me this issue, so that I can start working on it?

**Comment by arein** [comment]
Hooks makes sense. Here's how to do without hook: https://github.com/arein/mint-example-ui/blob/main/src/utils/smartAccount.ts#L10

@Sam-Newman for what the right hook api would be

**Comment by glitch-txs** [comment]
@arein
Since we're supporting EIP-6963 as a first class over window.ethereum, we could unified their info object with the WalletConnect metadata for a hook that returns the full info of a connected wallet

**Comment by arein** [comment]
> @arein
> 
> Since we're supporting EIP-6963 as a first class over window.ethereum, we could unified their `info` object with the WalletConnect `metadata` in a hook that returns the full info of a connected wallet

Sounds like a good solution to me @glitch-txs

**Comment by glitch-txs** [comment]
feel free to jump in @Nazeeh21

**Comment by Nazeeh21** [comment]
Cool! will start working on it soon

**Comment by dextfprotocol** [comment]
@Nazeeh21 what's the estimated completion for this? Really looking forward to it ;-)

**Comment by Nazeeh21** [comment]
Hey guys, was quite busy past few days. Will try getting it done by this week.

**Comment by DanilKasianenko** [comment]
Thank you, our team will eagerly anticipate these changes.
