### ISSUE TITLE
[bug] Cannot disable auto connect

### ISSUE THREAD

**Issue by BeycanDeveloper** [WalletConnect/web3modal#1675]
### Link to minimal reproducible example

It's not necessary

### Summary

In wagmi docs showing how i can disable auto connect. But in Web3Modal configurations it's showing impossible. How can i do that?

### List of related npm package versions

"@wagmi/core": "^1.4.12",
"@web3modal/wagmi": "^3.5.1",
"viem": "^1.20.3"

**Comment by glitch-txs** [comment]
In the implementation section select the "custom" tab, you can configure Wagmi separately.

https://docs.walletconnect.com/web3modal/react/about#implementation
