### ISSUE TITLE
[bug] Web3modal don't work with Base network

### ISSUE THREAD

**Issue by amcs99** [WalletConnect/web3modal#1683]
### Link to minimal reproducible example

[Web3modal official](https://web3modal.com/) also got this error

### Summary

Hi, I'm using web3modal together with Wagmi and Viem, my application was working very well with the [Base](https://base.org/) network. But today, it doesn't work, and when I open dev tools it shows below
![image](https://github.com/WalletConnect/web3modal/assets/45377610/b2fa00db-877a-4b42-a817-52540b84ae97)

When I clicked to view the error, it showed like this
![image](https://github.com/WalletConnect/web3modal/assets/45377610/d2eb0173-0408-43db-b645-b2e958bc61a9)

I also tried with [Web3modal official](https://web3modal.com/). It's also got that error if I was on  [Base](https://base.org/) mainnet. Everything will work well if I change the network to ETH or some other chain.

### List of related npm package versions

"viem": "^1.21.0",
 "wagmi": "^1.4.12",
"@wagmi/core": "^1.4.12",
"@web3modal/core": "^3.5.2",
"@web3modal/wagmi": "^3.5.2",

**Comment by 0xAsimetriq** [comment]
Weird, I just tried everything out and seems to work fine, are you still seeing this issue? Perhaps there was a downtime with bases rpc (that we proxy) or maybe you have vpn's enabled?
