### ISSUE TITLE
[bug] Coinbase is force added to the featured wallet list when featured list is defined

### ISSUE THREAD

**Issue by dirtycajunrice** [WalletConnect/web3modal#1687]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/animation-render-forked-wg8glj

### Summary

Walletconnect being added to the list and the browser wallet both make sense. However. Adding coinbase to the feature list is opinionated and should be removed.

### List of related npm package versions

```json
{
  "dependencies": {
    "next": "14.0.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "^1.21.1",
    "wagmi": "^1.4.12",
    "@web3modal/wagmi": "^3.5.3"
  },
  "devDependencies": {
    "@types/node": "20.10.3",
    "@types/react": "18.2.41",
    "@types/react-dom": "18.2.17"
  }
}
```

**Comment by dirtycajunrice** [comment]
> https://github.com/orgs/WalletConnect/discussions/4411#discussioncomment-9611994 It may help you.

it does not. The issue is not related to an ability to remove it, but rather its default setting of being added.

**Comment by glitch-txs** [comment]
We'll work on it 👍

**Comment by glitch-txs** [comment]
We need to do some internal refactor for this as it depends on the connector, we will consider it once this is fixed 👍 thanks!
