### ISSUE TITLE
V2 Wagmi / Viem

### ISSUE THREAD

**Issue by 0xbid** [WalletConnect/web3modal#1718]
### What problem does this new feature solve?

Compatibility with Wagmi and Viem V2, both of which updates recently.

### Describe the solution you'd like

Update to use V2.

**Comment by jacek0x** [comment]
Yeah, seems like the standard command isn't working with NPM anymore: 
```console
npm install @web3modal/wagmi wagmi@1.4.13 viem@1.21.4.
```
I had to use `--legacy-peer-deps` to install it properly. It would be great if the modal could integrate smoothly with Wagmi v2.

**Comment by glitch-txs** [comment]
this was fixed on the latest version so there's no need for the legacy tag anymore, we'll launch Wagmi v2 support this week :)

**Comment by jacek0x** [comment]
> this was fixed on the latest version so there's no need for the legacy tag anymore, we'll launch Wagmi v2 support this week :)

Awesome!

**Comment by Taosome** [comment]
> this was fixed on the latest version so there's no need for the legacy tag anymore, we'll launch Wagmi v2 support this week :)

Thank you for your hard work. When will it be released? I'm very anxious to refactor my code with wagmi V2.

**Comment by rhlsthrm** [comment]
> we'll launch Wagmi v2 support this week :)
Did this happen?

**Comment by 0xbid** [comment]
> > we'll launch Wagmi v2 support this week :)
> 
> Did this happen? @glitch-txs

Judging from #1588 it looks like they are ready to merge. Hoping a release to NPM can be initiated immediately after.

**Comment by vinaykharayat** [comment]
Docs need to be updated as well.

**Comment by 0xbid** [comment]
> Hi guys, we've released an alpha version, please test and give us feedback, sorry for the delay. https://docs.walletconnect.com/web3modal/react/about?platform=wagmi
> 
> Be aware there's currently [an issue with the cookies features](https://github.com/wevm/wagmi/issues/3415) that's on wagmi's side, you can still use the default storage + the ssr flag as true for SSR metaframeworks like Next.js

Will do, thanks so much! -- `npm install` will update to the version that has commit?

**Comment by glitch-txs** [comment]
you need also tanstack

```sh
npm install @web3modal/wagmi@4.0.0-alpha.0 wagmi viem @tanstack/react-query
```

you can also refer to Wagmi's migration guide here: https://wagmi.sh/react/guides/migrate-from-v1-to-v2

**Comment by glitch-txs** [comment]
update: cookies issue fixed https://github.com/wevm/wagmi/pull/3476#event-11520276425

**Comment by glitch-txs** [comment]
There's a typescript issue with chains and metadata, you can ignore them for now, we're fixing it in the next patch 👌

**Comment by socheatleang** [comment]
Hi @glitch-txs 

How about @web3modal/wagmi-react-native? Is there any place that said it upgrade to support wagmi@2 and viem@2?
