### ISSUE TITLE
WalletLink by Coinbase ? 

### ISSUE THREAD

**Issue by miketeix** [WalletConnect/web3modal#172]
Has anyone successfully used Coinbase's WalletLink with web3Modal?
Would it follow the same setup as WalletConnect etc.?

**Comment by waterdrop01** [comment]
There is a PR here: https://github.com/Web3Modal/web3modal/pull/78 but seems staled.

I'm also very interested in Coinbase wallet support.

**Comment by jovinual** [comment]
?

**Comment by rgutierrezatx** [comment]
any updates on this?

**Comment by hackyguru** [comment]
Looks like a duplicate, closing the issue. Track at #266
