### ISSUE TITLE
[bug] Web3Modal cannot open in Next i18n Routing

### ISSUE THREAD

**Issue by JoeKeIsKe** [WalletConnect/web3modal#1740]
### Link to minimal reproducible example

https://github.com/JoeKeIsKe/web3modal-intl-demo

### Summary

Hey, I am trying to do internationalization in Next App Route using next-intl. 

Everything goes okay until I switched the language which is like 'localhost:3000/en' to 'localhost:3000/de'. Then I found that <w3m-modal> tag was disappeared from the DOM and Web3Modal cannot open anymore. 
![image](https://github.com/WalletConnect/web3modal/assets/38954753/9775a92a-1748-4ca2-a088-1e7a1cdc7fab)

Here is a link to the demo: https://github.com/JoeKeIsKe/web3modal-intl-demo. I've tried router API from next-intl and next/navigation. It goes same. 

### List of related npm package versions

   "@web3modal/wagmi": "^3.5.5",
    "next": "14.0.4",
    "next-intl": "^3.4.2",
    "react": "^18",
    "react-dom": "^18",
    "viem": "1.21.4",
    "wagmi": "1.4.13"

**Comment by glitch-txs** [comment]
Likely caused by a hydration mismatch error on the app

**Comment by JoeKeIsKe** [comment]
Thank you for your comments. I am trying to figure out where the hydration mismatch error came from. But, actually, I do not get any error information from the console. The problem is still here when I removed next-intl.

**Comment by JoeKeIsKe** [comment]
Updates:

Web3modal can work again after putting **Web3ModalProvider** and **<body>** tag in layout.tsx under app folder rather than dynamic route folder. 

Kind of mislead by the demo provided by next-intl which put html & body tag in dynamic route folder. But, anyway, it works. Thank you for your help @glitch-txs and this issue will be closed.
