### ISSUE TITLE
[feature] Hope it could open({walletId:'walletId'}) directly.

### ISSUE THREAD

**Issue by KotenkaLily** [WalletConnect/web3modal#1743]
### What problem does this new feature solve?

Which can make those frequently used wallets be directly put on the page.

### Describe the solution you'd like

Add a prop for open();
`
open({
  walletId:'walletId'
}) 
`

**Comment by glitch-txs** [comment]
Hi, could you share a bit more about its use case? Why would you like to have this?

Have you also tried Wagmi's connectors?

**Comment by KotenkaLily** [comment]
> Hi, could you share a bit more about its use case? Why would you like to have this?
> 
> Have you also tried Wagmi's connectors?

Sorry for replying late.

Well I think it's not quite necessary either... Our dapp's designer said "hope so", for our users usually simply used those several wallet like MetaMask and XDEFI. However we do need to support new users who only have other wallets. 

The designer searched a lot and the conclusion is that many dapps were still using v2 together with their own implements on wallets, and now she hopes these "own implements" to have the same style as w3m's.

I've downloaded the source and found the best way is using your "wui" to rewrite one, which is quite embarrassing...... So I'm here to talk about if it's a enough good idea and if it's very easy for you to add this feature.

About the way of using Wagmi connectors, the key problem for me is I don't know how to make the invoking of connecting the wallet looks the same as the w3m.

**Comment by glitch-txs** [comment]
We're are not planning this feature at the moment, but we're going to be adding more customization features for theming, is this something could be useful for your case? Feel free if so to let me know which features.

Otherwise, if you're planning to rebuild the modal, you can use ethereum-provider which has the v2 designed as you mentioned, but you can also disable the modal and build your own on top, you will need to subscribe to the URI and with it create a QR code for desktop and for mobile you need to trigger a new window calling the wallet's deeplink+ the URI as URL param.

**Comment by KotenkaLily** [comment]
A late thanks again. I've been trying to make it during my spare time these days while I found it really hard. A rebuilding could cost very much and I doubt if I could implements the direct wallet function I mentioned through w3m's ethereum-provider.

Whatever, now I hope to know whether I could use wagmi (in 'VUE.js') to connect to wallet and to sign the infomation and the connected status into web3modal? I'm pretty sure it's possible but I'm not quite sure where to start... Although the Wagmi gives the Web3modal [support](https://wagmi.sh/react/guides/connect-wallet), its docs gave different options from [Web3modal's quickstart for vue](https://docs.walletconnect.com/web3modal/vue/about), and wagmi itself seems to be mainly supporting 'REACT.js', which made me, who's not professional in Javascript, a little embarrassed.

Maybe it's just the time I should study hard at wagmi...

**Comment by glitch-txs** [comment]
Sorry for the late reply, you can use Wagmi with Vue, they have released official support now.
