### ISSUE TITLE
[bug] w3m-button with hide balance dont looks good.

### ISSUE THREAD

**Issue by cesar4design** [WalletConnect/web3modal#1750]
### Link to minimal reproducible example

<w3m-button balance='hide' />

### Summary

If I hide the balance,` <w3m-button balance='hide' />`, when I hover the buttton appear a background box. If I dont hide the balance looks good. 

![image](https://github.com/WalletConnect/web3modal/assets/75784005/c2eb7498-6979-4be7-9271-cb0b3b291958)

### List of related npm package versions

"@web3modal/wagmi": "^3.5.6",
"viem": "^1.21.4",
"wagmi": "^1.4.13"

**Comment by wslyvh** [comment]
This issue still persists on @web3modal/wagmi ^4.1.6

cc @glitch-txs

**Comment by glitch-txs** [comment]
Could you please create a new issue if this still happens on the latest? We added a bit to automate and follow up on the new issue. Thanks!
