### ISSUE TITLE
[bug] useDisconnect doesn't work in vue

### ISSUE THREAD

**Issue by ernesck** [WalletConnect/web3modal#1751]
### Link to minimal reproducible example

https://docs.walletconnect.com/web3modal/vue/composables

### Summary

Documentation in here https://docs.walletconnect.com/web3modal/vue/composables tells that it's possible to useuseDisconnect in vue, however, @web3modal/wagmi/vue doesn't export such functionality.

<img width="916" alt="Screenshot 2024-01-15 at 13 55 29" src="https://github.com/WalletConnect/web3modal/assets/45652676/cc9bdcc0-6f5e-4fcc-a1dc-f25eed54d926">

Am I doing something wrong? Maybe it's possible to provide working useDisconnect example is vue?

### List of related npm package versions

"@wagmi/core": "^1.4.13",
"@web3modal/wagmi": "^3.5.6",

**Comment by glitch-txs** [comment]
you need to import it from 'wagmi' and not web3modal.
it should also be `disconnect`

https://1.x.wagmi.sh/core/actions/disconnect
