### ISSUE TITLE
[feature] SIWE / Signing get deeplink URL / routing.

### ISSUE THREAD

**Issue by ZeroTimeDrift** [WalletConnect/web3modal#1755]
### What problem does this new feature solve?

Signature signing on mobile using deeplinks, at the moment, SIWE on mobile is very fiddly with URLs - if I try to execute in a restricted environment such as an iFrame it is blocked on mobile.

### Describe the solution you'd like

To be able to extract the walletconnect URI / manually route the user to the app itself by exposing the URIs / wallet app in some way for SIWE as well as any other request that requires signing to handle the URL manually.

**Comment by glitch-txs** [comment]
Since Web3Modal is a high level SDK we're not planning exposing the URI, for this case you should use a more low level package like ethereum-provider where you can subscribe to the URI https://docs.walletconnect.com/advanced/providers/ethereum

**Comment by ZeroTimeDrift** [comment]
I’m using web3modal which requires wagmi or viem, is there a way to use
ethereum provider in web3modal and if so how can I set it up?

**Comment by glitch-txs** [comment]
yes, you can access ethereum-provider from wagmi connectors: https://github.com/wevm/wagmi/blob/main/packages/connectors/src/walletConnect.ts
