### ISSUE TITLE
Update Web3Modal Events

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal#1760]
**Requirements**
1.  Update the `MODAL_OPEN` and `MODAL_CLOSE` Events to include a new property 'Connected' which can be either true(wallet is connected) or false (no wallet is connected)
2. Add new events for the following:
- CLICK_CHOOSE_NETWORK
- SELECT_NETWORK
- CLICK_ACTIVITY

Details can be found in this spreadsheet:
https://docs.google.com/spreadsheets/d/1F07sUJhq29S0v5UTe_Q2SZinNQ9tGN9tTN_cOdcZUZk/edit#gid=0

**Comment by tomiir** [comment]
Applied naming changes and added descriptions in spreadhsheet
CLICK_CHOOSE_NETWORK => OPEN_NETWORKS_VIEW
SELECT_NETWORK => SWITCH_NETWORK
CLICK_ACTIVITY => OPEN_ACTIVITY_VIEW
