### ISSUE TITLE
Failed to publish source map

### ISSUE THREAD

**Issue by javaspeak** [WalletConnect/web3modal#1762]
### Link to minimal reproducible example

https://github.com/spotadev/next-id-wallet

### Summary

When in package.json I have:

"@web3modal/wagmi": "^3.5.6",

when I run:  npm run start

I get warnings like:

Failed to parse source map from '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-email-input/styles.ts' file: Error: ENOENT: no such file or directory, open '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-email-input/styles.ts'

Failed to parse source map from '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-icon-box/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-icon-box/index.ts'

Failed to parse source map from '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-icon-box/styles.ts' file: Error: ENOENT: no such file or directory, open '/Users/johndickerson/GITHUB_HOSTING/next-id-wallet/node_modules/@web3modal/ui/src/composites/wui-icon-box/styles.ts'

Is this warning to be expected?

### List of related npm package versions

"dependencies": {
        "@testing-library/jest-dom": "^5.17.0",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^13.5.0",
        "@types/jest": "^27.5.2",
        "@types/node": "^16.18.69",
        "@types/react": "^18.2.46",
        "@types/react-dom": "^18.2.18",
        "@web3modal/wagmi": "^3.5.6",
        "axios": "^1.6.5",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-scripts": "5.0.1",
        "typescript": "^4.9.5",
        "viem": "^1.21.4",
        "wagmi": "^1.4.13",
        "web-vitals": "^2.1.4"
      },

**Comment by s5s-TMD** [comment]
any updates guys?

**Comment by glitch-txs** [comment]
this is an outdated version, please open a new issue
