### ISSUE TITLE
Toggle: Users must accept T's & C's before continuing

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal#1763]
**Context**
Currently dApps can provide a link to their Terms & Conditions on W3M, but there is no way for dApps to ensure that users have accepted their T's & C's before they connect. 

**Example from Blocknative**
![Image](https://github.com/WalletConnect/web3modal/assets/84375331/2f67aed4-26d2-419f-b3b4-df8c38dd8b44)

**Current View in W3M**

![Image](https://github.com/WalletConnect/web3modal/assets/84375331/aa459ae9-2961-4f8e-a757-39dfbf159f54)

**Requirement**
- Add an option toggle that dApps can include to force their users to accept terms and conditions.

https://docs.walletconnect.com/web3modal/javascript/options#termsconditionsurl

**Comment by dianeben** [comment]
Hey @Sam-Newman , we could have a checkbix before the Wallets lists and disable them until T&Cs are agreed as here
https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?type=design&node-id=14656-367744&mode=design&t=EnkLa7jai4IMjbnq-4
![Image](https://github.com/WalletConnect/web3modal/assets/57009607/8b03fe6a-ab5c-4cdf-9e99-92bcc96252b8)
