### ISSUE TITLE
[bug] signature failed SIWE and can't disconnect wallet

### ISSUE THREAD

**Issue by ZeroTimeDrift** [WalletConnect/web3modal#1767]
### Link to minimal reproducible example

http://3.125.0.251:3002/ - select the "Ethereum wallet" option from connect wallet

### Summary

Error: No matching key when signed into a wallet using WC and trying to disconnect. Can't SIWE. Signature fails when trying to sign message. 

Steps to reproduce:
1. Connect WC compatible wallet
2. Sign message
3. Clear cache
4. attempt to sign in using another wallet by connecting

You will not be able to sign messages and if you try to disconnect you get the error No matching key in browser console.

### List of related npm package versions

    "@web3modal/core": "^3.5.6",
    "@web3modal/ethereum": "^2.7.1",
    "@web3modal/wagmi": "^3.5.3",

**Comment by glitch-txs** [comment]
If you're still experiencing this issue in the latest version please create a new one as we have integrated a new ticketing system, thanks!
