### ISSUE TITLE
[feature] Support for page router

### ISSUE THREAD

**Issue by hskang9** [WalletConnect/web3modal#1776]
### What problem does this new feature solve?

Next.js 14's app router is not suitable for real web app development as most next.js packages are now suited to page router. The only app that one can create is the tutorial like projects. I don't understand why this web3modal only supports integration for app router when most next.js developers are busy migrating from page router to app with so many errors and breaking changes.

### Describe the solution you'd like

Make integration for page router asap. just do it.

**Comment by glitch-txs** [comment]
Hi, Web3Modal already supports page routers.

**Comment by hskang9** [comment]
I don't see any integration guide in the documentation. https://docs.walletconnect.com/web3modal/nextjs/about. Where can I find the example?

**Comment by hskang9** [comment]
I see page router example after running the command `npx create-wc-dapp@latest -y w3m`. I hope to see page router guide though.

**Comment by glitch-txs** [comment]
you can use the React guide, the only thing that changes is adding the ssr feature https://wagmi.sh/react/guides/ssr

**Comment by hskang9** [comment]
Unfortunately, this does not support javascript. the library just does not integrate. it keeps showing 
`TypeError: Cannot read properties of undefined (reading 'queryClient')`. While the whole update is for predictable implementation, the integration is confusing and unpredictable more than ever before.

**Comment by hskang9** [comment]
Also, I have noticed now using wagmi hook in `_app.js` is not possible anymore. Is this true?

**Comment by hskang9** [comment]
Also, current WagmiConfig does not support using wagmi hook on `_app.js`, blowing up an log in feature on connecting wallet.
