### ISSUE TITLE
[bug] w3m / wagmi 4.alpha issues

### ISSUE THREAD

**Issue by wslyvh** [WalletConnect/web3modal#1782]
### Link to minimal reproducible example

https://github.com/wslyvh/w3m-demo

### Summary

Trying to upgrade wagmi/viem to V2 using the latest Web3Modal alpha version.
Noticed some issues during migration..

The documentation tries to use a WagmiConfig as provider instead of WagmiProvider
Submitted a PR at https://github.com/WalletConnect/walletconnect-docs/pull/1332

The metadata requires a verifyUrl, but I can't find any info on how to use or set this up properly.
In previous version this used to be optional
https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/src/utils/defaultWagmiCoreConfig.ts
It is required in the latest package alpha package @web3modal/wagmi@4.0.0-alpha.0

The chains type in the ConfigOptions also seems incorrect in that same package: `chains: [Chain, ...Chain[]];`
In previous version this used to be: `chains: Chain[]` (which seems to make more sense)
https://github.com/WalletConnect/web3modal/blob/V3/packages/wagmi/src/utils/defaultWagmiCoreConfig.ts

If I try to connect or of I'm already connected to a network that isn't configured, it shows I'm not connected.
w3m-button will just show "Connect account"
When I try to connect account using the Metamask adapter, it shows an error:
"Connection declined" - Connection can be declined if a previous request is still active
I think the proper flow should be to connect and then ask to switch network? 
This does happen if I try to connect using browser wallet.

Minimal reproducible demo
https://github.com/wslyvh/w3m-demo

### List of related npm package versions

npx create-next-app@latest
yarn add @web3modal/wagmi@4.0.0-alpha.0 wagmi viem @tanstack/react-query

**Comment by glitch-txs** [comment]
Thanks so much for this 🙏

cc @tomiir

**Comment by glitch-txs** [comment]
btw you won't need the setReady useState anymore, you can pass down `ssr: true` in `defaultWagmiConfig`

**Comment by tomiir** [comment]
@wslyvh First of all tyvm for this!
I'll try to answer all your points one by one:
-You are correct on the WagmiProvider vs WagmiConfig. Just saw the docs pr was merged, thank you 🔥 
- verifyUrl is required for now as it's a required arg in wagmi's WC connector but we have this on our radar as it doesn't make much sense to require this tbh. My main idea right now is make this all optional on the user side and provide defaults on our side.
- Chain type was changed by wagmi and it does make sense as `Chain[]` would allow an empty array, while `[Chain, ...Chain[]]` wouldn't. Still, from our testing, no casting should be necessary, will take a look. 
- Regarding connecting to a chain that's not configured, I think that kind of makes sense. The connector needs to know beforehand which chains it's allowed to connect to. I'd think (personal opinion) that if:
  a) you are on a non-configured chain on your wallet, connection should fail / should be disabled
  b) if you are on a non-configured chain in your wallet and you change network on your site to try and connect to a configured one, it should prompt you to connect + switch network.
  
  
 I hope I answered your points and this makes sense. Please feel free to drop any questions or comment that you may still have!
 
Cheers!

**Comment by wslyvh** [comment]
@tomiir thanks for quick response and info. Very helpful!

Can you share how verifyUrl should be used? I've currently configured it as a empty string (`''`) which seems to work. 
But this might have unintended side-effects?

The Chain type makes sense. Altho it does keep a type issue, if you define the chains elsewhere.
E.g. this example from the docs does NOT work, as it infers the type as `Chain[]`
```
const chains = [mainnet, arbitrum]
const wagmiConfig = defaultWagmiConfig({
    chains,
})
```

But this does work
```
const wagmiConfig = defaultWagmiConfig({
    chains:  [mainnet, arbitrum]
})
```

Not a huge deal, but it might be confusing for people who copy/paste from the docs.

The connection issue is somewhat annoying. I believe the behavior used to be different in V3. I.e. w3m recognized if the account was connect but on a wrong network. It now seems like you're not connected at all, without proper messaging that you should switch.

**Comment by glitch-txs** [comment]
We'll probably remove chains from createWeb3Modal.

For the cookies, you need to create the config on a different file, seems to break because it's inside the client component, I will update docs next week

**Comment by 0xbid** [comment]
@glitch-txs I'm pretty sure `useWeb3Modal` open does not work at all in v4, at least in Nextjs. Have you tested this?

**Comment by ethan-auroria** [comment]
@wslyvh it appears that the trick to get the chains array to work is by adding `as const`:

```js
const chains = [mainnet, arbitrum] as const;
const wagmiConfig = defaultWagmiConfig({
    chains,...
});
```

**Comment by glitch-txs** [comment]
Thanks so much again for all the feedback, we have address each item stated here, please let us know if you find anything else we could improve. Thanks!

Docs: https://docs.walletconnect.com/web3modal/about

**Comment by wslyvh** [comment]
Thanks for the update! Can confirm it all works nicely.
Just ugraded Nexth again to latest stable releases.

1 minor issue on the doc, which still mentions v3. Submitted a PR for it :)
Docs https://docs.walletconnect.com/web3modal/about
PR https://github.com/WalletConnect/walletconnect-docs/pull/1398
