### ISSUE TITLE
[bug] Telegram inAPP Android

### ISSUE THREAD

**Issue by mastbmawstaken** [WalletConnect/web3modal#1787]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

When trying to connect to a wallet in the web3modal inside the telegram ( you need to open it as in-APP) you're prompt with an error, this error does not seem to happen in iOS because you're capable of choosing the browser that telegram is opening internally, but in Android there's no such choice as such the user is prompted with the following error:

Error:

```
Webpage not available
The webpage at wc:e0cbf07c74c4e140169a6e8094eab4db72c6cda91aded28e98140dd240422a96@2?relay-protocol=irn&symKey=33687006de92293ca4637ac53c1bd68cba1ae48a6f5653ff4a694dd3209c6350 could not be loaded because:
net::ERR_UNKNOWN_URL_SCHEME
```

![image](https://github.com/WalletConnect/web3modal/assets/45356549/1716ca6d-0177-4abe-bb07-d5b866b64bd6)

Video reproducing error:

https://github.com/WalletConnect/web3modal/assets/45356549/4994dda3-24c8-4345-919e-f68b2a1cc7fd

### List of related npm package versions

    "@web3modal/ethereum": "^2.7.0",
    "@web3modal/react": "^2.7.0",
    "next": "13.2.4",
    "wagmi": "^1.3.9",
    "react": "18.2.0",
    "viem": "^1.3.0",

**Comment by glitch-txs** [comment]
Hi can you try upgrading to v3 or v4? I'm not able to reproduce the issue there.

Web3Modal v2 has been deprecated

**Comment by anthais** [comment]
I had the same issue on V3. And even when I use https://web3modal.com as bot URL, I got the same error.
![image](https://github.com/WalletConnect/web3modal/assets/26503206/4ba07b84-7de4-4d42-9648-a3160aca7285)
![image](https://github.com/WalletConnect/web3modal/assets/26503206/aded3845-06b8-4c6c-82a2-88163364549f)
My telegram app is here: https://t.me/AnthaisBot/web3modaldemo
