### ISSUE TITLE
[bug] SecurityError: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by vietddude** [WalletConnect/web3modal#1840]
### Link to minimal reproducible example

https://github.com/WalletConnect/web-examples

### Summary

Got this error while click to button Open Connect Modal
<img width="1032" alt="Screenshot 2024-01-26 at 11 40 37 AM" src="https://github.com/WalletConnect/web3modal/assets/75874082/1b04e33a-4fc3-46dc-929a-147a37ab3c6c">
clicking

### List of related npm package versions

   "@emotion/react": "^11.11.3",
    "@emotion/styled": "^11.11.0",
    "@fontsource/roboto": "^5.0.8",
    "@mui/material": "^5.15.6",
    "@tanstack/react-query": "^5.17.19",
    "@wagmi/core": "^2.5.0",
    "@web3modal/wagmi": "4.0.0-3a0b2d54",
    "axios": "^1.6.5",
    "next": "^14.1.0",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.49.3",
    "viem": "^2.5.0",
    "wagmi": "^2.5.0"

**Comment by glitch-txs** [comment]
Hi can you try updating to 4.0.0-alpha.3 and clearing cache?

**Comment by vietddude** [comment]
> Hi can you try updating to 4.0.0-alpha.3 and clearing cache?

Updated to 4.0.0-alpha.3 and cleared cache, but still facing the issue.

**Comment by davidkarim** [comment]
I believe I am seeing the same issue. I am trying to do a write operation on a smart contract and it looks like the browser is trying to open a modal. Not sure. Oddly, I did see a scenario where I got a popup on my mobile Metamask to confirm the transaction. That happened once, I am not seeing any response on my mobile Metamask. Looks like my desktop browser is trying to show a modal with a QR code but the transaction is just timing out. I have:

    "@web3modal/wagmi": "4.1.1",
    "wagmi": "^2.5.11",

I have the following error on my browser's console:

```
[Error] Blocked a frame with origin "https://XXX-XXX-XX-XX-XXX.ngrok-free.app" from accessing a frame with origin "https://verify.walletconnect.org". Protocols, domains, and ports must match.
```

**Comment by felipelincoln** [comment]
same problem using `ethers`
```json
{
    "@web3modal/ethers": "^4.1.8",
    "ethers": "^6.11.1"
}
```

**Comment by manish252488** [comment]
Any updates ?? im facing the same issue here

**Comment by felipelincoln** [comment]
This is the workaround I am using for now:

```js
function handleOpen(){
  try{
    open();
  } catch(_e){
    open();
  }
}
```
Because for me, calling `open()` twice works. 🤷

**Comment by glitch-txs** [comment]
This is Verify API and doesn't affect the functionality of the SDK, it is correct if the domain doesn't match with the verified one, but this error should go away on production. So for staging non-verified links this error is expected.

**Comment by felipelincoln** [comment]
> This is Verify API and doesn't affect the functionality of the SDK, it is correct if the domain doesn't match with the verified one, but this error should go away on production. So for staging non-verified links this error is expected.

@glitch-txs this is happening to me on production. Can you provide more details on how to fix it? I have the `metadata.domain` matching my production domain

**Comment by glitch-txs** [comment]
should be `metadata.url`

**Comment by felipelincoln** [comment]
> should be `metadata.url`

sorry, yeah, I meant I have the `metadata.url` matching my prod url.
this is what I have:
```js
const ethersConfig = defaultConfig({
  metadata:  {
      name: 'Some Name',
      description: 'Some description',
      url: 'https://<mysubdomain>.<mydomain>.io/'
      icons: [''],
    },
  rpcUrl: '<rpc>',
  defaultChainId: 1,
})
```

**Comment by felipelincoln** [comment]
1914112795a676dc1449b23b8bd1dc9e

**Comment by glitch-txs** [comment]
@felipelincoln you need to verify your domain: https://docs.walletconnect.com/cloud/verify

**Comment by manish252488** [comment]
> This is the workaround I am using for now:
> 
> ```js
> const { open } = useWeb3Modal();
> 
> function handleOpen(){
>   try{
>     open();
>   } catch(_e){
>     open();
>   }
> }
> ```
> 
> Because for me, calling `open()` twice it works. 🤷

nice work arround, works for me

**Comment by felipelincoln** [comment]
@glitch-txs got it, thanks.
Is there a way to disable the verify api though?

**Comment by glitch-txs** [comment]
> Is there a way to disable the verify api though?

No because is a security layer for wallet, but we will add the option to add more domains and whitelist localhost too

**Comment by JohnCido** [comment]
Any update on this? This is blocking me from test it in local environment.
