### ISSUE TITLE
[Unhandled Runtime Error] useWeb3ModalAccount()

### ISSUE THREAD

**Issue by bofomike** [WalletConnect/web3modal#1845]
### Link to minimal reproducible example

https://github.com/bofomike/wallet-connect-nextjs-test-app

### Summary

I'm trying to follow WalletConnect docs to integrate Web3Modal component into my Next.js application. 

Unfortunately, I'm getting an error even though I'm simply following [the instruction](https://docs.walletconnect.com/web3modal/nextjs/about?platform=ethers)

![Screenshot 2024-01-28 at 19 04 14](https://github.com/WalletConnect/web3modal/assets/32751280/95b37798-73c0-483a-ac34-7fa1f9243268)

### List of related npm package versions

node 20.8.1
npm 9.5.0
@web3modal/ethers 3.5.7
ethers 6.10.0

**Comment by glitch-txs** [comment]
Hi, hooks can only be called inside client components.

**Comment by bofomike** [comment]
Ahhh 🙃 thank you! 🫡

**Comment by Kipperlenny** [comment]
I ran into the same problem, I think the docs and examples for Next.JS with Ethers could be easier to understand here.
