### ISSUE TITLE
Peanut: Styling issue on Secure site and Get Wallet button

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal#1849]
**Issue**
 - Styling is incorrect
**Secure Site**
![Image](https://github.com/WalletConnect/web3modal/assets/84375331/b2da64fa-4d8b-457a-94b1-d0a5054d3e22)

**Get a Wallet**
![Image](https://github.com/WalletConnect/web3modal/assets/84375331/7de5942b-0d4e-430e-bf97-2091bdb78faf)

**Comment by xzilja** [comment]
We need to add new theming option for button text color as relying on "color mix" approach here is not working.
