### ISSUE TITLE
Infinite loader when editing an email

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal#1850]
Repro steps:
- Edit email 
- receive verify new email to updated email , ignore it
- Go back to W3M
-  Edit email again
- Infinite spinner

Expected result:
 - Resends verification email.
 https://www.loom.com/share/4b6d7b4a3d444140ab2515138b02bb88

**Comment by xzilja** [comment]
Should be unblocked / solved once https://github.com/WalletConnect/web3modal/issues/1851 is completed
