### ISSUE TITLE
dApps allowlist set in cloud

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal#1858]
dApps need to set an allowlist. 
Check validation works

https://walletconnect.slack.com/archives/C05QPSW56L8/p1706648406426349?thread_ts=1706534488.560559&cid=C05QPSW56L8

**Comment by arein** [comment]
They can already do it and it should already be required.
Based on the fact that Alfredo was able to use it on mobile though raises the question whether the implementation works.

@Sam-Newman @xzilja @tomiir can one of you check please? We can pair on this too

**Comment by xzilja** [comment]
This is done and we patched issue that Alfredo discovered.
