### ISSUE TITLE
[bug] SIWE session does not survive a page refresh

### ISSUE THREAD

**Issue by ukstv** [WalletConnect/web3modal#1869]
### Link to minimal reproducible example

https://github.com/ukstv/web3modal-caip-repro

Please, pay attention to `README` on `main` branch.
There is a `fix` branch that applies a patch to `@web3modal/scaffold` to fix the issue, similar to a proposed change in https://github.com/WalletConnect/web3modal/pull/1868

### Summary

Expectation:

1. A user signs in through SIWE flow ⇒ an application knows the person's address
2. A user reloads a page through Command+R ⇒ the application continues the session

<img width="1140" alt="Screenshot 2024-02-04 at 16 08 21" src="https://github.com/WalletConnect/web3modal/assets/193527/ab6170c5-6879-49ce-80fe-c2fac677dbbc">

Reality:

1. A user signs in through SIWE flow ⇒ the application knows the person's address
2. A user reloads a page through Command+R ⇒ **the application asks for a SIWE signature again** (bug!)

<img width="1140" alt="Screenshot 2024-02-04 at 16 19 41" src="https://github.com/WalletConnect/web3modal/assets/193527/15a2cbdc-5e15-4ed8-bd73-8bee4eb0c5af">

It looks like Web3Modal SIWE flow forgets about a SIWE session. The root cause is that
Web3Modal [gets `caipAddress` property
initialized from `AccountController.state.address`](https://github.com/WalletConnect/web3modal/blob/V4/packages/scaffold/src/modal/w3m-modal/index.ts#L170) which _is not_ a CAIP address.

### List of related npm package versions

```
"dependencies": {
    "@tanstack/react-query": "^5.18.1",
    "@wagmi/core": "^2.6.3",
    "@web3modal/core": "4.0.0-alpha.3",
    "@web3modal/siwe": "4.0.0-alpha.3",
    "@web3modal/wagmi": "4.0.0-alpha.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "siwe": "^2.1.4",
    "viem": "^2.7.3",
    "wagmi": "^2.5.5"
  }
```

**Comment by big-zak** [comment]
I am having similar issue, but after further tracing, I found the code causing that in node_modules/@web3modal/scaffold/dist/esm/index.js line 148
` const session = await SIWEController.getSession();
                if (session && !isConnected) {
                    await SIWEController.signOut();
                } else if (isConnected && !session) {
                    this.onSiweNavigation();
                }
            } catch (error) `

Siwe session is fetched before the wallet gets connected, making the the isConnected variable false which forces a signOut

**Comment by anxiubin** [comment]
hi @svenvoskamp
is this issue solved? i got same issue too 

```
    "@reown/appkit": "1.5.3",
    "@reown/appkit-adapter-wagmi": "1.5.3",
    "@reown/appkit-siwe": "1.5.3",
```
