### ISSUE TITLE
[bug] Failed to resolve '@web3modal/scaffold-utils/ethers' using Parcel

### ISSUE THREAD

**Issue by bonnopc** [WalletConnect/web3modal#1871]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/trzfxg

### Summary

Hey guys, I am trying to upgrade to Web3Modal v3. I am using vanilla typescript for my project. So far, I tried to follow the [documentation](https://docs.walletconnect.com/web3modal/javascript/about). But I am getting the following error while trying to bundle them using Parcel:

```
$ parcel build index.html
🚨 Build failed.

@parcel/core: Failed to resolve '@web3modal/scaffold-utils/ethers' from 
'./node_modules/@web3modal/ethers5/dist/esm/src/client.js'

  /Users/.../node_modules/@web3modal/ethers5/dist/esm/src/client.js:30:8
    29 |                 if (walletChoice?.includes(ConstantsUtil.WALLET_CONNECT_CONNECTOR_ID)) {
  > 30 |                     const provider = await this.getWalletConnectProvider();
  >    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    31 |                     if (!provider) {
    32 |                         throw new Error('networkControllerClient:getApprovedCaipNetworks - provider 

@parcel/resolver-default: Cannot load file './ethers' from module '@web3modal/scaffold-utils'
```

Detailed implementation can be found in the Codesandbox/ minimal reproducible example link. Following is what my `tsconfig.json` file looks like:

``` js
{
  "compilerOptions": {
    "target": "ES6",
    "module": "CommonJS",
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "outDir": "dist",
    "declaration": true,
    "typeRoots": ["./node_modules/@types"],
    "skipLibCheck": true
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules"]
}
```

*Additional Info*: I'm using this project as an SDK for a dapp built with Next.js. I tried ignoring the parcel build error and compiling them using `ts-node` to use it on my Next.js app. But I am getting a different error for it:

```
Server Error
Error: require() of ES Module /Users/.../node_modules/@web3modal/ethers5/dist/esm/exports/index.js from /Users/.../node_modules/.../dist/frontend/Account.js not supported.
Instead change the require of index.js in /Users/.../node_modules/.../dist/frontend/Account.js to a dynamic import() which is available in all CommonJS modules.
```

### List of related npm package versions

- `@web3modal/ethers5@3.5.7`
- `ethers@5.7.2`
- `parcel@2.2.1`

**Comment by glitch-txs** [comment]
Not sure about the first one, but for the second error you seems to be compiling it to CommonJS, you might want to config your bundler to both esm and csj. Also try upgrading to v4 which is the latest version of Web3Modal.
