### ISSUE TITLE
Allow to disable unsupported chain popup

### ISSUE THREAD

**Issue by iuriiiurevich** [WalletConnect/web3modal#1891]
### What problem does this new feature solve?

There is this awesome brand new unsupported chain popup: https://github.com/WalletConnect/web3modal/pull/1860 (thanks @svenvoskamp)
Related: https://github.com/WalletConnect/web3modal/issues/1422

But there are cases where it doesn't matter whether the user is connected to a supported network or not.
In these cases, this popup window may be intrusive and unwanted.

### Describe the solution you'd like

Add a flag that allows opt-out of this feature.

**Comment by wslyvh** [comment]
+1 

I created the linked issue for the network pop-up, but would be great to make this configurable. Not every App requires this, and it could often be considered very annoying actually :sweat_smile:

**Comment by nemmtor** [comment]
Unfortunately the popup still opens
