### ISSUE TITLE
Error integrating with Angular 8

### ISSUE THREAD

**Issue by beejay141** [WalletConnect/web3modal#190]
ERROR in node_modules/web3modal/dist/components/Modal.d.ts:34:19 - error TS2503: Cannot find namespace 'JSX'.

34     render: () => JSX.Element;
                     ~~~
node_modules/web3modal/dist/components/Provider.d.ts:1:23 - error TS2688: Cannot find type definition file for 'react'.

1 /// <reference types="react" />
                        ~~~~~
node_modules/web3modal/dist/components/Provider.d.ts:10:58 - error TS2503: Cannot find namespace 'JSX'.

10 export declare function Provider(props: IProviderProps): JSX.Element;
                                                            ~~~
node_modules/web3modal/dist/core/index.d.ts:10:9 - error TS1086: An accessor cannot be declared in an ambient context.

10     get cachedProvider(): string;
           ~~

**Comment by beejay141** [comment]
can anybody help with this..

**Comment by filipbarak** [comment]
Hey @beejay141 . I've had the same problem. This is what you need to do.
Get a pure build from here: https://github.com/Web3Modal/web3modal/releases
I've added the Web3Modal.js (renamed from index.js) into my `src/assets/scripts/Web3Modal.js`

Then, include into your index.html entrypoint like so: 

```
<body>
  <app-root></app-root>
</body>
<script src="./assets/scripts/Web3Modal.js"></script>
```
Then, wherever you wanna use it, initialize it like
`const Web3Modal = window.Web3Modal.default;
`

That's it. You can use Web3Modal now according to the docs.

**Comment by beejay141** [comment]
thanks @filipbarak ,i will try this out

**Comment by ctharvey** [comment]
While this works it is not great if you want to keep the asset up to date.  Any chance of fixing this issue?

**Comment by webcat12345** [comment]
@filipbarak 's solution works :+1

**Comment by hackyguru** [comment]
Update on this issue, we did not provide support for other frameworks except react based ones. But W3MV2 will be framework agnostic and will support majority of the most used frameworks.
