### ISSUE TITLE
[bug] Email feature w3i dogfooding issues

### ISSUE THREAD

**Issue by enesozturk** [WalletConnect/web3modal#1918]
### Link to minimal reproducible example

Can be reproducible with the following preview links:
- [GM Dapp Preview](https://gm-dapp-l7zkt38yi-walletconnect1.vercel.app/)
- [W3I Preview](https://app-web3inbox-g0of24pwk-walletconnect1.vercel.app/)

### Summary

We found some issues while dogfooding the email beta feature in web3inbox:

- [x] In the signing message modal, the message area is not toggling when clicking on it. So only a small part of the message is readable: 
<img width="255" alt="Screenshot 2024-02-13 at 17 02 58" src="https://github.com/WalletConnect/web3modal/assets/19428358/7f324dc8-240b-45dd-b92b-d22e2abcde26">

- [x] Clicking the 'x' or outside the window leaves the register spinning (need to check with w3i team)
- [x] When rejecting the device approving does nothing on w3m
- [x] When typing the wrong code, need to remove the first character to paste another code
- [x] Changing email address results in a back button that doesn't do anything
- [x] Bad error styling on OTP view

[Slack conv](https://walletconnect.slack.com/archives/C044SKFKELR/p1707831599918869?thread_ts=1707527886.425219&cid=C044SKFKELR) that includes all these screenshots

### List of related npm package versions

```json
"@web3modal/wagmi": "4.0.4"
```

**Comment by tomiir** [comment]
@enesozturk Testing the signign issue and I can sign messages just fine
<img width="665" alt="image" src="https://github.com/WalletConnect/web3modal/assets/12738697/4da41587-5e4b-45fc-84b2-b65703cfc166">
<img width="404" alt="image" src="https://github.com/WalletConnect/web3modal/assets/12738697/06de5417-b8dd-43c4-bcd0-e6c6ea19ef62">

What browser are you using? Any other error in console/network that you could provide?
