### ISSUE TITLE
[bug]  Browser window closes when disconnected

### ISSUE THREAD

**Issue by harniy** [WalletConnect/web3modal#1924]
### Link to minimal reproducible example

https://mfactory-lab.github.io/jpool-ssv-webapp/

### Summary

There is a problem on some computers with Windows and Mac (the browsers are completely different). When the wallet is disconnected from web3Modal, the browser window closes. We checked in Google Chrome, Firefox, Brave, Microsoft Edge. For unknown reasons, this bug is rare, and what’s most interesting is that if you open incognito mode in the browser, everything works well and the browser does not crash. Has anyone encountered this?

### List of related npm package versions

"@web3modal/ethers": "^3.5.7"

**Comment by glitch-txs** [comment]
This works well on our side
https://lab.web3modal.com/

Could you share a minimal reproducible example of the issue? Either a code sandbox or a small repo. Thanks!
