### ISSUE TITLE
[bug] Production Build with Qwik Framework - Uncaught TypeError

### ISSUE THREAD

**Issue by neotheprogramist** [WalletConnect/web3modal#1947]
### Link to minimal reproducible example

https://github.com/emeth-defi-automation/portfolio-management-platform/tree/350eecaa182cff2ae9861abae8fe1981cf344d40

## Description
I am currently developing a web3 app using Qwik as the framework. I have encountered a peculiar issue related to the production build when creating the `defaultWagmiConfig`. It seems to be a problem with the minification process, as everything works fine when running with `npm run dev`.

## To Reproduce
1. Run `npm run build`.
2. Run `npm run serve`.
3. Open `localhost:3000`.
4. Open the console.

## Issue
The following error is thrown:
```
Uncaught (in promise) TypeError: b is not a function
at f ((index):4:143)
```

Upon investigation, it appears that the variable `b` is undefined and not being initialized. It is created using `let`.

## Further Steps
1. Comment out the creation of `defaultWagmiConfig`.
2. Observe that the issue disappears.

## Expected Behavior
The production build should not result in the `Uncaught TypeError` when creating `defaultWagmiConfig`. The behavior should be consistent with running in development mode (`npm run dev`), where everything works fine.

## Additional Information
- Framework: Qwik
- Build command: `npm run build`
- Serve command: `npm run serve`

This issue is impacting the functionality of my web3 app, and I would appreciate assistance in resolving this issue. Thank you.

### List of related npm package versions

{
  "name": "my-qwik-empty-starter",
  "description": "App with Routing built-in ready to create your app",
  "engines": {
    "node": "21.6.2"
  },
  "private": true,
  "trustedDependencies": [
    "sharp"
  ],
  "type": "module",
  "scripts": {
    "build": "qwik build",
    "build-storybook": "storybook build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.server": "vite build -c adapters/fastify/vite.config.ts",
    "build.types": "tsc --incremental --noEmit",
    "deploy": "echo 'Run \"npm run qwik add\" to install a server adapter'",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "serve": "node server/entry.fastify",
    "start": "vite --open --mode ssr",
    "storybook": "storybook dev -p 6006",
    "test.unit": "vitest components",
    "test.unit.ui": "vitest --ui components",
    "update": "npx npm-check-updates -u",
    "update.check": "npx npm-check-updates",
    "qwik": "qwik"
  },
  "devDependencies": {
    "@builder.io/qwik": "1.4.5",
    "@builder.io/qwik-city": "1.4.5",
    "@fastify/compress": "7.0.0",
    "@fastify/static": "7.0.1",
    "@microsoft/eslint-formatter-sarif": "3.0.0",
    "@storybook/addon-essentials": "7.6.17",
    "@storybook/addon-links": "7.6.17",
    "@storybook/blocks": "7.6.17",
    "@storybook/builder-vite": "7.6.17",
    "@storybook/html": "7.6.17",
    "@storybook/html-vite": "7.6.17",
    "@stylexjs/eslint-plugin": "0.5.1",
    "@types/eslint": "8.56.2",
    "@types/node": "20.11.19",
    "@typescript-eslint/eslint-plugin": "7.0.2",
    "@typescript-eslint/parser": "7.0.2",
    "@vitest/ui": "1.3.1",
    "dotenv": "16.4.5",
    "eslint": "8.56.0",
    "eslint-plugin-qwik": "1.4.5",
    "fastify": "4.26.1",
    "fastify-plugin": "4.5.1",
    "prettier": "3.2.5",
    "storybook": "7.6.17",
    "storybook-framework-qwik": "0.3.0",
    "typescript": "5.3.3",
    "undici": "6.6.2",
    "vite": "5.1.3",
    "vite-plugin-stylex-dev": "0.3.0",
    "vite-tsconfig-paths": "4.3.1",
    "vitest": "1.3.1"
  },
  "dependencies": {
    "@dnlup/fastify-traps": "3.0.2",
    "@stylexjs/stylex": "0.5.1",
    "@wagmi/connectors": "4.1.14",
    "@wagmi/core": "2.6.5",
    "@web3modal/siwe": "4.0.6",
    "@web3modal/wagmi": "4.0.6",
    "siwe": "2.1.4",
    "viem": "2.7.11"
  }
}

**Comment by glitch-txs** [comment]
Thanks for reporting, please provide a minimal reproducible example, the example given is not minimal.

**Comment by neotheprogramist** [comment]
@glitch-txs 
You're right, I'm going to open new issue with minimal example

**Comment by neotheprogramist** [comment]
Here is new issue with minimal example - just Qwik init and install wagmi
https://github.com/WalletConnect/web3modal/issues/1950
