### ISSUE TITLE
[tests] Ensure Playwright tests cover all supported browsers

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/web3modal#1951]
### What problem does this new feature solve?

- Full context: https://www.notion.so/walletconnect/Web3Modal-Email-Broken-on-Brave-be2a045358194508bf727d276dd19814?pvs=4#ed67982e932b4a8fb5239af12b41768e
- Our [target devices](https://github.com/WalletConnect/web3modal/blob/V4/apps/laboratory/tests/shared/constants/devices.ts#L1) for playwright functional tests currently do not cover all browsers we want to ensure support for (e.g. Brave).

### Describe the solution you'd like

- Expand the playwright pipeline to run against Brave (or emulate/approximate Brave's behaviour) and any other browser envs that are currently not covered

**Comment by lukaisailovic** [comment]
Brave support implemented https://github.com/WalletConnect/web3modal/pull/1997

Safari still not working on CI
