### ISSUE TITLE
When used in Next.js project, web3modal fails the project

### ISSUE THREAD

**Issue by ukstv** [WalletConnect/web3modal#196]
When Next.js renders React code, there is no `document` or `window` available. Web3Modal heavily relies on these. I found I could eliminate some of the warnings with `typeof document !== "undefined"` kind of checks, but rendering process (https://github.com/Web3Modal/web3modal/blob/master/src/core/index.tsx#L146) is too intricate to intervene.

**Comment by jzstern** [comment]
I used the following snippet on my `Wallet` component containing `web3Modal` and it seems to have eliminated Next.js issues

```
import dynamic from 'next/dynamic'

const Wallet = dynamic(
  () => import('../../src/components/Wallet'),
  { ssr: false }
)
```

**Comment by AmanRaj1608** [comment]
Any solution here?

**Comment by carloshc** [comment]
Any solution here? (2)

**Comment by eth0izzle** [comment]
I was struggling with the same issue on Gatsby but I was using hooks instead of components, meaning I couldn't use `React.lazy()`. My solution was simply load the modal in a `useEffect`:

```
    const [web3Modal, setWeb3Modal] = useState(null);

    useEffect(() => {
        if (!web3Modal) {
            try {
                import("web3modal").then(Web3Modal => {
                    setWeb3Modal(new Web3Modal.default({
                        // options here
                    }))
                })
            } catch (e) {
                console.log('Error while creating Web3Modal');
            }
        }
    }, [])
```

**Comment by wbhob** [comment]
> I was struggling with the same issue on Gatsby but I was using hooks instead of components, meaning I couldn't use `React.lazy()`. My solution was simply load the modal in a `useEffect`:
> 
> ```
>     const [web3Modal, setWeb3Modal] = useState(null);
> 
>     useEffect(() => {
>         if (!web3Modal) {
>             try {
>                 import("web3modal").then(Web3Modal => {
>                     setWeb3Modal(new Web3Modal.default({
>                         // options here
>                     }))
>                 })
>             } catch (e) {
>                 console.log('Error while creating Web3Modal');
>             }
>         }
>     }, [])
> ```

This is a good way to do it. The reason it's failing is because of SSR, so putting anything in useEffect defers loading to client-side.

You could refine this a little further by separating it out into its own hook:

```ts
export function useWeb3Modal() {
    const [web3Modal, setWeb3Modal] = useState(null);

    useEffect(() => {
        if (!web3Modal) {
            try {
                import("web3modal").then(Web3Modal => {
                    setWeb3Modal(new Web3Modal.default({
                        // options here
                    }))
                })
            } catch (e) {
                console.log('Error while creating Web3Modal');
            }
        }
    }, [])

    return web3Modal;
}
```

Then in your components:

```ts
const web3Modal = useWeb3Modal();

/// web3Modal.present() or whatever
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
