### ISSUE TITLE
Error when attempting to import ConstantsUtil from @web3modal/core in client.js from @web3modal/wagmi  [bug] 

### ISSUE THREAD

**Issue by YVeselovskyi** [WalletConnect/web3modal#1962]
### Link to minimal reproducible example

Just update the libraries

### Summary

After updating to v2.0 now I have this error.

Steps to Reproduce:

Install @web3modal/wagmi and @web3modal/core.
Attempt to import ConstantsUtil from @web3modal/core in a file like client.js.

Observe the error mentioned above.

Expected Behavior:
The import of ConstantsUtil from @web3modal/core should work without errors.
<img width="1307" alt="Знімок екрана 2024-02-22 о 15 01 12" src="https://github.com/WalletConnect/web3modal/assets/16061418/0809970e-b031-43f8-99ec-3133a233e08d">

### List of related npm package versions

  "@wagmi/connectors": "^4.1.14",
  "@wagmi/core": "^2.6.5",
  "@web3modal/wagmi": "^4.0.9",
   "viem": "^2.7.12",
  "vite": "^5.1.4"

**Comment by kaushikriya** [comment]
Installing `web3modal/core` worked for me!
