### ISSUE TITLE
[bug] Binance Web3 Wallet <> Android

### ISSUE THREAD

**Issue by ggomaeng** [WalletConnect/web3modal#1971]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Binance Web3 Wallet connector seems to be broken on Android.

Connection Popup does not appear.

It works fine on iOS.

https://github.com/WalletConnect/web3modal/assets/18402191/6e433b73-4dc5-4d30-8595-e7d985883101

### List of related npm package versions

"@web3modal/wagmi": "^4.0.8",
"viem": "^2.4.1",
"wagmi": "^2.3.1"

**Comment by ggomaeng** [comment]
is this being reviewed?

**Comment by DanHumphry** [comment]
Request a review. 
I also faced the same issue.

"@web3modal/wagmi": "^4.1.6",
"viem": "2.8.4",
"wagmi": "2.5.7",

**Comment by redDwarf03** [comment]
@ggomaeng have you find the solution please ?
