### ISSUE TITLE
Different Events in mobile and desktop

### ISSUE THREAD

**Issue by mostafa-rio** [WalletConnect/web3modal#1989]
**Describe the bug**
If we try to write our logic based on this equality our logic will only work if this runs only  on dekstop:
   `web3ModalEvents.event === "CONNECT_SUCCESS"`
   
and in mobile version SELECT_WALLET will be fired
 
**To Reproduce**
Create a simple react app with walletconnect/ethers5 and add useWeb3ModalEvents and check the event on mobile and desktop

**Comment by glitch-txs** [comment]
hi, what's the expected behavior you're looking for?

**Comment by mostafa-rio** [comment]
The expected behavior is to have the same behavior as the desktop and the web3ModalEvents.event === "CONNECT_SUCCESS" must be evaluated to true whenever we successfully connect to a mobile wallet. If there is a limitation on mobile there should be a section in the document to explain this behavior.

**Comment by glitch-txs** [comment]
got it, in the meantime you can use these getters, you can also subscribe to them: https://docs.walletconnect.com/web3modal/javascript/actions?platform=ethers5#ethereum-library

```ts
const isConnected = modal.getIsConnected()

// or

function handleChange({ isConnected }) {
  //...
}

modal.subscribeProvider(handleChange)
```

**Comment by mostafa-rio** [comment]
Awesome that would solve my issue. You also may tag this issue for future pull requests.
