### ISSUE TITLE
[bug] Connect wallet modal stucks when open on mobile devices

### ISSUE THREAD

**Issue by lilhuy0405** [WalletConnect/web3modal#1992]
### Link to minimal reproducible example

https://game.xfish.pet/

### Summary

- the modal is opned by calling the open() method
- Then the modal is stucked. Nothing happens when buttons are clicked and even can not close the modal
- Problems only occurs on mobile devices ( includes the built in metamask browser, built in okx web browser or even the chrome, safari web browser).  For desktop browsers it works like a charm

### List of related npm package versions

- "@wagmi/core": "^1.4.10",
- "@web3modal/wagmi": "^3.4.0",
-   "viem": "^1.19.13"
-   "vite": "^5.0.0"

**Comment by glitch-txs** [comment]
Hi, feel free to open a [GitHub discussion](https://github.com/orgs/WalletConnect/discussions) sharing a minimal reproducible example

You can also test our official implementation: https://lab.web3modal.com/
and examples: https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal
