### ISSUE TITLE
[feature] Add possible to change default title on Modal

### ISSUE THREAD

**Issue by DanilKasianenko** [WalletConnect/web3modal#1995]
### What problem does this new feature solve?

Introducing the ability to dynamically change the default title in our modal component heralds customization and an improved user experience. By giving users the freedom to tailor the name to their specific needs, we open up a range of personalization and branding opportunities within our app.

### Describe the solution you'd like

![image](https://github.com/WalletConnect/web3modal/assets/150665419/0dd9dc43-34f1-4f1e-901a-f69c9a8d6349)
<img width="693" alt="image" src="https://github.com/WalletConnect/web3modal/assets/150665419/959b9638-52cd-4338-a7b6-a702725bc741">

**Comment by glitch-txs** [comment]
related: https://github.com/orgs/WalletConnect/discussions/4246
