### ISSUE TITLE
[docs] useWeb3Modal's close() function - Minimal Documentation on How to Fully Disconnect A Connection

### ISSUE THREAD

**Issue by ymonye** [WalletConnect/web3modal#2013]
### Summary

Looking through the Web3Modal React / Next Hooks page, it doesn't really explain how to use the close function to disconnect from a wallet. Also, how would you completely disconnect from  a wallet. Connecting with open() seems to work, yet you can see the documentation for close kinda just cut off:

https://docs.walletconnect.com/web3modal/react/hooks

```
import { useWeb3Modal } from '@web3modal/wagmi/react'

export default function Component() {
  const { open, close } = useWeb3Modal()

  open()

  //...
}
```

### Link to the related docs page

https://docs.walletconnect.com/web3modal/react/hooks

**Comment by ymonye** [comment]
Well in that case, I know running open() from useWeb3Modal() changes the states of "isConnecting, isConnected, isDisconnected" in wagmi's useAccount(). However now running disconnect() from wagmi's useDisconnect doesn't really update useAccount(). How would I do that, and I guess the close() from useWeb3Modal does nothing? If so, why is close() even still referenced in the docs?

**Comment by glitch-txs** [comment]
close function closes the modal
