### ISSUE TITLE
[bug] pull and npm install results in error on windows environment

### ISSUE THREAD

**Issue by kostia-lev** [WalletConnect/web3modal#2016]
### Link to minimal reproducible example

git repo is an example

### Summary

1. git pull
2. npm install results in error
 C:\Users\usr\Documents\Projects\opensource\web3modal\node_modules\bufferutil
npm ERR! errno -4058
npm ERR! enoent spawn sh ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

### List of related npm package versions

PS C:\Users\usr\Documents\Projects\opensource\web3modal> npm -v
10.5.0
PS C:\Users\usr\Documents\Projects\opensource\web3modal> node -v
v21.6.2
Windows 10 Pro

**Comment by glitch-txs** [comment]
What's the full error log? Can you try node 18/20?

**Comment by kostia-lev** [comment]
I opened wsl, installed node v18.19.1,  npm 10.2.4. And happy that npm install works.
