### ISSUE TITLE
Wallet Connect not working

### ISSUE THREAD

**Issue by Thrasymachus01** [WalletConnect/web3modal#202]
```javascript
        const web3Modal = new Web3Modal({
                providerOptions: {
                    disableInjectedProvider: false,
                    cacheProvider: false,
                    walletconnect: {
                        package: WalletConnectProvider, // required
                        options: {
                            infuraId: "INFURA_ID" // required
                        }
                    }
                }
            });

      const web3Provider = await web3Modal.connect(); // Hangs here but no errors thrown
      console.log("provider", web3Provider) // This line is never reached
```

Connection is successful (displays success message in Trust Wallet app and no errors are thrown in the client console) but it hangs on connecting in the client. Unclear if this is a web3modal issue or a trust wallet issue but banking on the issue being with web3modal since everything in the Trust Wallet app seems to be working fine.

This issue can be replicated in the demo site using Trust Wallet and Wallet Connect: https://web3modal.com/

**Comment by CRYPTO-GENIK** [comment]
Same issue - it seems that in my case https://unpkg.com/evm-chains@0.2.0/lib/index.js is now broken where as it was there this morning. 
Possibly related issue.
At any rate I can't connect to metamask via Web3Modal

**Comment by hackyguru** [comment]
Hello, this issue is now fixed in W3MV2, please reopen if you it persists.
