### ISSUE TITLE
[bug] "incorrectly extends interface" errors  when compiling with Typescript and Angular

### ISSUE THREAD

**Issue by Cadey** [WalletConnect/web3modal#2024]
### Link to minimal reproducible example

Angulat 17, TypeScript 5.3.3

### Summary

When adding the package to a Angular 17 (typescript 5.3.3) project I get the following errors when building the app.

If I change the 

```"export type CaipNetworkId = `${string}:${string}`;" ```
to 
```"export type CaipNetworkId = `${string}:${string}` | number;"```

and 

```
Class Web3ModalScaffold 

getState(): {
        open: boolean;
        selectedNetworkId?: `${string}:${string}` | undefined;
    };
```
to
```
   getState(): {
        open: boolean;
        selectedNetworkId?: `${string}:${string}` | number | undefined;
    }; 
```

it will then compile

rror: node_modules/@web3modal/ethers/dist/types/src/client.d.ts:21:11 - error TS2430: Interface 'Web3ModalState' incorrectly extends interface 'PublicStateControllerState'.
  Types of property 'selectedNetworkId' are incompatible.
    Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.
      Type 'number' is not assignable to type '`${string}:${string}`'.

21 interface Web3ModalState extends PublicStateControllerState {
             ~~~~~~~~~~~~~~


Error: node_modules/@web3modal/ethers/dist/types/src/client.d.ts:35:5 - error TS2416: Property 'getState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '() => { selectedNetworkId: number | undefined; open: boolean; }' is not assignable to type '() => { open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }'.
    Call signature return types '{ selectedNetworkId: number | undefined; open: boolean; }' and '{ open: boolean; selectedNetworkId?: `${string}:${string}` | undefined; }' are incompatible.
      The types of 'selectedNetworkId' are incompatible between these types.
        Type 'number | undefined' is not assignable to type '`${string}:${string}` | undefined'.

35     getState(): {
       ~~~~~~~~


Error: node_modules/@web3modal/ethers/dist/types/src/client.d.ts:39:5 - error TS2416: Property 'subscribeState' in type 'Web3Modal' is not assignable to the same property in base type 'Web3ModalScaffold'.
  Type '(callback: (state: Web3ModalState) => void) => () => void' is not assignable to type '(callback: (newState: PublicStateControllerState) => void) => () => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Types of parameters 'newState' and 'state' are incompatible.
        Type 'Web3ModalState' is not assignable to type 'PublicStateControllerState'.

39     subscribeState(callback: (state: Web3ModalState) => void): () => void;
 

### List of related npm package versions

"@web3modal/ethers": "^4.0.11",

**Comment by glitch-txs** [comment]
in the tsconfig.json file add `"skipLibCheck": true`

**Comment by glitch-txs** [comment]
Next.js has this by default and I think most vite projects too and it's fine, sometimes the Typescript version doesn't match with the library's one and so on, also without it you get extra computation that's unnecessary.

**Comment by Cadey** [comment]
Well the issue is with the types, if the base classes define the properties as "`${string}:${string}` | number | undefined" instead of just " `${string}:${string}` | undefined" then it would compile correctly.

The error here being the implementing class is overriding a base class with a different type, that breaks the OO rules.

Any I missing a reason why adding the number definition is incorrect when the implementing class clearly needs it?

**Comment by glitch-txs** [comment]
that's not the issue, types are correct you're just using a different configuration than ours.

**Comment by Cadey** [comment]
In the source there is a ``@ts-expect-error`` however this isn't being included in the dist. version. My guess is its being scrubbed out as a comment. May be this would resolve the issue?

https://github.com/WalletConnect/web3modal/blame/ef7a7754491ffe1c9fc48f45624f4e818d0910d7/packages/ethers/src/client.ts#L61

**Comment by glitch-txs** [comment]
If you check on your logs it's not the only error you'll see, the best is to use this option it will also optimize your build time.

**Comment by Cadey** [comment]
No, but its the only error that stops the build but anyway ill stop commenting and leave you be :)

**Comment by glitch-txs** [comment]
No problem, feel free to open a PR if you think it can improve the typing but I'm not sure that will fix your issue.
