### ISSUE TITLE
Changing the color of connected account informations misses out with w3m-router!

### ISSUE THREAD

**Issue by L1xus** [WalletConnect/web3modal#2041]
### Link to minimal reproducible example

Change the color of connected account informations misses out with w3m-router!

### Summary

Hi, I'm trying to change the theme of my app and wanna add specific colors to specific parts!
I tried to override the default style of the module with css but failed :/
I'm using this style now in createWeb3Model
`themeVariables: { '--w3m-accent': '#fe7e01', '--w3m-border-radius-master': '1px', '--w3m-color-mix': "#333333", '--w3m-color-mix-strength': 100 } `
  but I get this problem!

![20240309_02h02m03s_grim](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/19f2020f-1566-4c24-a0bd-d754db491e09/7f4e2748-4f44-438f-b1e4-5dfb64b784ee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS8xOWYyMDIwZi0xNTY2LTRjMjQtYTBiZC1kNzU0ZGI0OTFlMDkvN2Y0ZTI3NDgtNGY0NC00MzhmLWIxZTQtNWRmYjY0Yjc4NGVlIiwiaWF0IjoxNzExMzgwMTQ2LCJleHAiOjMzMjgxOTQwMTQ2fQ.Mu6khmV_G7voPOxQS3bymRvZSbefYsEiVnRDYmjYfXY)

### List of related npm package versions

```
  "@tanstack/react-query": "^5.25.0",
    "@web3modal/wagmi": "^4.0.13",
    "dotenv": "^16.4.5",
    "next": "14.1.3",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.7.20",
    "wagmi": "^2.5.7"
```

**Comment by svenvoskamp** [comment]
Hey, currently we don't support extensive theming. You can change the overall color of the modal with the `--w3m-color-mix` and `--w3m-color-mix-strength` variables. This color will blend into the modal, and --w3m-color-mix-strength determines how strongly it blends in.

I see you have a `--w3m-color-mix-strength` of 100. This is not recommended; try something like 40-50.

We will release support for extensive theming somewhere in Q2 of this year.

Hope this helps!

**Comment by svenvoskamp** [comment]
Closing as we will fix this with extensive theming in Q2
