### ISSUE TITLE
[bug] await modal.open() immediately resolves, does not await - how to get user address after wallet connection

### ISSUE THREAD

**Issue by hcote** [WalletConnect/web3modal#2047]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/yn4wks?file=%2Fsrc%2FApp.tsx%3A43%2C28

### Summary

Using `@web3modal/ethers5` I was expecting to login a user and get their wallet address with the following code:

```js
await modal.open();
const address = await modal.getAddress();
```

However `modal.open()` is not awaited and any following code immediately runs even though the modal for the user to connect is still showing. 

Or is there another way you should get the address of the logged in user (not using hooks, just vanilla js)?

Sort of separately, but when a user rejects the wallet connection from `modal.open()`, the `catch` block isn't hit - how would a developer know when this happens, to show some sort of alert error?

### List of related npm package versions

@web3modal/ethers5

**Comment by glitch-txs** [comment]
You need to use the `subscribeProvider` function to track account changes

https://docs.walletconnect.com/web3modal/javascript/actions#ethereum-library

**Comment by hcote** [comment]
@glitch-txs thank you - is there a way to remove the subscription so I'm not attaching multiple listeners?

For example with metamask it could look something like this
```
useEffect(() => {
  window.ethereum.on('accountsChanged', handleChange);
  return () => {
      provider.removeListener('accountsChanged', handleChange);
  }
}, []);
```

**Comment by glitch-txs** [comment]
I think `off` is the right function

**Comment by glitch-txs** [comment]
```ts
function handleChange({ provider, providerType, address, error, chainId, isConnected }) {
  console.log(isConnected, address)
}

const unsubscribe = modal.subscribeProvider(handleChange)

unsubscribe()
```

**Comment by hcote** [comment]
Thanks again, but I'm missing how calling `modal.subscribeProvider` unsubscribes the listener since that's how it's attached - can you please explain with a little more detail?

**Comment by rkreutzer** [comment]
I had the same issue and also assumed that modal.open would resolve once the connection has been made. I think the documentation could be expanded to to the point where you have access to the account info. Something like this would be super helpful.

`  async connectToWallet() {
    this.modal.subscribeState(newState => {
      this.modalState = newState
    })
    try {
      if (getAccount(this.config).isConnected) {
        await disconnect(this.config)
      } 
      this.modal.open()
      await this.waitForModalStateChange()
      const acct = getAccount(this.config)
      this.account = acct?.address
    } catch (e) {
      console.error(e);
    }
  }

  async waitForModalStateChange() {
    return new Promise<void>((resolve) => {
        const checkInterval = setInterval(() => {
          if (this.modalState?.open == false) { // modal is closed
                clearInterval(checkInterval);
                resolve();
            }
        }, 500); // check every 500ms
    });
  } 
`

**Comment by glitch-txs** [comment]
@hcote if you're using React why do you want to subscribe? you can use the hook to get the address and will rerender the component when it changes.

**Comment by hcote** [comment]
@glitch-txs I'm not using react, just vanilla js, I was just using that as an example of how metamask has a `removeListener` method, and am looking for the equivalent for web3modal's `subscribeProvider`.

**Comment by glitch-txs** [comment]
> @glitch-txs Thanks again, but I'm missing how calling modal.subscribeProvider unsubscribes the listener since that's how it's attached - can you please explain?

The function `subscribeProvider` doesn't unsubscribe, but it returns a function when called, this function will unsubscribe from the event when called.
