### ISSUE TITLE
[feature] Theming should support accent colors that are lighter.

### ISSUE THREAD

**Issue by mvillere** [WalletConnect/web3modal#2048]
### What problem does this new feature solve?

Currently, if you set a theming value for accent that is a light color, it nicely applies to button background colors. However, the text color remains white.

If you set a lighter color as the accent, since the text remains white, it looks bad, and there is no easy way to override.

### Describe the solution you'd like

Please provide a way to theme the foreground color of text, at least as it applies to text that is displayed on top of the accent color.

![image](https://github.com/WalletConnect/web3modal/assets/1437748/045cb2f5-f2ec-4174-aa91-084209e4dc15)

createWeb3Modal({
  wagmiConfig: wagmiConfig,
  projectId: walletConnect_projectId,
  enableAnalytics: false, // Optional - defaults to your Cloud configuration
  defaultChain: mainnet,
  themeMode: "dark",
  themeVariables: {
    "--w3m-font-family": "Inter, sans-serif",
    "--w3m-accent": "#FFD400",
    "--w3m-color-mix": "#867000",
    "--w3m-color-mix-strength": 16,
    "--w3m-border-radius-master": `${computedBorderRadius}rem`,
  },
})

**Comment by mvillere** [comment]
added screenshot and code sample

**Comment by svenvoskamp** [comment]
Closing as we currently don't support extensive theming. We will add support for extensive theming in Q2 this year which will solve this issue.

**Comment by rori4** [comment]
@svenvoskamp I can see theme is not added in Q2 2024. Any way to customize at least the text color?
