### ISSUE TITLE
[bug] Web3Modal sign message popup not working anymore in mobile

### ISSUE THREAD

**Issue by hustynetwork** [WalletConnect/web3modal#2067]
### Link to minimal reproducible example

merchant.dex3.io

### Summary

When trying to connect metamask mobile, the connection popup shows in metamask. However when trying to sign a transaction. There is no popup in metamask mobile. Issue is only in metmask mobile.

### List of related npm package versions

web3modal

**Comment by glitch-txs** [comment]
Hi, could you share a minimal reproducible example and steps to repro?
We have some examples here: https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal
