### ISSUE TITLE
[bug] - Hide logs on production

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#2071]
### Link to minimal reproducible example

labs

### Summary

From this discussion: https://github.com/orgs/WalletConnect/discussions/4357

Logs shouldn't be logged on production env.
![316282834-8c3a850c-53d2-4293-bbe1-2c87ef080f50](https://github.com/WalletConnect/web3modal/assets/66949816/ff65071c-8efb-4e73-98f2-42056b5adafa)

### List of related npm package versions

latest

**Comment by nsnull0** [comment]
just for updates.
environment 4.1.7 still received logs in production, exposed projectId in the logs.
![Screenshot 2024-04-11 at 23 34 09](https://github.com/WalletConnect/web3modal/assets/26643922/002be145-8457-4a67-9d04-200320fbeece)
