### ISSUE TITLE
[bug] The IOS metamask app does not switch back to the web application. When the connect is successfully

### ISSUE THREAD

**Issue by trimn-1012** [WalletConnect/web3modal#2076]
### Link to minimal reproducible example

[https://react-app.walletconnect.com/](https://react-app.walletconnect.com/)

### Summary

**Title:**

The IOS metamask app does not switch back to the web application. When the connect is successfully

**Environment:**

* Operating System: IOS
* Browser: Safari
* Device: Iphone 11 Pro
* Version: 17.3

**Description:**

Summary: The IOS metamask app does not switch back to the web application. When the connect is successfully.

Details: When I click connect using web3modal and I select metamask app. Now it will open the metamask on my device and show it on the connect popup. After connecting successfully, I don't see walletconnect open web app by deeplink. This only happens to IOS devices, but it does not happen to Android devices.

**Steps to Reproduce:**

1. Visit [Website](https://react-app.walletconnect.com/).
2. Click on the \['Connect'\] button.
3. Observe that the WalletConnect popup window appears.
4. Click on the Metamask.
5. Observe the Metamask open and the connect popup appears.
6. Click on the \['Connect'\] button.

**Expected Behavior:**

After connecting is successful, it will be redirected back to the web app.

**Actual Behavior:**

After connecting is successful, it is still open in the metamask application.

**Screenshots/Attachments:**

Android:

[Screenrecorder-2024-03-27-16-36-12-610.webm](https://github.com/WalletConnect/web3modal/assets/64879807/dfc47341-d0e5-4d92-83f9-b71c103e34d6)

IOS:

[https://github.com/WalletConnect/web3modal/assets/64879807/8181d1b1-4e91-4adb-b120-d747e6227b8d](https://github.com/WalletConnect/web3modal/assets/64879807/8181d1b1-4e91-4adb-b120-d747e6227b8d)

### List of related npm package versions

```
"@celo/wallet-base": "^5.1.1",
"@ethereumjs/tx": "^3.5.0",
"@kadena/client": "^0.5.0",
"@kadena/cryptography-utils": "^0.4.0",
"@kadena/types": "^0.6.0",
"@multiversx/sdk-core": "12.18.0",
"@multiversx/sdk-wallet": "4.2.0",
"@polkadot/util-crypto": "^10.1.2",
"@solana/web3.js": "^1.36.0",
"@walletconnect/encoding": "^1.0.1",
"@walletconnect/sign-client": "2.11.3",
"@walletconnect/types": "2.11.3",
"@walletconnect/utils": "2.11.3",
"@web3modal/standalone": "2.4.3",
```

**Comment by glitch-txs** [comment]
Hi, iOS 17 doesn't support this, we recommend wallets to use their UI to walk their users to manually go back.
