### ISSUE TITLE
[bug] Connection to WalletConnect wallets persists on repetitive reconnections

### ISSUE THREAD

**Issue by meri-maki** [WalletConnect/web3modal#2079]
### Link to minimal reproducible example

https://wc-connect-five.vercel.app/

### Summary

On mobile when reconnecting to WalletConnect via Web3Modal, the connection request is not sent to the wallet app
When connected this way (without approve in wallet app) the redirect popups do not appear on any interactions (sendTransaction/writeContract)

Normal flow (first connection):

https://github.com/WalletConnect/web3modal/assets/97887955/a614f5b8-5042-4284-aa93-a5c8f8f6cae5

Second connection to same wallet after page reload (wagmi config has ```reconnectOnMount={false}```):

https://github.com/WalletConnect/web3modal/assets/97887955/0bcd34ec-2b17-462b-b928-c8a4daa6641d

The connection happens without redirection and confirmation and later transactions fire but without redirect popup

additional discussion: https://discord.com/channels/492410046307631105/1221767594474995712

**Steps To Reproduce**
https://github.com/meri-maki/wc-connect
(npm i
npm run start)

https://wc-connect-five.vercel.app/
open on mobile
connect with WalletConnect to Zerion/Trust (default chain is set to sepolia)
try sending transaction - fires with popup
reload page
connect again to same wallet
try sending transaction - fires without popup

### List of related npm package versions

Wagmi Version 2.5.12

Viem Version 2.8.18

Web3Modal Version 4.1.1

**Comment by meri-maki** [comment]
Any news...?

**Comment by glitch-txs** [comment]
Are you still experiencing this issue in the latest version?

**Comment by glitch-txs** [comment]
Closing as this is a Wagmi issue. Let's open the issue there please.
