### ISSUE TITLE
The `<w3m-button/>` doesn't restore session after page reload in Next.js 14.

### ISSUE THREAD

**Issue by skibitsky** [WalletConnect/web3modal#2126]
**Describe the bug**
The `<w3m-button/>` doesn't restore session after page reload in Next.js 14.

The workaround is to disable `enableEmail` in the WAGMI config.

**SDK Version (if relevant)**
-   @web3modal/siwe: ^4.1.5
 - @web3modal/wagmi: ^4.1.5
 - viem: ^2.9.8,
 - wagmi: ^2.5.18
 - next: 14.1.4,

**To Reproduce**
1. Go to https://unity-web3modal-wagmi-gb75xhybh-skibitsky.vercel.app/
2. Click on `Connect Wallet` in the `React` section
3. Connect a wallet
4. Sign message. Confirm it works.
5. Close the tab. Open the same url again.
6. After the page is loaded, you will most likely see the `Account` button instead of `Connect Wallet`, as expected. However, after a few seconds, the button will turn into `Connect Wallet`.
7. However, the Sign Message button remains active and can still sign messages.

**Expected behavior**
After page reload, the `Account` button is shown instead of `Connect Wallet`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Arc, Safari
 - Version Arc 1.37.0, Safari 17.4.1

**Additional context**

**Comment by glitch-txs** [comment]
More context: https://walletconnect.slack.com/archives/C03RVH94K5K/p1712559383307539?thread_ts=1712235330.716649&cid=C03RVH94K5K

**Comment by tomheo11233aA** [comment]
Same issue with React Native. I don't know why but web3modal site currently also have this bug

**Comment by glitch-txs** [comment]
Linear ticket: https://linear.app/walletconnect/issue/W3M-238/[p0]-bug-in-web3modal-email-only-occurring-in-certain-environments
