### ISSUE TITLE
[bug] MetaMask logo Duplicated and is cropped

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#2134]
### Link to minimal reproducible example

[https://web3modal.com](https://web3modal.com)

Summary

On the connect wallet screen under default configuration the MetaMask logo is cropped. This is unlike the All Wallets view where there is proper padding.

![321001135-abf0a133-920c-4b48-86e7-a7f5955dc9fe](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/6e2c5ade-2445-461b-a74c-50203977d150/6e03c6e5-dbd5-4387-acd4-a7cb0ee156ff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS82ZTJjNWFkZS0yNDQ1LTQ2MWItYTc0Yy01MDIwMzk3N2QxNTAvNmUwM2M2ZTUtZGJkNS00Mzg3LWFjZDQtYTdjYjBlZTE1NmZmIiwiaWF0IjoxNzE0NzUzMjM1LCJleHAiOjMzMjg1MzEzMjM1fQ.p-Sb-\_5DCtNzmwg4WCQHXSh71geF6GHNxGvvok2ncdc)

![321001452-79e9a477-81ee-4cb0-b189-f513d3b2efa5](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/d49a9bdf-350b-489c-83de-e0dc86d684d0/95d74829-f505-4ed9-afec-52d1e2b0d281?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9kNDlhOWJkZi0zNTBiLTQ4OWMtODNkZS1lMGRjODZkNjg0ZDAvOTVkNzQ4MjktZjUwNS00ZWQ5LWFmZWMtNTJkMWUyYjBkMjgxIiwiaWF0IjoxNzE0NzUzMjM1LCJleHAiOjMzMjg1MzEzMjM1fQ.x6tNIXZsjx7MsEha8fKTgZDOvLhachuG0CrlicSXJaw)

**Comment by glitch-txs** [comment]
also with Ronin Wallet
![image](https://github.com/WalletConnect/web3modal/assets/66949816/8b519783-4d94-4c3e-8acf-1ce95263f6de)
