### ISSUE TITLE
https://pulse.walletconnect.org/e 403

### ISSUE THREAD

**Issue by hengshanMWC** [WalletConnect/web3modal#2135]
### Link to minimal reproducible example

null

### Summary
After passing the verification, what steps do I need to take?

<img width="1034" alt="image" src="https://github.com/WalletConnect/web3modal/assets/45714422/7813cbf2-17aa-4186-a416-74526c455208">

<img width="770" alt="image" src="https://github.com/WalletConnect/web3modal/assets/45714422/c68c5799-95ac-4c85-8b7a-6691f0714b13">

```
curl 'https://pulse.walletconnect.org/e' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'content-type: text/plain;charset=UTF-8' \
  -H 'origin: https://bogx-dev.bladeofgod.net' \
  -H 'referer: https://bogx-dev.bladeofgod.net/' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'x-project-id: f21c8d34e7a6dc74e4c7a690a3cd8ced' \
  -H 'x-sdk-type: w3m' \
  -H 'x-sdk-version: vue-wagmi-3.3.2' \
  --data-raw '{"eventId":"637c2085-ac6b-4f33-b31d-f65829310f6d","url":"https://bogx-dev.bladeofgod.net/","domain":"bogx-dev.bladeofgod.net","timestamp":1712743352805,"props":{"type":"track","event":"MODAL_LOADED"}}'
```

### List of related npm package versions

@wagmi/core@1.4.7
@web3modal/wagmi@3.3.2
viem@1.21.1

**Comment by hengshanMWC** [comment]
> [W3M-212 https://pulse.walletconnect.org/e 403](https://linear.app/walletconnect/issue/W3M-212/httpspulsewalletconnectorge-403)

？

**Comment by punk2513** [comment]
im geting this error too

**Comment by Yash-7504** [comment]
guys any fix for this error ?

**Comment by itxtoledo** [comment]
how to fix it?

**Comment by j4hangir** [comment]
Why's this closed?

**Comment by rtomas** [comment]
hi ! are you all using reown latest packages and verifying the domain into cloud ?

**Comment by j4hangir** [comment]
> hi ! are you all using reown latest packages and verifying the domain into cloud ?

Yes, it was verified before, but works now the problem seems to have been a browser issue here.

**Comment by AstonKhor** [comment]
Similar issue. Can't connect properly.

**Comment by maxsilvaweb** [comment]
> [W3M-212 https://pulse.walletconnect.org/e 403](https://linear.app/walletconnect/issue/W3M-212/httpspulsewalletconnectorge-403)

Hi, you're linking to a linear post that requires authentication from the linear owner to get access. I am getting the same issue. Ai  cant even fix this. Please could you give some clarity on the issue and is it being fixed?
