### ISSUE TITLE
[bug] overlapping transaction entries in activity tab

### ISSUE THREAD

**Issue by jiyuu-jin** [WalletConnect/web3modal#2138]
### Link to minimal reproducible example

https://web3modal.com

### Summary

<img width="345" alt="image" src="https://github.com/WalletConnect/web3modal/assets/19313806/45a76a78-d894-4a52-8e92-6c662a2bd795">

### List of related npm package versions

latest

**Comment by jiyuu-jin** [comment]
Can confirm styling is also messed up when a user only has a single piece of activity in a month; the list still expands to fill the container.

![image](https://github.com/WalletConnect/web3modal/assets/19313806/656118d2-410b-47fe-9948-a6c3b76dfbd8)

**Comment by chris13524** [comment]
Also seeing this on my account

https://github.com/WalletConnect/web3modal/assets/1979423/4d4c3aac-64c7-488d-bed3-eaa9427667ee
