### ISSUE TITLE
[bug] `modal.subscribeEvents` returns `CONNECT_SUCCESS` event after wallet rejects connection

### ISSUE THREAD

**Issue by hcote** [WalletConnect/web3modal#2143]
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/blazing-wave-8pymf7

### Summary

When the web3modal opens and a user clicks MetaMask, if a user rejects the MetaMask connection, `modal.subscribeEvents` returns a `CONNECT_SUCCESS` event, I believe it should be `CONNECT_ERROR`.

See the codesandbox to reproduce.

<img width="448" alt="Screenshot 2024-04-11 at 2 15 07 PM" src="https://github.com/WalletConnect/web3modal/assets/34493689/c96cd000-4184-4880-a400-9b7b425584e5">

### List of related npm package versions

ethers@5.7.2
@web3modal/ethers5@4.1.6

**Comment by glitch-txs** [comment]
Should be fixed latest
