### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by YudaAdiPratama** [WalletConnect/web3modal#2147]
### Summary

hello i have problem with web3modal at nextjs

this log error

```
 ./node_modules/@web3modal/siwe/dist/esm/scaffold/partials/w3m-connecting-siwe/index.js
Attempted import error: 'customElement' is not exported from '@web3modal/ui' (imported as 'customElement').

Import trace for requested module:
./node_modules/@web3modal/siwe/dist/esm/scaffold/partials/w3m-connecting-siwe/index.js
./node_modules/@web3modal/siwe/dist/esm/exports/index.js
./node_modules/@web3modal/scaffold/dist/esm/src/modal/w3m-modal/index.js
./node_modules/@web3modal/scaffold/dist/esm/index.js
./node_modules/@web3modal/wagmi/dist/esm/src/client.js
./node_modules/@web3modal/wagmi/dist/esm/exports/react/index.js
./src/context/Web3Modal.tsx

```
how do i solve it?

### Link to the related docs page

https://docs.walletconnect.com/web3modal/nextjs/about?platform=wagmi

**Comment by glitch-txs** [comment]
You're using an old version on Web3Modal somewhere

Try running:

```sh
npm ls @web3modal/ui
```

Check for the versions and which package is installing it.

**Comment by YudaAdiPratama** [comment]
> Referenc

i use this version
npm ls @web3modal/ui
midash-frontend@0.1.0 /Users/yuda/Github/midash-frontend/midash-frontend
├─┬ @web3modal/react@2.7.1
│ └── @web3modal/ui@2.7.1
└─┬ @web3modal/wagmi@4.1.7
  └─┬ @web3modal/scaffold@4.1.7
    └── @web3modal/ui@4.1.7

**Comment by glitch-txs** [comment]
Remove the react package, that's very old.
Please follow the docs here
https://docs.walletconnect.com/web3modal/about
