### ISSUE TITLE
A bug occurs when you click on the “connect wallet” button multiple times, even on the official website

### ISSUE THREAD

**Issue by DevTeaLeaf** [WalletConnect/web3modal#2150]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

When you press the button 2-3 times, the black bar does not disappear, but the modal does not appear either

### List of related npm package versions

Any, doesn't matter

**Comment by Sam-Newman** [comment]
I am unable to reproduce this but we will keep an eye out and resolve it.
