### ISSUE TITLE
[bug]  Magic Analytics disruptive

### ISSUE THREAD

**Issue by mergd** [WalletConnect/web3modal#2151]
## Requirement

* If the customer does not enable Email and/or Social login, then the Magic SDK and Magic analytics should not run

### Summary

The magic integration creates a lot of requests to Datadog, Vercel, and Segment for data analytics.

I have uBlock origin on, and it clutters up the console log with blocking errors as it keeps trying to post to the analytics endpoint. The easiest fix is to disable my adblocker on localhost, but Magic should also do better and cap the number of retries – especially if its something peripheral like analytics

![CleanShot 2024-04-13 at 23 45 49@2x](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/e886be8a-2b13-490b-8ab9-85e3ab342e77/81843912-3824-439e-9509-0c1a28d1bf9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9lODg2YmU4YS0yYjEzLTQ5MGItOGFiOS04NWUzYWIzNDJlNzcvODE4NDM5MTItMzgyNC00MzllLTk1MDktMGMxYTI4ZDFiZjllIiwiaWF0IjoxNzE2NTU3NjE1LCJleHAiOjMzMjg3MTE3NjE1fQ.GwWEDhkko7QB6setlmJq5YN_ogZCu0l1-0ryyBmU5Zo)

### List of related npm package versions

```
"@web3modal/siwe": "^4.1.6",
"@web3modal/wagmi": "^4.1.6",
```

**Comment by TipToe888** [comment]
Agreed this is extremely annoying although in production those errors go away

**Comment by cen1** [comment]
Same here but on top of that, `enableAnalytics: false` does not seem to disable it.

**Comment by ayv8er** [comment]
Magic here, those calls are very important to us.
But if you're blocking them anyways, capping after a number of retries make sense...
Let me bring this up with our team.

**Comment by ayv8er** [comment]
Hi all, we've disabled analytics on AppKit.
Tested on our end, but would love for you to confirm as well @mergd ?

**Comment by rtomas** [comment]
Please update to latest version to solve this issue
