### ISSUE TITLE
[feature] Disable Network Switch automatic modal

### ISSUE THREAD

**Issue by pepoospina** [WalletConnect/web3modal#2152]
### What problem does this new feature solve?

Right now the Switch Network modal is shown by default if the signer is not connected to the same network as the configured chain.

![image](https://github.com/WalletConnect/web3modal/assets/3278772/b7c7316b-e2a5-49a4-aa37-be1234f955f8)

However, we use the signer just for signatures, and not for broadcasting transactions, and so we don't really need to enforce the network switch. 

### Describe the solution you'd like

It would be nice to set something like

```ts
createWeb3Modal({
  wagmiConfig: config,
  projectId,
  enableAnalytics: false,
  forceNetworkSwitch: false // default to true
})
```

in the configuration.

Once set, web3Modal wont open the Switch Network modal automatically if the signer chain does not match the wagmi chain

**Comment by glitch-txs** [comment]
You can use the `allowUnsupportedChain` flag
