### ISSUE TITLE
[bug]: Vite big size, no treeshakable

### ISSUE THREAD

**Issue by reslear** [WalletConnect/web3modal#2159]
### Link to minimal reproducible example

[https://stackblitz.com/edit/vitejs-vite-zxnq49?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-zxnq49?file=src%2FApp.vue)

### Summary

A simple template, for playback

1. build the project and open the demo in a new tab
2. inspect the code - you will see a message about react devtools (which tells you to enable metamask sdk) and click on chunk.

![Screenshot 2024-04-16 at 08 01 32](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/5192cbf4-b4a4-4c78-8b16-43bf5c011198/11bbcfb8-9bd1-4b62-9020-d8698e05b5bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS81MTkyY2JmNC1iNGE0LTRjNzgtOGIxNi00M2JmNWMwMTExOTgvMTFiYmNmYjgtOWJkMS00YjYyLTkwMjAtZDg2OThlMDViNWJkIiwiaWF0IjoxNzEzMjU1NTA4LCJleHAiOjMzMjgzODE1NTA4fQ.gk3qyLc9V26vXkUKdvChn5liKYDLSKT6pfDWTAzKv64 "=573x")

we get chunk `chunk-22BZIRQV.js?v=998e5bee:39559` - 2,5mb :(

and more, so this is `@wagmi/connectors`:

![Screenshot 2024-04-16 at 08 05 52](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/2913c468-fd3b-4015-9957-411c4b3f23c1/c2462ca3-bdf6-4608-a4d2-ea1a8239ca5e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS8yOTEzYzQ2OC1mZDNiLTQwMTUtOTk1Ny00MTFjNGIzZjIzYzEvYzI0NjJjYTMtYmRmNi00NjA4LWE0ZDItZWExYTgyMzljYTVlIiwiaWF0IjoxNzEzMjU1NTA4LCJleHAiOjMzMjgzODE1NTA4fQ.AM2WgALDiD0cmfMjOp56Jo2LcaY7If9zer-C94ysEWY "=524x")

So i found solution use ESM:

fork [https://stackblitz.com/edit/vitejs-vite-bngsgj?file=vite.config.ts](https://stackblitz.com/edit/vitejs-vite-bngsgj?file=vite.config.ts)

```
  optimizeDeps: {
    exclude: ['@web3modal/wagmi'],
  },
```

but we got error:

```
Uncaught SyntaxError: The requested module '/node_modules/.pnpm/@walletconnect+time@1.0.2/node_modules/@walletconnect/time/dist/cjs/index.js?v=c28150ba' does not provide an export named 'fromMiliseconds' 
```

same [https://github.com/WalletConnect/walletconnect-utils/issues/134](https://github.com/WalletConnect/walletconnect-utils/issues/134)

so we need to prepare or customize vite so that it doesn't bandwidth huge files.

### List of related npm package versions

```
"@wagmi/connectors": "^4.1.26",
"@wagmi/core": "^2.6.17",
"@web3modal/wagmi": "^4.1.8",
"viem": "^2.9.19",
"vue": "^3.4.21"
```

**Comment by glitch-txs** [comment]
mmm, we do tree shaking.

We also don't use the MM SDK internally, so that shouldn't be bundled unless you're using the Wagmi's MetaMask connector.

Adding the package as external will break the app as you're not bundling it.

**Comment by reslear** [comment]
It is interesting that this happens only during development, as for the build it does not happen, maybe it is a vite problem.

**Comment by reslear** [comment]
i found similar issues:
- https://github.com/vitejs/vite/issues/6632

and work around https://github.com/vitejs/vite/issues/6582 :

```ts
// vite.config.mts
import externalize from 'vite-plugin-externalize-dependencies'
// ...
    externalize({
      externals: ['@wagmi/connectors'],
    }),
// ...
```

**Comment by glitch-txs** [comment]
I don't recommend that, you can however try

`externals: ['@walletconnect/modal', '@metamask/sdk']`

**Comment by glitch-txs** [comment]
tree shaking is not the same as dynamic import. We use package imports to tree shake unused hooks for other frameworks, but the rest we use pretty much everything.

Also, we use dynamic imports for the SIWE package, but this is still bundled, you will see it generates a chunk, but this won't be shipped to the browser because it's splitted.

You can also check for the JS size sent to the browser from the Network tab.

**Comment by reslear** [comment]
And better: 

```ts
import { defineConfig } from 'vite'
import externalize from 'vite-plugin-externalize-dependencies'

// https://vitejs.dev/config/
export default defineConfig({
    // https://github.com/WalletConnect/web3modal/issues/2159
    externalize({
      externals: [
        '@web3modal/siwe',
        '@walletconnect/modal',
        '@metamask/sdk',
        '@coinbase/wallet-sdk',
      ],
    }),
  ],
})
```

@glitch-txs This solves my problem, I can close it and add it to the FAQ.

**Comment by glitch-txs** [comment]
Coinbase one is used by Web3Modal, if you remove it the coinbase wallet won't work on mobile.
Of course it's up to you if you'd like to support it on mobile.

**Comment by reslear** [comment]
@glitch-txs 

Yes, but it's solution just ONLY for local development - [vite esbuild pre-bundling](https://vitejs.dev/guide/dep-pre-bundling).

for build vite use rollup, and it's needs modify:

```
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
```
