### ISSUE TITLE
[bug] can not integrate Web3modal into project using createClient from "urql"(node_modules)

### ISSUE THREAD

**Issue by Maltstar** [WalletConnect/web3modal#2171]
### Link to minimal reproducible example

https://github.com/Hack-Projects-n-Teams/eCoupon-ScalingEth24.git branch webshop
- just clone the repo
- switch to the webshop branch
- execute npm install
- then the error is located in /src/checkout/Root.tsx

### Summary

When adding the config file and the context file after installing web3modal into an exiting project, the createClient from "urql"(node_modules) does not work anymore

![image](https://github.com/WalletConnect/web3modal/assets/101098152/e51a11db-2567-4dd1-86c8-b083e4acbb61)

without the web3modal the app works fine, non complain from typescript

### List of related npm package versions

```json

                "@adyen/adyen-web": "5.53.2",
		"@adyen/api-library": "14.4.0",
		"@headlessui/react": "1.7.17",
		"@saleor/auth-sdk": "0.14.0",
		"@stripe/react-stripe-js": "2.3.1",
		"@stripe/stripe-js": "2.1.11",
		"@tanstack/react-query": "5.29.2",
		"@web3modal/wagmi": "4.1.10",
		"clsx": "2.0.0",
		"editorjs-html": "3.4.3",
		"formik": "2.4.5",
		"libphonenumber-js": "1.10.49",
		"lodash-es": "4.17.21",
		"lucide-react": "0.292.0",
		"next": "14.0.2",
		"query-string": "8.1.0",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-error-boundary": "4.0.11",
		"react-spinners": "0.13.8",
		"react-test-renderer": "18.2.0",
		"react-toastify": "9.1.3",
		"ts-invariant": "0.10.3",
		"url-join": "5.0.0",
		"urql": "4.0.5",
		"viem": "2.9.23",
		"wagmi": "2.5.20",
		"xss": "1.0.14",
		"yup": "1.3.2",
		"zustand": "4.4.6"

```

**Comment by glitch-txs** [comment]
Not a Web3Modal issue, can you try deleting the lock file and doing a clean install?
Might be an issue with the library you're using if your lock file was updated it might be using another version now.
