### ISSUE TITLE
[feature request] Customize all WalletConnect options while initialize `createModal`

### ISSUE THREAD

**Issue by yulafezmesi** [WalletConnect/web3modal#2172]
### What problem does this new feature solve?

as far as i can see, currently not possible to pass [optionalMethods](https://docs.walletconnect.com/advanced/providers/ethereum#:~:text=false-,optionalMethods,-The%20Ethereum%20methods) and all other optiona to initialize walletconnect eth. provider. can we make this possible?

https://github.com/WalletConnect/web3modal/blob/V4/packages/ethers5/src/client.ts#L383

### Describe the solution you'd like

create a new contractor object named like `ethereumProviderOptions`, and pass into walletconnect eth. provider.

`private ethereumProviderOptions: EthereumProviderOptions | undefined = undefined`

**Comment by glitch-txs** [comment]
Is there any particular method you'd like to add? We add all the Ethereum methods by default

**Comment by yulafezmesi** [comment]
we have special integration with [Avocado Wallet](https://avocado.instadapp.io/) and Avocado handling custom methods like `avocado_getOwner` or `avocado_sendTransaction`. this was possible with legacy Web3Modal, but currently is not possible. (we're migrating to v4)

**Comment by glitch-txs** [comment]
Ahh this is only supported when used with Wagmi atm

**Comment by yulafezmesi** [comment]
i see. can be possible for ethers5 as well? i'm willing to created PR if sounds good you.

**Comment by glitch-txs** [comment]
we will refactor the connectors logic, once that's done we can add it I think.

cc @svenvoskamp
