### ISSUE TITLE
Unsupported chains pops up after SIWE signing

### ISSUE THREAD

**Issue by LucyTrump0x** [WalletConnect/web3modal#2180]
### What problem does this new feature solve?

What I mean is that this situation arises after integrating SiweConfig.
The current issue is that the sign dialog pops up without checking if the chainId is supported. Moreover, there are no hooks or callbacks provided for customizing the sign, which leads to a situation where after signing, it checks for unsupported chains, prompts to switch chains, and then requires signing again. This is unreasonable and unfriendly.

### Describe the solution you'd like

Before executing the Siwe signature, it is necessary to check if the chainId is in the chains list. If it is not in the list, prompt to switch the chain first, or automatically switch to the default chain before executing the signature.

**Comment by glitch-txs** [comment]
Duplicated. Copied 👍

**Comment by TudorEsan** [comment]
is this solved? im having issues as well and if the chain is not supported i get this
<img width="661" alt="Screenshot 2024-09-11 at 15 06 04" src="https://github.com/user-attachments/assets/0bab8e83-bd47-496c-976e-70d20b6fd379">
