### ISSUE TITLE
[bug] Could not resolve "react" with yarn, vue web3modal

### ISSUE THREAD

**Issue by yooouuri** [WalletConnect/web3modal#2201]
### Link to minimal reproducible example

https://docs.walletconnect.com/2.0/web3modal/v3/vue/about

### Summary

Yarn doesn't install peer dependencies by default, pnpm for example does.

`@web3modal/core` has `valtio` as dependency, who has `use-sync-external-store` as dependency.

use-sync-external-store uses react, but as peerDependency.

![image](https://github.com/WalletConnect/web3modal/assets/12934957/b63889c5-1475-4619-9d1c-bfe65aef5df4)

So this is a problem for Vue users, they need to install react when using yarn...

### List of related npm package versions

```
"ethers": "^6.12.0",
"@web3modal/ethers": "^4.1.11",
```

**Comment by glitch-txs** [comment]
Can you try

```sh
yarn --save-dev react
```

Since this is a specific issue with yarn + other framework than React, we would like to avoid adding React as a core dependency.

Let me know if this works otherwise we might have to change Valtio for another library

**Comment by own2pwn** [comment]
@glitch-txs hey, can it be solved without depending on React, even as a dev dep?

**Comment by glitch-txs** [comment]
It doesn't depend on React, it's tree shaken as it's not used. The issue is with some bundlers that break when they are not installed locally.
