### ISSUE TITLE
`showQrModal: true` on walletConnect connector doesn't show the QR code

### ISSUE THREAD

**Issue by endophasie** [WalletConnect/web3modal#2202]
### Link to minimal reproducible example

[https://stackblitz.com/edit/web3modal-next-template-pd6ezo?file=components%2Fweb3modal-provider.tsx](https://stackblitz.com/edit/web3modal-next-template-pd6ezo?file=components%2Fweb3modal-provider.tsx)

### Summary

I want to make the wallet connect QR code appear first when `showQrModal: true`:

![image](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/24098c74-aa6e-47bf-a585-c3481d7358e9/60363880-a684-4097-b482-fb5c53056933?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS8yNDA5OGM3NC1hYTZlLTQ3YmYtYTU4NS1jMzQ4MWQ3MzU4ZTkvNjAzNjM4ODAtYTY4NC00MDk3LWI0ODItZmI1YzUzMDU2OTMzIiwiaWF0IjoxNzE0NzQ5Njg1LCJleHAiOjMzMjg1MzA5Njg1fQ.gXa1kvIVDZXlhC6r8Zq91NQtiU54o4Trq-3xVe-4fLg)

but instead modal renders same Connect Wallet:

![image](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/e7e0e43f-2b6a-4afd-aa63-7bc4cb46b465/2baafdc4-c7a4-43e8-8112-d94eb2162fff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9lN2UwZTQzZi0yYjZhLTRhZmQtYWE2My03YmM0Y2I0NmI0NjUvMmJhYWZkYzQtYzdhNC00M2U4LTgxMTItZDk0ZWIyMTYyZmZmIiwiaWF0IjoxNzE0NzQ5Njg1LCJleHAiOjMzMjg1MzA5Njg1fQ.sG2s5BFrzDc5TKUyRuOgzpJIX0dRaobhoInTl00pBEY)

### List of related npm package versions

```
"@web3modal/wagmi": "4.1.11",
"react": "18.2.0",
"react-dom": "18.2.0",
"viem": "2.9.31",
"wagmi": "2.8.0"
```

**Comment by glitch-txs** [comment]
This is not supported ATM.
showQrModal: true should be false because it will open another extra modal otherwise.

**Comment by glitch-txs** [comment]
why do you need this feature?

**Comment by MAYURESH0512** [comment]
![Image](https://github.com/user-attachments/assets/ecf25db2-bd39-40ec-b9c1-852003dfb966)
is there any snippet in this form of Auth
