### ISSUE TITLE
web3modal/wallet usses process client side [bug] 

### ISSUE THREAD

**Issue by pociej** [WalletConnect/web3modal#2209]
### Link to minimal reproducible example

no need 

### Summary

After update to version 4.1.11 

Uncaught ReferenceError: process is not defined
    at W3mFrameConstants.ts:2:3 

because of https://github.com/WalletConnect/web3modal/blob/V4/packages/wallet/src/W3mFrameConstants.ts#L2 

### List of related npm package versions

@web3modal/wallet : "4.1.11"

**Comment by hardingjam** [comment]
Bump 

Is there a version that doesn't have this problem? It's blocking me from using my local dev environment 😢

**Comment by hardingjam** [comment]
> ### Link to minimal reproducible example
> no need
> 
> ### Summary
> After update to version 4.1.11
> 
> Uncaught ReferenceError: process is not defined at W3mFrameConstants.ts:2:3
> 
> because of https://github.com/WalletConnect/web3modal/blob/V4/packages/wallet/src/W3mFrameConstants.ts#L2
> 
> ### List of related npm package versions
> @web3modal/wallet : "4.1.11"

I was able to solve this in svelte Kit by updating my vite.config.ts 

`export default defineConfig({
	plugins: [sveltekit()],
	// Define process.env here
	 define: {
    'process.env': {}
  }
});`
