### ISSUE TITLE
[bug] Cannot sign-in Email+SIWE

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#2212]
### Link to minimal reproducible example

https://lab.web3modal.com/library/wagmi-all/

### Summary

- Go to https://lab.web3modal.com/library/wagmi-all/
- Sign-in with email
- Attempt to sign SIWE message

[Video](https://walletconnect.slack.com/archives/C03RVH94K5K/p1714995843574429)

### List of related npm package versions

latest

**Comment by Another-DevX** [comment]
This issue is still happening :(
