### ISSUE TITLE
[bug] createSIWEConfig paramter "signOutOnNetworkChange" still signs out when set to "false"

### ISSUE THREAD

**Issue by tx-nikola** [WalletConnect/web3modal#2222]
### Link to minimal reproducible example

https://app.txsync.io/

### Summary

When setting up SIWE configuration, we're using the `createSIWEConfig` function from `@web3modal/siwe` package.
We're passing these options:
```
createSIWEConfig({
  getNonce,
  createMessage,
  verifyMessage,
  signOut,
  getSession,
  signOutOnNetworkChange: false,
});
```
where the last option, `signOutOnNetworkChange` which is set to `false`, doesn't work as expected. Whenever the user switches networks it asks to sign the message again, otherwise, it calls the `signOut` function and logs the user out.

I noticed that this file seems to be responsible for calling the `signOut` function:
`packages/scaffold/src/modal/w3m-modal/index.ts`

More specifically, this block:
```
if (isConnected && newCaipAddress && this.caipAddress !== newCaipAddress) {
  await SIWEController.signOut()
  this.onSiweNavigation()
  this.caipAddress = newCaipAddress
}
```
I didn't see the `signOutOnNetworkChange` parameter being used anywhere - I'm not sure if I missed something.

### List of related npm package versions

- `"@web3modal/siwe": "^4.1.9",` (and I tried it on the latest versions as well, still not fixed)
- `"@web3modal/wagmi": "^4.1.9",`
- `@web3modal/scaffold` - the issue is potentially in this package

**Comment by mshojaei-txfusion** [comment]
In cases DAPP includes a bridge (or any other multichain functionality) it is  annoying for users to sign the message everytime they change the network, maybe better to give the disable option for developers.

**Comment by x0good** [comment]
Can we reopen the ticket ?

with latest 1.5.3 version I notice that changing network lead to new SignIn modal window

@zoruka I see you refactored and did some fixes with createSiweConfig, maybe you know why with `signOutOnNetworkChange: false` changing networks still lead to new SignIn request ?
