### ISSUE TITLE
[feature] can you support vue nuxt3.js

### ISSUE THREAD

**Issue by phpmac** [WalletConnect/web3modal#2255]
### What problem does this new feature solve?

[feature] can you support vue nuxt3.js

### Describe the solution you'd like

[feature] can you support vue nuxt3.js

**Comment by glitch-txs** [comment]
we do already :)
https://docs.walletconnect.com/web3modal/vue/about

**Comment by phpmac** [comment]
I'm talking about nuxt3, which is currently poorly supported, if ssr is true

**Comment by phpmac** [comment]
Where can w3m-button be imported?

**Comment by phpmac** [comment]
But nuxt will prompt
```

[Vue warn]: Failed to resolve component: w3m-button                                                         18:58:21
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

**Comment by phpmac** [comment]
> you don't need to import it :)

up.

**Comment by glitch-txs** [comment]
seems like you need to declare it, from StackOverflow:

## Try this in your webpack.mix.js

```
mix.js('resources/assets/js/app.js', 'public/js').vue({
  options: {
    compilerOptions: {
      isCustomElement: (tag) => ['md-linedivider'].includes(tag),
    },
  },
});
```

## UPDATE 4.8.22 - for Vite projects: vite.config.js


```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => ['md-linedivider'].includes(tag),
        }
      }
    })
  ]
})
```

**Comment by Mimis** [comment]
setting ssr true metamask is not detected as installed in browser
