### ISSUE TITLE
[bug] SIWE Issued At is undefined

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#2258]
### Link to minimal reproducible example

https://lab.web3modal.com/library/wagmi-all/

### Summary

Login with email

![image](https://github.com/WalletConnect/web3modal/assets/1979423/11629de2-dc4d-42fe-bc50-106c4136f462)

### List of related npm package versions

latest

**Comment by wgcorrea** [comment]
I believe it's not a bug, and just the documentation is not covering all the getMessageParams possible arguments. Checking the source code, I can see that you can pass `iat`, which will work fine. E.g.:

```
	const getMessageParams = async () => ({
		domain: window.location.host,
		uri: window.location.origin,
		chains: [1],
		statement: 'Please sign with your account',
		iat: new Date().toISOString(),
	});
```

Tested with version 4.2.2

**Comment by chris13524** [comment]
> I believe it's not a bug

It is a bug. This field is required as per [`ERC-4361`](https://eips.ethereum.org/EIPS/eip-4361), so if it was a docs issue then not providing it should be a compile-time error. Second, even if it was optional, the field shouldn't be included at all instead of being an `"undefined"` string
