### ISSUE TITLE
[bug] infinite spinning on mobile browser

### ISSUE THREAD

**Issue by narekpetrosyan** [WalletConnect/web3modal#2260]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template-vtfcqm?file=config.ts

### Summary

I am getting an infinite spinning in mobile browser for each wallet for the ngrok but not on localhost.
My project id is not verified.

### List of related npm package versions

"@web3modal/wagmi": "^4.1.11",
"wagmi": "^2.8.6",
"viem": "^2.10.5",
"@tanstack/react-query": "^5.36.0",
"vite": "^5.1.6",
"react": "^18.2.0",

**Comment by narekpetrosyan** [comment]
![photo_2024-05-13_18-33-30](https://github.com/WalletConnect/web3modal/assets/51192656/1ac8d230-812c-4548-8a79-b70d4e3d7ce9)

**Comment by narekpetrosyan** [comment]
It should open the mobile application , which is installed

**Comment by glitch-txs** [comment]
Please make the minimal reproducible example as minimal as possible. You can also test the implementation on Labs https://lab.web3modal.com/
