### ISSUE TITLE
[bug] Android crash when user click on All Wallets to expand more wallets option

### ISSUE THREAD

**Issue by socheatleang** [WalletConnect/web3modal#2278]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template-mp5c98?file=components%2Fweb3modal-provider.tsx

### Summary

I am using react-native expo to develop dapp. 

With the android, it's always crash when user press on all wallets to expend more wallets option. This issue happened only android. 
![photo_2024-05-16_13-40-26](https://github.com/WalletConnect/web3modal/assets/98952747/fd710470-dbea-40ff-9ee3-12ee88e7b524)

### List of related npm package versions

```
    "viem": "1.21.4",
    "wagmi": "1.4.13",
    "web3": "^1.7.4"
    "@tanstack/react-query": "^5.35.1",
    "@walletconnect/client": "^1.7.8",
    "@walletconnect/react-native-compat": "^2.13.0",
    "@walletconnect/react-native-dapp": "^1.7.8",
    "@walletconnect/web3-provider": "^1.7.8",
    "@web3modal/wagmi-react-native": "^1.3.0",
   "react": "18.2.0",
    "react-native": "0.71.14",
```

**Comment by ignaciosantise** [comment]
Im closing this one, let's discuss it in the react native repo -> https://github.com/WalletConnect/web3modal-react-native/issues/160
