### ISSUE TITLE
[bug] Cannot change network to Polygon amoy (or any other) when using email wallet (authConnector)

### ISSUE THREAD

**Issue by gittygoo** [WalletConnect/web3modal#2284]
### Link to minimal reproducible example

https://walletconnect.com

### Summary

When logging in with an email wallet, if the dapp is not on a mainnet you cant change the network to a testnet, clicking the button doesn't really do anything if you want to change to a testnet (tried with sepolia and amoy)
![image](https://github.com/WalletConnect/web3modal/assets/2112957/314d0077-7d41-4758-9cae-4278f6f86cd3)
It work with all other wallets, just the email ones not

### List of related npm package versions

    "@web3modal/siwe": "^4.2.1",
    "@web3modal/wagmi": "^4.2.1",
    "siwe": "2.3.2",
    "wagmi": "2.6.0",

**Comment by glitch-txs** [comment]
Email only supports Magic supported chains as we are using it as a provider.
https://magic.link/docs/blockchains/overview

**Comment by volod-vana** [comment]
Magic docs has a mention of possibility of using custom nodes - https://magic.link/docs/blockchains/featured-chains/ethereum/javascript#custom-node. Can this be supported?
