### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by chrisZhangyifan** [WalletConnect/web3modal#2317]
### Link to minimal reproducible example

 I want to get wallet meta information, use the new hook useWalletInfo, and install new dependencies. It will appear that the module "@web3modal/wagmi/react" or its corresponding type declaration cannot be found.

### Summary

The useWalletInfo hook will show that the module cannot be found when it is introduced.

### List of related npm package versions

I want to get wallet meta information, use the new hook useWalletInfo, and install new dependencies. It will appear that the module "@web3modal/wagmi/react" or its corresponding type declaration cannot be found.

**Comment by chrisZhangyifan** [comment]
import { useWalletInfo } from '@web3modal/wagmi/react';

**Comment by glitch-txs** [comment]
Please provide a minimal reproducible example of the issue and steps to reproduce it
