### ISSUE TITLE
[bug] featuredWalletIds are not working

### ISSUE THREAD

**Issue by hmzakhalid** [WalletConnect/web3modal#2324]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template-pa5xgb?file=components%2Fweb3modal-provider.tsx

### Summary

The Featured Wallet IDs are not being picked up by the config and not displayed. It Only shows the Installed Wallet + Coinbase Wallet
```
createWeb3Modal({
	wagmiConfig: config,
	projectId: import.meta.env.VITE_WALLETCONNECT_PROJECT_ID,
	enableAnalytics: true,
	featuredWalletIds: [
		"c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96",
		"fd20dc426fb37566d803205b19bbc1d4096b248ac04548e3cfb6b3a38bd033aa",
		"4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0",
		"c03dfee351b6fcc421b4494ea33b9d4b92a984f87aa76d1663bb28705e95034a",
		"ef333840daf915aafdc4a004525502d6d49d77bd9c65e0642dbaefb3c2893bef",
		"0b415a746fb9ee99cce155c2ceca0c6f6061b1dbca2d722b3ba16381d0562150"
	],
	allWallets: "HIDE"
});
```

![image](https://github.com/WalletConnect/web3modal/assets/36852564/6c517b32-6424-424a-b987-9b2b16578ea9)

### List of related npm package versions

"@web3modal/wagmi": "^4.2.2",
"wagmi": "^2.9.6",
"viem": "^2.12.1",

**Comment by AlbertFiat24** [comment]
i confirm featuredWalletIds does not work for me neither
on the last web3modal v4.2.2
on v4.2.1 it works fine

**Comment by chenguzhen87** [comment]
is it solved?

**Comment by hmzakhalid** [comment]
> is it solved?

Nope

**Comment by chenguzhen87** [comment]
@hmzakhalid , when it is released?

**Comment by hmzakhalid** [comment]
> @hmzakhalid , when it is released?

I guess in the next release, Ive made the PR. It's under review right now.

**Comment by lyfmantle** [comment]
patch version brings breaking changes 😑

**Comment by hmzakhalid** [comment]
@lyfmantle patch versions are a release as well 🙂

**Comment by lyfmantle** [comment]
well, I guess the classic world is dead https://semver.org/

> @lyfmantle patch versions are a release as well 🙂

**Comment by lyfmantle** [comment]
yes, you're right. 
we can do nothing about the release.
you can release an empty `index.js` file to the npm as well.
because of that, you're right.

> MAJOR.MINOR.PATCH **release** I'm not saying you're wrong. I'm just saying I'm right as well. Doesn't matter what you call it. It's a release.
> 
> > well, I guess the classic world is dead https://semver.org/
> > > @lyfmantle patch versions are a release as well 🙂

**Comment by svenvoskamp** [comment]
We merged the PR and we will release a new version ASAP
