### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by chrispaul607** [WalletConnect/web3modal#2328]
### Link to minimal reproducible example

web3modal  example is not working 

### Summary

First i can use it ,when i close this project and then start the npm run laborary   can not work ,many bug ,i can not   use the command npm install,and npm install turbo,npm run watch use it  can not work again

### List of related npm package versions

i useweb3modal  4.0

**Comment by glitch-txs** [comment]
Hi the instructions to run the project is in the README.md file
