### ISSUE TITLE
[bug] web3modal has so many bug or i m confused

### ISSUE THREAD

**Issue by chrispaul607** [WalletConnect/web3modal#2330]
### Link to minimal reproducible example

step by step to study the web3modal

### Summary

what npm  version i can use? my npm is 10.2.4  \  node 23.0.11,see the screenshot

### List of related npm package versions

![photo_2024-05-26_09-58-16](https://github.com/WalletConnect/web3modal/assets/116169040/83b9968a-5c06-4fa4-ac6c-2035f433a5b4)
![photo_2024-05-26_09-58-33](https://github.com/WalletConnect/web3modal/assets/116169040/4e1eecd0-20f6-4e9e-8661-12781aa3f380)
![photo_2024-05-26_09-58-37](https://github.com/WalletConnect/web3modal/assets/116169040/d2579c63-4aac-4f77-8d13-91f55f521a09)

**Comment by hmzakhalid** [comment]
Hey @chrispaul607, the steps to run the project are mentioned in the README. Also, I see that you're in the `/apps` directory. You need to run these commands from the root directory, and they should work fine.

You can get the project ID from https://cloud.walletconnect.com/

Here's the steps to run the project step by step in detail.

# Dev Setup

1. **Create the `.env.local` File for Laboratory**
   - Navigate to the `apps/laboratory` directory.
   - Create a new file named `.env.local` using the template provided in the `apps/laboratory/.env.example` file. 
     - You can do this by copying the contents of `.env.example` and pasting them into the new `.env.local` file.
     - Save the `.env.local` file in the `apps/laboratory` directory.

2. **Create the `.env.local` File for Each Example**
   - Navigate to each of the `examples` directories within the project.
   - In each `examples` directory, create a new file named `.env.local`.
   - Add the following content to each `.env.local` file:
     ```zsh
     VITE_PROJECT_ID="your_project_id"
     ```
     - Replace `"your_project_id"` with the actual project ID you are using.
   - Save each `.env.local` file within its respective `examples` directory.

3. **Run the Build and Watch Command**
   - Open a terminal window and navigate to the root directory of the project.
   - Run the following command to build the project and watch for file changes:
     ```zsh
     npm run watch
     ```
   - Keep this terminal window open as it will continuously monitor changes in your files and rebuild as necessary.

4. **Run the Laboratory, Gallery, or Examples**
   - Open another terminal window and navigate to the root directory of the project.
   - To run the laboratory, gallery, or any example, use the following command:
     ```zsh
     npm run laboratory
     ```
     - Replace `laboratory` with `gallery` or the specific example you want to run, if applicable.
   - Keep this terminal window open as it will run the selected part of your project.
