### ISSUE TITLE
[bug] @web3modal/siwe did not specify the version of @web3modal/common and version conflict issue happen

### ISSUE THREAD

**Issue by EasonSoong** [WalletConnect/web3modal#2331]
### Link to minimal reproducible example

nope

### Summary

@web3modal/siwe did not specify the version of @web3modal/common
my app have two @web3modal/common version, one is v3.x and the other one is v4.x
the latest @web3modal/siwe depend on v4.x but it's using v3.x in my app now, because the version is missing here

### List of related npm package versions

@web3modal/siwe@4.2.2
@web3modal/ethers5@4.2.2

**Comment by glitch-txs** [comment]
Versions are fine in our end, try deleting the lock file and installing everything again, if this doesn't resolve the issue please provide access to the source code and we can take a look.
