### ISSUE TITLE
How to switch selected chain of Metamask in modal v4? I mean switching the current chain of metamask app by call web3 modal function. I seems can't do it just by call "switchChain"

### ISSUE THREAD

**Issue by Mikegoossens1980** [WalletConnect/web3modal#2333]
How to switch selected chain of Metamask in modal v4? I mean switching the current chain of metamask app by call web3 modal function. I seems can't do it just by call "switchChain"

_Originally posted by @defchen in https://github.com/WalletConnect/walletconnect-monorepo/discussions/4561_

**Comment by glitch-txs** [comment]
Hi MetaMask is working on a fix for this, should be ready for the next release.
