### ISSUE TITLE
[optimization] Lazy load wallet images in all wallets page

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#2350]
### Link to minimal reproducible example

lab.web3modal.com

### Summary

Web3Modal currently pre-loads ALL connector and network images. I'm wondering if these could be made to be lazy-loaded? Many users won't open the modal, and all these images are being loaded immediately upon page load via getAssetImage

[Slack conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1716500590323799)

### List of related npm package versions

latest

**Comment by fawaikuangtutu** [comment]
Very good advice
