### ISSUE TITLE
[bug] webscoket is error problem,how can i set

### ISSUE THREAD

**Issue by chrispaul607** [WalletConnect/web3modal#2351]
### Link to minimal reproducible example

webscoket is error problem,how can i set

### Summary

webscoket is error problem,how can i set,if i click the wallet logo,can not show up the dapp [tips.so](http://tips.so) how can i do this and test it

### List of related npm package versions

![photo_2024-06-03_10-49-18](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/70b12c91-f7ee-4c84-8a91-9ad3c4958893/ad1eb4c2-b45f-42eb-a7c5-58f8af0c76fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS83MGIxMmM5MS1mN2VlLTRjODQtOGE5MS05YWQzYzQ5NTg4OTMvYWQxZWI0YzItYjQ1Zi00MmViLWE3YzUtNThmOGFmMGM3NmZlIiwiaWF0IjoxNzE3NTkzODQxLCJleHAiOjMzMjg4MTUzODQxfQ.u_BjJztY2hnj7drReG4MIQ3_2cvcBl7loYUqae5qxew)

![photo_2024-06-03_10-52-58](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/9eaa40ea-2b75-4da4-a976-48f2c386414f/a43b85f4-a461-4ead-8012-c2dfec08a5ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS85ZWFhNDBlYS0yYjc1LTRkYTQtYTk3Ni00OGYyYzM4NjQxNGYvYTQzYjg1ZjQtYTQ2MS00ZWFkLTgwMTItYzJkZmVjMDhhNWFjIiwiaWF0IjoxNzE3NTkzODQxLCJleHAiOjMzMjg4MTUzODQxfQ.wBljUQfdf3C-wYgb2gj4KWGYFuB1CFMlFlXsZFb0Wo0)

**Comment by glitch-txs** [comment]
Make sure your allowlist is set correctly, you can check here the different possible configurations: https://docs.walletconnect.com/cloud/relay#allowlist
