### ISSUE TITLE
[bug] vue3 use useWalletInfo() function run is undefined

### ISSUE THREAD

**Issue by far310** [WalletConnect/web3modal#2354]
### Link to minimal reproducible example

import { useWalletInfo } from '@web3modal/wagmi/vue' vue3 use useWalletInfo() function run is undefined

### Summary

import { useWalletInfo } from '@web3modal/wagmi/vue'

function getUseWalletInfo() {
  walletInfo.value = useWalletInfo();
  console.log("===========================");
  console.log([walletInfo.name](http://walletInfo.name), walletInfo.icon);
}

![image](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/1492030c-7374-4caa-b156-9e62c714b200/b8f489d9-4f00-48ab-9ad7-464da5280673?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS8xNDkyMDMwYy03Mzc0LTRjYWEtYjE1Ni05ZTYyYzcxNGIyMDAvYjhmNDg5ZDktNGYwMC00OGFiLTlhZDctNDY0ZGE1MjgwNjczIiwiaWF0IjoxNzE3NTkzODUwLCJleHAiOjMzMjg4MTUzODUwfQ.rP9DlWR7rjo4deJ_LhBxrv5wJ02Rf0mqgI8ZHQof58U "=1454x")

### List of related npm package versions

```
"@mdi/font": "7.0.96",
"@tanstack/vue-query": "^5.40.0",
"@wagmi/vue": "^0.0.11",
"@web3modal/wagmi": "^4.2.3",
"copy-to-clipboard": "^3.3.3",
"core-js": "^3.34.0",
"decimal.js": "^10.4.3",
"roboto-fontface": "*",
"viem": "^2.13.1",
"vue": "^3.4.0",
"vue-blockies": "^1.0.0",
"vuetify": "^3.5.0"
```

**Comment by glitch-txs** [comment]
Please provide a minimal reproducible example and steps to repro

**Comment by far310** [comment]
> Please provide a minimal reproducible example and steps to repro

It is used normally in vue3
