### ISSUE TITLE
[bug] dev copy address success, product copy failed

### ISSUE THREAD

**Issue by li460930736** [WalletConnect/web3modal#2370]
### Link to minimal reproducible example

modal copy address failed when i deploy to server

### Summary

![image](https://github.com/WalletConnect/web3modal/assets/56672001/1a91ce46-8209-4771-8010-168a98e43a62)

### List of related npm package versions

"@wagmi/core": "^1.4.12",
"@web3modal/wagmi": "^3.5.2",
"use-wagmi": "^0.4.9",
"viem": "^1.21.0",

**Comment by glitch-txs** [comment]
Could you please update the dependencies to Wagmi v2 and Web3Modal v4 latest. This should be fixed already, you can test it [here](https://lab.web3modal.com/)
