### ISSUE TITLE
Why can't I delete the 'Coinbase' wallet option in the main interface?[bug] 

### ISSUE THREAD

**Issue by wangzhenyuWZY** [WalletConnect/web3modal#2376]
### Link to minimal reproducible example

createWeb3Modal({     defaultChain: bsc,     allowUnsupportedChain: false,     allWallets: 'HIDE',     wagmiConfig: config,     projectId,     enableAnalytics: true, // Optional - defaults to your Cloud configuration     enableOnramp: true, // Optional - false as default     themeVariables: {       '--w3m-accent': '#E9BF15',       '--w3m-color-mix': '#000',     },     featuredWalletIds: [],     includeWalletIds: [       '20459438007b75f4f4acb98bf29aa3b800550309646d375da5fd4aac6c2a2c66',     ]   });

### Summary

Why can't I delete the 'Coinbase' wallet option in the main interface?
![image](https://github.com/WalletConnect/web3modal/assets/26293595/16637052-545c-4208-a43a-7d6e62873554)

### List of related npm package versions

web3modal v4
wagmi 2.7.1

**Comment by Ivan-dev-RED** [comment]
Same issue

**Comment by glitch-txs** [comment]
you can use `enableCoinbase: false`

**Comment by Ivan-dev-RED** [comment]
@glitch-txs It's not working

![image](https://github.com/WalletConnect/web3modal/assets/104828301/b447a35b-db07-415e-85ec-2bf3e918eeaf)
![image](https://github.com/WalletConnect/web3modal/assets/104828301/4c44a9ba-2302-489e-a462-e9035e8861d8)

Coinbase is still on the main screen

**Comment by glitch-txs** [comment]
this should be added in the `defaultWagmiConfig` function
