### ISSUE TITLE
[bug] signOutOnNetworkChange: false causes hang on network switch in injected MetaMask

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3modal#2378]
### Link to minimal reproducible example

http://localhost:3000/library/wagmi-all/

### Summary

Using the `signOutOnNetworkChange: false` option and injected MetaMask, if you switch chains and approve in MetaMask the modal will hang on "Approve in wallet" after approving the network switch in MetaMask.

Can reproduce in lab by changing this setting. [Video reproduction](https://walletconnect.slack.com/archives/C03RVH94K5K/p1717787630388469)

### List of related npm package versions

latest

**Comment by rtomas** [comment]
This issue seems to be solve in the latest packages.
