### ISSUE TITLE
[bug] featuredWalletIds option is broken, starting from v4.2.2

### ISSUE THREAD

**Issue by Karkunow** [WalletConnect/web3modal#2383]
### Link to minimal reproducible example

let options = {     defaultChain: aurora,     featuredWalletIds: [         '76260019aec5a3c44dd2421bf78e80f71a6c090d932c413a287193ed79450694', //AuroraPass     ]};

### Summary

Try to use the options as above, you will not see Aurora Pass wallet added to the main wallets page.
<img width="459" alt="Screenshot 2024-06-10 at 12 55 51" src="https://github.com/WalletConnect/web3modal/assets/2808283/1db47b0f-1a3d-408f-a590-311af5decc6b">

In 4.2.1 and lower versions - it is working and is diplayed as expected.
<img width="410" alt="Screenshot 2024-06-10 at 12 55 04" src="https://github.com/WalletConnect/web3modal/assets/2808283/484f6607-a82b-4272-9661-552f5f0b8cb7">

### List of related npm package versions

4.2.2, 4.2.3

**Comment by christophercr** [comment]
Same issue here.

**Comment by rtomas** [comment]
Related issue with customization:
+ https://github.com/WalletConnect/web3modal/discussions/2657

**Comment by rtomas** [comment]
trying to feature -> Coinbase 
```
featuredWalletIds: [
  'fd20dc426fb37566d803205b19bbc1d4096b248ac04548e3cfb6b3a38bd033aa'
]}
```

![image](https://github.com/user-attachments/assets/3ed937f5-db40-4d28-a2d3-70a20ea4d60b)

**Comment by rtomas** [comment]
please update to the latest version so solve featuredWalletIds & excludeWalletIds issues.

**Comment by halilgungor511** [comment]
**_[](https://bitgetwallet.onelink.me/6Vx1/svurlmli)_**
