### ISSUE TITLE
[bug]  Coinbase on Ethers

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#2425]
### Link to minimal reproducible example

N/A

### Summary

RPC and default chain are no longer required for the Coinbase SDK

https://github.com/WalletConnect/web3modal/blob/0db5605f256bbcf554621bcbe102d9d5fc086432/packages/ethers/src/utils/defaultConfig.ts#L98

### List of related npm package versions

source code

**Comment by PhantomOz** [comment]
Hello, I would love to fix this issue

**Comment by glitch-txs** [comment]
you can go ahead @PhantomOz
