### ISSUE TITLE
[bug]  {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/publisher'} Error: Failed to publish payload, please try again.

### ISSUE THREAD

**Issue by Rubanrubi** [WalletConnect/web3modal#2426]
### Link to minimal reproducible example

{context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/publisher'} Error: Failed to publish payload, please try again.   and  TransactionExecutionError     at getTransactionError (getTransactionError.js:11:12)     at sendTransaction.js:123:34

### Summary

I'm using an Angular 16 application. Everything works fine when triggering transactions on a desktop, but I encountered an issue when I opened my dApp URL in the mobile Chrome browser and connected with my mobile MetaMask wallet app. The problem arises while triggering a write transaction on mobile.

To debug this, I enabled the developer settings and USB debugging feature on my mobile device, connected it to my laptop via a USB data cable, and inspected the mobile Chrome browser logs.

### List of related npm package versions

    "@wagmi/core": "^1.4.13",
    "@web3modal/wagmi": "^3.5.7",
    "viem": "^1.21.4",

**Comment by glitch-txs** [comment]
please update to the latest version of the SDK and Wagmi/Viem v2 🙏
