### ISSUE TITLE
[BUG] Don't add too much extra content to HTML tags

### ISSUE THREAD

**Issue by Pszz** [WalletConnect/web3modal#2441]
**Describe the bug**
[https://github.com/rainbow-me/rainbowkit/issues/2056](https://github.com/rainbow-me/rainbowkit/issues/2056)

**Comment by glitch-txs** [comment]
This is from WalletConnectModal and not AppKit (Web3Modal). We don't maintain WalletConnectModal any more. We'll release a new update eventually.

You can ask rainbow to use `showQrModal: false` in their WalletConnect configuration to remove this.
