### ISSUE TITLE
[bug] Connect Phantom but get Not Detected

### ISSUE THREAD

**Issue by cong1223** [WalletConnect/web3modal#2469]
### Link to minimal reproducible example

https://lab.web3modal.com/library/solana/

### Summary

https://lab.web3modal.com/library/solana/

When I click on the "Connect Wallet" button in the document, the popup displays "Not Detected", but I have already installed the Phantom wallet and I am logged in normally.

<img width="863" alt="image" src="https://github.com/WalletConnect/web3modal/assets/37927942/9e848306-d06a-4e99-9a1e-e68904b6f42d">

### List of related npm package versions

latest

**Comment by cong1223** [comment]
<img width="1705" alt="image" src="https://github.com/WalletConnect/web3modal/assets/37927942/69873340-6df8-44c0-9016-815435571cc8">
Actually, I have already installed Phantom, and I am able to connect my wallet normally on other dApps.

**Comment by DApps-Github** [comment]
> ### Link to minimal reproducible example
> https://lab.web3modal.com/library/solana/
> 
> ### Summary
> https://lab.web3modal.com/library/solana/
> 
> When I click on the "Connect Wallet" button in the document, the popup displays "Not Detected", but I have already installed the Phantom wallet and I am logged in normally.
> 
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/37927942/343713266-9e848306-d06a-4e99-9a1e-e68904b6f42d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODIzNjIsIm5iZiI6MTcxOTU4MjA2MiwicGF0aCI6Ii8zNzkyNzk0Mi8zNDM3MTMyNjYtOWU4NDgzMDYtZDA2YS00ZTk5LTlhMWUtZTY4OTA0YjZmNDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEzNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZGMzYTYwY2RjYmQyOGEzNmIxOWQ1NWMyMTkxM2Y0N2U3ZmFlMTgyZjQ0YTM4NjUzMDk2NWEzYTkyMDA4M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUMiyiK1Og9thGRpiqMUXOg8DaiuQnBoua-hnYRClj4">
> ### List of related npm package versions
> latest

 Hey there @cong1223   ,

kindly refresh your wallet, if the issue persists, It means the backend systems went down as a result of transcript error. 
Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID PHT7463
 
Please see the link below to our dedicated support line: 
 [Phantom wallet Dapps Support Requests Ticket](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by JeffWScott** [comment]
I'm getting this same issue. I have Phantom installed in the browser but Wallet Connect is not detecting it.
