### ISSUE TITLE
[feature] Fordefi MPC wallet support

### ISSUE THREAD

**Issue by heyitsarpit** [WalletConnect/web3modal#2479]
### What problem does this new feature solve?

[Fordefi wallet](https://docs.fordefi.com/reference/api-overview) is not supported by web3modal currently.

### Describe the solution you'd like

Have it be searchable as a wallet to connect to in the web3modal wallet search interface.

**Comment by glitch-txs** [comment]
The search interface is for wallets supporting the WalletConnect protocol. You can build a custom Wagmi connector to integrate with the modal.
