### ISSUE TITLE
How to customize the rpc logo

### ISSUE THREAD

**Issue by phpmac** [WalletConnect/web3modal#2485]
### Link to minimal reproducible example

https://ton.x.com/i/ton/data/dm/1807702276792005095/1807702267870785536/QSTSztHF.jpg:medium

### Summary

![image](https://github.com/WalletConnect/web3modal/assets/86544347/24f3b8f9-4929-41b1-8b6c-99caabca5fb9)

How to customize the rpc logo

### List of related npm package versions

![image](https://github.com/WalletConnect/web3modal/assets/86544347/24f3b8f9-4929-41b1-8b6c-99caabca5fb9)

How to customize the rpc logo

**Comment by cryptomarabout** [comment]
In version 5.0.2 I managed to customize the RPC logo using [the "chainImages" option](https://docs.walletconnect.com/appkit/react/core/options#chainimages), however this RPC logo is not added to Metamask when we add the network via the modal. 
Is there a way to customize the logo for a config network to be added to Metamask?
