### ISSUE TITLE
google social login not working

### ISSUE THREAD

**Issue by javaspeak** [WalletConnect/web3modal#2502]
### Link to minimal reproducible example

https://github.com/spotadev/wallet-connect-email-socials-login/blob/main/README.md

### Summary

While email login works, Google Login did not and looked like this:

<img width="1063" alt="Screenshot 2024-07-03 at 10 56 12" src="https://github.com/WalletConnect/web3modal/assets/26520180/b20e24cc-b60e-4bb3-9c0f-bb641d1e7c71">

### List of related npm package versions

"@web3modal/wagmi": "^5.0.5",
"wagmi": "^2.10.9"

**Comment by javaspeak** [comment]
Main code:

https://github.com/spotadev/wallet-connect-email-socials-login/blob/main/src/main.tsx

https://github.com/spotadev/wallet-connect-email-socials-login/blob/main/src/App.tsx

**Comment by prayagsingh** [comment]
I checked with @web3modal/wagmi": "5.0.6" and issue still persist. It stuck after opening the popup.
Browser: Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)


![Screenshot 2024-07-04 at 7 19 41 PM](https://github.com/WalletConnect/web3modal/assets/8455114/da7d5dcf-84a9-438e-9c97-73fdf5140329)

**Comment by prayagsingh** [comment]
@svenvoskamp Still same even with 5.0.6. Is there any specific version of wagmi I should be using with 5.0.6?
current version: 
"viem": "^2.17.0",
 "wagmi": "^2.10.9",

**Comment by javaspeak** [comment]
@svenvoskamp thanks a million.  Works for me with 5.0.6 :-)

@prayagsingh this small example works for me with Google social login:

https://github.com/spotadev/wallet-connect-email-socials-login

**Comment by prayagsingh** [comment]
Thanks @javaspeak for sharing the example. Its working fine on the localhost. But when I deployed it to vercel then it is not working. Also, Can you check it in the Incognito tab as well? Somehow, it is not working for me in the incognito as well.
for reference: you can check https://app.soclly.com. It is using v5.0.6. 

cc: @svenvoskamp

**Comment by svenvoskamp** [comment]
@Prateekrajput1999 @prayagsingh Did you verify your domain in https://cloud.walletconnect.com/?

**Comment by prayagsingh** [comment]
@svenvoskamp Thanks for the help, it was verified domain issue on my side.
