### ISSUE TITLE
[bug] When using the @web3modal/solana package in an Angular 17 project, an error occurs. [SyntaxError: Unexpected token ':']

### ISSUE THREAD

**Issue by Jacky-Young1123** [WalletConnect/web3modal#2561]
### Link to minimal reproducible example

https://stackblitz.com/edit/stackblitz-starters-xspw8z?file=package.json

### Summary

 When using the @web3modal/solana package in an Angular 17 project, an error occurs. [SyntaxError: Unexpected token ':']
![img_v3_02cu_56cb8f28-2224-4944-9572-e55a28279b5h](https://github.com/user-attachments/assets/6c454a93-afd7-4256-a8e1-50d8564600dc)

### List of related npm package versions

![image](https://github.com/user-attachments/assets/49a09ed3-7b91-4923-a417-71102b1431db)

**Comment by glitch-txs** [comment]
Duplicated of https://github.com/WalletConnect/web3modal/issues/2616
