### ISSUE TITLE
examples/vue-solana installing error

### ISSUE THREAD

**Issue by chenguzhen87** [WalletConnect/web3modal#2569]
### Link to minimal reproducible example

no

### Summary

s://xrpl.org/xrpljs2-migration-guide.html
npm ERR! code ENOENT
npm ERR! syscall spawn sh
npm ERR! path C:\chenzhen\github\web3modal\node_modules\bigint-buffer
npm ERR! errno -4058
npm ERR! enoent spawn sh ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

### List of related npm package versions

exmaple

**Comment by glitch-txs** [comment]
Please share a minimal reproducible example.
