### ISSUE TITLE
[bug] Cannot disconnect when using Trust Wallet Extension w/ethers v5 or v6

### ISSUE THREAD

**Issue by rtomas** [WalletConnect/web3modal#2594]
### Link to minimal reproducible example

https://lab.web3modal.com/library/ethers/

### Summary

Using Trust Wallet Extension with ethers v5 or v6 failed to disconnect.

1. Connect 
2. Try to disconnect.

![image](https://github.com/user-attachments/assets/d0d4eb04-6e3d-42c8-906d-2109f35a05cd)

### List of related npm package versions

"@web3modal/ethers": "^5.0.6",

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-795/[bug]-cannot-disconnect-when-using-trust-wallet-extension-wethers-v5

**Comment by rtomas** [comment]
**Rabby Wallet** also report that is not working in "@web3modal/ethers": "5.0.8" but is working ok if you downgrade to v5.0.6

**Comment by 0xSzeth** [comment]
I'm experiencing the same issue. @reown/appkit 1.14.1 @reown/appkit-adapter-wagmi 1.4.1 @wagmi/core 2.14.6 viem 2.21.47
