### ISSUE TITLE
Social account demo login error

### ISSUE THREAD

**Issue by DannyFi** [WalletConnect/web3modal#2596]
### Link to minimal reproducible example

https://lab.web3modal.com/library/ethers-email/

### Summary

When visit https://lab.web3modal.com/library/ethers-email/ ,
Click the 'Connect Wallet' button,
Choose X social account to login,
But show this error
![image](https://github.com/user-attachments/assets/9f217407-f9b8-4044-9853-62acb6d63a6d)

### List of related npm package versions

web3modal 5.0.7

**Comment by rtomas** [comment]
I'm testing it and it's working ok.
