### ISSUE TITLE
[bug] in all wallets search bar, searched out nothing for any wallet names

### ISSUE THREAD

**Issue by lyfmantle** [WalletConnect/web3modal#2598]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template

### Summary

click "all wallets", in the all wallets panel top search bar, search anything, always return an empty array.

### List of related npm package versions

"@web3modal/wagmi": "^5.0.8"

**Comment by rtomas** [comment]
In the minimal example, you are using an old version : "@web3modal/wagmi": "4.0.10".
Please check our docs to implement the solution: https://docs.walletconnect.com/appkit/react/onboarding/socials
