### ISSUE TITLE
[bug] w3m-wallet button doesn't change on disconnect

### ISSUE THREAD

**Issue by ayabelarbi** [WalletConnect/web3modal#2601]
### Link to minimal reproducible example

<template>   <header>     <div>       <w3m-button /><div></header> </template>

### Summary

In Vue3.js, the button is not changing the state when the user toogle the disconnect button in the modal of the w3m-button. The user have to refresh the page 

### List of related npm package versions

  "@wagmi/connectors": "^5.1.1",
    "@wagmi/core": "^2.13.1",
    "@web3modal/wagmi": "^5.0.8",
    "axios": "^1.7.2",
    "ethers": "^6.13.2",
    "viem": "^2.18.2",
    "vue": "^3.4.29"

**Comment by rtomas** [comment]
It's working ok in this example
https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal/vue

Please, if you continue with this error, send us an example using the latest packages.
