### ISSUE TITLE
[bug] Multiple errors when working with Angular 18 and @web3modal/wagmi

### ISSUE THREAD

**Issue by vanyasav** [WalletConnect/web3modal#2618]
### Link to minimal reproducible example

https://github.com/vanyasav/web3modal-wagmi-angular-example

### Summary

- Error when connect to metamask wallet:
```
TypeError: rest.transports[chainId2] is not a function
    at Object.transport (createConfig.js:103:57)
    at createClient (createClient.js:19:18)
    at Object.getClient2 [as getClient] (createConfig.js:97:16)
    at getBalance.js:46:25
    at Generator.next (<anonymous>)
    at chunk-WME3VOFU.js?v=0e1f1629:93:61
    at new ZoneAwarePromise (zone.js:2702:25)
    at __async (chunk-WME3VOFU.js?v=0e1f1629:77:10)
    at getBalance2 (getBalance.js:7:54)
    at _Web3Modal.<anonymous> (client.js:447:29)
```

- Can not disconnect wallet using the modal
- Wallet is disconnected after page reload

[Screencast from 30-07-2024 14:24:08.webm](https://github.com/user-attachments/assets/7a785ac8-7a62-41db-9f2f-19a73be1305e)

### List of related npm package versions

```
"@wagmi/core": "2.13.1",
"@web3modal/wagmi": "5.0.9"
```

**Comment by rtomas** [comment]
please update to latest version.
"@web3modal/wagmi": "5.0.11"

**Comment by vanyasav** [comment]
I've tried the latest versions but I still have to connect to metamask every time I refresh the page. I can not disconnect as well.
The other error is fixed.

**Comment by mentasuave01** [comment]
@vanyasav  
I have the same error today, looks like you add a custom chain but forgot to add transports on getDefaultConfig
