### ISSUE TITLE
Does it support BSC? 

### ISSUE THREAD

**Issue by dlpigpen** [WalletConnect/web3modal#263]
and if Yes, is there any example to do?

**Comment by nithronium** [comment]
It supports custom networks so I assume it supports BSC too.

Define your provider options like this;

```
    const providerOptions = {
        walletconnect: {
            package: WalletConnectProvider,
            options: {
            rpc: {
                NETWORKID: "https://YOURPROVIDER"
            },
            network: "bsc"
            }
        }
    };
```

Then use;

```    
try {
        provider = await web3Modal.connect();
    } catch(e) {
        onConnectError();
    }
```

Also if you want to make sure user is on same network, while interacting, use;

```    
const chainId = await web3.eth.getChainId();
    if(chainId != YOURCHAINID) {
        alert("Wrong network! Switch to BSC");
        return;
    }```

Also add 
```            CHAINID: {
                chainId: CHAINID,
                chain: "BSC",
                network: "BSC",
                networkId: NETWORKID
            }
```

to the library. It should be around on line 11K, simply CTRL+F and search for callisto-testnet, add yours below that

**Comment by BryantS11** [comment]
> It supports custom networks so I assume it supports BSC too.
> 
> Define your provider options like this;
> 
> ```
>     const providerOptions = {
>         walletconnect: {
>             package: WalletConnectProvider,
>             options: {
>             rpc: {
>                 NETWORKID: "https://YOURPROVIDER"
>             },
>             network: "bsc"
>             }
>         }
>     };
> ```
> 
> Then use;
> 
> ```
> try {
>         provider = await web3Modal.connect();
>     } catch(e) {
>         onConnectError();
>     }
> ```
> 
> Also if you want to make sure user is on same network, while interacting, use;
> 
> ```
> const chainId = await web3.eth.getChainId();
>     if(chainId != YOURCHAINID) {
>         alert("Wrong network! Switch to BSC");
>         return;
>     }
> ```
> 
> Also add
> 
> ```
>  CHAINID: {
>                 chainId: CHAINID,
>                 chain: "BSC",
>                 network: "BSC",
>                 networkId: NETWORKID
>             }
> ```
> 
> to the library. It should be around on line 11K, simply CTRL+F and search for callisto-testnet, add yours below that

```
   const providerOptions = {
      /* See Provider Options Section */
      walletconnect: {
        package: WalletConnectProvider, // required
        options: {
          rpc: { 56: 'https://bsc-dataseed1.defibit.io/', },
          network: "binance",
        }
      },
      // Other Providers Go Here
    };
```

You can switch out "https://bsc-dataseed1.defibit.io/" to any other BSC RPC Node that you want.

In the Code it accepts `binance` as the network.

You dont have to do the extra steps as long as you put network as `binance`

**Comment by luatnd** [comment]
BSC testnet was not supported yet

**Comment by ricburton** [comment]
oh no 🤣

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
