### ISSUE TITLE
[bug] Talisman Wallet does not working properly 

### ISSUE THREAD

**Issue by vikiival** [WalletConnect/web3modal#2641]
### Link to minimal reproducible example

https://deploy-preview-10670--koda-canary.netlify.app/base/drops/quadz

### Summary

Talisman wallet uses `window.talismanEth` if `window.ethereum` is not empty.
For users with multiple wallets, therefore Talisman does not work properly

![Screenshot 2024-08-01 at 14 53 22](https://github.com/user-attachments/assets/093b0eb2-848f-4a43-b7a0-e76c53760f96)

Reading:
- https://docs.talisman.xyz/talisman/external-resources/evm-integration-for-dapps
- https://github.com/TalismanSociety/talisman-web3react-example/blob/c5cd7fe276d9a94191d10583b3c7baf6abefc08a/README.md?plain=1#L14C1-L14C132

### List of related npm package versions

-All latest-

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-843/[bug]-cant-sing-a-tx-with-talisman-wallet

**Comment by glitch-txs** [comment]
They should support EIP-6963 instead. Window.ethereum is a legacy implementation in Ethereum wallets.
