### ISSUE TITLE
[bug] Wallet displays incorrect balance for small ETH amounts

### ISSUE THREAD

**Issue by 0xashu** [WalletConnect/web3modal#2647]
### Link to minimal reproducible example

https://jam.dev/c/af15aed4-72f7-45d2-8c43-84d245aa940f

### Summary

**Describe the bug**
The wallet balance display is inaccurate for small amounts of ETH. For example, a balance of 0.000000015094843384 ETH is incorrectly displayed as 1.509 ETH. This appears to be an issue with number truncation or rounding.

**SDK Version (if relevant)**
 - Client: Web Browser
 - Version: "@web3modal/siwe": "^5.0.3"

**To Reproduce**
https://jam.dev/c/af15aed4-72f7-45d2-8c43-84d245aa940f

**Expected behavior**
The wallet should accurately display small amounts of ETH. For comparison, Rainbow Kit displays this amount as "1.509e-8 ETH", which is a more accurate representation.

**Additional context**
- Address: 0x61991904B6dd0B7c6e7cA60906D07D8C1BA00619
- Network: Optimism Mainnet

### List of related npm package versions

- "@web3modal/siwe": "^5.0.3",
- "@web3modal/wagmi": "^5.0.3",

**Comment by rtomas** [comment]
It's working ok for me. Please try update to the last version. 
In case the problem persists please show a video with the OP explorer and the webpage showing different amounts.

**Comment by 0xashu** [comment]
Hey @rtomas 

When I upgraded to the latest 5.0.11, the problem persisted.

Again, you can check the video I provided and I believe you will be able to reproduce it using this address.
> https://vimeo.com/994903409
