### ISSUE TITLE
[bug] cannot verify Second Level Domain through /.well-known/walletconnect.txt

### ISSUE THREAD

**Issue by Revolution1** [WalletConnect/web3modal#2693]
### Link to minimal reproducible example

N/A for this is a pure server side issue.

### Summary

I'm debugging walletconnect on a [blockscout](https://github.com/blockscout/frontend/tree/v1.33.1).
The domain name is like: `www.example.com`
I don't have control of the DNS, but I have controll of the HTTP server.
I setup the verification code and tested it OK:
```
$ curl https://www.example.com/.well-known/walletconnect.txt
76b2ab15-3907-49b8-xxxx-c49d68fe77a5=10424409466a39733b063c6a147847b0d15847f0980003b874feedeee881c037
```

Then I wen to the dashboard, trying to verify the domain and failed:
![image](https://github.com/user-attachments/assets/08249abc-75af-4bbe-9e8a-0d6dcd0f571e)
![image](https://github.com/user-attachments/assets/38fa2402-833c-4a61-8752-33f981ab3ffb)
![image](https://github.com/user-attachments/assets/89ae78da-3c32-4e14-a4f8-bdce1467e3ad)
It seems it's not trying to get the code from HTTP, or it's getting from `example.com` instead of `www.example.com`

Can you help me to solve this issue?
Email me if you need the actual domain.

### List of related npm package versions

```
"wagmi": "2.9.2"
"@web3modal/wagmi": "4.2.1"
```

**Comment by minapham17** [comment]
any update on this issue? I had the same issue
- I can access our site /.well-known/walletconnect.txt with curl or on browser correctly 
- but on Verify domain site, it said DNS TXT Not found as well

**Comment by rtomas** [comment]
This problem is resolved.

**Comment by marclauren90-boop** [comment]
Please give me a hint on how you solved the problem.
