### ISSUE TITLE
[bug] Connecting to Base Sepolia With Social Logins not working well 

### ISSUE THREAD

**Issue by rtomas** [WalletConnect/web3modal#2699]
### Link to minimal reproducible example

https://github.com/WalletConnect/web-examples/tree/issue/with-base-sepolia/dapps/web3modal/react

### Summary

Connect to the Sepolia Base using Social Login. 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/58f99647-b87e-4672-b342-4a6c48254749">

Then a modal appears to change the network upon connection, but clicking it does not yield any response. If I close it, the connection remains ok.

https://github.com/user-attachments/assets/99ed5b84-62f2-4205-a84c-117f225130eb

### List of related npm package versions

"dependencies": {
    "@tanstack/react-query": "5.49.2",
    "@web3modal/wagmi": "5.0.11",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "viem": "2.16.5",
    "wagmi": "2.10.9",
    "@wagmi/core": "2.11.6"
  },

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-875/%5Bbug%5D-connecting-to-base-sepolia-with-social-logins-not-working-well

**Comment by killergerbah** [comment]
We have also observed this problem. Switching network to Base Sepolia seems to fail.

**Comment by big-zak** [comment]
It still exists, for me I cant switch to Base Sepolia
