### ISSUE TITLE
[bug] '@stablelib/random' does not contain a default export 

### ISSUE THREAD

**Issue by martianacademy** [WalletConnect/web3modal#2710]
### Summary

Attempted import error: '@stablelib/random' does not contain a default export (imported as 'Bo').
ERROR in ./node_modules/@walletconnect/utils/dist/index.es.js 4946:12-14
export 'default' (imported as 'Bo') was not found in '@stablelib/random' (possible exports: __esModule, defaultRandomSource, randomBytes, randomString, randomStringForEntropy, randomUint32)

### Link to the related docs page

no

**Comment by kstulgys** [comment]
Same issue. Using Nextjs 14.

**Comment by jason810496** [comment]
Same issue. 
- yarn `v1.22.19`
- Next.js `v13.5.6`

**Comment by MihaiHng** [comment]
I've got the same error
Any fix?

**Comment by ziubelluu** [comment]
Same issue.

- yarn `1.22.22`
- React `18.2.0`

**Comment by rtomas** [comment]
can anyone give more context or any reproducible repository ?
thanks 

cc @ziubelluu @MihaiHng @jason810496 @kstulgys @martianacademy

**Comment by hyphenwave** [comment]
"@walletconnect/utils": "^2.15.0",

**Comment by shawnlim23** [comment]
> can anyone give more context or any reproducible repository ? thanks
> 
> cc @ziubelluu @MihaiHng @jason810496 @kstulgys @martianacademy

I'm not sure how others are facing the issue, but you can replicate it even through cloning the starter kit for thirdweb on https://github.com/thirdweb-example/next-starter

**Comment by ziubelluu** [comment]
@shawnlim23 The starter kit has no issues but checking in the node_modules folder you can see that it uses @walletconnect/utils 2.12.2 while web3modal 5.1.0 uses 2.15.0

**Comment by shawnlim23** [comment]
> @shawnlim23 The starter kit has no issues but by looking in the node_modules folder you can see that it uses @walletconnect/utils 2.12.2 while web3modal 5.1.0 uses 2.15.0

Think we can concur that the issue lies in @walletconnect/utils 2.15.0. On my end, I've been trying to install the thirdweb package on an existing project and i'm facing the same issue. Did a fresh clone of the thirdweb starter kit and still see the same issue, as the dependency package references walletconnect v2.15.0

**Comment by ziubelluu** [comment]
> > @shawnlim23 The starter kit has no issues but by looking in the node_modules folder you can see that it uses @walletconnect/utils 2.12.2 while web3modal 5.1.0 uses 2.15.0
> 
> Think we can concur that the issue lies in @walletconnect/utils 2.15.0. On my end, I've been trying to install the thirdweb package on an existing project and i'm facing the same issue. Did a fresh clone of the thirdweb starter kit and still see the same issue, as the dependency package references walletconnect v2.15.0

From what i can see the issue is caused by @walletconnect/utils trying to import default as Bo when the module @stablelib/random doesn't contain any `import Bo,{randomBytes as Ei}from"@stablelib/random"`

**Comment by MorganDPickens** [comment]
We might have to wait for the creator to push a new update

**Comment by ziubelluu** [comment]
> We might have to wait for the creator to push a new update

Maybe we can open a issue on the walletconnect-monorepo

**Comment by MihaiHng** [comment]
What worked for me was downgrading @web3modal/wagmi from 5.1.0 to 5.0.11

**Comment by ziubelluu** [comment]
> What worked for me was downgrading @web3modal/wagmi from 5.1.0 to 5.0.11

Downgrading to 5.0.11 gets me this error:

`ERROR in ./node_modules/@walletconnect/universal-provider/node_modules/@walletconnect/core/dist/index.es.js 3042:16-18
export 'verifyP256Jwt' (imported as 'Bi') was not found in '@walletconnect/utils'`

**Comment by arsen39** [comment]
Same issue. Using React 18.

And 
"@solana/spl-token": "^0.3.8",
"@solana/wallet-adapter-base": "^0.9.23",
"@solana/wallet-adapter-react": "^0.15.35",
"@solana/wallet-adapter-react-ui": "^0.9.34",
"@solana/wallet-adapter-wallets": "^0.19.23",
"@solana/web3.js": "^1.87.6",

**Comment by ziubelluu** [comment]
> > What worked for me was downgrading @web3modal/wagmi from 5.1.0 to 5.0.11
> 
> Downgrading to 5.0.11 gets me this error:
> 
> `ERROR in ./node_modules/@walletconnect/universal-provider/node_modules/@walletconnect/core/dist/index.es.js 3042:16-18 export 'verifyP256Jwt' (imported as 'Bi') was not found in '@walletconnect/utils'`

Apparently deleting the node_modules folder and reinstalling everything fixed this issue

**Comment by Iliavas** [comment]
same issue, reinstalling node_modules doesnt work

**Comment by urban-hostel** [comment]
Same, Angular 17 with @web3modal/ethers 5.1.0

Downgrading back to 5.0.11 helped solve the issue

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-894/[bug]-stablelibrandom-does-not-contain-a-default-export

**Comment by roshan-synquote** [comment]
We are also facing the same problem.

**Comment by VoQuocViet** [comment]
lol dev can't fix? 3 days ago.

**Comment by fabwaseem** [comment]
I'm facing the same error

**Comment by shayesteMalekpour** [comment]
isn't it fixed?

**Comment by propy-keys** [comment]
Same issue. Downgrading does not help for some reason.

**Comment by urban-hostel** [comment]
https://github.com/WalletConnect/web3modal/issues/2710#issuecomment-2299329980

Try uninstall delete node-modules (I'd applicable) and install new.

**Comment by rtomas** [comment]
We released a fix -> WalletConnect/core v2.15.1
please, run `pnpm install` to update to the latest package.

**Comment by shayesteMalekpour** [comment]
> We released a fix -> WalletConnect/core v2.15.1 please, run `pnpm install` to update to the latest package.

i'm using Wagmi and i still have the issue

**Comment by rtomas** [comment]
@shayesteMalekpour please check this PR -> https://github.com/wevm/wagmi/pull/4213

**Comment by shayesteMalekpour** [comment]
> @shayesteMalekpour please check this PR -> [wevm/wagmi#4213](https://github.com/wevm/wagmi/pull/4213)

thank you so much but i still have it in @rainbow-me/rainbowkit :)
