### ISSUE TITLE
[bug] Web3 Modal Does Not Open Correctly (Empty Modal)

### ISSUE THREAD

**Issue by mprouve** [WalletConnect/web3modal#2712]
### Link to minimal reproducible example

https://github.com/mprouve/web3-modal-minimal-test

### Summary

Expected Behavior:

- When clicking `<w3m-connect-button />` button component, the state should move from **"Connecting..."** to opening the web3 modal. 
- When calling `open()` function provided by `useWeb3Modal()` hook on a custom component, web3 modal should open with populated wallet / email / social logins. 

Observed Behavior:

Under slow network conditions, clicking the `<w3m-connect-button />` button or calling `open()` immediately after the button component renders causes the connections to hang:

- `<w3m-connect-button />` button hangs on "Connecting..."
- `open()` results in an empty modal

Messing with network conditions provides accentuated results (3G conditions makes it easier to trigger this issue). 

OF NOTE: This issue is occurring in the attached Github repo [web3-modal-minimal-test](https://github.com/mprouve/web3-modal-minimal-test), however in my company repo (much larger build size) our network conditions are fast but the slow app rendering due to large files is also causing this issue.

Browser Chrome - Version 127.0.6533.89
Device - Mac 16" M1 Pro 
OS - Ventura 13.1

### List of related npm package versions

"@web3modal/ethers": "^5.0.11",
"@web3modal/siwe": "^5.0.11",
"ethers": "^6.13.2",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"react-scripts": "5.0.1",

**Comment by rtomas** [comment]
hi @mprouve .. I cannot reproduce with our latest version 5.1.6.

Please message me if the problem persists so I can reopen the issue.

**Comment by Doko-Demo-Doa** [comment]
@rtomas We have the same issue. The modal is empty.

![image](https://github.com/user-attachments/assets/c3928269-8642-4306-91e2-89b39cbcbde2)

It worked with version `5.0.11`. We used the hook:

```ts
const { open: openW3M } = useWeb3Modal()
```

**Comment by rtomas** [comment]
Do you have a minimal reproducible example so I can view the issue ?

**Comment by Doko-Demo-Doa** [comment]
@rtomas Yes, please see following ones: Click on "Connect Wallet" button on the top-right, choose "EVM wallets".

Buggy link, using `@web3modal/wagmi` version ^5.1.7: [Link](https://tf-dashboard-git-chore-cleanup-deps-trustswap.vercel.app/)
Working link, using `@web3modal/wagmi` version ^5.0.11: [Link](https://tf-dashboard-git-tf-2050-team-finance-dashboar-638d4d-trustswap.vercel.app/)

Looking at the network inspector, there are some 403 errors in buggy link:

![image](https://github.com/user-attachments/assets/6b114b7f-00d3-4d2e-ab0e-560cdc507463)

Maybe that's where the fetching failed?

**Comment by IvanLudvig** [comment]
I had this problem because project id wasn't passed correctly
