### ISSUE TITLE
[bug] '@stablelib/random' does not contain a default export (imported as 'Bo').

### ISSUE THREAD

**Issue by VoQuocViet** [WalletConnect/web3modal#2719]
### Link to minimal reproducible example

https://www.npmjs.com/package/@web3modal/scaffold-utils/v/5.1.0

### Summary

Attempted import error: '@stablelib/random' does not contain a default export (imported as 'Bo').

### List of related npm package versions

"@web3modal/wagmi": "5.1.0"

**Comment by rtomas** [comment]
Clone #2710
