### ISSUE TITLE
[bug] SwitchChain is not working

### ISSUE THREAD

**Issue by davidli108** [WalletConnect/web3modal#2726]
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/test-switchchain-hdn6hr

### Summary

To reproduce
 - connect wallet to Arbitrum One network (Any other network is possible but not Sepolia). You will see the popup to switch to Sepolia but don't switch.
 - Refresh the page
 - As soon as page is refreshed, you should see popup to switch to Sepolia. But it doesn't happen.

### List of related npm package versions

wagmi: 2.12.7
@web3modal/wagmi 5.1.1
viem: 2.19.8
@tanstack/react-query 5.52.0

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-904/problems-switching-to-arbitrum-one

**Comment by glitch-txs** [comment]
you're forcing the switch in your code
![image](https://github.com/user-attachments/assets/18dad69e-3342-4396-828b-3eb3a31d9d77)
