### ISSUE TITLE
[bug] Cannot select Fantom as chain when connected with a Social login (supported according to the docs)

### ISSUE THREAD

**Issue by paintoshi** [WalletConnect/web3modal#2837]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template-q2bar1

### Summary

According to this doc https://docs.walletconnect.com/appkit/features/socials#supported-chains Fantom is supported.

But when connected by email, discord, github etc Fantom can't be selected. Other "supported" chains works fine. So either it's not supported yet, or something is wrong.

My sandbox demo can't deal with social logins (no sandboxes does), but can download the code and run locally.

![image](https://github.com/user-attachments/assets/4fa6e18c-eafe-4ad9-afed-978a8d1a0888)

### List of related npm package versions

"@web3modal/wagmi": "5.0.6",
"viem": "^2.17.4",
"wagmi": "^2.10.10"

**Comment by rtomas** [comment]
Working with latest version.

tested with 5.1.7

**Comment by paintoshi** [comment]
> Working with latest version.
> 
> tested with 5.1.7

@rtomas Can you please provide an example where it does work? I updated my demo sandbox with latest web3modal 5.1.7, wagmi and viem but still can't switch to Fantom. And re-open the issue until you can prove it's been solved.
