### ISSUE TITLE
Webpack5 failed

### ISSUE THREAD

**Issue by safead** [WalletConnect/web3modal#317]
UPD: the problem is after 
```
npm install --save @walletconnect/web3-provider
```

Is this project alive? Webpack5 is already not young, but compilation of this lib fails with messages:

```
ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js 21:11-26
Module not found: Error: Can't resolve 'http' in 'node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
 @ ./node_modules/xhr2-cookies/dist/index.js 6:9-38
 @ ./node_modules/@walletconnect/http-connection/dist/esm/index.js 2:0-46 4:47-61
 @ ./node_modules/@walletconnect/web3-provider/dist/esm/index.js 3:0-60 268:28-42
 @ ./src/components/BodyTop/index.jsx 8:0-65 147:29-50
 @ ./src/components/AppIndex/AppIndex.jsx 3:0-37 7:133-140
 @ ./src/components/AppIndex/index.js 1:0-31 1:0-31
 @ ./src/components/index.js 2:0-27 2:0-27
 @ ./src/index.jsx 3:0-35 4:41-44
```

and a lot of the same errors:
```
Can't resolve 'https'
Can't resolve 'util' in 'node_modules\web3-provider-engine\util'
 Can't resolve 'os' in '\node_modules\xhr2-cookies\dist'
```

**Comment by hoangnamhr** [comment]
Im also getting the same error :((

**Comment by leviyehonatan** [comment]
cannot upgrade to react-script 5.0.0 since it uses webpack 5 had to stay at 4.0.3

**Comment by enfaceai** [comment]
Really? You made a stand-alone component which is addicted to react-script?

**Comment by Jayanth9710** [comment]
Any luck on this problem?? Breaking my head for a long time now :(

**Comment by leviyehonatan** [comment]
no luck still waiting for an update like everyone else here who/where are the creators of this library?

**Comment by repinsky13** [comment]
Been getting the same error when trying to use solely WalletConnect standalone client, no response in the related issue in their repo either. I guess the only way to go is to manually polyfill all the missing node.js modules?

**Comment by Wemmons831** [comment]
anyone figure this out I had manually polyfilled everything but nothing seems to be rendering I get a bunch of warnings all something along the lines of " to parse source map from 'node_modules\xhr2-cookies'    Error: ENOENT: no such file or directory, open"

**Comment by mushegdavtyan** [comment]
I was had the same problem. I did next steps to resolve it:
1. Run `npm run eject` [more](https://create-react-app.dev/docs/available-scripts/#npm-run-eject)
2. Install `npm i stream-http --save`
3. Add `resolve.fallback` to config/webpack.config.js. Example: `resolve: { fallback: {
        "http": require.resolve("stream-http")
      }}`

**Comment by mikjakbiak** [comment]
We use CRA 5, and to fix the problem I installed [craco](https://www.npmjs.com/package/@craco/craco/v/7.0.0-alpha.3), created `craco.config.js` and put there
```
const webpack = require('webpack')

module.exports = {
    webpack: {
        plugins: {
	    add: [
	        new webpack.ProvidePlugin({
		    Buffer: ['buffer', 'Buffer'],
		}),
	    ],
	},
	configure: {
	    resolve: {
		fallback: {
		    stream: require.resolve('stream-browserify'),
		    https: require.resolve('https-browserify'),
		    os: require.resolve('os-browserify/browser'),
		    http: require.resolve('stream-http'),
		    buffer: require.resolve('buffer'),
		},
	    },
	},
    },
}
```
And then install all necessary packages `yarn add stream-browserify url assert util stream-http https-browserify os-browserify buffer`. Everything works fine but I still get those source maps warnings @Wemmons831 mentioned

**Comment by 3on** [comment]
> We use CRA 5, and to fix the problem I installed [craco](https://www.npmjs.com/package/@craco/craco/v/7.0.0-alpha.3), created `craco.config.js` and put there
> 
> ```
> const webpack = require('webpack')
> 
> module.exports = {
>     webpack: {
>         plugins: {
> 	    add: [
> 	        new webpack.ProvidePlugin({
> 		    Buffer: ['buffer', 'Buffer'],
> 		}),
> 	    ],
> 	},
> 	configure: {
> 	    resolve: {
> 		fallback: {
> 		    stream: require.resolve('stream-browserify'),
> 		    https: require.resolve('https-browserify'),
> 		    os: require.resolve('os-browserify/browser'),
> 		    http: require.resolve('stream-http'),
> 		    buffer: require.resolve('buffer'),
> 		},
> 	    },
> 	},
>     },
> }
> ```
> 
> And then install all necessary packages `yarn add stream-browserify url assert util stream-http https-browserify os-browserify buffer`. Everything works fine but I still get those source maps warnings @Wemmons831 mentioned

Thanks a lot for the craco tip.
To save some people's time, craco doesnot support CRA 5 yet, you have to use an early version
`npm install @craco/craco@7.0.0-alpha.3 --save`
Find the latest version: https://www.npmjs.com/package/@craco/craco

@mikjakbiak did you ever found a way to remove all the source map errors?

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
