### ISSUE TITLE
Set ZIndex for the modal

### ISSUE THREAD

**Issue by fsobh** [WalletConnect/web3modal#332]
Im not able to control zindex of modal and its causing it to be last layered item (stopping me from clicking button)

**Comment by fsobh** [comment]
> 

im still facing this issue

**Comment by chadyj** [comment]
Dupe of https://github.com/WalletConnect/web3modal/issues/332

**Comment by chadyj** [comment]
Dupe of https://github.com/WalletConnect/web3modal/issues/165
