### ISSUE TITLE
Not seeing the option to connect to MetaMask on Firefox

### ISSUE THREAD

**Issue by phileasthefogg** [WalletConnect/web3modal#351]
On Chrome this doesn't seem to be an issue -- I'm presented with options for both MetaMask and Walletconnect (a provider I included).  
<img width="502" alt="Screen Shot 2021-12-01 at 4 34 16 PM" src="https://user-images.githubusercontent.com/54925839/144336339-5c0c6e60-8c8d-4d9f-a562-e865c7f0f4a0.png">
 As long as the Chrome browser im connecting with has the MetaMask extension, this modal will offer the selection.  Unfortunately this isn't the case with Firefox and I can't seem to figure out why.  Has anyone else run into this issue?

**Comment by samirspatel** [comment]
![Screen Shot 2021-12-07 at 9 05 48 AM](https://user-images.githubusercontent.com/22302566/145054195-aa7cc799-5d05-4028-9ba1-13ca224f6b84.png)

works on ff
