### ISSUE TITLE
how do you sort the wallet list?

### ISSUE THREAD

**Issue by dmidnight** [WalletConnect/web3modal#392]
I have my providerOptions sorted in the order I want, but the list comes out in a different order. How do I control the order of the wallets in the list?

**Comment by Enigmatic331** [comment]
Eyes on this too... 😁

**Comment by 0xSzeth** [comment]
+1

**Comment by jcurbelo** [comment]
any updates on this?

**Comment by bennyvenassi** [comment]
would be really interesting :)

**Comment by leo-icp** [comment]
flex
order

**Comment by shkyung** [comment]
I'm also waiting for this feature to be added

**Comment by engineersamuel** [comment]
+1

**Comment by hackyguru** [comment]
There has been a lot of questions and feedback related to sorting the wallet list. We took all your feedback into account and worked on Web3Modal v2 which provides a personalized list of wallets. The list is contextual and depends on the user's preferences. Stay tuned to our social handles for our upcoming announcement! :) Again, on behalf of our team - I'd like to thank you all for raising this feature request.
