### ISSUE TITLE
Display loading animation while connecting

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/web3modal#42]
Each button should track the connector promise and add a shimmer animation on top.

**Comment by jamesmorgan** [comment]
This would be great, asked a question on Discord about this last week. I looks like some providers do this but would be nice for web3Connect to expose either some hooks/callbacks which the implementing app can then leverage or a native loading/spinning feedback.

**Comment by T-Damer** [comment]
How about displaying animation for formatic, aetherium, etc? Of course, we can create a loading state in our apps, but it would be nicer, to have such a state inside your library :)

**Comment by hackyguru** [comment]
The loading animation is handled on v2, closing the issue.
