### ISSUE TITLE
Blocked with error in production with ViteJS Vue-3 

### ISSUE THREAD

**Issue by edeuxk** [WalletConnect/web3modal#463]
Hello everyone,

Thanks for this amazing package, it saved me a lot of time building my dApp but here is why I post an issue.

I'm using ViteJS, Vue 3, Web3Modal, Web3 and walletconnect/web3-provider.

In development I can use web3 and retrieve my eth account after connection.
![image](https://user-images.githubusercontent.com/8247995/163579770-9e020da9-e3b1-40fb-9963-4fe88f646988.png)

In production with the exact same code, after running yarn build, I get this error that I can't manage to solve
![image](https://user-images.githubusercontent.com/8247995/163579842-b2d89bf4-7447-4fa3-ac6e-f72570e8a983.png)

The whole code is here: https://github.com/edeuxk/vite-example-error-web3

Quick view of what I did, my App.vue
```
<template>
  <div>Hello</div>
</template>

<script>
import Web3 from "web3";
import Web3Modal from "web3modal";
import WalletConnectProvider from "@walletconnect/web3-provider";

export default {
  async mounted() {
    const providerOptions = {
      walletconnect: {
        package: WalletConnectProvider, // required
        options: {
          infuraId: "INFURA_ID" // required
        }
      }
    };

    const web3Modal = new Web3Modal({
      network: "mainnet", // optional
      cacheProvider: true, // optional
      providerOptions // required
    });

    const provider = await web3Modal.connect();

    const web3 = new Web3(provider);
    let accounts = await web3.eth.getAccounts();
    console.log('passed4');

    console.log(accounts);

  }
}
</script>
```

and my vite.config.js
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

//vite.config.js
import nodePolyfills from 'rollup-plugin-polyfill-node';
const production = process.env.NODE_ENV === 'production';

export default defineConfig({

  plugins: [
    // ↓ Needed for development mode
    vue(),
    !production && nodePolyfills({
        include: ['node_modules/**/*.js', new RegExp('node_modules/.vite/.*js')]
      })
  ],

  build: {
    rollupOptions: {
      plugins: [
        // ↓ Needed for build
        nodePolyfills(),
      ]
    },
    // ↓ Needed for build if using WalletConnect and other providers
    commonjsOptions: {
      transformMixedEsModules: true
    }
  }
});
```

**Comment by edeuxk** [comment]
Ok I finally managed to fix it but you should do a quick fix for ViteJS Installation.

I managed to find that it was using "readable-stream" function from "rollup-plugin-polyfill-node" package who wasn't working properly with ViteJS.

So I did a quick fix :
Run: npm install vite-compatible-readable-stream --save-dev

Then add to your vite.config.js
```
  resolve: {
    alias: {
      "readable-stream": "vite-compatible-readable-stream",
    }
  },
```

Please team, take time to look at it anyway and maybe use my patch to fix the ViteJS Installation tutorial.

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
