### ISSUE TITLE
How to connect to localhost:8545

### ISSUE THREAD

**Issue by y0unghe** [WalletConnect/web3modal#472]
What value should I put to key `network` so it can connect to localhost:8545 node with chainId:1337?

**Comment by chattertechno** [comment]
` const providerOptions = {
        walletconnect: {
            package: WallectConnectProvider,
            options: {
                rpc: {
                    1337: 'http://localhost:8545',
                },
                chainId: 1337,
            },
        },
    } `
You just need to change the provider options!.

**Comment by hackyguru** [comment]
> `const providerOptions = { walletconnect: { package: WallectConnectProvider, options: { rpc: { 1337: 'http://localhost:8545', }, chainId: 1337, }, }, }` You just need to change the provider options!.

Appreciate you helping out @chattertechno 🙌
