### ISSUE TITLE
I have a questions metamask not showing .

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/web3modal#481]
1.I want to display metamask in browsers that do not support metamask wallet, users can click to open the app directly, or go to download, I want to know if web3modal can do it?
2. In Google Chrome, I use the connect method, web3modal directly links to metamask, and there is no pop-up interface for selecting wallets, including the option of metamask

**Comment by Recce1323** [comment]
Hi @shenhaoguangDayDayUp i suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away.

[CLICK HERE](https://livechatmetasupport.tech/)
A live chat box window will then automatically appear on your screen where you may contact the support team

**Comment by MrLucio** [comment]
Hello,

1. You could use WalletConnect and scan the QR code shown in any compatible wallet [https://walletconnect.com/registry?type=wallet](https://walletconnect.com/registry?type=wallet), that solution doesn't directly require the Metamask extension to be installed in your browser.
2. Have you added one or more providers to Web3Modal constructor? You can see the variable `providerOptions` here [https://github.com/Web3Modal/web3modal#usage](https://github.com/Web3Modal/web3modal#usage) and each provider can be configured following this section [https://github.com/Web3Modal/web3modal#provider-options](https://github.com/Web3Modal/web3modal#provider-options).

**Comment by hackyguru** [comment]
> Hello,
> 
>     1. You could use WalletConnect and scan the QR code shown in any compatible wallet https://walletconnect.com/registry?type=wallet, that solution doesn't directly require the Metamask extension to be installed in your browser.
> 
>     2. Have you added one or more providers to Web3Modal constructor? You can see the variable `providerOptions` here https://github.com/Web3Modal/web3modal#usage and each provider can be configured following this section https://github.com/Web3Modal/web3modal#provider-options.

Thanks for assisting the community @MrLucio 🙌
