### ISSUE TITLE
On the mobile terminal, after jumping to the metamask connection, you will be prompted to return to the browser, but you cannot obtain the wallet address and other information after returning to the browser.

### ISSUE THREAD

**Issue by zddyx258** [WalletConnect/web3modal#487]
On the mobile terminal, after jumping to the metamask connection, you will be prompted to return to the browser, but you cannot obtain the wallet address and other information after returning to the browser.
code:
<script>
import Web3 from 'web3';
import Web3Modal from 'web3modal';
import Web3Provider from '../../static/js/web3Provider.min.js';
export default {
	data() {
		return {
			web3: '',
			web3Modal: '',
			provider: '',
			contract: '',
			is_connect: false,
			accountAddress: '',
			info: {},
			contract_info: {}
		}
	},
	components: {
		Web3,
		Web3Modal,
		Web3Provider
	},
	methods: {
		async connect() {
			try{
				this.provider = await this.web3Modal.connect();
			}catch(e){
				console.log('Could not get a wallet connection', e);
				return;
			}
			
			this.provider.on('accountsChanged', (accounts)=>{
				console.log('accountsChanged');
				this.getAccountData();
				return;
			});
			this.provider.on('chainChanged', (chainId)=>{
				console.log('chainChanged');
				this.getAccountData();
				return;
			});
			this.provider.on('networkChanged', (networkId)=>{
				console.log('networkChanged');
				this.getAccountData();
				return;
			});
			
			await this.getAccountData();
		},
		
		async getAccountData() {
			this.web3 = new Web3(this.provider);
			this.is_connect = true;
			
			let chainId = await this.web3.eth.getChainId();
			let blockNumber = await this.web3.eth.getBlockNumber();
			let block = await this.web3.eth.getBlock(blockNumber);
			let blockTimestamp = block.timestamp;
			let account = await this.web3.eth.getAccounts();
			this.accountAddress = account[0];
			let accountBalance = await this.web3.eth.getBalance(this.accountAddress);
			accountBalance = this.web3.utils.fromWei(accountBalance, 'ether');
			this.info = {
				chainId,
				blockNumber,
				blockTimestamp,
				accountAddress: this.accountAddress,
				accountBalance
			};
		},
		
		async disconnect() {
			if(this.provider.close) {
				await this.provider.close();
				await this.web3Modal.clearCachedProvider();
				this.provider = '';
				this.contract = '';
			}
			this.is_connect = false;
			this.accountAddress = '';
			this.info = {};
			this.contract_info = {};
		}
	},
	onLoad(e) {
		let providerOptions = {
			walletconnect: {
				package: Web3Provider,
				options : {
					rpc: {
						56: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
					},
					network: 'binance',
					chainId: 97,
				},
			}
		};
		this.web3Modal = new Web3Modal({
			network: 'binance',
			cacheProvider: false,
			providerOptions
		});
	}
}
</script>

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
