### ISSUE TITLE
 Does web3modal not support the lower version of Android? For example, Android 5 and Android 6

### ISSUE THREAD

**Issue by zhoujian917** [WalletConnect/web3modal#498]
The project uses vue2 + web3modal. After the introduction of web3modal, the page white screen will be opened in Android 6 and below. Does web3modal not support the lower version of Android? For example, Android 5 and Android 6...

I use the official demo, and the page opened on Android 6 and below is also blank

**Comment by Vivienne-CPZ** [comment]
I have the same problem with web3modal V2

Android 9.0/Android 8.1 arm64 is also blank and error is reported

Android 10 arm64 runs well

Have you solved this problem

**Comment by 0xAsimetriq** [comment]
@Vivienne-CPZ What error do you get? What version do you use?

**Comment by chadyj** [comment]
I did some testing:

Google Pixel 2 - Android 8
Samsung Galaxy S8 - Android 7
Google Nexus 7 - Android 6

All worked as expected.  Please let us know if you have specific reproduction steps.

**Comment by 0xAsimetriq** [comment]
Closing this issue, as we are now testing on android emulators and everything works as expected for majority. This also depends on which browser is used and if there are any os specific blocks.

Android now has it's own flow where it shows you native "sheet" with options that you can connect to.
