### ISSUE TITLE
Avoid showing uninstalled wallet

### ISSUE THREAD

**Issue by afiorenza** [WalletConnect/web3modal#525]
I don't know if this is a bug or a feature request, but i would like to avoid showing Browser/Frame wallets on the modal if the user does not have some of them installed. Is there any way to check it? 

Thanks in advance.

**Comment by hackyguru** [comment]
Helo @afiorenza we noted your feedback earlier and worked on a more contextual modal which shows a personalized list of wallets :) Stay tuned to our social handles for further updates!
