### ISSUE TITLE
Can I connect wallets with vanilla javascript?

### ISSUE THREAD

**Issue by ene519** [WalletConnect/web3modal#530]
I would like to implement many connectors in a vanilla javascript website.
I found https://github.com/Web3Modal/web3modal-vanilla-js-example but the look & feel is not very customizable (and I would need to change it completely). Therefore, I am trying to implement MetaMask, WalletConnect, Binance Chain Wallet etc from scratch but all the examples I found were for React or Node.js.
Can I implement these with vanilla javascript?
![connectwallet](https://user-images.githubusercontent.com/103062534/179430975-25431b3c-248c-40fd-b4f6-4c67d03039e6.png)

**Comment by hadi73ebrahimi** [comment]
if the problem still remains, there is two option that you got. 
the first one is to use provided api to change the colors but it's limited and does not provide much control over how modal should be shown. 
the second option that i used was by editing the web3modal source code and then export. the overall process is simple and straightforward.

**Comment by hackyguru** [comment]
> if the problem still remains, there is two option that you got. the first one is to use provided api to change the colors but it's limited and does not provide much control over how modal should be shown. the second option that i used was by editing the web3modal source code and then export. the overall process is simple and straightforward.

thanks for helping out @hadi73ebrahimi
