### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by JSanchezFDZ** [WalletConnect/web3modal#545]
**Hello!**

I need to update the npm package with the new github commits.

Thanks!

**Comment by nrgbistro** [comment]
What exactly does this mean? You want to update your app's version of web3modal?

**Comment by JSanchezFDZ** [comment]
Thanks for answering.

The NPM version does not have the latest commits from the Github repository.

There are bugs with injected wallets that have been fixed.

I need to apply all the new changes, update the existing npm package.

**Comment by emirsavran** [comment]
@JSanchezFDZ you can use git repos as npm packages:
https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a#:~:text=To%20npm%20install%20a%20public,repo%23branch%2Dname%20format.&text=Run%20npm%20install%20and%20npm,into%20your%20%2Fnode_modules%2F%20folder.

**Comment by hackyguru** [comment]
Just checked, all the npm packages are upto date right now :) Closing the issue, feel free to reopen if you still have problems.
