### ISSUE TITLE
WalletConnect not working

### ISSUE THREAD

**Issue by Aeddon** [WalletConnect/web3modal#550]
Hi, 
I have troubles of using WalletConnect in Web3Modal. 
I did already some tests around 10monthes ago, back then it worked.

Now I have the following symptoms: 
QR Code is shown, JS is establishing WS connection to `wss://bridge.walletconnect.org/`, 
it sends two messages to the wss. All looks correct.

When I scan the QR code in Trust Wallet, it seems to process it, a message comes "Connecting may take a few seconds", 
and then nothing happens. There should come a screen to allow connection, but it doesn't. No messages in WS, nothing...

When I use the same Trust Wallet app to test-connect to web3modal.com (example app), all is working fine, 
so it's not a Trust Wallet issue... 

I played around with different versions of web3modal and web3-provider, everywhere I have the same outcome.

Any clue where the problem could be? And more important: how to debug this stuff?

Cheers C

**Comment by Aeddon** [comment]
problem solved... seems the bridge could not extract the needed website information due to an wrong character in the html document.

**Comment by Bright-Glitch** [comment]
Hi @Aeddon could you specify on that? I'm having the same issue but I don't seem to find the solution, I running it on Next.js on a simple sandbox I made
