### ISSUE TITLE
cannot connect when minted from web3model

### ISSUE THREAD

**Issue by kingsop** [WalletConnect/web3modal#560]
I am trying to connect from the provider so that I can show a screen with a button to connect when minted ,but i couldn't connected Wallet when i click mint butten. although i already connected Wallet,it also alert('Please connect your Ethereum wallet!')

code:

`// constants
const contractAddress = ''
const tokenPrice = 0.001
const presaleLive = false
const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      infuraId: ''
    }

  }
}

// web3 obj inst
window.web3Modal = new Web3Modal({
  network: 'mainnet',
  cacheProvider: true,
  providerOptions
})

function App () {
  // hooks
  const [account, setAccount] = useState('Connect Wallet')
  const [total, setTotal] = useState(0)
  const [totalSupply, setTotalSupply] = useState(0)
  const [connectionStatus, setConnectionStatus] = useState(false)
  const [proof, setProof] = useState('')
  const [loading, setLoading] = useState(false)

  // funcs
  let connectWallet = async () => {
    window.provider = await window.web3Modal.connect()
    window.web3 = new Web3(window.provider)

    window.accounts = await window.web3.eth.getAccounts()
    setAccount(
      String(window.accounts[0]).substring(0, 6) +
      '...' +
      String(window.accounts[0]).substring(38)
    )

    window.contract = new window.web3.eth.Contract(contractAbi, contractAddress)

    const supply = await window.contract.methods.totalSupply().call()
    setTotalSupply(supply)

    let whitelist = [
      "0x5C3351c9f5043984e4CecBF0EA858Ae782087607"
    ]
    const leafNodes = whitelist.map(addr => keccak256(addr))
    const merkleTree = new MerkleTree(leafNodes, keccak256, { sortPairs: true })
    setProof(merkleTree.getHexProof(keccak256(window.accounts[0])))

    setConnectionStatus(true)
  }

  let mintTokens = async (e) => {
    e.preventDefault()
    setLoading(true)

    try {
      if (presaleLive) {
        if (!(await window.contract.methods.presaleLive().call())) {
          alert('Presale is not currently live!')
          setLoading(false)
          return
        } else if (!(await window.contract.methods.isWhitelisted(window.accounts[0], proof).call())) {
          alert('Connected wallet is not whitelisted for the presale!')
          setLoading(false)
          return
        }
      } else {
        if (!(await window.contract.methods.saleLive().call())) {
          alert('Sale is not currently live!')
          setLoading(false)
          return
        }
      }
    } catch {
      alert('Please connect your Ethereum wallet!')
      setLoading(false)
      return
    }

    var quantity = document.getElementById('tokenQuantity').value
    try {
      var totalWei = window.web3.utils.toWei(String(total))
      if (presaleLive) {
        await window.contract.methods.presaleBuy(quantity, proof).send({ from: window.accounts[0], value: totalWei })
          .on('receipt', function (receipt) {
            if (receipt !== null) {
              alert('Minting was successful!')
            }
          })
      } else {
        await window.contract.methods.buy(quantity).send({ from: window.accounts[0], value: totalWei })
      }
    } catch (err) {
      if (err.code === 'INVALID_ARGUMENT') {
        alert('Please select a quantity to mint!')
      } else if (err.code === 4001) {
        alert('Transaction cancelled by user!')
      } else if (err.code === -32603) {
        alert("Quantity exceeds wallet's available tokens!")
      } else {
        alert('An error occured!')
      }
      setLoading(false)
      return
    }

    setTotal(0)
    setLoading(false)
    e.target.reset()
  }

  let handleInputChange = (e) => {
    setTotal(parseFloat(parseFloat(e.target.value * tokenPrice).toPrecision(12)))
  }

  if (connectionStatus) {
    // Subscribe to accounts change
    window.provider.on("accountsChanged", (accounts: string[]) => {
      connectWallet()
      console.log(accounts)

    })
  }

  return (
    <div className="App">

      <Container fluid>

        <img class="bg-image" alt="" src="/back.jpeg" />
        <div class="overlay"></div>
        <Row className="min-vh-100 main-bod">
          <Col>
            <div className="d-flex flex-column h-100">

              <Row>
                <Navbar expand="lg" bg="dark" variant="dark">
                  <Container className="mob-center">
                    <Navbar.Brand>
                      <img class="main-logo" alt="" src="/logo.png" />
                    </Navbar.Brand>
                    <Button variant="primary" className="connect-button" onClick={connectWallet}>{account}</Button>
                  </Container>
                </Navbar>
              </Row>

              <Row className="justify-content-md-center align-items-center flex-grow-1 pt-5 main-body">
                <Col md="auto" />
                <Col xs md={4}>
                  <h2 className="mint-title align-center">
                    Mint Your Joker{presaleLive && ' '}
                    {presaleLive && (
                      <Badge className="bg-primary pb-2 mt-3 mt-md-sm-0 tag-btn">Presale</Badge>
                    )}
                  </h2>
                  <Card>
                    <Card.Body>

                      {presaleLive && connectionStatus ? [
                        <p className="mb-0">Total Joker Minted</p>,
                        <h4>{totalSupply}/2000</h4>,
                        <ProgressBar animated now={(totalSupply / 2000) * 100} label={`${Math.round((totalSupply / 2000) * 100)}%`} />,
                        <hr className="my-3" />
                      ] : connectionStatus ? [
                        <p className="mb-0">Total Joker Minted</p>,
                        <h4>{totalSupply}/10000</h4>,
                        <ProgressBar animated now={(totalSupply / 10000) * 100} label={`${Math.round((totalSupply / 10000) * 100)}%`} />,
                        <hr className="my-3" />
                      ] : null}

                      <Form onSubmit={mintTokens}>
                        <p className="mb-0 text-end">Price Per Joker</p>
                        <h4 className="text-end">{tokenPrice + ' '}
                          <b>ETH</b>
                        </h4>

                        <Form.Group className="mb-3">

                          {presaleLive ? (
                            <Form.Control
                              id="tokenQuantity"
                              type="number"
                              min="1"
                              max="2"
                              placeholder="Enter number of Joker to mint*"
                              onChange={handleInputChange}
                            />
                          ) : (
                            <Form.Control
                              id="tokenQuantity"
                              type="number"
                              min="1"
                              max="10"
                              placeholder="Enter number of Joker to mint*"
                              onChange={handleInputChange}
                            />
                          )}

                          <p className="text-end">
                            {presaleLive ? (
                              <small>*Max 10 Joker Per Wallet</small>
                            ) : (
                              <small>*Max 10 Per Wallet</small>
                            )}
                          </p>
                        </Form.Group>

                        <hr className="my-3" />
                        <div className="total-text">
                          <p className="m-0">Total</p>
                          <h5 className="m-0">{total}{' '}
                            <b>ETH</b>
                          </h5>
                        </div>

                        <div className="d-grid gap-2">
                          <Button variant="primary" type="submit">
                            {!loading && "Mint"}
                            {loading && (
                              <Spinner
                                style={{
                                  marginBottom: "0.1em",
                                  marginLeft: "0.6em",
                                  marginRight: "0.6em"
                                }}
                                as="span"
                                animation="border"
                                size="sm"
                                role="status" />
                            )}
                          </Button>
                        </div>
                      </Form>

                    </Card.Body>
                  </Card>
                </Col>
                <Col md="auto" />
              </Row>

            </div>
          </Col>
          <Navbar className="pt-0 footer-nav">
            <span className="navbar-text mx-auto my-0 pt-0">
              View contract on
              {' '}
              <a href={'https://etherscan.io/address/' + contractAddress} target="blank" >
                <b>Etherscan</b>
              </a>
            </span>
          </Navbar>
        </Row>
      </Container>

    </div>
  )
}`

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
