### ISSUE TITLE
error at walletconnect.ts

### ISSUE THREAD

**Issue by A-M-H-F** [WalletConnect/web3modal#564]
binancechainwallet working & metamask working.

only walletconnectprovider
when i click on it it respond with error without showing qr or other thing

i'm using laravel and js
---------------------

**Error:**
walletconnect.ts:34 Uncaught (in promise) TypeError: e is not a constructor
    at walletconnect.ts:34:22
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at Module.l (tslib.es6.js:72:12)
    at walletconnect.ts:16:44
    at new Promise (<anonymous>)
    at t.default (walletconnect.ts:16:10)
    at e.<anonymous> (providers.ts:204:30)

-----------------------------
**Files used by CDNs:**
<script src="https://cdn.ethers.io/lib/ethers-5.7.0.umd.min.js" type="application/javascript"></script>
<script type="text/javascript" src="https://unpkg.com/web3modal@1.9.8/dist/index.js"></script>
<script type="text/javascript" src="https://unpkg.com/@walletconnect/web3-provider@1.7.8/dist/umd/index.min.js"></script>

------------------------

**My Configuration** 

`  
    
    <script>

    class LaravelWeb3 {
    constructor() {
        this._provider = null;
        this.reloadAfterFetching = true;
        this.alertUserIfMetamaskIsNotInstalled = true;
        this.contracts = @json(config('web3.contracts'));
        this.web3ModalOptions = {
            theme: "dark",
            cacheProvider: true,
            disableInjectedProvider: false,
            providerOptions: {
                binancechainwallet: {
                    package: true
                },
                walletconnect: {
                    package: WalletConnectProvider,
                    options: {
                    infuraId: "***** // i keep it hidden bcz public post",
                    },
                },
            },
        };
     }
    
    async onConnect() {
        try {
            const web3Modal = this.prepareWeb3Modal();
            const provider = await web3Modal.connect();
            provider.on("accountsChanged", async (accounts) => {
                console.log("accountsChanged", accounts);
                web3Modal.clearCachedProvider();
                await this.fetchAccount(provider);
                if (this.reloadAfterFetching) window.location.reload();
            });
            provider.on("chainChanged", async (chainId) => {
                console.log("chainChanged", chainId);
                web3Modal.clearCachedProvider();
                await this.fetchAccount(provider);
                if (this.reloadAfterFetching) window.location.reload();
            });
            provider.on("connect", ( { chainId }) => {
                console.log("connect", chainId);
            });

            provider.on("disconnect", ( { code, message }) => {
                console.log("disconnect", code, message);
            });
            await this.fetchAccount(provider);
            if (this.reloadAfterFetching) window.location.reload();
        } catch (e) {
            console.log({ e });
        }
    }

    async fetchAccount(web3Provider) {
        const provider = new ethers.providers.Web3Provider(web3Provider);
        const message = await(await(await fetch("/_web3/users/signature", {
        method: "get",
        headers: {
            "Content-Type": "application/json",
            "X-CSRF-Token": "{{ csrf_token() }}",
        },
    })).json()).message;
    await fetch("/_web3/users",{
        method:'post',
      body: JSON.stringify({
            signature: await provider.getSigner().signMessage(message),
            address: await provider.getSigner().getAddress(),
      }),
      headers: {
            "Content-Type": "application/json",
            "X-CSRF-Token": "{{ csrf_token() }}",
        },
    })
        this._provider = provider;
    }

    async onDisconnect() {
        this._provider = null;
        const web3Modal = this.prepareWeb3Modal();
        await web3Modal.clearCachedProvider();
        await fetch("/_web3/users/logout",{
        method: "delete",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": "{{ csrf_token() }}",
            },
        });
        if (this.reloadAfterFetching) window.location.reload();
    }

    async getProvider() {
        if (!this._provider) {
            const web3Modal = this.prepareWeb3Modal();
            const web3Provider = await web3Modal.connect();
            this._provider = new ethers.providers.Web3Provider(web3Provider);
        }
        return this._provider;
    }

    prepareWeb3Modal () {
        let Web3Modal, WalletConnectProvider;
        if (window.Web3Modal.default) {
            Web3Modal = window.Web3Modal.default;
        }
        if (window.WalletConnectProvider) {
            WalletConnectProvider = window.WalletConnectProvider.default;
        }
        const web3Modal = new Web3Modal(this.web3ModalOptions);
        return web3Modal;
    }

    addContract(address,contract) {
        this.contracts = [...this.contracts, { address, contract }];
    }
    }
    window.laravelWeb3 = new LaravelWeb3();
    </script>`

**Comment by A-M-H-F** [comment]
I have fixed the problem, by adding

const WalletConnectProvider = window.WalletConnectProvider.default;

inside constructor()

**Comment by hackyguru** [comment]
Appreciate you letting us know the fix @A-M-H-F . Closing the issue :)
