### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by reslear** [WalletConnect/web3modal#580]
I propose to describe an example of use with Vue and [Vagmi](https://github.com/wobsoriano/vagmi)

**Comment by IljaDaderko** [comment]
We'll be adding support to Vue very soon and with that will also add an example 👌 web3modal relies on `@wagmi/core` internally and exposes its own hooks / compostables (that are mostly identical to wagmi/ract and vagmi, but with few changes to help us support cross framework / chain features that we will release in the future).

Once Vue is supported, your experience will be identical to current react implementation, you'd just need to change your framework package i.e.

```
npm i @web3modal/vue @web3modal/ethereum
```

**Comment by Droppix** [comment]
Hi,

Currently, there is no framework, compatible with vue 2.x, in how long can we expect to have access to an alpha/beta version?
Thks

**Comment by reslear** [comment]
I don't think it's worth focusing on vue 2

**Comment by IljaDaderko** [comment]
We'll support vue, but likely starting from v3. In terms of when it depends on how soon we stabilise / finalise all features with react being main test framework. Otherwise we'll have to re-do apis on vanilla + 2 frameworks. But shouldn't be too long :)

**Comment by callmejm** [comment]
cant wait to see vue version release 👍👍

**Comment by mohdxnizamv** [comment]
how i can get source for vue version

**Comment by Droppix** [comment]
I try implement (Vue + Nuxt 2) the sample (Vanilla JS), and I have this error

```
 ERROR  Failed to compile with 1 errors                           friendly-errors 10:56:17
 ERROR  in ./node_modules/@web3modal/core/dist/index.js           friendly-errors 10:56:17

Module parse failed: Unexpected token (1:1731)                    friendly-errors 10:56:17
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import{proxy as l,subscribe as u}from"valtio/vanilla";import{Buffer as W}from"buffer";func```

**Comment by kennyyS** [comment]
Hi, do we have an ETA regarding a Vue support ?

**Comment by donnyquixotic** [comment]
I see that Vue support was removed from the 2.2.0 milestone, any update on when support will be added?

**Comment by 0xAsimetriq** [comment]
Had to re-prioritise, but Vue is next framework we aim to add official library for, meanwhile you can use `@web3modal/html` with it.

**Comment by thirdman** [comment]
pls.

**Comment by MaxVast** [comment]
Hello,
Can you tell us when the version with VueJS will be ready?
I tried to integrate @web3modal/html version but it doesn't work.
Best,
Max

**Comment by BigtoC** [comment]
Consider using [vue-dapp](https://github.com/vu3th/vue-dapp) for now?

**Comment by 0xAsimetriq** [comment]
> I tried to integrate @web3modal/html version but it doesn't work.

Might be able to help if you expand on this i.e. some repor repo or codesanbox

**Comment by MaxVast** [comment]
I managed to integrate the @web3modal/html package with vueJs v3 and with npm, with npm no problem, with yarn I have an problem : "Error: ClientCtrl has no client set", whatever it wasn't easy.
Is there a date set for integration with VueJS like for React ?

**Comment by MaxVast** [comment]
> No set date yet

Okay, thanks for you reply !
Best,

**Comment by scholtz** [comment]
```v1.0 has been sunset. Wallets and Dapps must upgrade to v2.0 before June 28```

I hope it is some kind of joke that v1 will not be supported while vue support for v2 is not there yet.

**Comment by haidarabdillah** [comment]
any update on v2?

**Comment by dataexcess** [comment]
How can I use web3Modal with nuxt 3 ?? there must be some simple example?? using use-wagmi plugin I did not manage to replace the connector with web3modal (as is the case in the react example), also following the html example it is not working... please help

**Comment by 0xAsimetriq** [comment]
@dataexcess just follow html docs https://docs.walletconnect.com/2.0/web/web3modal/html/wagmi/installation

**Comment by dataexcess** [comment]
I tried... I don't see the modal opening...

`<template>
    <div>
        <button
            @click="connect"
        >
            Connect Wallet
        </button>
    </div>
</template>

<script setup>
import { configureChains, createConfig, mainnet, sepolia } from 'use-wagmi'
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/html'

const projectId = process.env.WALLETCONNECT_PROJECT_ID
const chains = [mainnet, sepolia]

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })])
const wagmiConfig = createConfig({
    autoConnect: true,
    connectors: w3mConnectors({ projectId, chains }),
    publicClient
})
const ethereumClient = new EthereumClient(wagmiConfig, chains)
const web3modal = new Web3Modal({ projectId }, ethereumClient)

const connect = () => {
    console.log('did click connect...')
    web3modal.openModal()
}
</script>
`

**Comment by 0xAsimetriq** [comment]
Answer is in the error, your `projectId` is invalid, it's `undefined`

**Comment by dataexcess** [comment]
You are correct. I don't know why my .env var does not work. I have my value in the .env file and declared it in the nuxt.config.ts file in the runtimeConfig -> public object. Then I use useRuntimeConfig().walletConnectProjectId but it is always undefined. 

Anyway hardcoding the project id value made it work! thnx.

**Comment by 0xAsimetriq** [comment]
After a long while 😅 we got vue support coming in next major release of web3modal (3.0.0) no concrete deadline yet, but we are wrapping things up there. There is a vue example on v3 branch https://github.com/WalletConnect/web3modal/tree/V3/examples/vue-wagmi 

I want to ask participants of this issue to have a look at implementation (in essence it's just a simple composable for web3modal, everything else comes from `@wagmi/core` package). Does this look ok to you?

**Comment by haidarabdillah** [comment]
> After a long while 😅 we got vue support coming in next major release of web3modal (3.0.0) no concrete deadline yet, but we are wrapping things up there. There is a vue example on v3 branch https://github.com/WalletConnect/web3modal/tree/V3/examples/vue-wagmi
> 
> I want to ask participants of this issue to have a look at implementation (in essence it's just a simple composable for web3modal, everything else comes from `@wagmi/core` package). Does this look ok to you?

true legend sir thanks a lot

**Comment by ssotomayor** [comment]
> After a long while 😅 we got vue support coming in next major release of web3modal (3.0.0) no concrete deadline yet, but we are wrapping things up there. There is a vue example on v3 branch https://github.com/WalletConnect/web3modal/tree/V3/examples/vue-wagmi
> 
> I want to ask participants of this issue to have a look at implementation (in essence it's just a simple composable for web3modal, everything else comes from `@wagmi/core` package). Does this look ok to you?

On a regular Vue 3 app (not Nuxt) i'm having issues importing them, getting:
```
Missing file extension for "@web3modal/wagmi/vue"
eslint[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/extensions.md)

Unable to resolve path to module '@web3modal/wagmi/vue'.
eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-unresolved.md)
```
![image](https://github.com/WalletConnect/web3modal/assets/1304919/3b42e09f-3a2a-4784-b5ee-5b05a2519eec)

Package Manager: NPM
Node: 16
Typescript: 5.1.6

**Comment by 0xAsimetriq** [comment]
@ssotomayor Looks like your eslint rules are asking to add `.js` at the end of an import.

**Comment by ssotomayor** [comment]
@0xAsimetriq thanks for replying, other imports are not requiring `.js` at the end and are working fine, here is my eslintrc.js:

```javascript
module.exports = {
	root: true,
	env: {
		node: true,
	},
	extends: [
		'plugin:vue/vue3-essential',
		'@vue/airbnb',
		'@vue/typescript/recommended',
	],
	parserOptions: {
		ecmaVersion: 2020,
	},
	rules: {
		'vue/max-len': ['warn', {
			"template": 150,
			"code": 150,
			"ignoreComments": true,
			"ignoreUrls": true,
			"ignoreStrings": true,
			"ignoreTemplateLiterals": true
		}],
		"max-len": [
			'warn',
			{
			  "code": 200,
			  "ignoreComments": true,
			  "ignoreUrls": true,
			  "ignoreStrings": true,
			  "ignoreTemplateLiterals": true
			}
		],
		'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
		'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
		indent: [2, 'tab', { SwitchCase: 1, VariableDeclarator: 1 }],
		'no-tabs': 0,
		'linebreak-style': 0,
		'@typescript-eslint/no-var-requires': 0,
		'class-methods-use-this': 0,
		'no-param-reassign': 0,
		'prefer-const': 'off',
		'import/no-extraneous-dependencies': [
			'warn',
			{
				devDependencies: true,
				optionalDependencies: true,
				peerDependencies: true,
			},
		],
	},
	// https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/Troubleshooting.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
	overrides: [
		{
			files: ['*.ts', '*.vue'],
			rules: {
				'no-undef': 'off',
			},
		},
	],
};
```

**Comment by ssotomayor** [comment]
Ignoring ESLint rules
```
// eslint-disable-next-line import/extensions, import/no-unresolved
import { createWeb3Modal } from '@web3modal/wagmi/vue';
```

Makes the build fail here:
```
 ERROR  Failed to compile with 1 error                                                                                                                                           2:49:58 AM

This dependency was not found:

* @web3modal/wagmi/vue in ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-2!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--1-1!./src/views/MyClub/MyClubInitial.vue?vue&type=script&lang=ts
```

**Comment by 0xAsimetriq** [comment]
All of these issues combined lead me to believe that there can be 2 things at play

1. Library was not installed properly for whatever reason (try to delete node_modules and .lock file and install fresh)
2. Perhaps old version of build tool like webpack / babel is in use, in which case you might need to add some plugins or update to recent versions (we use quiet modern esm bundling + features like optional chaining etc. All of these well supported by browsers for past few years, but not older tools).

**Comment by 0xAsimetriq** [comment]
Closing this issue, vue support is added in v3, currently in alpha, docs are available here https://docs.walletconnect.com/2.0/web3modal/v3/vue/about
