### ISSUE TITLE
2.0.0 Enhancements

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#585]
- [x] Better injected wallet management, add default wallet images and names
until dynamic packages are loaded)
- [x] Add artificial loader while explorer is opening when there is cached data (animation performance improvement)
- [x] Add hover effect for modal header buttons (need to discuss with Maciej)
- [x] Fix edge case and re-generate wallet connect code on cancel / expiry
- [x] ~Create custom jsonrpc providers for unsupported chains if they provide rpc url in config~ this is now handled on wagmi side
- [x] Add more horizontal space to wallet-button label
- [x] Add app details to config so it shows up nicer in wallets
- [x] Correct mobile re-direct handling for chain switching (why does it deep link after first time instead of universal?)
- [x] Check for issues with reconnection on mobile when safari is fully closed (I suspect we should delay rendering of app 
- [x] Look into react hooks / ethereal api implementation, check if they are unsubscribed correctly
- [x] ~Create `getWeb3Provider` helper and `useWeb3Provider` hook (https://github.com/WalletConnect/web3modal/issues/602)~
- [x] Add ethers as peerDependency
- [x] Fix "…" color in explorer screen
- [x] Move wage/core management to ethereal package, expose its options
- [x] Add buffer polyfill by default once we manage @wagmi/core
- [x] Make higher breakpoint for mobile
- [x] Add modal shadows
- [x] More mobile breakpoints (stretch + add spacing latter)
- [x] Dynamic spacing between wallet reel on mobile to ensure there is indication of scroll
- [x] Play with spring animations

**Comment by tussiharel** [comment]
I want to help, what can I do?
