### ISSUE TITLE
Disconnect account (using v2)

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#596]
Hey,

I'm just getting started with using web3modal v2.

I don't see anywhere in the react docs how I can disconnect an account?
Which hook / function should I use?

Thanks in advance!

**Comment by IljaDaderko** [comment]
Apologies for this, I think we missed exposing it in a hook, will be added in next alpha 👍 
Meanwhile you could disconnect via

```ts
import { Web3ModalEthereum } from '@web3modal/ethereum'

Web3ModalEthereum.disconnect()
```

**Comment by jellohouse** [comment]
Ok thanks that works for now!

**Comment by IljaDaderko** [comment]
`useDisconnect` hook was added in alpha.5
https://github.com/WalletConnect/web3modal/tree/V2/packages/react#usedisconnect

Make sure to have another glance at the readme as there are some slight implementation changes.
