### ISSUE TITLE
UI fix - modal sticks out on the right on desktop (V2)

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#601]
Is it normal the modal sort of sticks out on the right side like this?

On mobile it's not a problem as it's properly aligned in the center, but on desktop it sticks out to the right.

<img width="475" alt="Screen Shot 2022-09-22 at 4 48 12 PM" src="https://user-images.githubusercontent.com/35238978/191848828-52fc2d52-1418-4f73-8d2d-0bf8c62a995c.png">

**Comment by IljaDaderko** [comment]
This is intended by our design 😃

**Comment by jellohouse** [comment]
Ohh i see... a bit strange I would say, but ok
