### ISSUE TITLE
bug: useSigner() is always null for Metamask [v2.0.0-alpha.4]

### ISSUE THREAD

**Issue by dirtycajunrice** [WalletConnect/web3modal#604]
**Describe the bug**
When connected - atleast via metamask - useSigner() hook never returns a signer.
This is needed for full adoption as the useContract/useContractRead/etc are only available at the top level of a component, and when you need to make multiple calls to multiple contracts it becomes a serious namespacing conflict. Additionally it would be needed to allow useContract to work.

**SDK Version**
 - Version  2.0.0-alpha.4

**To Reproduce**
```js
const { signer } = useSigner();

useEffect(() =>{
  console.log("Signer value has been modified, causing state change:", signer);
], [signer])
```

**Expected behavior**
I expect it to print null until the signer is populated, then print the signer object. That never occurs.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by IljaDaderko** [comment]
Should be fixed now in alpha.5

**Comment by adamwong246** [comment]
I am still reproducing this.

```
   ?   npm ls @web3modal/react                                  ~/Code/liquidCollectionXChroma master
liquidCollectionXChroma@0.0.1 /Users/adam/Code/liquidCollectionXChroma
└── @web3modal/react@2.0.0-alpha.7


   ?   npm ls @web3modal/ethereum                              ~/Code/liquidCollectionXChroma master !
liquidCollectionXChroma@0.0.1 /Users/adam/Code/liquidCollectionXChroma
├── @web3modal/ethereum@2.0.0-alpha.7
└─┬ @web3modal/react@2.0.0-alpha.7
  └─┬ @web3modal/core@2.0.0-alpha.7
    └── @web3modal/ethereum@2.0.0-alpha.7
    ```
    
    
    ```
    const SignerTest = (props: any) => {
  const signer = useSigner()

  return (<>
    <Web3Modal config={config} />
    <ConnectButton />
    <pre>{JSON.stringify(signer.isLoading)}</pre>
  </>);
};


document.addEventListener("DOMContentLoaded", (event) =>
  ReactDom.render(<SignerTest />, document.getElementById('root')));
  ```
