### ISSUE TITLE
bug: "Ethereum client was not provided" on refresh with Metamask [v2.0.0-alpha.4]

### ISSUE THREAD

**Issue by dirtycajunrice** [WalletConnect/web3modal#605]
**Describe the bug**
When connected via metamask, refreshing a page that has a useContractRead hook seems to never initialize properly. If i navigate to another page within the app, and then navigate back - without refreshing - it works properly. It also works properly if disconnected and then connect while on that page.

Error:
```
Error: Ethereum client was not provided
    at Object.ethereum (main.31b307f8.js:2:1073229)
    at main.31b307f8.js:2:1189120
    at l (main.31b307f8.js:2:1042899)
    at Generator._invoke (main.31b307f8.js:2:1042687)
    at Generator.next (main.31b307f8.js:2:1043328)
    at n (main.31b307f8.js:2:1060809)
    at s (main.31b307f8.js:2:1061012)
    at main.31b307f8.js:2:1061071
    at new Promise (<anonymous>)
    at main.31b307f8.js:2:1060952
```

**SDK Version**
 - Version  2.0.0-alpha.4

**To Reproduce**
```js
  const ids = [0, 1, 2, 3, 4, 5, 6];
  const addresses = Array(ids.length).fill(address);

  const { isLoading, error, read } = useContractRead({
    addressOrName: CUBadges,
    functionName: 'balanceOfBatch',
    contractInterface: ERC1155Artifact.abi,
    args: [addresses, ids],
    chainId: `eip155:43114`,
    overrides: undefined
  })
  
useEffect(() => {
  if (error) {
    console.log("Error:", error);
    return;
  }
  if (isLoading) {
    console.log("isLoading");
    return;
  }

  console.log(read)
}, [isLoading, error, read, address])
  ```

**Expected behavior**
I expect it to not even try to query until i have a connected provider... as there is nowhere for me to set a provider in the hook. A QOL improvement would also be an `enabled: boolean` on all of the chain call hooks to allow conditional call logic. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by IljaDaderko** [comment]
Should be fixed in aplha.5, ty for bearing with us 😅
