### ISSUE TITLE
bug: ENS queried without useFetchENS* hook [v2.0.0-alpha.4]

### ISSUE THREAD

**Issue by dirtycajunrice** [WalletConnect/web3modal#606]
**Describe the bug**
When connected via metamask, ens is being called regardless of whether a useFetchENS* hook is called. This results in many unnecessary errors and causes component reloads as error state is properly watched. 

Error:
```
Error: resolver or addr is not configured for ENS name (argument="name", value="", code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at e.value (main.31b307f8.js:2:26767)
    at e.value (main.31b307f8.js:2:26911)
    at e.value (main.31b307f8.js:2:26990)
    at main.31b307f8.js:2:90600
    at l (main.31b307f8.js:2:1042899)
    at Generator._invoke (main.31b307f8.js:2:1042687)
    at Generator.next (main.31b307f8.js:2:1043328)
    at a (main.31b307f8.js:2:89650)
```

**SDK Version**
 - Version  2.0.0-alpha.4

**To Reproduce**
Simply connect to avalanche

**Expected behavior**
I would suggest that ens is not called unless an ens hook is explicitly used, and as a feature request it would be awesome if a property was added to Chains of `ensResolver?: string` and set on the provider (like ethers.providers.JsonRpcProvider network object) if configured. In most multi-chain based systems (including web3-react) it is effectively impossible to configure custom ens resolvers per chain (which is odd to me as there is only one ethereum... and a significant amount of other chains... XD).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by IljaDaderko** [comment]
Could you please give this a shot on alpha.5 and see if issue is still happening?

**Comment by IljaDaderko** [comment]
A lot of work has been done around this in latest alphas and I can no longer replicate the issue. Will be closing this, but feel free to ping me if you are still running into the error.
