### ISSUE TITLE
Connect Brave wallet opens Metamask (V2)

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#609]
When you are in brave browser and try to connect brave wallet, it automatically prompts to open metamsk.

**To Reproduce**
1. Install Brave browser with Brave Wallet and Metamask installed
2. Open an example of web3modal
3. In web3modal click on Brave wallet to connect
4. It opens Metamask

**Expected behavior**
It should connect with Brave Wallet

**Comment by IljaDaderko** [comment]
Investigated this today and looks like this is a common issue in web3 space i.e. all of these extensions live on `window.ethereum` and if you have metamask installed, usually it is being picked / prioritised over others.

Will need a bit of time to figure this out / see if we can come up with some better ux flows for this case.

**Comment by IljaDaderko** [comment]
We released new design in beta.2 that solves this. There now is just one (but adaptive) slot for injected wallet.
