### ISSUE TITLE
Compilation error - unexpected token in @web3modal/ethereum

### ISSUE THREAD

**Issue by beepsaidblue** [WalletConnect/web3modal#612]
**Describe the bug**
Compilation error after adding `@web3modal/ethereum` and `@web3modal/react` to react app.

```
./node_modules/@web3modal/ethereum/dist/index.js 416:14
Module parse failed: Unexpected token (416:14)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           if (l === "connecting") {
|             const i = await n.getProvider();
>             e?.(i.qrUrl), s();
|           }
|         });
```

**SDK Version**
2.0.0-alpha.4

**Comment by IljaDaderko** [comment]
Looks like this is an issue related to optional chaining i.e that `e?.` bit. Easiest way to resolve this is to upgrade your underlying tooling i.e. if you use create-react-app / nextjs etc. try updating it, as they all should support this.

Other ideas are to add appropriate plugins (i.e. if you are using babel https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining), but again, this is already included in up to date version of babel.

**Comment by IljaDaderko** [comment]
Closing this issue for now, we added readme section about targeting ES2020 and recommend using up to date versions of bundlers.
