### ISSUE TITLE
'Ethereum client was not provided' with custom chain and walletconnect provider

### ISSUE THREAD

**Issue by TimC0de** [WalletConnect/web3modal#620]
**Describe the bug**
I'm encountering problem with connecting to different chain with `Web3ModalProvider` in react.
When I use `useContract` hook I'm getting message `Ethereum client was not provided`

**SDK Version**
 - Version 2.0.0-alpha.4

**To Reproduce**
This is the code

```
const velasTestnetChain: Chain = {
  id: 111,
  name: 'Velas Testnet',
  network: 'velas',
  nativeCurrency: {
    decimals: 18,
    name: 'Velas',
    symbol: 'VLX',
  },
  rpcUrls: {
    default: 'https://evmexplorer.testnet.velas.com/rpc',
  },
  blockExplorers: {
    default: { name: 'EVM Explorer', url: 'https://evmexplorer.testnet.velas.com/' },
  },
  testnet: true,
}

// Configure web3modal
const modalConfig: ConfigOptions = {
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  accentColor: "default",
  ethereum: {
    appName: "web3Modal",
    autoConnect: true,
    chains: [velasTestnetChain],
    providers: [
      providers.walletConnectProvider({
        projectId: process.env.NEXT_PUBLIC_PROJECT_ID
      })
    ]
  }
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Web3ModalProvider config={modalConfig}>
      <Component {...pageProps} />
    </Web3ModalProvider>
  );
}
```

**Expected behavior**
I expect contract creation in order to execute `allowance` and `approve` functions

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 105.0.5195.127

**Comment by IljaDaderko** [comment]
alpha.5 was pushed up yesterday, which re-works the hooks a lot. Could you please give that a shot and see if issue still persists? Also we no longer require wrapping your app in provider, just need to pop `Web3Modal` component somewhere on the page (usually at the end of app root).

New readme reflects all of these changes https://github.com/WalletConnect/web3modal/blob/V2/packages/react/readme.md

**Comment by TimC0de** [comment]
'Ethereum client' issue gone now, but I'm still not able to use custom chains, so the contract instance is not created. I moved from `chainId` in `useAccount` hook, to `data` in `useSwitchNetwork` hook, and this property is undefined always. What may cause this issue?

**Comment by IljaDaderko** [comment]
@TimC0de I think you need to add another provider (rpc) in this case as we don't support "Velas" out of the box. You can reference how we crate walletconnect one here https://github.com/WalletConnect/web3modal/blob/V2/chains/ethereum/src/utils/wagmiTools.ts#L31-L46

And associated wagmi documentation https://wagmi.sh/docs/providers/jsonRpc#configuration

**Comment by TimC0de** [comment]
Okay, with your help I made it possible for ethereum to see my chain, but contract isn't initializing, even thought `contract.json` is valid I get empty contract prototype and therefore am not able to send any requests.


![contract output](https://user-images.githubusercontent.com/33065662/194322331-20447435-dd34-4bcb-acd6-50c54cdea207.PNG)

Maybe you have any ideas on how to fix it?

**Comment by IljaDaderko** [comment]
Nothing comes to mind from the top of my head, perhaps these read and write examples from https://web3modal.pages.dev can help

Read from contract
https://github.com/WalletConnect/web3modal/blob/V2/examples/react/src/sections/UseContractRead.tsx

Write to contract
https://github.com/WalletConnect/web3modal/blob/V2/examples/react/src/sections/UseContractWrite.tsx

**Comment by TimC0de** [comment]
Hi again, I was able to initialize the contract, but when I try to execute request - I receive this response from rpc.walletconnect.com
```
{
    "status": "FAILED",
    "reasons": [
        {
            "field": "chainId",
            "description": "We don't support the chainId you provided: eip155:111"
        }
    ]
}
```

What even is rpc.walletconnect.com? Can I get some documentation about it?
Here is the full CURL request:
```
curl --location --request POST 'https://rpc.walletconnect.com/v1/?chainId=eip155:111&projectId=f9bd5ed1ca15fce6b4013b1959594451' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"eth_call","params":[{"to":"0x7c7449d6d6346b1f5f9f5a362d3508e02b6f0c0b","data":"0xdd62ed3e0000000000000000000000007ba6ca9e159252d7ef7a736896aef1a534637be900000000000000000000000088ba645f6092338271559f7da8c1d603c5ba5261"},"latest"],"id":42,"jsonrpc":"2.0"}'
```

The chain is supported, by the way, because guys, who I contacted, are using `web3-react/walletconnect-connector` and they somehow managed to make it.

Thank you in advance

**Comment by IljaDaderko** [comment]
Rpc and connector are unrelated. Basically rpc is an api that allows you to communicate with a chain. In your case it looks like you are trying to communicate with EtherLite Chain (chainId: 111) which has it's own rpc outlined here https://chainlist.org/chain/111

`rpc.walletconnect.com` is our own rpc service we provide for some chains like ethereum, optimism, polygon, avalanche etc. however we don't support EtherLite one, so you'll have to set up rpc for that separately following examples I mentioned above.

Once that is done, you should be able to make api calls to your contract on that chain 👍 

For now I'll close this as original issue(s) are resolved.
