### ISSUE TITLE
Is `wallet_watchAsset` supported in web3Modal v2 and WC v2 ?

### ISSUE THREAD

**Issue by paouvrard** [WalletConnect/web3modal#623]
MetaMask provides the `wallet_watchAsset` api to add tokens to MetaMask: https://docs.metamask.io/guide/rpc-api.html#wallet-watchasset

Is this api available from web3Modal v2 when connected to MetaMask or through WalletConnect ?
I didn't see it mentioned in the docs.

**Comment by IljaDaderko** [comment]
Not at the moment, but this sounds as an interesting feature to add at some point

**Comment by 0xAsimetriq** [comment]
Closing this one as we are now handling all actions like this through wagmi, so I'd suggest opening / contributing feature request with them.
