### ISSUE TITLE
Localize web3modal with new languages

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#627]
**Is your feature request related to a problem? Please describe.**

Web3modal usage is global, but the modal is english only.

**Describe the solution you'd like**

Add more languages.

**Additional context**

WalletConnect modal supports several languages.

**Comment by callmejm** [comment]
any update on this ?

**Comment by br0wnD3v** [comment]
Just a thought : Can use a translation api to convert ui texts on the fly and present the user with the translated text

**Comment by advanceddev** [comment]
Any updates?

**Comment by Snake-Zeng** [comment]
Any updates?
