### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by AlexL0ng** [WalletConnect/web3modal#628]
**Describe the bug**
when i try run `yarn dev:react` ,there is a moudule parse failed
```
error - ../../chains/ethereum/index.ts
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export type { Chain, ChainProviderFn, Connector, Provider, WebSocketProvider } from '@wagmi/core'
| export { Web3ModalEthereum } from './src/api'
| export { chains, providers } from './src/utils/wagmiTools'
```
**SDK Version**
 - Version [2.0.0-alpha.2]

**To Reproduce**
1. `yarn`
2. `cd example/react`
3. write my projectID in `.env.local.example` and then run `cp .env.local.exmale .env.local`
4. `cd ../../` and run `yarn dev:react`

**Expected behavior**
i hope it's normal working,but there is a error

**Screenshots**
![image](https://user-images.githubusercontent.com/53669064/195340484-e2fff8d4-02cf-4e06-9b07-46031a10aec9.png)

**Comment by chadyj** [comment]
@AlexL0ng Can you please try using [2.0.0-alpha.7](https://github.com/WalletConnect/web3modal/releases/tag/2.0.0-alpha.7)?

**Comment by AlexL0ng** [comment]
> @AlexL0ng Can you please try using [2.0.0-alpha.7](https://github.com/WalletConnect/web3modal/releases/tag/2.0.0-alpha.7)?
oh,sorry!i write write wrong the sdk version.
I make sure my code is the newst.And using the 2.0.0-alpha.7.

**Comment by IljaDaderko** [comment]
@AlexL0ng have you modified anything within the build pipeline? If you have cloned `V2` branch (with latest changes), there should be no trouble in starting react example via these steps

1. `yarn install`
2. `yarn dev`
3. `yarn dev:react` (in a separate terminal tab, so that `yarn dev` runs in the background)

**Comment by IljaDaderko** [comment]
I would also make sure you are using LTS node / yarn v1 version

**Comment by netqom** [comment]
I am getting the same error as @AlexL0ng facing, I am using Node -v 16.13.0 and installed the web3modal V2 version by yarn. I also followed the same step as running yarn dev and yarn dev:react (in a separate terminal) which is giving the same, Module parse failed error.

**Comment by AlexL0ng** [comment]
> I would also make sure you are using LTS node / yarn v1 version

Thanks reply,i done as your step.But the same error was happened.
and i using Node -v 16.7.1
yarn -v 1.22.19

**Comment by IljaDaderko** [comment]
Found the issue, will be fixed in next pr. Meanwhile you guys can replicate these changes locally https://github.com/WalletConnect/web3modal/pull/630/commits/7d8e14ca7c6e8df4ca03c6cf8f6d6863dd459928

I think we had this invalid type re-export cached somehow on our dev machines.

**Comment by netqom** [comment]
Hi @IljaDaderko , Thanks for the answer. I am getting the same error after the changes to the files. It is not working after making changes as described in "fix invalid type export".

**Comment by IljaDaderko** [comment]
@netqom @AlexL0ng Looked deeper into this today and I believe pr I mentioned above is the appropriate fix. Could you guys please confirm? (remember to pull fresh from the rep and run `yarn` to install extra packages)

**Comment by IljaDaderko** [comment]
also cc @Crytogenz
