### ISSUE TITLE
useDisconnect hook not working

### ISSUE THREAD

**Issue by adamlevoy** [WalletConnect/web3modal#631]
**Describe the bug**
useDisconnect hook resulting in the following error when called:

<img width="585" alt="Screen Shot 2022-10-15 at 11 36 38 AM" src="https://user-images.githubusercontent.com/81095429/196003440-e6671724-b270-4a18-a891-f8adf3685392.png">

Other hooks like useConnectModal, useAccount, and useBalance working fine.

All implemented following the react examples with Next.js, sans TypeScript.

***index.js***
```
import {
  useConnectModal,
  useAccount,
  useBalance,
  useDisconnect,
} from "@web3modal/react";

export default function Home() {
  const { isOpen, open, close } = useConnectModal();
  const { address, isConnected } = useAccount();
  const disconnect = useDisconnect();
  const { data, error, isLoading, refetch } = useBalance({
    addressOrName: address,
    formatUnits: "ether",
  });

  return (
    <div>
      {!isConnected ? (
        <button onClick={open}>Connect</button>
      ) : (
        <button onClick={disconnect}>Disconnect</button>
      )}
      <p>
        Connected: <span>{isConnected ? "Yes" : "No"}</span>
      </p>
      {address && <p>{address}</p>}
      {data && <p>{`${data.symbol}: ${data.formatted}`}</p>}
    </div>
  );
}
```

***_app.js***
```
import { chains, providers } from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";

const config = {
  projectId: "process.env.NEXT_PUBLIC_PROJECT_ID",
  theme: "dark",
  accentColor: "default",
  ethereum: {
    appName: "web3Modal",
    autoConnect: false,
    chains: [chains.mainnet],
    providers: [
      providers.walletConnectProvider({
        projectId: "process.env.NEXT_PUBLIC_PROJECT_ID",
      }),
    ],
  },
};

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Component {...pageProps} />
      <Web3Modal config={config} />
    </>
  );
}
```

**SDK Version**
 - Version ^2.0.0-alpha.7

**To Reproduce**
1. Call disconnect hook via onClick event
2. Open console
3. See error

**Expected behavior**
Account to disconnect from network.

**Desktop (please complete the following information):**
- macOS v12.6
 - Chrome v106.0.5249.119 (Official Build) (arm64)

**Comment by IljaDaderko** [comment]
Will look into this, it has to be something to do with combination of hooks used together I think, ty for reporting this 👍

**Comment by crackcodesprogramloads** [comment]
I ran into an issue with useDisconnect but did not receive a console error.

**How to reproduce this bug:** 
1. Click Connect button
2. Connect to MetaMask
3. Click Disconnect and trigger `disconnect()`
4. "Connected sites" in MetaMask still shows connected to localhost
5.  Click Connect again it let me connect to MetaMask which should not be the expected behaviour

App.js
```
import { useConnectModal, useAccount, useDisconnect } from "@web3modal/react"

export default function ConnectWallet() {
    const { isConnected } = useAccount()
    const disconnect = useDisconnect()

    const { open } = useConnectModal()

    return (
        <button onClick={() => (!isConnected ? open() : disconnect())}>
            {!isConnected ? "Connect" : "Disconnect"}
        </button>
    )
}
```
package.json
```
 "dependencies": {
        "@chakra-ui/react": "^2.3.6",
        "@emotion/react": "^11",
        "@emotion/styled": "^11",
        "@testing-library/jest-dom": "^5.14.1",
        "@testing-library/react": "^13.0.0",
        "@testing-library/user-event": "^13.2.1",
        "@web3modal/ethereum": "^2.0.0-alpha.7",
        "@web3modal/react": "^2.0.0-alpha.7",
        "ethers": "^5.7.1",
        "framer-motion": "^6",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.4.2",
        "react-scripts": "5.0.1",
        "web-vitals": "^2.1.0",
        "web3": "^1.8.0"
    },
    "devDependencies": {
        "@types/jest": "^29.1.2",
        "@types/node": "^18.11.0",
        "@types/react": "^18.0.21",
        "@types/react-dom": "^18.0.6",
        "autoprefixer": "^10.4.12",
        "ether": "^0.0.9",
        "hardhat": "^2.12.0",
        "postcss": "^8.4.18",
        "solhint": "^3.3.7",
        "tailwindcss": "^3.1.8",
        "typescript": "^4.8.4"
    }
```

**Comment by IljaDaderko** [comment]
@crackcodesprogramloads You are disconnected on the website but metamask is still in connected state correct?

If so, it is expected behaviour. I think the only way to disconnect from metamask is to do it explicitly there (although dapp will be disconnected anyway and can't do anything). This is how ethers behaves and I also tested to see what happens from other projects similar to web3modal, looks like it behaves same there as well.

**Comment by adamlevoy** [comment]
Hey @IljaDaderko thanks for circling back. Working great on my end, able to connect and disconnect with no issues now.

**Comment by crackcodesprogramloads** [comment]
> @adamlevoy 
Thanks! Using Alpha 8 fixed the issue for me. It now allows me to connect after clicking disconnect while on Alpha 7 it would say I'm still connected

**Comment by adityapandey9** [comment]
@0xAsimetriq Hi, While adding Metamask in the connectors, please try to add custom configurations for each connector. I found this is the issue: 

```
    new MetaMaskConnector({
      chains,
      options: {
        UNSTABLE_shimOnConnectSelectAccount: true,
      },
    })
```

We need to add `UNSTABLE_shimOnConnectSelectAccount: true` as an option for the MetaMaskConnector. Then we can use this. Let me know if it is possible. :)

**Comment by 0xAsimetriq** [comment]
@adityapandey9 Thank you for the update, we actually changed everything up in a way where users can now provide their own wagmi configuration, including connectors (we only require WalletConnectConnector to be present in that case).

Our default connector selection only uses `InjectedConnector` and its available shims.
