### ISSUE TITLE
 walletconnect provider not working on HECO-TEST      No chainId found match HECO-TEST

### ISSUE THREAD

**Issue by EternalShallow** [WalletConnect/web3modal#632]
it's a vue project

i see web3modal/dist/index.js  has a "CHAIN_DATA_LIST",  

If it is not on the chain where this variable changes, an error will be reported
 such as: No chainId found match HECO-TEST
![image](https://user-images.githubusercontent.com/20839720/196079893-e3b068bc-07db-4c74-b090-3398c49be480.png)

I didn't find custom "CHAIN_DATA_LIST" configuration item

**Comment by IljaDaderko** [comment]
Some examples of custom evm chains can be found here https://github.com/WalletConnect/web3modal/blob/V2/chains/ethereum/src/utils/chains.ts

You can create similar config object and pass it to your config's `ethereum.chains` filed. Keep in mind, you will also need to add custom rpc that supports this chain.

**Comment by mspaansen** [comment]
#Mspaansen

Op ma 17 okt. 2022 19:01 schreef Ilja ***@***.***>:
