### ISSUE TITLE
Cannot connect on mobile with new alpha web3modal

### ISSUE THREAD

**Issue by Miktua** [WalletConnect/web3modal#633]
Hi, have a problem with connecting on android mobile phone through web3modal and wallet connect to metamask, 
Desctop version works great, walletconnect with QR code also
Open modal -> touch metamask icon -> throwing error TypeError: Cannot read properties of undefined (reading: importKey)
here are screenshots

![photo_2022-10-17_19-17-21](https://user-images.githubusercontent.com/103890631/196218148-c113dea8-eba1-4104-9af7-dc1ef9b0a273.jpg)
![photo_2022-10-17_19-17-22](https://user-images.githubusercontent.com/103890631/196218154-6ca1a507-1c87-4912-b3b3-a56458ed39c7.jpg)
![photo_2022-10-17_19-17-22 (2)](https://user-images.githubusercontent.com/103890631/196218159-217bd251-7534-44dd-b825-414d30f4336b.jpg)

**Comment by IljaDaderko** [comment]
Could you please add your os / browser details.

**Comment by Miktua** [comment]
> 

Android 11
MIUI 12.5.3
Chrome 106.0.5249.118

**Comment by Miktua** [comment]
Found that this problem only appears when running my app at localhost, and debugging it on the phone through wifi.
tried to install v1, and got there same problem 

Build my app on vercel - and there problem problem is gone.
but have a new problem - after pushing wallet icon - wallet app opens, and there is nothing inside, any connection messages

**Comment by IljaDaderko** [comment]
@Miktua could you link me / give name of the wallet that you are testing against that doesn't show connection message? I personally tested with rainbow / omni / metamask / trust and few others, and everything was working as expected.

**Comment by IljaDaderko** [comment]
Closing this as stale, however we made a lot of improvements in recent releases, make sure to check them out 👍
