### ISSUE TITLE
useContractRead with args from other hooks (useState)

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#640]
Trying to `useContractRead` that has as an arg the `address` from `useAccount` like this:

```javascript
    const { address, isConnected } = useAccount();
    
    const userContractBalance = useContractRead({
       addressOrName: process.env.NEXT_PUBLIC_MY_CONTRACT_ADDRESS,
       contractInterface: myABI,
       functionName: 'balances',
       args: [address]
    });
    
    console.log('userContractBalance is', address, userContractBalance.data);
```

However I notice that sometimes when I switch pages in my app and go back to this,
the `userContractBalance.data` is undefined even though the `address` is defined... 
Sometimes it works sometimes not...

I then even tried adding this lower in my code:

```javascript
  useEffect(() => {
     if (address) userContractBalance.refetch();
  }, [address])
```

But it did not help. Not sure what the problem is. Any tips would be greatly appreciated.

**Comment by IljaDaderko** [comment]
I think that when you switch pages, `useContractRead` starts re-fetching data, thus it will be undefined initially until it is resolved. Hook has `enabled` param to bypass fetching data on render, you could utilise that alongside some sort of cache.

**Comment by jellohouse** [comment]
I understand that when I switch pages, it will be undefined initially until the it is resolved.
But why does sometimes it does not resolve at all?

I do a console log of the address I'm inputting as `arg` to `useContractRead` and the object returned from useContractRead like this:
```javascript
console.log('userContractBalance is', address, userContractBalance);
```

And in my console log I see:
```
userContractBalance is 0xA490DBDF2E3211fDXXXXXXXXXXXXXXX // valid address that user connected with
{
    "data": undefined,
    "isLoading": false,
    "error": {
        "reason": "resolver or addr is not configured for ENS name",
        "code": "INVALID_ARGUMENT",
        "argument": "name",
        "value": ""
    }
}
```

The address is clearly defined in the log, but the useContractRead gives error that:
"resolver or addr is not configured for ENS name"

So it's like it's using the wrong address or something.

**Comment by IljaDaderko** [comment]
@jellohouse could you please try with `alpha.8`. If issue still persists, any chance you could provide small repo that replicates this issue for me to dig in?

I tried to replicate this with contract address from `useState` that was changing via `setInterval`, but everything seemed to work as expected.

**Comment by jellohouse** [comment]
yeah I think this was an issue with my code and useEffects... consider it resolved.
