### ISSUE TITLE
useContractWrite estimates gas price

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#641]
In the react docs here: https://github.com/WalletConnect/web3modal/tree/V2/packages/react#usecontractwrite-example

it says `useContractWrite` can estimate the gas price...

But how? Where is the gas price estimate?

I thought it would maybe be in the `data` parameter but it isn't.

**Comment by IljaDaderko** [comment]
It combines these 2 hooks from wagmi

https://wagmi.sh/docs/prepare-hooks/usePrepareContractWrite
https://wagmi.sh/docs/hooks/useContractWrite

implementation is here

https://github.com/WalletConnect/web3modal/blob/V2/packages/core/src/controllers/stateless/ContractCtrl.ts#L23-L28

I don't think it actually exposes that info. There is more about the topic here https://wagmi.sh/docs/prepare-hooks/intro

**Comment by IljaDaderko** [comment]
We've dropped hooks in latest release and are now fully compatible with wagmi, so you can use their hooks (which have this functionality separated) 👍 See updated docs https://docs.walletconnect.com/2.0/introduction/web3modal/about
