### ISSUE TITLE
Cannot sign messages v2.0.0-alpha.8 

### ISSUE THREAD

**Issue by bshyong** [WalletConnect/web3modal#654]
**Describe the bug**

I am trying to sign a message as follows. The message is constructed with a nonce fetched from API, so I cannot use the signMessage hook. However, I am unable to sign and receive this error:

```
index.js:289 Uncaught (in promise) Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":42,\"error\":{\"code\":-32601,\"message\":\"The method personal_sign does not exist/is not available\"}}", error={"code":-32601}, requestBody="{\"method\":\"personal_sign\",\"params\":[\"0x416c6c2074683238383238323832323132\",\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\"],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.walletconnect.com/v1/?chainId=eip155:1&projectId=ad4b621ec25179121f07c6d0cd5c7a60", code=SERVER_ERROR, version=web/5.7.1)
```

**SDK Version**
  @web3modal/react:  2.0.0-alpha.8

**To Reproduce**
```
  const { account, isReady } = useAccount()
  const { provider } = useProvider()
  const signer = provider.getSigner(account.address)
  signer.signMessage("message")
```

**Expected behavior**
Successful signature

**Comment by IljaDaderko** [comment]
Ty for bringing this up, looks like something is erroring on our rpc level related to `personal_sign`. I will propagate this to our infra team 👍 Meanwhile, any chance you could configure this with public or your own custom rpc and check if you are still getting that error? 

Also, could you explain why exactly you are not able to use `signMessage` hook, perhaps I could adopt it to account for workflows that include nonce.

**Comment by bshyong** [comment]
Thanks for the update - I got it to work successfully with the hook by passing in the constructed message. I was confused with the example but I figured out we can pass the message directly into `signMessage()` instead of setting it initially with `useSignMessage` 

#### Example
```
const { data, error, isLoading, signMessage } = useSignMessage({
  message: 'WalletConnect web3modal message'
})
signMessage()
```

#### Implementation (this works)
```
  const { data, error, isLoading, signMessage } = useSignMessage()

async function handleSignIn() {
    // user object is usually fetched from API
    const user = {
      "nonce": 49383131388212,
      "id": 1,
      "public_address": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "email": null,
      "created_at": "2022-10-25T22:27:27.682Z",
      "updated_at": "2022-10-25T22:27:29.185Z"
    }

  const message = `Login code: ${user.nonce}`

  try {

    const signature = await signMessage({ message })

    // validate signed message with nonce on backend
    const response = await fetch(`/api/users/signin?public_address=${account.address}&signature=${signature}`, {
      method: 'post'
    })
    const apiResponse = await response.json()
    setSignedIn(apiResponse.authenticated)
  } catch (e) {
    console.log('Wallet login canceled - please try again')
    console.error(e)
  }
}
```


I also tested by  using @web3modal/core directly and was able to sign:
```
import { SignerCtrl } from '@web3modal/core'

  async function handleSignIn() {
    const signer = await SignerCtrl.fetch({ chainId: 1 })
    const message = `Login code: ${user.nonce.toString()}`
    const signature = await signer.signMessage(message)
  }
```

**Comment by IljaDaderko** [comment]
Awesome! I'll see if we can improve docs / examples to make this more clear. Hook tries to account for 2 use cases

1. Message is known initially
2. Message is constructed later (your use case)
