### ISSUE TITLE
useWaitForTransaction seems not to work

### ISSUE THREAD

**Issue by asimaranov** [WalletConnect/web3modal#660]
**Describe the bug**
I'm trying to wait for approve transaction ends. So I use `useWaitForTransaction` hook as follows: 

```ts
  const { data, error, isLoading, write } = useContractWrite({
    address: '0x4B0e8DAfd97679a1e393330F2B112160a97Cee73',
    abi: ERC20_ABI,
    functionName: 'approve',
    args: [account.address, 1],
    chainId: 421613,
  });

  console.log("data:", data, "\nerror:", error, "\nisLoading:", isLoading);

  const waitForTransaction = useWaitForTransaction({
    hash: data?.hash,
    chainId: 421613,
  })

  console.log("waitForTransaction", waitForTransaction)
```

Result in browser:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/25568730/198751749-1a25e33a-345a-4704-b0d3-241fdb527f2a.png">

So `waitForTransaction` seems not to get the receipt after transaction successfully executed.

**SDK Version**

    "@web3modal/ethereum": "^2.0.0-beta.1",
    "@web3modal/react": "^2.0.0-beta.1",

**Comment by IljaDaderko** [comment]
@asimaranov thank you for reporting this, I'll dig into it on Monday. At the moment nothing comes up to mind, I have this example using send transaction set up https://github.com/WalletConnect/web3modal/blob/V2/examples/react/src/sections/UseSendTransaction.tsx

That works, so I wonder if this is specific to a contract hook 🤔

**Comment by asimaranov** [comment]
The problem was that I haven't specified rpc url in config in rpcUrls
