### ISSUE TITLE
Unable to pass signer in useContract.signerOrProvider hook options

### ISSUE THREAD

**Issue by crackcodesprogramloads** [WalletConnect/web3modal#661]
**Describe the bug**
When I passed the signer data returned from useSigner hook in useContract.signerOrProvider hook, it threw this error: `Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'd'
    |     property '_readableState' -> object with constructor 'b'
    |     property 'pipes' -> object with constructor 'i'
    |     property '_readableState' -> object with constructor 'b'
    --- property 'pipes' closes the circle`

**SDK Version**
 - Version [2.0.0-alpha.2]

**To Reproduce**
```
    const { data: signer } = useSigner({ chainId: 5 })
    const { contract, isReady: isContractReady } = useContract({
        address: process.env.REACT_APP_PUBLIC_DEPLOYED_CONTRACT_ADDRESS,
        abi: Waitlist.abi,
        signerOrProvider: signer
    })
```

**Expected behavior**
Will let me pass signer to useContract

**Screenshots**
<img width="986" alt="Screen Shot 2022-10-29 at 12 54 36 pm" src="https://user-images.githubusercontent.com/59869248/198763316-67c982a2-44b1-45dc-ad48-16b7d758f3ce.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: Chrome 
 - Version: 105.0.5195.125 (Official Build) (arm64)

**Comment by b4rtt** [comment]
I have same problem here

`import { useAccount, useContractRead } from "@web3modal/react";

import USDC from "./ABI/USDC.json";
import { chains } from "@web3modal/ethereum";

function Approve() {
  const { account } = useAccount();

  const config = {
    address: "xxx",
    abi: USDC,
    functionName: "allowance",
    chainId: chains.polygonMumbai.id,
    args: [account, "xxx"],
  };

  const { data, error, isLoading, refetch } = useContractRead(config);

  return (
    <div className="Approve">
      {account.isConnected && (
        <>
          <ul>
            <li>
              Contract read config: <span>{JSON.stringify(config)}</span>
            </li>
            <li>
              Returned data:{" "}
              <span>{isLoading ? "Loading..." : JSON.stringify(data)}</span>
            </li>
            <li>
              Error: <span>{error ? error.message : "No Error"}</span>
            </li>
          </ul>
          <button onClick={async () => refetch()}>Refetch data</button>
        </>
      )}
    </div>
  );
}

export default Approve;
`

**Comment by IljaDaderko** [comment]
@crackcodesprogramloads just doeuble checking, are you actually on `alpha.2` (stated in issue) or on latest release `beta.1`?

Also, few ideas that come to mind:

1. Set same chain id on contract hook
2. By default contract hook will already use that signer, so why are you passing it there (I believe `signerOrProvider` should be optional, if it's not, let me know as this would be a bug)

I will dig deeper into this next week as well 👍

**Comment by IljaDaderko** [comment]
@b4rtt what's your exact problem? Code snippet you provided is not using `signer` at all, so perhaps your issue is something else? Feel free to open another issue here on GitHub with more details, I'll look into it.

**Comment by crackcodesprogramloads** [comment]
@IljaDaderko Sorry just checked and am using beta.1. 

1. Set same chainId and the same error occurred
2. The reason for passing there is because when I try to send a write transaction it says a signer is required

![Screen Shot 2022-10-30 at 10 36 45 am](https://user-images.githubusercontent.com/59869248/198856320-2c1837bb-638c-40ba-8585-cd5acfd7cdd2.png)

As you can see below signer and provider is null

![Screen Shot 2022-10-30 at 10 33 37 am](https://user-images.githubusercontent.com/59869248/198856323-a6006682-a324-4cb8-8843-9046ef557d4a.png)

Here is the config(not sure if that's relevant)

![Screen Shot 2022-10-30 at 10 39 32 am](https://user-images.githubusercontent.com/59869248/198856373-3c07dc97-85a6-4ca8-a8a1-b21b69279e7c.png)

Thanks for your help 🙏

**Comment by IljaDaderko** [comment]
There were some substantial changes in beta.4, please see new docs that moved to https://docs.walletconnect.com/2.0/introduction/web3modal/about

We are no longer exposing our own hooks and instead moved to fully support [Wagmi](https://wagmi.sh/) for much better and reliable dev experience.

Thus you should now be able to do this 👍
