### ISSUE TITLE
Fetch request error on first initialization

### ISSUE THREAD

**Issue by erm-am** [WalletConnect/web3modal#662]
**Describe the bug**
When the application is initialized, there is a request for https://explorer-api.walletconnect.com/v3/wallets?projectId=&page=1&entries=10&version=1 and an error occurs. (the projectId parameter is lost)

**SDK Version**
     "@web3modal/core": "^2.0.0-beta.1",
    "@web3modal/ethereum": "^2.0.0-beta.1",
    "@web3modal/react": "^2.0.0-beta.1",
    "@web3modal/ui": "^2.0.0-beta.1",

**To Reproduce**
https://github.com/WalletConnect/web3modal/tree/V2/examples/html
https://codesandbox.io/s/magical-silence-gndjtl?file=/src/index.js

**Screenshots**
<img width="807" alt="image" src="https://user-images.githubusercontent.com/16826727/198828480-c0929f22-5f49-4267-b3d0-ac2f8be71206.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/16826727/198828529-bf098efc-5a00-438a-a633-650b2132720e.png">

**Comment by IljaDaderko** [comment]
@erm-am was able to reproduce, will investigate, ty for the issue 👍

**Comment by saintmaxi** [comment]
just to piggyback, i see the same issue (using vanilla js implementation myself)

**Comment by IljaDaderko** [comment]
Found the root cause, this issue will be solved in next (`beta.2`) release

**Comment by IljaDaderko** [comment]
Beta.2 was released 👍 with fixes for this
