### ISSUE TITLE
useContractRead - TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by jellohouse** [WalletConnect/web3modal#668]
I just upgraded from:
```
    "@web3modal/ethereum": "^2.0.0-alpha.7",
    "@web3modal/react": "^2.0.0-alpha.7",
```
to:
```
    "@web3modal/ethereum": "^2.0.0-beta.1",
    "@web3modal/react": "^2.0.0-beta.1",
```

Both cases using the latest ethers: `"ethers": "^5.7.2",`

Now nothing changed in the code, I have something like:
```javascript
const info = useContractRead({
    addressOrName: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS,
    contractInterface: myABI,
    functionName: 'totalUsers',
});
```

And now the data does not load and in `info.error` I get:
"Uncaught TypeError: Cannot read properties of undefined (reading 'map')"

**Comment by IljaDaderko** [comment]
Api for this hook was updated to match underlying wagmi changes - https://github.com/WalletConnect/web3modal/blob/V2/docs/react.md#usecontractread-example

In the future we will also support their typescript autocomplete for contracts based on their abi json, stay tuned 😉
