### ISSUE TITLE
Convenient function to get a provider for web3js use

### ISSUE THREAD

**Issue by davidchingmy** [WalletConnect/web3modal#670]
**Is your feature request related to a problem? Please describe.**
Existing dapp already uses web3js v1.6 + web3modal v1. Currently, web3modal v2 seems to use ethersjs exclusively. Thus, there is no compatible provider for web3js. [ContractCtrl](https://github.com/WalletConnect/web3modal/blob/V2/docs/html.md#contractctrl) also will requires rewrite part of existing dapp especially for contract interaction.

**Describe the solution you'd like**
Provide a way to get provider for web3js use.

**Describe alternatives you've considered**

1. Tried to use `getConnectorById` (`new Web3(ClientCtrl.state.ethereum.getConnectorById('injected'))`) but getting `Error: Provider does not have a request or send method to use.` upon contract interaction.
2. Tried to use `new Web3(ProviderCtrl.get({}).connection.url)` but getting `Returned error: unknown account` upon write contract call.

**Additional context**
N/A

**Comment by IljaDaderko** [comment]
Hey @davidchingmy 

I'm not sure when we'll have time to realistically look into full web3js support, as we are using wagmi a lot under the hood for evm chains, but that said, next version of web3modal introduces concept of "standalone" mode.

We will enable you to use it with our sign v1/v2 sdk's which also have their own providers that you can pass to web3js. So you will be able to leverage ui part of web3modal and just continue using your current codebase as it is.

Example of this is in draft pr here https://github.com/WalletConnect/web3modal/blob/0d8272e1a60a54e5357eb9d77bfc3b57bac92dd2/examples/react-standalone/src/pages/index.tsx

And providers are
https://www.npmjs.com/package/@walletconnect/ethereum-provider for v1
https://www.npmjs.com/package/@walletconnect/universal-provider for v2

More docs and examples will follow on this as well

**Comment by IljaDaderko** [comment]
@davidchingmy beta.2 released with support for standalone modal (i.e. no wagmi / ethersjs), you just use it with walletconnect provider

Example of how to do it with v2 sign sdk is here
https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone/src/pages/index.tsx

Pretty much same principles apply to v1 (you just need to open modal with wcUri and close it after connection manually)
