### ISSUE TITLE
Local Development: TS Loader Issues

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/web3modal#671]
**Describe the bug**
On different machines when you try to do a localhost `yarn dev` + `yarn dev:react` for the sample app, a babeLoader issue occurs. Might be a TS issue. 

This behaviour occurs on some machines / not. Sometimes solved with a `node_modules` + `yarn.lock` remove + cleaning cache. Other times not. 

**SDK Version**
 - Version [^2.0.0-alpha.2]

**To Reproduce**
1. Go to 'V2' branch
2. `yarn install`
3. `yarn dev`
4. `yarn dev react`

**Expected behavior**
No errors on the initial dev loading. 

**Screenshots**

Run into errors such as this:
```You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export type { ConfigOptions } from '@web3modal/core'```

**Comment by akinncar** [comment]
what is the solution?
