### ISSUE TITLE
Errors on Vanilla (Beta.2)

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#677]
**Describe the bug**
There is a clear improvement on beta 2 compared to beta 1, however, we still have some errors: 
- see image (use switchNetwork + querySelector (UIHelpers.js))
- sometimes on Event "**NetworkCtrl.watch((network)...**" -> chain name = 'Chain1' instead of 'Ethereum' 

**FYI:**  We reused the component <w3-modal/> several times  (no reallocation)

So, another question: 
LOBSTR (Stellar) is compatible WalletConnect v2, but why is it not in your list of wallets?

**Envirionement Dev**
- Vue + Nuxt v2
- Use Web3Modal + Vanilla

**SDK Version**
 - Version [2.0.0-beta.2]

**To Reproduce**
```
  <template>
    <div>
      <w3m-modal />
    </div>
  </template>


 import {
  AccountCtrl,
  BalanceCtrl,
  ClientCtrl,
  ConfigCtrl,
  ModalCtrl,
  NetworkCtrl,
  TransactionCtrl
 } from '@web3modal/core'
 import { chains, providers } from '@web3modal/ethereum'
 import '@web3modal/ui'
  ...
  data: { 
    clientConfig: {
          projectId: PROJECT_ID,
          theme: 'dark',
          accentColor: 'green'
     }
    ethereumConfig: {
          appName: 'O21Pay',
          autoConnect: true,
          chains: [],
          providers: []
    },
   watchAccount: undefined,
  }
  
  async connect(chainId) {
      chainId = parseInt(chainId)

      if (chainId === 1) {
        this.ethereumConfig.chains = [chains.mainnet]
      } else if (chainId === 97) {
        this.ethereumConfig.chains = [chains.binanceSmartChainTestnet]
      } else {
        return
      }

      await ConfigCtrl.setConfig(this.clientConfig)
      await ClientCtrl.setEthereumClient(this.ethereumConfig)

      if (this.watchAccount) {
        this.watchAccount()
        this.watchAccount = undefined
      }
      // We force the network switch, because on the beta.1, "ClientCtrl.setEthereumClient(this.ethereumConfig)" was not 
      //   enough -> see chains
      NetworkCtrl.switchNetwork({ chainId })

      this.watchAccount = AccountCtrl.watch(async (account) => {
        console.log('******* Account ')
      })

      const account = AccountCtrl.get()
      if (account.isConnected === false) {
        ModalCtrl.open()
     }
  } 
```

**Expected behavior**
During the call of the method '**connect()**', we have systematically these 2 errors which are displayed...

**Screenshots**
(https://gist.github.com/Droppix/c6411d4c75ee42d89fc74f4fd85a6921)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [22]

Thanks

**Comment by IljaDaderko** [comment]
Ty for report @Droppix will look into this 👍 Judging by the error and broken qrcode, looks like walletconnect connector was not initialised. Any chance you have full repo where I could reproduce this?

Few initial ideas here would be to check for `initialized` state before doing actions on controllers like Account or Network. You can either subscribe to it as per html example https://github.com/WalletConnect/web3modal/blob/V2/examples/html/src/events.js#L8 or just get it from `ClientCtrl.state.initialized` and check it before other actions.

And of course more improvements to vanilla flow and docs around it will soon start rolling out.

**Comment by Droppix** [comment]
@IljaDaderko 
I prepared a skeleton, which reproduces the error... and I sent you an invitation on my repo...
So, LOBSTR (Stellar) is compatible WalletConnect v2, but why is it not in your list of wallets?

Thanks

**Comment by IljaDaderko** [comment]
<img width="370" alt="Screenshot 2022-11-05 at 18 55 19" src="https://user-images.githubusercontent.com/3154053/200131947-f01d2ea9-b883-4c5a-940f-e47caaf211dd.png">

It is when users are on mobile (for deep linking), otherwise we show desktop ones (or qr code scan for desktop/mobile flow)

**Comment by Droppix** [comment]
No found:
<img width="421" alt="Capture d’écran 2022-11-05 à 17 58 48" src="https://user-images.githubusercontent.com/8955379/200132073-f4290539-a286-4d06-83e9-7a7a10d763f6.png">

**Comment by Droppix** [comment]
Ok! Thanks

**Comment by Droppix** [comment]
One more question about LOBSTR (Stellar)
If I look at the list of chains in '@web3modal/ethereum'" we can see :

```
export declare const chains: {
    avalanche: import("@wagmi/core").chain;
    fantom: import("@wagmi/core").Chain;
    binanceSmartChain: import("@wagmi/core").Chain;
    binanceSmartChainTestnet: import("@wagmi/core").Chain;
    ...
}```
Which "chainid" should be used?

Thanks

**Comment by IljaDaderko** [comment]
@Droppix stellar is not evm compatible correct? Thus you can't use ethereum package / react hooks at the moment.
To use web3modal with stellar you will have to use it in "standalone" mode. This means that you have to use our sign sdk (that supports all chains) and pass connection uri to the modal manually. This will be documented soon, but for now there is a standalone example of how to acheive this here:

https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone/src/pages/index.tsx

This is definitely a more complex use case, so you need to have good grasp about how stellar works and how our plain sign v2 sdk works. If you have further questions about this, our Discord should be good or feel free to start discussion here on GitHub under our organisation and @ me 👍

**Comment by IljaDaderko** [comment]
As I am unfamiliar with stellar I can only provide general overview with some placeholders, but essentially you need to keep this in mind

1. `eip155` is namespace for evm compatible chains
2. `1` is a chainId on evm compatible chains
3. `eip155:1` is a [CAIP-10](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md) compatible chainId that our sign sdk uses

Thus for stellar you need to find these bits and construct your namespaces accordingly i.e. maybe it could be something like

```
const namespaces = {
  stellar: {
    methods: ['???'],
    chains: ['xyz'],
    events: ['???']
  }
}
```

Method names and events will also depend on what that chain uses i.e. in `eip155` context, they could be `eth_sign` (a method name defined by ethereum rpc)

**Comment by IljaDaderko** [comment]
We have dapp and wallet examples available that go hardcore on this "multichain" usage of sign v2 sdk (sign v1 sdk only supports ethereum evm chains). You can look at them as well

https://react-app.walletconnect.com/
https://react-wallet.walletconnect.com/

**Comment by Droppix** [comment]
Ok, I understand, the problem is that Stellar is not very communicative, so finding information about the chain used and the methods is difficult, but we will continue to investigate...

Thanks for the new links, we used the old version v2 beta to find the right connection with LOBSTR

**Comment by IljaDaderko** [comment]
For lobster to appear in results they need to add all compatible chains to their entry on https://cloud.walletconnect.com (standalone modal only requests wallets for chains that were provided)

**Comment by Droppix** [comment]
Yes, thanks, it was already done (on obvious21.com)

**Comment by Droppix** [comment]
I found some information by looking at the StellarX and WalletConnect connection, the information used is :

const stellar = {
  chains: ['stellar:pubnet'],
  methods: ['stellar_signAndSubmitXDR'],
  events: []
}

So I tried to do a test on what you told me, the "standalone" mode, and I did a quick test to see what was going on, 

```
// PROJECT_ID is declared on cloud.walletconnect.com
signClient = await SignClient.init({ projectId: PROJECT_ID })
...
await ConfigCtrl.setConfig(this.clientConfig)
const namespaces = {
  stellar
}
const { uri, approval } = await signClient.connect({ requiredNamespaces: namespaces })
// my uri is 
// wc:23afeed01204c3a82f53ea569bb74113d958ced21869f5de8ce55c1d3fb3506c@2?relay-protocol=irn&symKey=b29f482cd0422fb7591c8bb9953fb28048c15b718d2b7f2382773f744b2e90fe

ModalCtrl.open({ uri, standaloneChains: namespaces.stellar.chains })
      await approval()
      ModalCtrl.close()
```

Web3Modal display,but the QR code seems wrong?
and LOBSTR display "Invalid QR Code"...
<img width="1606" alt="Capture d’écran 2022-11-08 à 13 54 02" src="https://user-images.githubusercontent.com/8955379/200571892-26e552d0-d26e-4afa-a308-15e4e86e7e66.png">

**Comment by IljaDaderko** [comment]
```
ModalCtrl.open({ uri, standaloneChains: namespaces.stellar.chains })
```

this is only available on `beta.3`, any chance you are still on previous version? Also for better ux, you can define `standaloneChains` inside your `this.clientConfig`. One in ModaCtrl should only be used if you don't know your chains beforehand (i.e. if users need to make selection first)

**Comment by Droppix** [comment]
:) I have the beta 2, I will try to do some tests!

**Comment by Droppix** [comment]
I try this, but it's the same (I must have missed something?)

```
 clientConfig: {
        projectId: PROJECT_ID,
        theme: 'dark',
        accentColor: 'green',
        standaloneChains: namespaces.stellar.chains
 },        
  await ConfigCtrl.setConfig(this.clientConfig)
  const { uri, approval } = await signClient.connect({ requiredNamespaces: namespaces })

  if (uri) {
    ModalCtrl.open({
      uri: encodeURIComponent(uri)
    })
    await approval()
    ModalCtrl.close()
  }
 ```

**Comment by IljaDaderko** [comment]
@Droppix could you please update that `appWeb3Modal` project you invited me to few days ago, I will have a look.

**Comment by Droppix** [comment]
Done! I add Stellar Chain...

**Comment by Droppix** [comment]
Hi,

**Comment by IljaDaderko** [comment]
There were some substantial changes in beta.4, please see new docs that moved to https://docs.walletconnect.com/2.0/introduction/web3modal/about

We are no longer exposing our own hooks and instead moved to fully support [Wagmi](https://wagmi.sh/) for much better and reliable dev experience.

This doesn't affect standalone usage we discussed above.
