### ISSUE TITLE
Solana/Solib integration

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#679]
Integrate Solib into web3modal.

WIP at https://github.com/WalletConnect/web3modal/pull/653

**Comment by Cliv3** [comment]
Any progress on this ?

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin-cmyk > Integrate Solib into web3modal.
> 
> WIP at https://github.com/WalletConnect/web3modal/pull/653
