### ISSUE TITLE
Integrate with v1/v2 provider packages

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#680]
Web3modal now supports standalone mode and can be used directly with out sign sdk's. We now need to integrate it with our v1 and v2 provider packages.

Note: The v1/v2 versioning should also update the Explorer API query to only show relevant wallets.

**Comment by chadyj** [comment]
@IljaDaderko Added a note about the explorer API versions

The v1/v2 versioning should also update the Explorer API query to show supported wallets.
Eg https://explorer.walletconnect.com/?type=wallet&version=2&chains=eip155%3A1

**Comment by 0xAsimetriq** [comment]
closing in favor of #805
