### ISSUE TITLE
Documentation content completion

### ISSUE THREAD

**Issue by IljaDaderko** [WalletConnect/web3modal#684]
- [x] Full hooks documentation with correct content / snippets
- [ ] Vanilla usage documentation
- [ ] Standalone usage documentation (placeholder: https://docs.walletconnect.com/2.0/web3modal/standalone)
- [ ] Configuration documentation

**Comment by chadyj** [comment]
todo: move to another issue

- [ ] Better "For Wallets" section, explaining flows of how they can add custom wagmi connectors, explorer entries, injected extension data (image / name)
