### ISSUE TITLE
Pagination display issue when choosing preferred wallet

### ISSUE THREAD

**Issue by ayv8er** [WalletConnect/web3modal#693]
**Describe the bug**
When trying to select a mobile wallet to connect to, the paginated numbers at the bottom of the display container runs off both sides of the container. 

**SDK Version**
 - "@walletconnect/web3-provider": "1.7.8"

**To Reproduce**
1. Use iOS device, Chrome browser
2. Go to https://rarible.com/
3. De-collapse menu by clicking on hamburger button
4. Click on 'Connect wallet'
5. Click on 'WalletConnect'
6. See error

**Expected behavior**
To view and select from paginated numbers within the container

**Screenshots**
![IMG_7285](https://user-images.githubusercontent.com/84942969/200662057-b0844123-93e2-4223-8ffc-c23b0a8540da.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 15.6.1
 - Browser: Google Chrome

**Additional context**

**Comment by chadyj** [comment]
Hey @ayv8er thank you for the feedback.  This is indeed a problem, but something that has been fixed with our new v2 work.  I'll close this since the v1 project is deprecated.
