### ISSUE TITLE
ModalCtrl.open() did not return error from Trust Wallet in-app browser

### ISSUE THREAD

**Issue by davidchingmy** [WalletConnect/web3modal#694]
**Describe the bug**
When using single chain as provided in ClientCtrl.setEthereumClient, ModalCtrl.open() will automatically switch to the correct network.  In Trust Wallet in-app browser however, switch network is not supported thus the wallet will return an error but on dApp web, ModalCtrl.open() did not able to catch this error even after surround with try catch. 

**SDK Version**
 - Declared @web3modal/core /ethereum /ui in package.json as ^2.0.0-beta.3. Did npm install to avoid using old version too.

**To Reproduce**
1. Configure chains to only use single chain:
```
    ClientCtrl.setEthereumClient({
      appName: 'appName',
      autoConnect: true,
      chains: environment.production ? [chains.binanceSmartChain] : [chains.binanceSmartChainTestnet],
      providers: [providers.walletConnectProvider({ projectId: environment.walletConnectProjectId })],
    })
```
2. Set wallet to use different network from declared in chains above.
3. Proceed to connect wallet in dApp using Trust Wallet option in Web3Modal.
4. See error generated in console.

**Expected behavior**
- Surrounded ModalCtrl.open() with try catch should be able to catch the error.
- or ModalCtrl.open() can return Promise<boolean> to indicate of connection successful/unsuccessful.

**Screenshots**
![image](https://user-images.githubusercontent.com/103477413/200826302-b9bde99d-4b38-45a9-843d-f154fbc137c6.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android 10
 - Browser Trust Wallet In-app browser
 - Version Trust Wallet 6.55

**Additional context**
Works correctly on wallet that supports switch network - MetaMask extension, MetaMask in-app browser.

**Comment by IljaDaderko** [comment]
Thank you for report! I'm not sure if we'll throw an error in this case, rather an error message will be displayed to user within the modal and we'll re-generate qr code for connection, so that if they try again with already switched network it will work.

On your end, you can check if user ever connected or closed the modal to determine whether they completed or canceled connection flow.

Will something like this work?

**Comment by davidchingmy** [comment]
The connection is **not** made using QR code (as in image). I don't see error/notification within web3modal itself. The AccountCtrl.watch do emit an event after first success connection; however it gave me isDisconnected as true instead. Thus, combining with ModalCtrl.open() didn't able to return error, currently there is no way the dApp knows when to handle the connection or no way to notify user to switch network manually within wallet. Thank you

![image](https://user-images.githubusercontent.com/103477413/201040699-2e619802-3b22-4895-a927-773d4b457da8.png)

**Comment by IljaDaderko** [comment]
In this case uri for deep link will be re generated. Just to re-iterate, error handling within modal itself still needs to be added, I will close this issue once it is ready 👍 Right now, this is accurate bug that you reported, ty.
