### ISSUE TITLE
 After connecting to Ambire Wallet, I try to sign a message and I get an "Invalid address" error

### ISSUE THREAD

**Issue by blocknomad** [WalletConnect/web3modal#698]
**Describe the bug**

After connecting to Ambire Wallet, I try to sign a SIWE message with SignerCtrl from @web3modal/core and I get an "Invalid address" error.

**SDK Version**

"@web3modal/core": "^2.0.0-beta.3",
"@web3modal/ethereum": "^2.0.0-beta.3",
"@web3modal/ui": "^2.0.0-beta.3",

**To Reproduce**

1. Copy WalletConnect link from Web3Modal;
2. Choose Ambire Wallet on Web3Modal;
3. Go to wallet.ambire.com, paste the WalletConnect link on "Connect dApp" and successfully connect wallet to dapp;
4. Try to sign a message with `SignerCtrl.signMessage({ message: "..." })` from "@web3modal/core@^2.0.0-beta.3";
5. Get "Invalid address" error.

**Expected behavior**

The message should be successfully signed and complete sign in on my dapp

**Screenshots**

<img width="966" alt="Screenshot 2022-11-13 at 19 26 28" src="https://user-images.githubusercontent.com/6414876/201548257-1426fa19-e891-4cf6-8c5f-2f8779dd7b93.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Ventura 13.0.1 
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)

**Additional context**

The very same message can be signed without issues with MetaMask injected wallet and with Exodus iOS wallet via WalletConnect.

**Comment by IljaDaderko** [comment]
There were some substantial changes in beta.4, please see new docs that moved to https://docs.walletconnect.com/2.0/introduction/web3modal/about

We are no longer exposing our own hooks and instead moved to fully support [Wagmi](https://wagmi.sh/) for much better and reliable dev experience.

For vanilla users we are now relying on methods from `@wagmi/core` package instead of our controllers. Please see updated example for html as well, as initial setup steps changed. We are working with wagmi team on documentation for their package, meanwhite you can inspect functions that are exported by the package. (similar to our controllers, they have things like `getAccount` / `watchAccount` / `getSigner` etc.)

**Comment by blocknomad** [comment]
Hello @IljaDaderko . Thank you so much for your response.

I've upgraded my SDKs according to the vanilla example, but I still get the same error. I've opened a ticket on Ambire support and they suggested that it might be caused by wagmi doing its own signature validation, which doesn't support Smart Contract wallets. They sent me this link https://blog.ambire.com/ambires-signature-validator-library-unlocks-smart-wallet-support-for-dapps/

Looking at wagmi issues I could confirm that smart contract wallets signature validation is not supported by the package yet https://github.com/wagmi-dev/wagmi/discussions/90. Should Ambire and other smart contract wallets be removed from the list of wallets supported by web3modal until wagmi becomes EIP-1271 compliant?

**Comment by IljaDaderko** [comment]
@blocknomad I'm not too familiar with the topic, but if you just use raw signer (from their `useSigner`) would that work? As it exposes standard ethers instance.

**Comment by blocknomad** [comment]
@IljaDaderko I just tried what you suggested and it indeed doesn't work. Then I checked out ethers documentation and they say that Contract-based Wallet or Meta-Transaction-based Wallet message signing isn't supported https://docs.ethers.io/v5/api/signer/#Signer--signing-methods. Recently, they have also added warnings for it saying that developers need to implement EIP-1271 compliance separately if they want to support wallets such as Gnosis and Ambire https://github.com/ethers-io/ethers.js/pull/3481

**Comment by IljaDaderko** [comment]
I see, well if wagmi does not implement that soonish, you can always use modal in "standalone" mode (no wagmi / lightweight mode) that works with any dev-tooling.

here is an example of this with our v2 sign sdk https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone/src/pages/index.tsx

**Comment by Ivshti** [comment]
@IljaDaderko this also means that web3modal woud be broken with Argent, Gnosis Safe, Sequence and others.

Supporting smart contract wallet signatures is vital IMO
