### ISSUE TITLE
onSuccess on useSwitchNetwork

### ISSUE THREAD

**Issue by callmejm** [WalletConnect/web3modal#699]
Hi, how can do onSuccess like wagmi

```
import { useSwitchNetwork } from 'wagmi'
 
function App() {
  const network = useSwitchNetwork({
    onSuccess(data) {
      console.log('Success', data)
    },
  })
}
```

**Comment by IljaDaderko** [comment]
Hey @callmejm , with next release `beta.4` we are dropping our own hooks and will make it possible to work with wagmi directly. So you will be able to do exactly what you have above 👍

**Comment by IljaDaderko** [comment]
There were some substantial changes in beta.4, please see new docs that moved to https://docs.walletconnect.com/2.0/introduction/web3modal/about

We are no longer exposing our own hooks and instead moved to fully support [Wagmi](https://wagmi.sh/) for much better and reliable dev experience.
