### ISSUE TITLE
Option to invoke wallet creation page directly.

### ISSUE THREAD

**Issue by niksmac** [WalletConnect/web3modal#700]
**Is your feature request related to a problem? Please describe.**
It is not really a problem but a great way for non-crypto users to choose between options of "Create a wallet" or "Connect wallet"

**Describe the solution you'd like**
```jsx
import { useConnectModal } from '@web3modal/react'

// Usage
const { isOpen, open, close, createWallet } = useConnectModal()

// Returns
interface Return {
  isOpen: boolean
  open: () => void
  close: () => void,
  createWallet: () => cb
}
```

**Describe alternatives you've considered**
Use the same `open` with a different CTA

**Comment by IljaDaderko** [comment]
Just to confirm, is this the screen you are referring to?

<img width="381" alt="Screenshot 2022-11-15 at 09 28 11" src="https://user-images.githubusercontent.com/3154053/201856176-69a798b2-3501-41f0-a0ed-30d5432c5a9b.png">

**Comment by niksmac** [comment]
@IljaDaderko Yes the same screen.

**Comment by 0xAsimetriq** [comment]
This has now been added via options in modal's open method https://docs.walletconnect.com/2.0/web3modal/html-js/actions#web3modalopenmodal
