### ISSUE TITLE
fetchBalance exception on chainId 97

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#705]
**Describe the bug**
fetchBalance on wagmi/core with chainId=97 (Binance Testnet), don't work.
Error: "We don't support the chainId you provided: eip155:97"

```
POST https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=XXXXXXXXXXXXXX 400 (Bad Request)
....
index.js?ffb2:224 Uncaught (in promise) Error: bad response (status=400, headers={"content-length":"120","content-type":"application/json"}, body="{\"status\":\"FAILED\",\"reasons\":[{\"field\":\"chainId\",\"description\":\"We don't support the chainId you provided: eip155:97\"}]}", requestBody="{\"method\":\"eth_getBalance\",\"params\":[\"0x5aeebfxxxxxxxxxxxxxx\",\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=XXXXXXXXXXXXX", code=SERVER_ERROR, version=web/5.7.1)

```
** Reproduce

```
import {
  chain,
  configureChains,
  createClient,
  getNetwork,
  watchNetwork,
  switchNetwork,
  getAccount,
  watchAccount,
  fetchBalance,
  prepareSendTransaction,
  sendTransaction
} from '@wagmi/core'

const binanceSmartChainTestnet = {
        id: 97,
        name: 'Binance Smart Chain Testnet',
        network: 'binanceSmartChainTestnet',
        nativeCurrency: {
          decimals: 18,
          name: 'Binance',
          symbol: 'BNB'
        },
        rpcUrls: {
          default: 'https://data-seed-prebsc-1-s1.binance.org:8545'
        },
        blockExplorers: {
          default: {
            name: 'BSC Scan testnet',
            url: 'https://testnet.bscscan.com'
          }
        },
        testnet: true
}

let chains = [binanceSmartChainTestnet]
const { provider } = configureChains(chains, [
          walletConnectProvider({ projectId: PROJECT_ID })
])

wagmiClient = createClient({
          autoConnect: true,
          connectors: modalConnectors({ appName: 'O21App', chains }),
          provider
})

const ethereumClient = new EthereumClient(wagmiClient, chains)
ConfigCtrl.setConfig(this.clientConfig)
ClientCtrl.setEthereumClient(ethereumClient, chains)

const account = getAccount()
/// ....  Account is connected on chainID 97

const balance = await fetchBalance({
    address: account.address
})

```

**SDK Version**
 - Version [e.g. v1.9.8 or 2.0.0-BETA.4]

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g. chrome]

**Comment by IljaDaderko** [comment]
@callmejm @Droppix I assume both of you are using `walletConnectProvider` as your only rpc provider?
It does not support binance chains, so you will need to add another rpc option that does.

**Comment by Droppix** [comment]
@IljaDaderko 

ok, it works, but to get the balance, do I really have to integrate 'infura'?
If I remove 'infuraProvider', I get the balance, but there are access errors to eth_balance...

```
const { provider } = configureChains(
  [chain.mainnet, avalancheChain],
  [
    infuraProvider({ apiKey: 'yourInfuraApiKey' }),
    jsonRpcProvider({
      rpc: (chain) => {
        if (chain.id !== avalancheChain.id) return null
        return { http: chain.rpcUrls.default }
      },
    }),
  ],
)
```

**Comment by IljaDaderko** [comment]
@Droppix It's hard to tell without full picture, but you previously posted about binance smart chain and your example above adds custom rpc only for `avalancheChain`, i.e. your setup currently uses infura for mainnet and custom rpc from chain config for avalanche.

You can still use walletConnectProvider for mainnet for example. Please look into prociders, check what chains they support / ensure you understand how jsonRpcProvider works. Depending on which chains your app needs to support, you'll have to use appropriate providers as no one provider supports all chains.

**Comment by Droppix** [comment]
What I meant was, I don't understand why I would need infura, when the wallet (metamask), already has my balance, I would just like to get the balance from metamask without access by infura...

**Comment by IljaDaderko** [comment]
That's implementation detail of wagmi not web3modal, I believe it is done this way, because getBallance hook / util can get balance for any address thus needs to use rpc. Could be a good idea to ask them for something like `getMyBalance` util as a feature request.

Once we roll our stable release of web3modal and have a bit more time, we might look into extra utilities like this one on our end 👍 You can also access raw ethersjs instances for provider / signer and perhaps use them to get balance without rpc?

**Comment by Droppix** [comment]
I understand, but as before we had FetchBalanceCtrl (we3modal), it was simpler and we didn't need to integrate an apikey...

**Comment by IljaDaderko** [comment]
We were actually just adding `jsonRpcProvider` for some custom chains under the hood before, but it has now moved outside into wagmi scope, so you should still be able to acheive exact functionality you had before. You don't need api key for binances rpc, they are open. Nor do you need infura for binance, so there must be something misconfigured in provider setup.

**Comment by Droppix** [comment]
ok, i'm going to investigate, however, i don't see any error on my side, because to get the balance i just did a big test to see, namely, a loop that insists on the fetchBalance (without infura), and after 2/3 times, not only i get the balance but. i don't have any more error (without change config)

```
 let balance = { formatted: '0' }
        let countTry = 5
        do {
          try {
            balance = await fetchBalance({
              address: account.address
            })
            break
          } catch (e) {
            countTry--
          }
        } while (countTry)

...
 setConfigureChains(chains) {
      const { provider } = configureChains(chains, [
        // infuraProvider({ apiKey: 'xxxxxx' }),
        jsonRpcProvider({
          rpc: (chain) => {
            let c = chains.find((o) => o.id === chain.id)
            if (!c) {
              return null
            }

            return { http: chain.rpcUrls.default }
          }
        })
      ])
      return provider
    },

    /**
     *
     */
    createClient(chains) {
      const provider = this.setConfigureChains(chains)
      let wagmiClient = createClient({
        autoConnect: true,
        connectors: modalConnectors({ appName: 'App', chains }),
        provider
      })

      const ethereumClient = new EthereumClient(wagmiClient, chains)

      ConfigCtrl.setConfig(this.clientConfig)
      ClientCtrl.setEthereumClient(ethereumClient, chains)
    },
```
