### ISSUE TITLE
Beta.4 add alchemy rpc like wagmi example

### ISSUE THREAD

**Issue by callmejm** [WalletConnect/web3modal#706]
Hi, how to add alchemy rpc to `walletConnectProvider from '@web3modal/ethereum'` , like wagmi example below 

```
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect'
 
const connector = new WalletConnectConnector({
  options: {
    qrcode: true,
    rpc: {
      1: 'https://eth-mainnet.alchemyapi.io/v2/yourAlchemyId',
    },
  },
})
```

**Comment by IljaDaderko** [comment]
`walletConnectProvider` uses our own rpc under the hood, so you either need to add alchemy alongside it or replace it with it. You can add / change providers inside your `configureChains` function. Here is an example from wagmi docs for alchemy https://wagmi.sh/docs/providers/alchemy
