### ISSUE TITLE
Cosmos support in web3modal

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#709]
**Is your feature request related to a problem? Please describe.**
Web3Modal doesn't work with Cosmos

**Describe the solution you'd like**
Extend web3modal v2 to work with Cosmos

**Describe alternatives you've considered**
n/a

**Additional context**
Adding Cosmos would offer another alternative to https://cosmoskit.com/

Other resources:
- https://github.com/osmosis-labs/telescope
- https://cosmoskit.com/
- https://github.com/cosmos/chain-registry

**Comment by o-az** [comment]
is there anyway to use cosmos with appkit at the moment? Seeing this moved to complete but no info in docs.
