### ISSUE TITLE
Modal customisation - part 1

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#721]
From @errorists 
the one i have in mind is Stage 1, delivering on all the things we agreed on that can be toggled by overriding some props in code, where you will be able to customise it to your preference within the limitations of what we provide: 

- themes (done)
- accents (not fully done)
- backgrounds (not done)
- branding (not done)
- modal's z-index override (not done)

**Comment by 0xAsimetriq** [comment]
Closing in favour of https://github.com/WalletConnect/web3modal/issues/893
