### ISSUE TITLE
Problems (Web3Modal bad switch LOBSTR/Metamask) + Slowly connection +  Bad QR)

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#730]
**Describe the bug**
There are several problems, however, I will try to detail the 3 problems:

1/ Problem on the mobile  (iPhone)

I have 2 Wallets applications on the mobile (Metamask and LOBSTR), in my PWA application (Safari), when I try to use my Binance account through web3Modal (Login then payment), it works fine.

Now, if I do the same thing with LOBSTR (standalone mode + wagmi), I log in, it switches to LOBSTR, I wait a bit (sometimes it's very very very slow), and connected...

OK, I stop here (no payment attempt).

Now, I try to redo the connection with my first test (BNB + Metamask still in web3Modal), web3Modal systematically switches to LOBSTR and not metamask! 
I tried to redo the test, it is systematic, I closed Safari and restarted, always switch to LOBSTR! 
I think that there are data which saved in the localstorage, then must pose problem, because it is not possible any more that web3modal opens metamask.
The only thing that works, I have to delete all the data on Safari (, and then it works again!

2/ Speed problem

There are several issues of slow connections or transactions with both Metamask and LOBSTR

3/ QR problem with the BETA 6

The 1st QR displayed by Web3Modal is not good, I had to switch to BETA 5 for it to work.

**SDK Version**
 - Web3Modal Version [2.0.0-beta.5]
 ```
  "@wagmi/core": "^0.7.5",
  "@walletconnect/sign-client": "^2.1.3",
  "@web3modal/core": "^2.0.0-beta.5",
  "@web3modal/ethereum": "^2.0.0-beta.5",
  "@web3modal/ui": "^2.0.0-beta.5",
```

**Smartphone (please complete the following information):**
 - Device: [iphone 13]
 - OS: [16]
 - Browser [Safari]

**Comment by IljaDaderko** [comment]
@Droppix There is a lot here, do you have reproduction to look at in github?

First guess is that you are using wagmi and standalone together, wagmi uses v1 of wallet connect while you also have sign-client, these will conflict together. Standalone mode should be used without wagmi / ethereum client.

**Comment by Droppix** [comment]
@IljaDaderko (

I've updated the project (the test project on github) so you can see the issues, there are a few, sometimes difficult to reproduce content from contexts.
You will also need to install LOBSTR, create an account, ...

I put in the package "**web3modal5 -> npm run web3modal5"** and "**web3modal6 -> npm run web3modal6**".

1/ In web3Modal5 it works, but sometimes the switch between Metamask/LOBSTR goes wrong (you have to be patient to reproduce it)
2/ IN web3Modal6
	- I can't connect to Metamask -> (Touch on Metamask -> no effect), see screenshot 
	- For LOBSTR, there is no app that displays and presents me with a QR-Code (on mobile??)

If you want to clear the localStorage, in the **_WalletConnect.vue file, function selected(),_** you can activate the localStorage.clear()

```
selected(chain) {
   ...
  localStorage.clear()
}
```

Also I am attaching the screenshots (in web3Modal6), web3Modal5 -> it works better
- 2 Screenshots for QR (a suspicious display??)
- 1 Capture on mobile (for Metamask)
- 1 Capture on mobile (for LOBSTR)

<img width="1254" alt="QR_first" src="https://user-images.githubusercontent.com/8955379/203796079-8376a2f8-e7de-4ada-b505-345c907f4dd4.png">

<img width="1307" alt="QR_second" src="https://user-images.githubusercontent.com/8955379/203796089-a2499875-de0c-4674-b596-bb35e1b75540.png">

![mobile_metamask](https://user-images.githubusercontent.com/8955379/203798278-faee0f3f-c19a-4576-9220-fe4c6eeb87d8.jpg)
![mobile_lobstr](https://user-images.githubusercontent.com/8955379/203798318-375253d4-555f-4ea5-a431-b8a5f4d53215.jpg)


Thks

**Comment by Droppix** [comment]
I'm having a lot of trouble getting web3Modal beta 6 to work, despite all the cleanup...
So, I just tested your url https://f87fe93e.web3modal-dev.pages.dev on the iphone 13, and I find somewhat similar symptoms, for example, 2 Metamask icons, the 1st of which is inoperative (see screenshot)
![IMG_BE384EC966B7-1](https://user-images.githubusercontent.com/8955379/203826874-bb84f429-5828-4299-84d6-50e1200196eb.jpeg)

**Comment by IljaDaderko** [comment]
Second mm is definitely a bug, will fix in next beta (it is showing injected version that should not be shown in safari, only inside wallet browsers).

**Comment by IljaDaderko** [comment]
Tracking here - https://github.com/WalletConnect/web3modal/issues/732

**Comment by Droppix** [comment]
Another problem that I didn't have in BETA 5.... 

````
vue.runtime.esm.js?2b0e:4603 
[Vue warn]: Unknown custom element: <w3m-core-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Web3Modal> at components/Web3Modal.vue
       <ElContainer> at packages/container/src/main.vue
         <WalletConnect> at components/WalletConnect.vue
           <Pages/index.vue> at pages/index.vue
             <Nuxt>
               <.nuxt/layouts/default.vue> at .nuxt/layouts/default.vue
                 <Root>
warn @ vue.runtime.esm.js?2b0e:4603
createElm @ vue.runtime.esm.js?2b0e:6518
createChildren @ vue.runtime.esm.js?2b0e:6625
createElm @ vue.runtime.esm.js?2b0e:6529
patch @ vue.runtime.esm.js?2b0e:7056
Vue._update @ vue.runtime.esm.js?2b0e:3763
....
vue.runtime.esm.js?2b0e:4603 [Vue warn]: Unknown custom element: <w3m-modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

.....
```

**Comment by IljaDaderko** [comment]
Duplicate issue should be fixed now, here is new preview
https://55305db7.web3modal-dev.pages.dev/

Regarding that second vue error, it is complaining about webcomponents `<w3m-core-button>` and `<w3m-modal>`. How to solve that has to be figured out on vue side, I'm afraid I'm not that familiar with it.

As some pointers
1. Make sure you imported ui package as per docs https://docs.walletconnect.com/2.0/web3modal/html-js/installation#configure

2. Maybe it is typescript related error, for example, in react we have to register them this way https://github.com/WalletConnect/web3modal/blob/V2/packages/react/src/components/Modal.tsx#L14

We will eventually get to working on vue package, but to use web3modal there right now, you'll have to work out these extra steps that are needed via their docs or by asking vue community for help.

**Comment by Droppix** [comment]
Ok I found...

**Comment by Droppix** [comment]
On the mobile, when I connect a "stellar:pubnet" chain, it does not show me the good wallets that accept this chain, to see for example "LOBSTR", I have to go to "View more". In beta 5, it worked, but not in beta 6... (see screenshot)

![IMG_0308](https://user-images.githubusercontent.com/8955379/203849687-08c714f0-ca23-4e12-aa4b-1fb17246fc97.PNG)

![IMG_0309](https://user-images.githubusercontent.com/8955379/203849613-38cc03e7-8590-4535-9cec-0fb849938d7c.PNG)

**Comment by IljaDaderko** [comment]
@Droppix Just got around to looking at your new comments. I think you are confusing standalone and wagmi usages here.

I'm not sure what your final use case is, but as you mentioned `stellar:pubnet`, you can't use wagmi as it is only used for evm chains. You have to use modal as standalone. I just made this a bit easier with new `@web3modal/standalone` package and updated the docs as well as examples https://docs.walletconnect.com/2.0/web3modal/standalone/installation

You need to remove wagmi from your project (likely node_modules as well and just fresh install). And you have to use v2 sign sdk as per example. Similarly, you'll have to manually manage metamask (does it even support stellar?)

Let me know if more issues arise feel free to open another issue. Closing this one, as it is not really an issue, rather needed clarity on usage with stellar.

**Comment by Droppix** [comment]
Hi @IljaDaderko 

I reassure you, I think I understood, Web3Modal, Standalone mode, Wagmi, ...  in broad terms:)
I will try to clarify the situation, because indeed, my explanation and my English, not being terrible, it gives the effect of confusion;)

Our application will allow the use of different Wallets of the user whether it is on EVM compatible blockchains (ETH, BNB, CELO, ... ) but also (as far as possible) wallets running on other blockchains (XLM, XRP, BCH, BTC ...) and therefore not EVM compatible.
And of course, we want to use Web3Modal so that the user can choose his wallet, and his connection mode (mobile / desktop).

For EVM compatible blockchains, we use Web3Modal for Wallet selection, and Wagmi for Balance/PrepareTransaction/prepareSendTransaction/prepareWriteContract/WriteContract/...

For other blockchains (AltCoin, Stellar, Ripple...), we also use Web3Modal for Wallet selection (LOBSTR, ...) but **we don't use WAGMI** (as you said, it is only EVM compatible), so **we use Standalone mode + v2 sign sdk** (as in the example https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone)

For this reason, we have to integrate all these technologies (Web3Modal and Wagmi) and they are only used when needed, but they are present in the PWA.

If you have time;) look at our test application that I prepared for you, and you will see that Wagmi is declared but not used for "stellar".

Now, regarding the web3Modal (or wagmi) bugs, I'm still struggling to find out who is responsible for the 'random' bugs we have on mobile (iOS), and in particular the 1st one I had declared, namely: 

The application works very well during several tests, and suddenly, when the user must pay with his Wallet, instead of opening the wallet (Metamask for example) with the confirmation of the transaction, it opens "App Store" by presenting Metamask (whereas Metask is installed, opened, logged...)
From this moment, despite the destruction of Safari, re-initialization of our app (LocalStorage + SessionStorage deleted), it does not work anymore!

The only solution is to delete all the history/data from Safari, so that it works again ....

I hope I have explained a little more...

FYI:
Also, Metamask & most Wallets are not Stellar compatible (and even Trust, which provides a Stellar wallet, does not work properly...)

**Comment by IljaDaderko** [comment]
Hmm I see, I think you'll need to use just `standalone` modal for your use case (even for evm chains), as mixing them both this way is likely to cause errors such as this and perhaps even more in the future.

> while our code has not changed
Each beta introduces changes (main reason we haven't released stable yet), code changes will be required according to latest docs (currently beta.7).
