### ISSUE TITLE
Unable to use on ZkSync testnet

### ISSUE THREAD

**Issue by asimaranov** [WalletConnect/web3modal#736]
**Describe the bug**
If I enter the config for zkSync testnet (https://v2-docs.zksync.io/dev/fundamentals/testnet.html#connecting-metamask), requests are failed with error `{"status":"FAILED","reasons":[{"field":"chainId","description":"We don't support the chainId you provided: eip155:280"}]}`
Config: 
```
const config: ConfigOptions = {
  projectId: '...',
  ethereum: {
    appName: 'web3Modal',
    chains: [
      {
        id: 280,
        name: "zkSync alpha testnet",
        network: "zkSync alpha testnet",
        rpcUrls: { default: 'https://zksync2-testnet.zksync.dev' }
      }
    ],
  },
```

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/25568730/204156172-e890162f-b9d9-4268-83f8-5345ce9da070.png">

How can I deal with zkSync network using this widget?

**Comment by asimaranov** [comment]
Seems to be fixed by adding 
```
  ethereum: {
    appName: '...',
    chains: [
      {
        id: 421613,
        name: "Arbitrum",
        network: "Arbitrum",
        rpcUrls: { default: 'https://goerli-rollup.arbitrum.io/rpc' }
      },
      {
        id: 280,
        name: "zkSync alpha testnet",
        network: "zkSync alpha testnet",
        rpcUrls: { default: 'https://zksync2-testnet.zksync.dev' },
      }
    ],
    providers: [
      jsonRpcProvider({
        rpc: (chain) => {
          return { http: chain.rpcUrls.default }
        }
      }),
    ]
  },

```

**Comment by IljaDaderko** [comment]
Indeed, you needed to add custom rpc for this, as default one won't support it. We also made a lot of changes in recent releases where this is now fully configurable via https://wagmi.sh and they have docs describing how to work with custom chains and rpc's as well.

This should help in migrating web3modal to latest beta as well https://docs.walletconnect.com/2.0/web3modal/about
