### ISSUE TITLE
Venly transcation not getting tx in response

### ISSUE THREAD

**Issue by usama1050** [WalletConnect/web3modal#737]
I have Integrated Web3Modal in my DAPP everything work fine except Venly  giving me an issue when i am calling a contract function executes, transcation runs successfully but it does not give me tx hash in return.
Note: My function does not have return value

**Comment by IljaDaderko** [comment]
What is Venly and can you provide reproduction github / info of what version and what packages you use please?

**Comment by 0xAsimetriq** [comment]
Closing as stale, feel free to reopen with that extra info.
