### ISSUE TITLE
Failed to launch <URL> because the scheme does not have a registered handler.

### ISSUE THREAD

**Issue by gitvictortom** [WalletConnect/web3modal#740]
Hello, everyone.
Hope you are doing well.

I am new to web3modal and I gonna integrate web3modal on my project.

I visited https://web3modal.com/try-it-out
I tried to connect my onekey wallet to web3modal.
My wallet uses Ethereum mainnet.

But it raised this error in chrome console.

Failed to launch onekey-wallet://wc?uri=wc%3A4a22509c-5878-4c2f-8cdd-fa6da69dd8ae%401%3Fbridge%3Dhttps%253A%252F%252Fx.bridge.walletconnect.org%26key%3Dbff53361ca7796b428ba78a0a20f85e05ed96b7e726b0c9eb8d988c44c3deeaa  because the scheme does not have a registered handler.

How can I deal with this error and connect my onekey wallet to web3modal ?

Looking forward to your kind consideration.

Best regards.

![1](https://user-images.githubusercontent.com/110610454/204677320-d35951f9-26d6-4bb2-b615-76230cc5c3ca.png)

![2](https://user-images.githubusercontent.com/110610454/204677329-d26afb43-3985-42b9-9689-ef641639b219.png)

![3](https://user-images.githubusercontent.com/110610454/204677339-92861cfe-f39f-40df-acfe-ac712dd7877c.png)

**Comment by IljaDaderko** [comment]
Hey, this error usually means that there is no desktop app installed that can handle that deep link (`onekey-wallet://`).
I assume you are using something else like their browser extension or mobile app?

**Comment by Droppix** [comment]
I have a similar problem on the mobile where I installed the imToken app, and as I press on it, the app does not launch...

![imtoken](https://user-images.githubusercontent.com/8955379/204797244-a05f06f5-ba3b-4a1d-99f0-16d6483add18.png)

The only visible log in safari is:

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.renderRoot.querySelector')
	dispatchException (622:2235)
	(fonction anonyme) (622:124)
	asyncGeneratorStep (10:4)
	_next (10:23)
	(fonction anonyme) (10:28)
	Promise
	(fonction anonyme) (10:20)
	(fonction anonyme) (929:2469)
	(fonction anonyme) (1366:261)
	promiseReactionJob
```

**Comment by IljaDaderko** [comment]
@Droppix your issue is different from what @gitvictortom is experiencing. Could you please open another ticket where we can deep dive into this. I see that `imToken` have only provided deeplink for their app in our https://cloud.walletconnect.com maybe that could be causing that error.

**Comment by gitvictortom** [comment]
Thx for your reply. Yes, I tried with Onekey Wallet Chrome Extension.
I got what was wrong.

**Comment by IljaDaderko** [comment]
@gitvictortom Gotcha, so in theory if that's the only extension you have installed, you should still be able to use it by clicking that first icon in the modal's home page (one that usually shows metamask and other extensions). Could you please check your `window.ethereum` and see if it has some unique flag for Onekey (i.e. extensions usually expose something like `window.ethereum.isMetaMask` / `window.ethereum.isTrustWallet`). 

If there is one, I can add name and image handling to Onekey browser extension so it shows up properly.

**Comment by timefordroids** [comment]
I have the same issue when multiple extensions are installed.

For example:
I have installed the following extensions: MetaMast, Binance Wallet, Trust Wallet, BitKeep

My config:
`desktopWallets: [
bitKeep: {
    id: '38f5d18bd8522c244bdd70cb4a68e0e718865155811c043f052fb9f1c51de662',
    name: 'BitKeep',
    links: {
      native: 'bitkeep:',
      universal: 'https://bitkeep.com',
    },
  },
trustWallet: {
    id: '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0',
    name: 'Trust Wallet',
    links: {
      native: 'trust:',
      universal: 'https://link.trustwallet.com',
    },
  },
]`

When I click corresponding wallet button on the modal, I get the same error.
Is there any way to configure the modal?

**Comment by IljaDaderko** [comment]
@timefordroids could you check on latest beta preview i.e. https://beta-8.web3modal-dev.pages.dev 

But essentially, if you get that error it means that your pc/mac can't open native desktop app i.e. it is either not installed or deeplink uri is wrong.

You mentioned MetaMask and Trust Wallet, as far as I know, they don't have any native desktop apps, only extensions. To work with extensions you need to use wagmi's injected connector (https://wagmi.sh/react/connectors/injected) which is configured in wagmi itself. Wallets you configure in modal's config (mobile and desktop) are for native apps.

**Comment by timefordroids** [comment]
Oh, got it! Thank you for the explanation 👍

**Comment by timefordroids** [comment]
Sorry but I have another one question
Is it possible to declare all injected connectors I need to make them visible on the modal?

**Comment by IljaDaderko** [comment]
Not reliably, as this has bing a big pain point with injected connectors for a while. In essence:

1. Most of these call same method on `window.ethereum`, if you have multiple extensions installed it is likely that one will be picked at random (depending on when browser loaded it in) and opened or all of them will open at once.

2. Extensions do export unique flags like `isTrust` / `isBrave` etc..., but all of them also add `isMetaMask` so that they are compatible with most dapps.

To deal with this what we do within web3modal is as follows: When users are on a desktop machine, we show 1 slot for injected wallet (first one) which uses those `isTrust / isBrave` etc... flags to add wallet icon and name. This slot chooses first installed extension that user has, if there are none it defaults to metamask and asks them to install it.

wagmi has another connector for metamask that you can use as well, but if you use MetaMask and Injected connectors, you'll basically end up still calling metamask with injected one.

This behaviour of `window.ethereum` is exactly why protocols like have a general "Browser Wallet" button instead of showing multiple options. We are working on something like that as well to improve upon this ux.

**Comment by timefordroids** [comment]
@IljaDaderko thank you a lot!

**Comment by gitvictortom** [comment]
Thanks for everyone's help!
I learned a lot from you
