### ISSUE TITLE
The imToken mobile application does not launch

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#741]
**Describe the bug**
I installed the imToken app, and as I press on it, the app (on mobile) does not launch...

The only visible log in safari is:

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.renderRoot.querySelector')
	dispatchException (622:2235)
	(fonction anonyme) (622:124)
	asyncGeneratorStep (10:4)
	_next (10:23)
	(fonction anonyme) (10:28)
	Promise
	(fonction anonyme) (10:20)
	(fonction anonyme) (929:2469)
	(fonction anonyme) (1366:261)
	promiseReactionJob
```

**SDK Version**
 - Version [2.0.0 BETA 7]

**Screenshots**
![imtoken](https://user-images.githubusercontent.com/8955379/204810196-db2ac286-54e6-43d2-9018-b2ce9851912b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13 Pro]
 - OS: [e.g. iOS 16.1]
 - Browser [Safari]

**Comment by chadyj** [comment]
Thanks for reporting this.
 
Wallets are responsible for managing their Explorer data, so please contact imToken with this issue.  We will also ping them so they are aware.

**Comment by xwartz** [comment]
I think this is web3modal bug，In some cases `root` is undefined.

```
export function getShadowRootElement(root: LitElement, selector: string) {
  const el = root.renderRoot.querySelector(selector)
  if (!el) {
    throw new Error(`${selector} not found`)
  }

  return el
}
```

https://github.com/WalletConnect/web3modal/blob/86328d912375fd3b9f3e3bc521f50c91df55f781/packages/ui/src/utils/UiHelpers.ts#L21

**Comment by IljaDaderko** [comment]
@xwartz Do you by any chance know when this happens? We run web3modal in ssr / static and plain vanilla setups and I never came across it being undefined.

**Comment by chadyj** [comment]
Re-opening this, as the explorer link seems correct.
imToken works at https://example.walletconnect.org/

**Comment by IljaDaderko** [comment]
Found an issue on our end, will be fixed in beta.8
