### ISSUE TITLE
Avast thinks https://explorer.walletconnect.com/ is a Phishing site

### ISSUE THREAD

**Issue by WarrickFitz** [WalletConnect/web3modal#744]
**Describe the bug**
Avast thinks https://explorer.walletconnect.com/ is a Phishing site

**SDK Version**
 - N/A

**To Reproduce**
1. Install Avast AV scanner
2. Go to https://explorer.walletconnect.com/

**Expected behavior**
Expect no warning

**Screenshots**
![2022-12-02_22-37-45](https://user-images.githubusercontent.com/40346010/205420927-40a257cd-e11a-4149-9bf3-79d596d27203.png)

**Desktop (please complete the following information):**
 - OS: ioS
 - Browser Chrome
 - Version n/a

**Comment by chadyj** [comment]
Thanks for the heads up.
This has been submitted as a false positive to Avast. Hopefully it will be back up soon.
https://www.avast.com/false-positive-file-form.php#mac
