### ISSUE TITLE
Unable to remove metamask and coingate wallets from widget

### ISSUE THREAD

**Issue by asimaranov** [WalletConnect/web3modal#745]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/25568730/205428680-7b9f7097-3eed-4ada-ad73-e4d327b808d9.png">

How can I remove the metamask and coingate wallets? I passed only Raise wallet to desktopWallets, but they are still here

**Comment by IljaDaderko** [comment]
You are likely using out connector helper in your wagmi setup i.e. `connectors: modalConnectors({ appName: "web3Modal", chains })`

This adds walletconnect, coinbase and mm, so you can remove it and add `WalletConnectConnector` (https://wagmi.sh/react/connectors/walletConnect) on your own, as this is the only one that is required.

**Comment by asimaranov** [comment]
Thanks. And it there an opportunity to remove just coinbase and leave metamask?

**Comment by IljaDaderko** [comment]
Yep, you can use wallet connect conector and metamask connector.
