### ISSUE TITLE
ZkSync integration

### ISSUE THREAD

**Issue by asimaranov** [WalletConnect/web3modal#746]
I'm trying to use the widget with zkSync network. 
The integration looks like 
```
import { Web3Provider } from "zksync-web3";

const provider = new Web3Provider(window.ethereum);
```
(https://v2-docs.zksync.io/api/js/providers.html#web3provider)
Where window.ethereum is an eip-1193 compatible provider.
But I haven't found how to get a eip-1193 provider from the library. Both useSigner and useProvider give StaticJsonRpcProvider or Web3Provider and no eip-1193 compatible provider that can be used here

**Comment by asimaranov** [comment]
Also how can I call wallet_switchEthereumChain to request a network switch, if I have no provider with request function?

**Comment by IljaDaderko** [comment]
You could try these steps:

1. Create custom wagmi chain with zksync config (I believe these are correct details https://chainlist.org/chain/280)
2. Use following wagmi utilities to switch the network
    2.1 React - https://wagmi.sh/react/hooks/useSwitchNetwork
    2.2 Vanilla - https://wagmi.sh/core/actions/switchNetwork
    
If this doesn't work for some reason, you can try to use ethersjs directly perhaps?

**Comment by asimaranov** [comment]
The thing is that zkSync provides additional features in rpc, e.g allows to specify paymaster for a transaction. So I need to use the zkSync provider. 
> you can try to use ethersjs directly perhaps
How can I use ethersjs directly? You mean in standalone mode? I tried, but found this issues
- Unable to add metamask to widget for standalone mode
- Example use walletconnect 2.0. I need 1.0 because I need the metamask mobile support.
- @walletconnect/client use walletconnect 1.0 widget inside and seems not to have support for event like display_uri.
I found a workaround to deal with zkSync provider.
```ts
    const { connector} = useAccount();
```
If I call the await connector.getProvider(), this provider has request function, and can be used as a provider for zkSync provider. But it seems to be not a nice solution

**Comment by IljaDaderko** [comment]
I see, I think your best bet is to open a similar issue with wagmi as they would be the ones to add support for propper zkSync provider in this scenario. Maybe they can also suggest a workaround.

Ethers with standalone modal would be my next suggestion, however, as you mentioned you will need to manage metamask yourself in this case, thus using web3modal just for WalletConnect. It is possible to add metamask mobile in standalone https://docs.walletconnect.com/2.0/web3modal/configuration#mobilewallets-optional however managing its browser extension will require extra work, as we currently manage it through wagmi.
