### ISSUE TITLE
Send `app=web3modal` parameter to RPC/Explorer API

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3modal#758]
We want to be able to identify web3modal usage.
To do so, let's add this query parameter to all RPC/Explorer API requests.

**Comment by pedrouid** [comment]
We could do something like Twitter does which is more cryptic. They use numbers for different "sources". Something like `url?s=20`

**Comment by pedrouid** [comment]
So we could so something similar like:
0 - default/unknown
1- website/homepage
2- web3modal
etc

**Comment by arein** [comment]
Yeah that's probably better

**Comment by 0xAsimetriq** [comment]
@arein this will be set to `app=2`

**Comment by pedrouid** [comment]
Honestly I would just copy Twitter with the `s=2` so that it's as generic and cryptic as possible 

Because the website could be considered an app but web3modal is not an app. So "source" covers both

**Comment by chadyj** [comment]
Closing for now. 
Will revisit after a proper spec.
