### ISSUE TITLE
Web3Modal connect bsc testnet trust wallet extension

### ISSUE THREAD

**Issue by cheetoss37** [WalletConnect/web3modal#759]
Hi,
I've integrate web3modal v2 follow this link: [https://docs.walletconnect.com/2.0/web3modal/react/installation](url)

Here the config:

```
const bscTestnet = {
	id: 97,
	name: 'Smart Chain - Testnet',
	network: 'bsc testnet',
	nativeCurrency: { decimals: 18, name: 'Smart Chain - Testnet', symbol: 'BNB'},
	rpcUrls: { default: 'https://data-seed-prebsc-1-s1.binance.org:8545/' },
	blockExplorers: { default: { name: 'BSC', url: 'https://testnet.bscscan.com' } },
	testnet: true
}

const chains = [bscTestnet];

const { provider } = configureChains(chains, [
	walletConnectProvider({ projectId })
])

const wagmiClient = createClient({
	autoConnect: true,
	connectors: modalConnectors({ appName: 'web3Modal', chains }),
	provider
})
```

I'm facing this issue, not sure what is wrong! 
<img width="368" alt="Screen Shot 2022-12-09 at 02 43 39" src="https://user-images.githubusercontent.com/49990830/206552729-4e2b9785-c4ab-4ed0-9061-e8530af07e33.png">

But Trust Wallet still show that the site is connected

<img width="367" alt="Screen Shot 2022-12-09 at 02 48 18" src="https://user-images.githubusercontent.com/49990830/206553217-3c8a7c3e-2fac-4609-88de-0e531d49bb53.png">

Pls help! Thanks

**Comment by 0xAsimetriq** [comment]
At what point does this error happen and do you see any issues printed out in the console? Does similar flow also fail with other extensions i.e metamask (I assume from the screenshot that this is TrustWallets browser extension)?

Which version of web3modal and wagmi are you using?

**Comment by cheetoss37** [comment]
> At what point does this error happen and do you see any issues printed out in the console? Does similar flow also fail with other extensions i.e metamask (I assume from the screenshot that this is TrustWallets browser extension)?
> 
> Which version of web3modal and wagmi are you using?
 
 I am using TrustWallets browser extension. It's work with fine with metamask, and I'm using @web3modal/react: 2.0.0-beta.8, wagmi: 0.8.10
 
 I've check the console and got this error after connect
 
![Screen Shot 2022-12-09 at 09 31 12](https://user-images.githubusercontent.com/49990830/206613893-14766b8e-3d7e-405b-86e9-19aeba6a4e07.png)

**Comment by 0xAsimetriq** [comment]
So few ideas here:

1. As per wagmi docs here https://wagmi.sh/core/chains#build-your-own I think you need to change your 

```
rpcUrls: { 
    default: 'https://data-seed-prebsc-1-s1.binance.org:8545/' 
}
```

to

```
rpcUrls: { 
    default: { http: ['https://data-seed-prebsc-1-s1.binance.org:8545/'] }
}
```

Also go over your chain config just in case and see if you misconfigured any other fields.

2. If above doesn't solve your issue, you probably need to add extra provider (jsonRpc - https://wagmi.sh/core/providers/jsonRpc) to your wagmi config as additional rpc that uses binances testnet one.

I'll close this issue for now, as this doesn't look like web3modal issue, rather missing or misconfigured wagmi provider for bsc testnet. But if after changes above it still doesn't work feel free to ping me 👍
