### ISSUE TITLE
about useWeb3Modal open method

### ISSUE THREAD

**Issue by rick20220222** [WalletConnect/web3modal#760]
Can the open method return a promise object, I need to perform the following actions after the connection

**Comment by 0xAsimetriq** [comment]
Open method only opens the modal, so awaiting it wouldn't solve the issue, however you can await user connection in 2 ways

1. If you are using web3modal with wagmi, check out https://wagmi.sh/react/hooks/useAccount hook, which gives you all the data about users connection state

2. If you are using modal in standalone mode without wagmi, you should already have access to WalletConnect client and can await connection on it i.e. as in this example https://docs.walletconnect.com/2.0/web3modal/standalone/installation#create-pairing-and-open-the-modal
