### ISSUE TITLE
When the web3modal pops up in Google Chrome, if I choose the metamask wallet, it will force me to switch networks, from goerli to Ethereum Mainnet. Why is this?

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/web3modal#761]
**Describe the bug**
When the web3modal pops up in Google Chrome, if I choose the metamask wallet, it will force me to switch networks, from goerli to Ethereum Mainnet. Why is this?

**SDK Version**
 - Version [e.g. v2.0.0-beta.8]

**To Reproduce**

**Expected behavior**
This is demo link https://incomparable-buttercream-e11a78.netlify.app

**Screenshots**
<img width="1693" alt="WeChatf800fac3e4963f4ea74f4e85e7a8dced" src="https://user-images.githubusercontent.com/17617821/206633972-1bd7f47f-1720-4982-be1a-72afa3623658.png">

**Desktop (please complete the following information):**
 - OS: [e.g.Mac]
 - Browser [ chrome]
 - Version [108.0.5359.94]

**Comment by 0xAsimetriq** [comment]
Could you please drop your configuration code here / or better provide link to github repo please? Do you have both chains defined in wagmi config?

But I think it could be a good idea to add "default" chain prop to modals open method 👍 will make a ticket.

**Comment by 0xAsimetriq** [comment]
@shenhaoguangDayDayUp would something like this solve your use case? https://github.com/WalletConnect/web3modal/issues/762

**Comment by shenhaoguangDayDayUp** [comment]
> Could you please drop your configuration code here / or better provide link to github repo please? Do you have both chains defined in wagmi config?
> 
> But I think it could be a good idea to add "default" chain prop to modals open method 👍 will make a ticket.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/17617821/206654819-5b596a83-4710-402b-b82d-97ef698f7d3b.png">

 I added both the main chain and the test chain to the chains,it's fine when I remove the main chain. thank you.

**Comment by shenhaoguangDayDayUp** [comment]
> I didn't see this page. I remember that it used to be possible to see this page in v2.0.0-beta.8, but after upgrading, I never saw the page that let me choose which chain again.

**Comment by shenhaoguangDayDayUp** [comment]
> Cool, I'll close this for now, but in theory you should see view like this where you can select chain to connect to. Does the error still appear when you choose goerli here?
> 
> <img alt="Screenshot 2022-12-09 at 10 20 26" width="502" src="https://user-images.githubusercontent.com/3154053/206657066-31786d9c-e79c-4e53-8dac-22b2eb0ca42c.png">

I didn't see this page. I remember that it used to be possible to see this page in v2.0.0-beta.8, but after upgrading, I never saw the page that let me choose which chain again.

**Comment by 0xAsimetriq** [comment]
Hmm, did you by any chance disable it via `enableNetworkView` flag?

**Comment by shenhaoguangDayDayUp** [comment]
> Hmm, did you by any chance disable it via `enableNetworkView` flag?

No , It's my code 
```

export default class Core {

  private wagmiClient:Client<any, WebSocketProvider>;

  private chains:Chain[] = [];

  public ethereumClient:EthereumClient; 

  public web3Modal:Web3Modal;

  constructor(env:string = 'production'){

    const projectId = '8e6b5ffdcbc9794bf9f4a1952578365b'
 
    const chains = [chain.goerli,chain.polygonMumbai]

    // chain.mainnet, chain.polygon

    // 2. Configure wagmi client
    const { provider } = configureChains(chains, [walletConnectProvider({ projectId })])

     this.wagmiClient = createClient({
      autoConnect: true,
      connectors: modalConnectors({ appName: 'web3Modal', chains }),
      provider
    })

    this.ethereumClient =  new EthereumClient(this.wagmiClient, this.chains)

    this.web3Modal = new Web3Modal({ projectId }, this.ethereumClient)
   

  }
  
} 
```
