### ISSUE TITLE
When I use the class syntax, the web3modal does not pop up a page for me to choose the chain,Is there a problem with my syntax?

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/web3modal#763]
**SDK Version**
 - Version [ v2.0.0-alpha.8]

**To Reproduce**
https://codesandbox.io/p/sandbox/strange-sinoussi-it3utr?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A7%7D%5D

**Screenshots**
I cannot appear on this page. 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/17617821/206849135-18be6ca3-0571-49f4-918b-56714d7f1840.png">

**Desktop (please complete the following information):**
 - OS: [macos]
 - Browser [chrome, safari]

**Comment by 0xAsimetriq** [comment]
Inside your core class, change

```
const chains = [chain.mainnet, chain.polygon];
```

to 

```
this.chains = [chain.mainnet, chain.polygon];
```

And replace all `chain` instances with `this.chain`.

Currently in your class `this.chains` is always empty and you pass it to ethereum client, while passing `const chains` to wagmi client.
