### ISSUE TITLE
Error: No wagmi client found. Ensure you have set up a client: https://wagmi.sh/react/client

### ISSUE THREAD

**Issue by LaMemeBete** [WalletConnect/web3modal#764]
**Describe the bug**
I encounter the following issue on my project when I try to run web3modal from the react example project.

**SDK Version**
 - 2.0.0-beta.8

**To Reproduce**
1. npm run dev from web3modal/examples/react 
3. Open localhost:3000
4. See error:
Unhandled Runtime Error
Error: No wagmi client found. Ensure you have set up a client: https://wagmi.sh/react/client

Call Stack
getClient
node_modules/@wagmi/core/dist/chunk-63RNYADG.js (1023:0)
Proxy.getAccount
node_modules/@wagmi/core/dist/chunk-63RNYADG.js (3154:36)
getAccount
node_modules/@web3modal/core/dist/index.js (1:732)
w
node_modules/@web3modal/ui/dist/index.js (1:13779)
legacyCustomElement
node_modules/@lit/reactive-element/development/decorators/custom-element.js (7:0)
eval
node_modules/@lit/reactive-element/development/decorators/custom-element.js (42:0)
i
node_modules/@web3modal/ui/dist/index.js (1:13377)
Le
node_modules/@web3modal/ui/dist/index.js (1:16843)
./node_modules/@web3modal/ui/dist/index.js
file:///Users/mosheborochov/Desktop/work/davote/experiments/web3modal/examples/react/.next/static/chunks/node_modules_web3modal_ui_dist_index_js.js (1528:1)
options.factory
/_next/static/chunks/webpack.js (718:31)
__webpack_require__
file:///Users/mosheborochov/Desktop/work/davote/experiments/web3modal/examples/react/.next/static/chunks/webpack.js (37:33)
Function.fn
/_next/static/chunks/webpack.js (373:21)
async eval
node_modules/@web3modal/react/dist/index.js (1:2129)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xAsimetriq** [comment]
This error usually happens when users upgrade from an earlier version. Could you try following as a fix

1. Remove `node_modules` and your npm / yanr .lockile
2. Install packages fresh (make sure you also have wagmi in your dependencies)

Note, wagmi recently released new version of their package which changes how chains are imported, so if you are using latest version, make sure to check their docs. We'll update ours once beta.9 is released.

**Comment by 0xAsimetriq** [comment]
Closing this issue since it's been a while from last response and issue is related to installation / module versions.
