### ISSUE TITLE
Cleanup desktop explorer data

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#766]
We have good chunk of data in our explorer api now. Unfortunately a lot of entries have bad data. I'll outline some common issues below, but we need to address this before stable release in order to look more polished and stable. Not sure what the best approach here is, but we prob need to go over this manually in both w3m desktop and mobile mode and see what is missing:

1. Some wallets go to 404 pages
2. Some mobile wallets are missing deeplinks
3. Some projects are no longer existing
4. Some projects have rounded logo images (should be square to look good in our ui)
5. There are projects in desktop category that don't have desktop wallets
6. There are projects in mobile category that don't have mobile wallets

**Comment by 0xAsimetriq** [comment]
<img width="373" alt="Screenshot 2022-12-12 at 17 36 19" src="https://user-images.githubusercontent.com/3154053/207088064-ec70b556-5a5f-4327-ada9-164d34091e0f.png">

First batch of wallets that either have broken links, go to 404 pages, don't have desktop wallets

**Comment by 0xAsimetriq** [comment]
<img width="460" alt="Screenshot 2022-12-12 at 17 40 55" src="https://user-images.githubusercontent.com/3154053/207089115-4bc1c10c-a964-4da2-a181-b8f42364e71e.png">

**Comment by 0xAsimetriq** [comment]
Progress

```
KEYRING PRO - [Edited] desktop urls, they are mobile only app
 [Nftrade.com](http://nftrade.com/) -  [Deleted] they are not a wallet, but an nft marketplace
 PhunkWallet - [Deleted] It's a template wallet, which shows private keys and acts as example for scafold.eth github projects, not an actual product.
 RiceWallet - [Edited] removed desktop links, they led to broken page, and they are mobile only wallet
 Vision: Crypto Wallet - [Edited] Mobile only app, removed desktop link
 PREMA - [Edited] Mobile only app, removed desktop links
 secux - [Edited] Mobile only app, removed desktop links
 KryptoGo - [Edited] Mobile only app, removed desktop links
```

**Comment by chadyj** [comment]
>  [Nftrade.com](http://nftrade.com/) -  [Deleted] they are not a wallet, but an nft marketplace

Deleted from the explorer, or from the wallets section?

For dapps reporting as wallets or hybrid, can we just edit the category to dapp?
