### ISSUE TITLE
Beta.10 - Details, Feedback and Discussion

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#767]
Change log
https://github.com/WalletConnect/web3modal/releases/tag/2.0.0-beta.10

**Comment by timefordroids** [comment]
Great work! I've integrated this version on our DEX and going to deploy on prod tomorrow.

**Comment by 0xAsimetriq** [comment]
closing in favour of https://github.com/WalletConnect/web3modal/issues/794
