### ISSUE TITLE
es2020 syntax issues when running in emulated android 9

### ISSUE THREAD

**Issue by Vivienne-CPZ** [WalletConnect/web3modal#769]
**Describe the bug**
Open web3modal click on 'view more' , view more no data

**SDK Version**
 -  "@web3modal/ethereum": "^2.0.0-beta.7",
    "@web3modal/react": "^2.0.0-beta.7",
     "wagmi": "^0.8.10"

**To Reproduce**
1. open web3modal 
2. Click on 'view more'
3. show other wallet 

**Expected behavior**
click view more 
show other wallet 

**Screenshots**
![117711670901223_ pic](https://user-images.githubusercontent.com/104967115/207217528-b592b9a3-62cb-44dd-a57d-e3d210e95c06.jpg)

**Smartphone (please complete the following information):**
 - pixel 6 Pro 
 - android 10.0 | X86
 - app
 - X86

**Additional context**
<img width="893" alt="截屏2022-12-13 11 09 47" src="https://user-images.githubusercontent.com/104967115/207216998-ba740f1a-100f-456c-84fe-0ee1b47bfb26.png">
<img width="949" alt="截屏2022-12-13 11 10 12" src="https://user-images.githubusercontent.com/104967115/207217054-48c352ea-2ed7-4bdd-b8fa-83b3b1e538cf.png">

 const { open: web3ModalOpen } = useWeb3Modal();
 {!isConnected && (
                  <IonButton className={styles.connectBtn} onClick={() => web3ModalOpen()}>
                    Connect Wallet
                  </IonButton>
                )}

**Comment by 0xAsimetriq** [comment]
@Vivienne-CPZ do you see any error on your side when opening that view? And is PROJECT_ID populated (if it is missing, there is no way to access our explorer api).

**Comment by Vivienne-CPZ** [comment]
Android 10  ABi  arm64-v8a view more is ok 
but Android 10  ABi  X86 view more is blank

**Comment by 0xAsimetriq** [comment]
When you visit website on https://web3modal.com/try-it-out do you see any errors?

Judging by what you posted however `Unexpected token ?`, this means that your js bundler is not set up to work with es2020 syntax. Usually this is fixed via updating to lates version of tools like babel / webpack / vite etc.

**Comment by Vivienne-CPZ** [comment]
visit website on https://web3modal.com/try-it-out  android 11 ok.   android 9 is error. 

https://user-images.githubusercontent.com/104967115/207257506-60d5459a-6a3d-4ab9-ba74-615c4644d65f.mov
<img width="415" alt="截屏2022-12-13 15 53 15" src="https://user-images.githubusercontent.com/104967115/207257735-9feab890-2f4b-4257-94a6-8fc0324e3d96.png">

**Comment by Vivienne-CPZ** [comment]
![截屏2022-12-13 15 56 09](https://user-images.githubusercontent.com/104967115/207258443-50e1fa19-be2d-4547-b7b3-d07494d5413a.png)

**Comment by 0xAsimetriq** [comment]
Combining all the info above, the only idea that comes to mind is that you might be using some exotic emulator browser that does not support es2020 syntax perhaps?

I also assume you are trying to run this inside Capacitor / Ionic setup, correct? Make sure you use latest versions of their webviews based on chromium and safari.

Here is one of the es2020 syntax features that we use and it's support chart as an example, is your browser within the supported range?
https://caniuse.com/?search=chainin

**Comment by Vivienne-CPZ** [comment]
Android 10 ABi X86 view more will be blank， and not error message, how to fix?

**Comment by 0xAsimetriq** [comment]
Do you have a github repository I could look at to see specifics of your implementation?

**Comment by Vivienne-CPZ** [comment]
https://github.com/Vivienne-CPZ/web3modal-test

**Comment by 0xAsimetriq** [comment]
We are now testing on android emulators and android has it's unique flow of how it opens wallets. Web3Modal related things seem to work great there which leads me to think that this error might be on web3modal.com page itself. We are currently rebuilding it, so will try to address, but for now closing this issue.
