### ISSUE TITLE
Add Binance Wallet (extension) data

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#771]
**Describe the bug**
I have 2 Wallets extension connected (Metamask + Binance)
When injecting a Binance Wallet, there are several issues:

1/ The icon is not correct
2/ When you click on Binance Wallet, it opens Metamask??

**SDK Version**
 - Version [e.g. v2.0.0-beta.9]

**To Reproduce**
**Expected behavior**

```
      let connectors = modalConnectors({ appName: APP_NAME, chains })
      const connectorBinanceWallet = new InjectedConnector({
        options: {
          name: 'Binance Wallet',
          getProvider: () => (typeof window !== 'undefined' ? window.BinanceChain : undefined)
        }
      })
      connectors.push(connectorBinanceWallet)

      let wagmiClient = createClient({
        autoConnect: true,
        connectors,
        provider
      })
```

**Screenshots**
<img width="362" alt="Capture d’écran 2022-12-13 à 16 13 16" src="https://user-images.githubusercontent.com/8955379/207372347-834b345d-9cec-49a3-939f-b852060decf1.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]

**Comment by 0xAsimetriq** [comment]
1. I will add binance assets in so we display correct icon 👍 
2. This is something that is a core issue of `window.ethereum` wallets (that injected connecotr uses) unfortunately. Injected connector will show extension that got loaded in first by the browser, usually it is metamask. To further complicate things, most extension wallets add `ethereum.isMetaMask` to themselves as well, making things even more complicated.

This is why we only show one slot for installed wallet in web3modal that auto adopts to installed wallet. With multiple browser extension connectors most users found it more confusing.

**Comment by Droppix** [comment]
ok, thanks...
Is there a way to get the deep-link / universal-link of the selected application in the web3modal?
Or any other way (api ? explorer-api.walletconnect.com ?)

**Comment by 0xAsimetriq** [comment]
You can access `localStorage.W3M_RECENT_WALLET` which will have details about wallet that user connected with. It includes deep and universal link. It will be undefined if user hasn't connected yet.

And yep, https://docs.walletconnect.com/2.0/cloud/explorer#cloud-explorer-api explorer api is also available if you want to get a list of WalletConnect supported wallets and their data like these links.

**Comment by 0xAsimetriq** [comment]
@Droppix I just tried to add support for binance wallet extension, but unfortunately it will not work. They don't add `window.ethereum` object which is normally present in all other evm extensions, so it will probably need a custom wagmi connector to work, which we don't have capacity to add atm.

I'll close this issue for now, but wagmi has docs about how to create such custom connector https://wagmi.sh/examples/custom-connector that you can utilise for this.

**Comment by Droppix** [comment]
Thanks, I will try to contact Wagmi, and see with him if it is possible to do something...

Anyway, thks.
