### ISSUE TITLE
Coinbase name appears on the Metamask option

### ISSUE THREAD

**Issue by upendra-metasky** [WalletConnect/web3modal#773]
**Describe the bug**
I have metmask and coinbase google extensions added to my chrome browser. When the web3modal pops up it shows me an installed option with metamask image but name being Coinbase. I guess thats definitely a bug where these extensions installed together as doing

**SDK Version**
 - Version [e.g. v1.9.8 or 2.0.0-alpha.2]

**To Reproduce**
1. add coinbase google extension and create/import your wallet
2. add metmask extension and create/import your wallet
3. open web3modal to see view as shown in attached image
<img width="368" alt="Screenshot 2022-12-15 at 2 11 29 PM" src="https://user-images.githubusercontent.com/102647133/207812969-19c9d419-a9a7-45c1-aa67-9713e248d082.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by 0xAsimetriq** [comment]
Was able to reproduced this, ty for report 👍

**Comment by upendra-metasky** [comment]
> Was able to reproduced this, ty for report 👍
My pleasure @0xAsimetriq . Thanks for the fix
