### ISSUE TITLE
Web3Modal.com is down - pending WHOIS verification

### ISSUE THREAD

**Issue by jamesscaur** [WalletConnect/web3modal#774]
**Describe the bug**
Web3Modal.com is down pending WHOIS verification.

"Since January 2014, all ICANN accredited registrars (like Namecheap) have been required to verify the contact information (Registrant Whois) of customers registering domain names. This includes modifications to the contact details."

"We need email address verification from the owner" - @pedrouid

**SDK Version**
N/A

**To Reproduce**
1. Go to http://www.web3modal.com/

**Expected behavior**
Web3Modal information page should appear, SSL certificate warning should not appear.

**Screenshots**
<img width="1552" alt="Screenshot 2022-12-16 at 08 22 37" src="https://user-images.githubusercontent.com/9779954/207948731-ead4fad7-9273-44c8-a2fb-b294ee2143bd.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by chadyj** [comment]
@jamesscaur Thanks for reporting. 

This has been fixed, and should be working again.
