### ISSUE TITLE
When I switch the bsc network, I always get disconnected

### ISSUE THREAD

**Issue by rick20220222** [WalletConnect/web3modal#781]
**Describe the bug**
When I switch the bsc network, I always get disconnected

**SDK Version**
  "@web3modal/ethereum": "^2.0.0-beta.7",
  "@web3modal/react": "^2.0.0-beta.7",
  "wagmi": "^0.9.2",

**Comment by 0xAsimetriq** [comment]
Could you try on latest beta.10 please

**Comment by rick20220222** [comment]
There are also problems

**Comment by 0xAsimetriq** [comment]
I see, could you provide reproduction repo for me to look at please.

**Comment by rick20220222** [comment]
https://web3modal.com/try-it-out  

This demo has the same problem

**Comment by 0xAsimetriq** [comment]
Unable to reproduce. I think this issue could be related to how the wallet you use handles network switching / bsc. Which one are you using for testing?

https://user-images.githubusercontent.com/3154053/209426114-3db1c219-7d2d-4998-86c6-6b905c4498f4.mov

**Comment by rick20220222** [comment]
https://user-images.githubusercontent.com/100116396/209595549-5447e159-ac2d-42d4-abfe-64aff115d491.mp4

**Comment by 0xAsimetriq** [comment]
Will need to see some code, but few ideas

1. Did you configure rpc provider for binance testnet?
2. Do you see any errors in the console?

**Comment by rick20220222** [comment]
1、
![image](https://user-images.githubusercontent.com/100116396/209895316-c35cb103-cf65-47ae-91c8-b94155d14bd3.png)

2、no errors in the console

**Comment by SaTiSH-K-R** [comment]
This issue still persists in web3modal.com as well.
Connect to the Metamask(not through WalletConnect) and try switching networks to polygon, bsc, or something in the Metamask. The wallet disconnects immediately.
@0xAsimetriq any work around for this issue?

**Comment by SaTiSH-K-R** [comment]
@0xAsimetriq But It's not working as expected for me. What might be the problem?

https://user-images.githubusercontent.com/61915099/220393846-b73da30b-abd5-4d3c-8c0b-4932a83e1d04.mp4

**Comment by 0xAsimetriq** [comment]
Hmmm, first of all ty for the video, really weird. I can see you are using brave, any chance brave wallet is active here and perhaps conflicting? (could you disable it and re-test). Would help determine what the bug could be

**Comment by 0xAsimetriq** [comment]
@SaTiSH-K-R also, no errors pop up in the console or any other feedback to act on? Any issues in network view (i.e. rpc calls etc.)

**Comment by SaTiSH-K-R** [comment]
This console error always comes when first load
![error](https://user-images.githubusercontent.com/61915099/220433816-0fd33289-a5e0-44d9-af15-b79e2f8a7469.png)

When I switched to avalanche the request went like this(with avax chainId as param) and the network switched to avalanche perfectly.
![switch-to-avax](https://user-images.githubusercontent.com/61915099/220434375-b7e5c395-12a6-45b2-9bd0-2e95d51e0000.png)

Later I switched to Polygon and the chainId in the request params is not polygon's chainId(56) but mainnet's chainId(1) and then the wallet disconnected.
![switch-to-polygon](https://user-images.githubusercontent.com/61915099/220435209-382cb8f1-107d-46f4-8900-55ebdc3bb52f.png)

@0xAsimetriq See if it helps in any way

**Comment by SaTiSH-K-R** [comment]
> This console error always comes when first load ![error](https://user-images.githubusercontent.com/61915099/220433816-0fd33289-a5e0-44d9-af15-b79e2f8a7469.png)
> 
Never mind this console error. It's because of brave shield

**Comment by 0xAsimetriq** [comment]
Thank you, I'm still confused to why this happens but will keep investigating
