### ISSUE TITLE
Cannot support bsc networks

### ISSUE THREAD

**Issue by rick20220222** [WalletConnect/web3modal#782]
**Describe the bug**
[A clear and concise description of what the bug is.](https://rpc.walletconnect.com/v1/?chainId=eip155:56&projectId=b1b2890b083005af64edee71d9b14d10)

{"status":"FAILED","reasons":[{"field":"chainId","description":"We don't support the chainId you provided: eip155:56"}]}

**Comment by 0xAsimetriq** [comment]
WalletConnect rpc doesn't support bsc, however since beta.10 we automatically fallback to use rpc defined in chain config, so that should now work.

You can also define your own rpc provider in wagmi config.
