### ISSUE TITLE
Why mobile browsers don't show metamask wallet

### ISSUE THREAD

**Issue by rick20220222** [WalletConnect/web3modal#786]
![image](https://user-images.githubusercontent.com/100116396/208686277-b77d2eea-7099-4e4f-a866-36d3203f75cd.png)

**Comment by rick20220222** [comment]
I just want to realize metamask coinbase trust three wallets, what should I do?

**Comment by 0xAsimetriq** [comment]
1. Which packages and their versions are you using
2. Which mobile browser is this
3. Are you using any custom configs
