### ISSUE TITLE
Web3Modal Explorer API

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#792]
# Overview
Web3Modal grew into a complex front end library that relies on explorer api for some of its functionality. It is probably time to create separate project / endpoint for w3m specific api? This will allow to return specific and combined data for more optimal queries and tackle modal assets from image cdn separately. 

## Image assets
We currently store and allowlist a set of web3modal specific images for token, wallet and blockchain image fetching. Getting rid of such allowlist and creating a separate endpoint for web3modal would be preferable.

Suggestion
```
GET /w3m/v1/[img_id].webp
```

## Wallet filtering on api level
Users have ability to filter results from explorer via `allowList` and `denyList` config options. There will soon be another option for general list of wallets that users can use for custom ordering and other purposes. Filtering happens purely client side right now which is not ideal (extra data fetched / pagination incorrect).

Suggestion
```
GET /w3m/v1/wallets?allowList=...
GET /w3m/v1/wallets?denyList=...
GET /w3m/v1/wallets?list=... (returns wallets for specified id, ordered as specified)
```

## Better mobile / desktop wallet fetching
We now introduced new category of wallets (injected), this fetching desktop wallets requires 2 queries as well as custom logic to place items (one desktop, one native, one desktop, one native ...). This also complicates pagination. Current filters for chains, pages, walletconnect versions and sdks still apply.

Suggestion
```
GET /w3m/v1/wallets?platform=mobile
GET /w3m/v1/wallets?platform=desktop (includes injected as well)
```

## Recomended wallets
Highly cached endpoint that returns recomended top 6 (maybe more in the future) wallets. Current filters for chains, walletconnect versions and sdks still apply.

Suggestion
```
GET /w3m/v1/previewWallets?platform=...
```

**Comment by 0xAsimetriq** [comment]
What did you put in `explorerAllowList`?

**Comment by obernardovieira** [comment]
some wallet ids
like
```
explorerAllowList={[
    'bc949c5d968ae81310268bf9193f9c9fb7bb4e1283e1284af8f2bd4992535fd6',
    'afbd95522f4041c71dd4f1a065f971fd32372865b416f95a0b1db759ae33f2a7'
]}
```
