### ISSUE TITLE
Deeplink parsing breaks deeplinks with nested paths

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [WalletConnect/web3modal#793]
**Describe the bug**
"When I try to connect to OKEx using the web3modal, I am unable to redirect to the OKEx app
**SDK Version**
 - Version [2.0.0-alpha.10]

**Screenshots**
![4541671762721_ pic](https://user-images.githubusercontent.com/17617821/209260157-9e83187f-31fc-4b82-a726-8c9b25c81da9.jpg)

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/17617821/209262146-df662493-688e-4b55-9428-a84c6d8ca113.png">

**Comment by 0xAsimetriq** [comment]
Found the issue, our current formating doesn't account for sub-paths in deeplinks, will be fixed in rc.1 release 👍

**Comment by 0xAsimetriq** [comment]
@shenhaoguangDayDayUp could you please test on https://rc-1.web3modal-dev.pages.dev and check if it works now

**Comment by shenhaoguangDayDayUp** [comment]
> @shenhaoguangDayDayUp could you please test on https://rc-1.web3modal-dev.pages.dev and check if it works now

After testing with the link you provided, I found that it works well. Can it now support the Okex desktop application?

**Comment by 0xAsimetriq** [comment]
In theory yes, since desktop apps also use deeplinks, but okx will need to update their data in our https://cloud.walletconnect.com as they only specified mobile details atm. I will reach to a member of our team to see if we can update this on our end.

**Comment by shenhaoguangDayDayUp** [comment]
> In theory yes, since desktop apps also use deeplinks, but okx will need to update their data in our https://cloud.walletconnect.com as they only specified mobile details atm. I will reach to a member of our team to see if we can update this on our end.

Ok, thanks for your help.
