### ISSUE TITLE
Release Candidate 1 - Details, Discussion and Feedback

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#794]
Changelog
https://github.com/WalletConnect/web3modal/releases/tag/2.0.0-rc.1

**Comment by 1kko-ahnlabio** [comment]
Seems like ABC Wallet support is dropped. Any issues?

**Comment by 0xAsimetriq** [comment]
closing in favour of https://github.com/WalletConnect/web3modal/issues/811
