### ISSUE TITLE
Pure HTML/JS Solution Needed

### ISSUE THREAD

**Issue by scorpionmit01** [WalletConnect/web3modal#798]
** Failed Use Case **
I'm running in a security sandboxed environment, and I can't import external libraries. Attempting to load them locally - using unpkg and loading them from the server runs into problem.

The HTML / Vanilla JS is technically HTML / Vanilla JS, but not implemented the way one would normally bring an external library in.

**Desired Functionality **
```
<button id="web3modal">Wallet Connect</button>
<script>
    // web3modal_loaded is called at the end of the Javascript loading, so as soon as the library loads, it runs
    function success() { console.log("Success, logged in from "WalletAddress); }
    function failure(err) { console.log("Failure: " + err); }
    const web3modal_loaded = function() {
         const connectButton = document.getElementById('connect-button');
         const modal = new web3Modal( projectid );

         connectButton.addEventListener('click', function() { web3Modal.connect(success(WalletAddress), failure(err)); }
    }
</script>
<script url="Web3ModalForHTML.js" type="module">
```

** Hoping this helps **

 I'm hoping that explains what I'd love for a "pure HTML" version that is implementable in a common HTML/JS environment (think Wordpress, Shopify, or custom PHP website scenario).

Essentially, the ability to load Web3 Modal, call it as a Method (or function) and have a success callback with the wallet address and a failure callback with an error.

That scenario would mean behaving like a much more common JS Library.

**Comment by 0xAsimetriq** [comment]
What you have described is already achievable via out html package, but I assume you are referring to not using npm modules here? In which case I will close this issue as a duplicate of https://github.com/WalletConnect/web3modal/issues/678

We will get to working on a pre-compiled cdn version soonish, so in theory you can grab that code and populate your local file. Meanwhile few people who needed this used webpack / vite to compile npm module into pre-built file as well. I believe they just set up these compilers to output target that the needed and imported all necessary libs into one file.

**Comment by scorpionmit01** [comment]
Thank you for the pointers. Obvious the CDN deployable solution is when you have a genetic solution for non-node websites to implement this with ease.Thank you for all your hard work.Sent from my iPhoneOn Dec 25, 2022, at 3:30 AM, 0xAsimetriq ***@***.***> wrote:﻿
What you have described is already achievable via out html package, but I assume you are referring to not using npm modules here? In which case I will close this issue as a duplicate of #678
We will get to working on a pre-compiled cdn version soonish, so in theory you can grab that code and populate your local file. Meanwhile few people who needed this used webpack / vite to compile npm module into pre-built file as well. I believe they just set up these compilers to output target that the needed and imported all necessary libs into one file.

**Comment by scorpionmit01** [comment]
Thanks! Got it working in this environment.

**Comment by tcvdh** [comment]
@scorpionmit01 hey. I can't get it working.. can you explain how to create the files? i can't get webpack to work and vite is also not working for me. giving me weird outputs

**Comment by 0xAsimetriq** [comment]
@tcvdh deff go with vite over webpack if this is for a new project and their docs, particularly on library mode should be a good start https://vitejs.dev/guide/build.html#library-mode

**Comment by tcvdh** [comment]
@0xAsimetriq yeah ive tried but can't seem to get the right files.. right now i am using the V1 for my site. it's just a plain html/js site with some stuff. i used https://github.com/WalletConnect/web3modal/tree/V1#using-in-vanilla-javascript to get everything woring. all just using CDN to import them as a script into the html and then use it. so yeah need the files just like this. can't seem to figure out how to do that myself

**Comment by FSM1** [comment]
In the same boat as some of the other users - I am also attempting to use Web3Modal in a basic HTML+JS solution (Unity WebGL) and therefore don't have access to a build tool as part of the build process.

We had previously used a setup that was based on the https://github.com/WalletConnect/web3modal-vanilla-js-example sample, and that worked perfectly.
