### ISSUE TITLE
We don't support the chainId you provided: eip155:31337

### ISSUE THREAD

**Issue by JohnathanWhite** [WalletConnect/web3modal#801]
Hey there! Using the latest 2.0.0-rc1 - I am getting this error when connected to hardhat

`[{\"field\":\"chainId\",\"description\":\"We don't support the chainId you provided: eip155:31337\"}]}", requestBody="{\"method\":\"eth_getBalance\",\"params\":
`

my config:

```
const chains = [mainnet, polygon, avalanche, bsc, hardhat];
const {provider} = configureChains(chains, [
  walletConnectProvider({projectId}),
]);
const wagmiClient = createClient({
  autoConnect: true,
  connectors: modalConnectors({appName: "web3Modal", chains}),
  provider,
});

const ethereumClient = new EthereumClient(wagmiClient, chains);
```

**Comment by JohnathanWhite** [comment]
workaround for now its to manually specify jsonRpcProvider

const {provider} = configureChains(chains, [
  jsonRpcProvider({
    rpc: (chain) => ({
      http: `http://127.0.0.1:8545`,
    }),
  }),
],);

**Comment by 0xAsimetriq** [comment]
Error is coming from our `walletConnectProvider` which is essentially an rpc, that chain id seems to be refereeing to something called GoChain Testnet which is not supported, hence why you needed custom rpc.
