### ISSUE TITLE
Release Candidate 3 - (hotfix) Details, Discussion and Feedback

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#811]
Changelog
https://github.com/WalletConnect/web3modal/releases/tag/2.0.0-rc.3

**Comment by 1kko-ahnlabio** [comment]
@0xAsimetriq I don't want to be look like spamming, but I really would like to know if there any reason for dropping ABC Wallet. If not, would you add it back again?

**Comment by 0xAsimetriq** [comment]
We started listing injected wallets alongside explorer wallets few versions ago which exposed abc wallet, however it was not working within web3modal due to not exposing itself on `window.ethereum` (as we discussed in prior issue when it was initially added). Did this change by any chance? If so we can look into adding it back. If not, please open a new issue once this is implemented.

**Comment by 1kko-ahnlabio** [comment]
> We started listing injected wallets alongside explorer wallets few versions ago which exposed abc wallet, however it was not working within web3modal due to not exposing itself on `window.ethereum` (as we discussed in prior issue when it was initially added). Did this change by any chance? If so we can look into adding it back. If not, please open a new issue once this is implemented.

Support for `window.ethereum` is on the way for chrome store. I'll update here whenever it's released.

**Comment by 1kko-ahnlabio** [comment]
> We started listing injected wallets alongside explorer wallets few versions ago which exposed abc wallet, however it was not working within web3modal due to not exposing itself on `window.ethereum` (as we discussed in prior issue when it was initially added). Did this change by any chance? If so we can look into adding it back. If not, please open a new issue once this is implemented.

@0xAsimetriq ABC Wallet version 16 has just now released. you may test `window.etherum` with newest version.

**Comment by paouvrard** [comment]
Thank you @0xAsimetriq. I've made a test integration for [rainbowbridge.app](https://rainbowbridge.app/) which has been working well for us. It connects to multiple networks, and uses the ethers Web3Provider from useSigner() which was discussed [here](https://github.com/WalletConnect/web3modal/issues/602). Are there any risks we should be aware of before launching it ? There are currently no "bug" issues reported, when do you think it will be safe/stable to launch, are you planning a major release in the coming days ?

**Comment by 0xAsimetriq** [comment]
@paouvrard We are extremely close to releasing stable version now, I don't forsee any major breaking changes (there haven't been any for few versions now). But we will be changing how theming works at some point to allow for better and easier customisation i.e. config options like `accentColor` etc.. will likely be replace with `theme: {}` object that takes in overrides for multiple styles via css variables like

```
theme: {
 --w3m-color-accent: ...
 --w3m-border-radius: ...
 --w3m-h1-font: ...
}
```

But since there are not that many theming options atm, hopefully this is a quick update latter on for you guys.

**Comment by 0xAsimetriq** [comment]
Closing for https://github.com/WalletConnect/web3modal/issues/832
