### ISSUE TITLE
Reordering Wallet List

### ISSUE THREAD

**Issue by fachryadhitya** [WalletConnect/web3modal#812]
**Is your feature request related to a problem? Please describe.**
Hi guys, I want to use the default wallet list but I cant find a way to re-order it, is there a way to re order the wallet list so I can customize it before the View All wallet?

**Comment by fachryadhitya** [comment]
thanks for the answer! another question that I don't find in the docs:

1. Is there a way to open extension when connecting to trust wallet from desktop? because I've tried in the docs, and when I click trust wallet, the modal told me to install the extension even though  I have installed it 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/58819726/210951425-8324d82c-1992-4e1c-a2c5-c46246d9e8e0.png">

2. We have to specify links if we want to custom wallet options, where can I got those links? https://docs.walletconnect.com/2.0/web3modal/configuration
<img width="263" alt="image" src="https://user-images.githubusercontent.com/58819726/210951670-cebe88e0-7057-4277-9b6f-f6857e1496e6.png">

@0xAsimetriq

**Comment by 0xAsimetriq** [comment]
1. For trust, web3modal should pick it up and open it by default, this is what I'm getting. Do you have any other active extensions that could be conflicting? Have you added `InjectedConnector` to wagmi config (this one is required for extensions)
https://user-images.githubusercontent.com/3154053/211260487-9935c671-f5b0-46c0-b9e8-10b017851b1a.mov

2. `desktopWallets` is used to configure native desktop wallets i.e. ledger live, all these details are up to you to provide (idea here is that you know which custom wallets you want to use). To reuse entries from our explorer (https://explorer.walletconnect.com) you can use allow / deny list configs, but I think there is no way to order them atm, only exclude or include certain wallets.

**Comment by fachryadhitya** [comment]
yeah I have more than one injected wallet; metamask, core, and trust. Can I still open the extension if I have more than one wallet? I actually tried from the docs, and I choose Trust, it's still wont open for me :/

**Comment by 0xAsimetriq** [comment]
That could be the issue. There is no way to reliably open specific one with all of them relying on `window.ethereum` (limitation you'll find in other similar projects as well). This is something extension wallets are currently working on (new standard).

**Comment by fachryadhitya** [comment]
okay then I got it, thanks for the answer, appreciate it! do you want me to close this or no because I saw that you change the label to enhancement and v2 haha

**Comment by 0xAsimetriq** [comment]
We can keep this open 👍 As it is initially about better mechanism to order wallets, which we do need to add

**Comment by fachryadhitya** [comment]
hi @0xAsimetriq sorry for asking again, but how do I disable phantom list in default wallet list? because I don't see phantom in https://explorer.walletconnect.com

**Comment by 0xAsimetriq** [comment]
At the moment it is not possible, as phantom (on desktop) is an injected / extension wallet which comes from manual list available here https://github.com/WalletConnect/web3modal/blob/V2/packages/ui/src/presets/EthereumPresets.ts

But this is part of the greater re-ordering task we are working on which would bring these into cloud explorer as well, thus allowing you to use id's to allow/deny in the future, as well as order.

**Comment by fachryadhitya** [comment]
okay thanks man appreciate it

**Comment by fachryadhitya** [comment]
also this is not related to our topic here but because lately I've been playing so much with web3modal package I realized that you have a small typo here for fetchEnsName, wanted to open my first PR but I feel so shame for just contributing small typo like that hahah  @0xAsimetriq 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/58819726/212335536-ac4bd1b1-bf9d-4441-b3f7-9d90b9dedee6.png">

**Comment by 0xAsimetriq** [comment]
@fachryadhitya Deff go ahead and open that pr 👌 Gotta get into that contributor list 😄

**Comment by fachryadhitya** [comment]
> @fachryadhitya Deff go ahead and open that pr 👌 Gotta get into that contributor list 😄

hahah so kind, LFG
