### ISSUE TITLE
Update Ripio Portal Wallet metadata (injected wallet)

### ISSUE THREAD

**Issue by nicolaswww** [WalletConnect/web3modal#814]
**Is your feature request related to a problem? Please describe.**
Previously we had added Ripio Portal to the list of injected wallets: https://github.com/WalletConnect/web3modal/pull/381
In [this version](https://web3modal.com/try-it-out) of web3modal, the icon and name seems to be broken.

**Describe the solution you'd like**
Extension name: Ripio Portal
Extension image / icon: 
 https://github.com/ripio/web3modal/blob/d0073e7d1eb4061f942de027cb117982ebe4b02d/src/providers/logos/portal.svg
Uniquely identifiable flag: `window.ripioExtension` / `window.ethereum.isPortal`

**Describe alternatives you've considered**
For more compatibility, Ripio Portal is also found in Wagmi.

**Additional context**
<img width="389" alt="Captura de Pantalla 2023-01-09 a la(s) 16 39 34" src="https://user-images.githubusercontent.com/22847001/211394693-de7e6a36-31c4-45e0-9cb3-0db86ddbb929.png">

Thank you!

**Comment by 0xAsimetriq** [comment]
Aiming to have this added in next release 👍

**Comment by nicolaswww** [comment]
@0xAsimetriq great! Can you list our wallet in "view all" too? like MetaMask:

![Captura de Pantalla 2023-01-10 a la(s) 11 38 17](https://user-images.githubusercontent.com/22847001/211580270-42759a71-b330-4149-bdb2-3b235269be80.png)

![Captura de Pantalla 2023-01-10 a la(s) 11 37 39](https://user-images.githubusercontent.com/22847001/211580170-dff47cc4-b301-4a6c-81d8-cc62894c2a2c.png)

**Comment by 0xAsimetriq** [comment]
Will be there by default once added, can you please provide all relevant links and square image of your logo (ideally 400x400) as a png or jpeg

**Comment by nicolaswww** [comment]
@0xAsimetriq yes, of course
<img width="400" alt="Logo_Dark (2)" src="https://user-images.githubusercontent.com/22847001/211604098-75e73c3e-330c-4b5d-be08-769a1f4b1b3d.png">

**Comment by nicolaswww** [comment]
URLs (Button "install extension):

https://www.ripio.com/portal/

Or

Chrome: https://chrome.google.com/webstore/detail/ripio-portal/ddamhapapianibkkkcclabgicmpnpdnj
Firefox: https://addons.mozilla.org/es/firefox/addon/ripio-portal/

**Comment by 0xAsimetriq** [comment]
Injected wallets are now managed through https://cloud.walletconnect.com you can either create a new entry for your project or add your unique injected flag to existing entry.

**Comment by nicolaswww** [comment]
> Injected wallets are now managed through https://cloud.walletconnect.com you can either create a new entry for your project or add your unique injected flag to existing entry.

Thank you for your response, I already submitted the request on https://cloud.walletconnect.com
