### ISSUE TITLE
WalletConnect cloud injected wallet management

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#820]
- We'll be pulling injected wallet data from the cloud soon
- Set up connector to safely parse injected id i.e. check if value exists, run through `String()`, catch error, check for `typeof string` before passing into `window.ethereum`
- Determine wallet's platforms i.e. mobile / desktop / injected

Some known issues exist with ethereum's injected wallets when multiple of them are installed i.e. you expect to open one, but another opens / there are invalid names / some extensions mask themselves as metamask etc.

We could look into developing a custom wagmi connector that takes in injected wallet id/flag and only works when that particular extension is present / installed or prompts user to download it.

- Check `window.ethereum[injectedId]` for existence of provided flag
- Use combination of `name` and `injectedId` to determine metamask masking (lol)
- Test how such connector would work with default wagmi one's (mm, injected etc...)

**Comment by bettiolo** [comment]
Examples of this issue attached

https://user-images.githubusercontent.com/1333608/212993998-8d2f186d-98b3-4812-9977-ee47b14c6713.mov

More context here: https://discord.com/channels/492410046307631105/1063046762622877696/1063046762622877696
