### ISSUE TITLE
Allow to skip rpc calls for balance / ens

### ISSUE THREAD

**Issue by Mahan-F** [WalletConnect/web3modal#824]
**Describe the bug**
As soon as a wallet is connected through the web3modal. A bunch of RPC requests are being made. From what I can see, all the calls are to the following contracts which belong to ENS.

- 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41
- 0xa2c122be93b0074270ebee7f6b7292c7deb45047
- 0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e

I am not calling any of the ENS methods (e.g. `fetchEnsName` or `fetchEnsAvatar`).

Also, one of the calls is for `eth_getBalance`. Again, I'm not calling the `fetchBalance` method.

Are these calls intended? If they are, how can I access their responses? For example the response for `eth_getBalance`. Because when I do call the `fetchBalance` method, I can see that the same request is called again.

**SDK Version**
 - Version 2.0.0-rc.2

**To Reproduce**
1. Connect a wallet through web3modal
2. Watch the chrome dev tools "network" tab

**Expected behavior**
From my understanding, the calls for getting balance, or ENS related stuff should only be called when their methods are called.

**Screenshots**
![image](https://user-images.githubusercontent.com/6375360/212426395-60fe428b-67cf-4f1c-b2c0-9287bd487fb0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by 0xAsimetriq** [comment]
These are intentional calls to resolve some data for web3modal's account view (vid below), however it could be a valid idea to have a flag to skip these. Maybe using `staleTime` from wagmi could result in no additional call in the rpc here? https://wagmi.sh/react/hooks/useBalance#staletime-optional

If not, would you like a flag within config to skip this (we will probably display 0 balance or hide it all together in web3modal ui and will never show ens data in this case).

https://user-images.githubusercontent.com/3154053/212431567-5140d0cf-bc7e-462e-a677-1849bb207201.mov

**Comment by Mahan-F** [comment]
Thanks for the clarification @0xAsimetriq. The app I'm creating has a custom account view, and we call the ENS/Balance endpoints ourselves to populate it.

I think having a flag to skip/disable the account view would be perfect. That way, I can use the wallet connection and handle the account/profile views myself.

Btw, just to clarify, I'm not using the JS version of web3modal 2 (not react).

**Comment by 0xAsimetriq** [comment]
Gotcha, I'll work on this soonish, definitely a valuable option for use cases like yours.

**Comment by 0xAsimetriq** [comment]
@Mahan-F will be part of the 2.0.1 via `enableAccountView` config option, just set it to false for your use case once this version is out

**Comment by Mahan-F** [comment]
> @Mahan-F will be part of the 2.0.1 via `enableAccountView` config option, just set it to false for your use case once this version is out

Thanks a lot!
