### ISSUE TITLE
clone project web3modal/examples/react/ yarn dev Error

### ISSUE THREAD

**Issue by champseo2017** [WalletConnect/web3modal#828]
**Describe the bug**
I clone project web3modal/examples/react/ and command yarn and yarn dev after that got following error

**SDK Version**
"dependencies": {
    "@web3modal/ethereum": "^2.0.0-rc.3",
    "@web3modal/react": "^2.0.0-rc.3",
    "ethers": "^5.7.2",
    "next": "^13.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "wagmi": "^0.10.10"
  },
  "devDependencies": {
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10"
  }

**Error**
<img width="964" alt="Screen Shot 2566-01-17 at 12 11 00" src="https://user-images.githubusercontent.com/32265715/212815556-d076a8d2-b541-4673-9802-872cd8cb701b.png">

TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.

**Comment by 0xAsimetriq** [comment]
There are some docs around dev here https://github.com/WalletConnect/web3modal/blob/V2/.github/docs/development.md

First things first, you need to clone whole repository (it's a monorep) and run `yarn` at the root. Then to start react example

1. Run `yarn dev` to start monorepo packager
2. In new terminal window `yarn dev:react` to start react example

**Comment by champseo2017** [comment]
@0xAsimetriq Thank you very much, I will start following the steps you suggested.

**Comment by champseo2017** [comment]
It works. Success. Thank you very much. @0xAsimetriq
