### ISSUE TITLE
Binance testnet rpc proxy partial outage

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#830]
**Describe the bug**

1/ When we call the ModalCtrl.open() function (from the 2nd time, but sometimes randomly), we have an error which is displayed "Failed preloading" (see screenshot)

Any idea?

![a547404f72b8cf8ea5dc9445f9585d2fdf0810d99f83a8a10040258f49eb5589](https://user-images.githubusercontent.com/8955379/213138303-7a8c0dd6-ff99-44b8-8f9a-6ad2d001674f.jpg)

2/ We would like to hide "w3m-modal-backcard + w3m-toolbar", would it be possible to have an option?
By playing with the style + timer, it's works, but we have a "flicking"

**SDK Version**
 - Version [2.0.0 RC3]

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]

**Environment 
- Vue + Nuxt 2

Thanks

**Comment by 0xAsimetriq** [comment]
If you open network tab, can you pinpoint which requests are failing during preload please. Also you can try `await web3modal.open()` (there is no ModalCtrl in rc3, so I assume that was a typo?)

Currently no plans to removing header section, but we will be re-reviewing that soon once we release stable version and start on customisation tasks.

**Comment by Droppix** [comment]
Strange...
1/ Package.json
"@web3modal/core": "^2.0.0-rc.3",
"@web3modal/ethereum": "^2.0.0-rc.3",
"@web3modal/ui": "^2.0.0-rc.3",

import { ClientCtrl, ConfigCtrl, ModalCtrl, OptionsCtrl } from '@web3modal/core'
import { WalletConnectConnector } from '@wagmi/core/connectors/walletConnect'
import { EthereumClient, modalConnectors, walletConnectProvider } from '@web3modal/ethereum'

2/ the node_modules directory has been destroyed

3/  npm i @wagmi/core@latest @web3modal/core@latest @web3modal/ethereum@latest @web3modal/ui@latest

Did I forget something?

**Comment by 0xAsimetriq** [comment]
You should no longer be using controller pattern, all methods are now accessible on instance of web3modal. Nor using `core` package.

You are probably coming from an older version vanilla js, so want to start using new and simpler html package i.e. https://docs.walletconnect.com/2.0/web3modal/html-js/installation

**Comment by Droppix** [comment]
Ok, but would this explain the POST errors below? (this has been happening frequently for some time)

`
geturl.js?21de:48          POST https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=962def0af1c680c26d6e0f8d4a24bd87 503 (Service Temporarily Unavailable)

geturl.js?21de:48          POST https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=962def0af1c680c26d6e0f8d4a24bd87 503 (Service Temporarily Unavailable)
eval @ geturl.js?21de:48

geturl.js?21de:48          POST https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=962def0af1c680c26d6e0f8d4a24bd87 503 (Service Temporarily Unavailable)

geturl.js?21de:48          POST https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=962def0af1c680c26d6e0f8d4a24bd87 503 (Service Temporarily Unavailable)
```

**Comment by 0xAsimetriq** [comment]
Just checked with bsc testnet, everything seems to be fine with rpc.
Are you by any chance using some sort of proxy / vpn / located in country that might be blocking this request?

For latter, we are working on exposing non `.com` endpoints to unlock our api's in countries that might be blocking them atm. You will be able to configure these i.e. `.org` domains for example. Associated issue https://github.com/WalletConnect/web3modal/issues/829

**Comment by Droppix** [comment]
No VPN, no proxy, we are in France, and we have no problems with the network... We see this error from time to time, but without really understanding...

I also tried with curl ( https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=962def0af1c680c26d6e0f8d4a24bd87 ), same error ....

And there without touching the code, it works again!

**Comment by Droppix** [comment]
Thanks

**Comment by thisisandreww** [comment]
> FYI: 503 Service Temporarily Unavailable (NGINX) same with curl -X POST <img alt="image" width="1494" src="https://user-images.githubusercontent.com/8955379/213225743-43496877-bd64-4c15-9515-c700132fe830.png">

I am receiving this issue from time to time as well when connecting to bsc test net. It seems to occur intermittently when i'm trying to get the wallet balance.

**Comment by arein** [comment]
Hi. We strongly believe that this is not us but our BSC testnet RPC provider.
https://github.com/WalletConnect/rpc-proxy/issues/90 such that we can provide it and give you an according error message for when this happens in the future.

You are also welcome to add a BSC testnet provider you deem stable here: https://github.com/WalletConnect/rpc-proxy

**Comment by Droppix** [comment]
@arein 
It's still very strange, you must admit that it's your NGINX daemon that answers 503 and it's not us?

**Comment by arein** [comment]
We don't use `nginx` at WalletConnect so you're just getting the 503 from our RPC provider as described above

**Comment by Droppix** [comment]
sorry;) I didn't read your previous answer correctly "**but our BSC testnet RPC provider."**
