### ISSUE TITLE
Error Switch Between mode Standard / Standalone

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#837]
**Describe the bug**
I have manage integrated 2 modes in my app (one instance) (Standard: '@web3modal/html' + Standalone: '@web3modal/standalone').
Each mode independently works fine, but if I launch the standalone mode (one or several times), the standard mode doesn't work anymore (openModal seems to stop working, no display, and no logs in the console). 
if I refresh the page, the standard mode works again (I try delete LocalStorage, it has no effect)

```
import { Web3Modal as Web3ModalHTML } from '@web3modal/html'
import { Web3Modal as Web3ModalStandalone } from '@web3modal/standalone'
```

Mode standard:
```

          const ethereumClient = new EthereumClient(wagmiClient, chains)
          this.web3Modal = new Web3ModalHTML(
            {
              projectId: PROJECT_ID,
              themeMode: 'dark',
              themeColor: 'green',
              standaloneChains: undefined
            },
            ethereumClient
          )
          await this.web3Modal.openModal()
```

Mode standalone:
```

          const ethereumClient = new EthereumClient(wagmiClient, chains)
          this.web3Modal = new Web3ModalStandalone(
            {
              projectId: PROJECT_ID,
              themeMode: 'dark',
              themeColor: 'green',
              standaloneChains: undefined
            },
            ethereumClient
          )
          await this.web3Modal.openModal()
```
**SDK Version**
 - Version [2.0.0]

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome, Safari]

**Comment by 0xAsimetriq** [comment]
Using both is almost certain to cause bugs, I don't think we have any plans to support this use case, so a custom fork might be required. Out of curiosity, why do you want to use both? If it is to support WalletConnect v2, that will be coming to react/html packages soon.

**Comment by Droppix** [comment]
We allow the connection of several wallets with different chains of EVM, for example Stellar (WalletConnect V2), and it is unfortunate that we have to reload the page each time we (users) change chainID. The problem is you should have a method of resetting you states. For the moment the only quick and **working** method is this one:


```
import { OptionsCtrl } from '@web3modal/core'

OptionsCtrl.setIsStandalone(false)
OptionsCtrl.setIsDataLoaded(false)
OptionsCtrl.setIsUiLoaded(false)
OptionsCtrl.setStandaloneChains([])
OptionsCtrl.setStandaloneUri(undefined)
```

**Comment by 0xAsimetriq** [comment]
There is complexity of managing wagmi (managed evm) and reacting to some external events here (in html package) while supporting non evm chains as well. I think best case scenario for you is to just use standalone mode for all your chains, as it will provide most stable experience around multi chain via sign sdk.

There are methods to reset states, but these are for internal use only, hence not documented and using controllers in the way above can be risky as it can lead to unexpected state bugs either now or in future updates. You should only use `web3Modal` instance as per docs.
