### ISSUE TITLE
Document edge case when using localhost / ip tunnel for mobile testing 

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#840]
Several reports came in from users who were tunneling their dapp to mobile via localhost / ip setup. Some wallets either threw error or did nothing in this case (potentially a security feature?). Hence for mobile testing to work it needs to be deployed somewhere like vercel. Likely https over localhost / missing certs are also at play here.

I'm not sure if there is anything on our side to do here besides documenting this.

**Comment by paintoshi** [comment]
It's an http issue. It works when using an https tunnel, such as https://www.npmjs.com/package/localtunnel
