### ISSUE TITLE
Angular integration example 

### ISSUE THREAD

**Issue by playground** [WalletConnect/web3modal#844]
When will the example for Angular be available?

**Comment by 0xAsimetriq** [comment]
You can already use web3modal with angular via html package https://docs.walletconnect.com/2.0/web3modal/html-js/installation , but as for actual angular framework wrapper, we are hoping to get started on that as soon as possible, but there are some priorities we need to address first

- Support WalletConnect v2 protocol
- Implement another chain (non evm) support, to then open up web3modal to any chain once we know how multichain api will work
- Few other things like auth sdk support

So if all goes well, hopefully angular and other framework work can begin shortly after.

**Comment by 0xAsimetriq** [comment]
You should definitely go ahead with Web3Modal v2 html (again perfectly usable in angular) implementation as Web3Modal v1 is now deprecated. Support for WalletConnect v2 is also coming soon to Web3Modal, which will be a simple option in config you can update to when WalletConnect v1 gets deprecated. As for when specific angular package will be released, we are probably at least 1 month if not more away from that, unless of-course someone from community tackles that before we do.

**Comment by REPTILEHAUS** [comment]
@0xAsimetriq is there any way to use this with Angular at present ?

**Comment by 0xAsimetriq** [comment]
@REPTILEHAUS Sure, you can use `@web3modal/html` package

**Comment by REPTILEHAUS** [comment]
I tried to follow those docs but i get 
```
1. If 'w3m-core-button' is an Angular component, then verify that it is part of this module.
```

**Comment by 0xAsimetriq** [comment]
`w3m-core-button` is a standard web-component, perhaps you need to define something special in Angular for these? But in general they work fine in any framework.

**Comment by REPTILEHAUS** [comment]
I get type errors coming from coinbase dep etc - Ive always had issues with this library, never any information on getting it to play nice with angular, for now this one just seems to work https://gitlab.com/minds/web3modal-angular i

**Comment by REPTILEHAUS** [comment]
I can never get this library to play nice with angular, its throwing ts issues on the coinbase dep, for anyone that needs it this is a more viable angular solution https://github.com/Minds/web3modal-angular

**Comment by playground** [comment]
@0xAsimetriq  any updates?
