### ISSUE TITLE
useContractRead error "We don't support: eip155:11155111\" (Sepolia), but useContractWrite works!?

### ISSUE THREAD

**Issue by dataexcess** [WalletConnect/web3modal#849]
**Describe the bug**

Hello I am using Web3modal together with wagmi to communincate to my smartcontract on the sepolia network.
I am currently succesfully performing a useContractWrite() but when I try to do a simple useContractRead call however I get the following error:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"xxxxx","data":"xxxxx","accessList":null}, error={"reason":"bad response","code":"SERVER_ERROR","status":400,"headers":{"content-length":"126","content-type":"application/json"},"body":"{\"status\":\"FAILED\",\"reasons\":[{\"field\":\"chainId\",\"description\":\"We don't support the chainId you provided: eip155:11155111\"}]}","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"xxxxx\",\"data\":\"xxxxx\"},\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.walletconnect.com/v1/?chainId=eip155:11155111&projectId=xxxxxxxxx"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (index.js?ffb2:224:1)
    at Logger.throwError (index.js?ffb2:233:1)
    at checkError (json-rpc-provider.js?3e80:64:1)
    at StaticJsonRpcProvider.eval (json-rpc-provider.js?3e80:575:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js?3e80:6:42)
```
Wondering how this is possible? Shouldn't both calls use the same network connection? Is it because wallet connect does not yet support Sepolia? When I go to my wallet connect dashboard I cannot see Sepolia in the list of supported chains. 
Should i use goerli instead? Please help me.

This is how I setup the wagmi environment:

```
import { ReactNode } from 'react'
import { EthereumClient, modalConnectors, walletConnectProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/react'
import { configureChains, createClient, WagmiConfig } from 'wagmi'
import { sepolia } from 'wagmi/chains'

if (!process.env.WALLET_CONNECT_PROJECT_ID) {
  throw new Error('You need to provide WALLET_CONNECT_PROJECT_ID env variable')
}

const projectId = process.env.WALLET_CONNECT_PROJECT_ID
const chains = [sepolia]
const { provider } = configureChains(chains, [
    walletConnectProvider({ projectId }),
])
const wagmiClient = createClient({
    autoConnect: true,
    connectors: modalConnectors({ appName: 'web3Modal', chains }),
    provider,
})
const ethereumClient = new EthereumClient(wagmiClient, chains)

interface Props {
    children: ReactNode
}

export default function Web3Connection({ children }: Props): JSX.Element {
  return (
    <>
      <WagmiConfig client={wagmiClient}>
        { children }
      </WagmiConfig>
      <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
    </>
  )
}

```

**SDK Version**
    "@web3modal/ethereum": "^2.0.0-beta.7",
    "@web3modal/react": "2.0.0-beta.7",

**To Reproduce**
Perform a useContractRead code when connected to Sepolia.

**Expected behavior**
For it to work without this error appearing.

**Comment by 0xAsimetriq** [comment]
Not too much we can give feedback on here, I'd suggest asking wagmi community however.

**Comment by dataexcess** [comment]
Seems like a wallet connect issue to me... 
look at the line "https://rpc.walletconnect.com/v1/?chainId=eip155:11155111&projectId=xxxxxxxxx" in the error message.

Nobody else issued problems using web3 modal with sepolia? 
I just swapped to rainbowkit and now everything works nicely. Rainbowkit also mentions they do support Sepolia while I cannot find that information on the wallet connect dashboard website (please correct me if I'm wrong)

Sorry, I am just trying to help. You can close this issue if you want.

**Comment by 0xAsimetriq** [comment]
@dataexcess ah yes, sorry missed that. So, basically this chain is not supported by our rpc. (which comes from `walletConnectProvider`) . I just noticed you are on `2.0.0-beta.7`, can you try this on latest version? We fall back to rpc defined in wagmi `chain` when it is not supported by us

**Comment by dataexcess** [comment]
do you mean with npm i @web3modal/react@latest ?  => 2.0.0.

I updated  @web3modal/react and  @web3modal/ethereum to 2.0.0

Now I cannot get the code to work anymore. I get a typescript error where i am initialising the wagmi client here:

```
// 2. Configure wagmi client
const chains = [sepolia]
const { provider } = configureChains(chains, [walletConnectProvider({ projectId })])
export const wagmiClient = createClient({
  autoConnect: true,
  connectors: modalConnectors({
    appName: 'web3Modal',
    chains
  }),
  provider
})
```


```
(property) connectors?: (() => Connector<any, any, any>[]) | Connector<any, any, any>[] | undefined
Connectors used for linking accounts

@default

[new InjectedConnector()]
Type '(WalletConnectConnector | InjectedConnector | CoinbaseWalletConnector)[]' is not assignable to type '(() => Connector<any, any, any>[]) | Connector<any, any, any>[] | undefined'.
  Type '(WalletConnectConnector | InjectedConnector | CoinbaseWalletConnector)[]' is not assignable to type 'Connector<any, any, any>[]'.
    Type 'WalletConnectConnector | InjectedConnector | CoinbaseWalletConnector' is not assignable to type 'Connector<any, any, any>'.
      Type 'WalletConnectConnector' is not assignable to type 'Connector<any, any, any>'.
        Property 'onAccountsChanged' is protected but type 'WalletConnectConnector' is not a class derived from 'Connector<Provider, Options, Signer>'.ts(2322)
index.d.ts(799, 5): The expected type comes from property 'connectors' which is declared here on type 'CreateClientConfig<(FallbackProvider | ProviderWithFallbackConfig<Provider>) & { chains: Chain[]; pollingInterval: number; }, WebSocketProvider>'
```

I don't know what's going on

**Comment by dataexcess** [comment]
ahh that's probably a wagmi error then... sorry let me check

**Comment by dataexcess** [comment]
Ok it seems to work on 2.0.0 :D 🙌🙌🙌🙌 
So somehow the fallback chain code is lost in the beta versions?

Thank you for the help
