### ISSUE TITLE
Silence error log in preloadModalData for missing images (testnets / tokens etc.)

### ISSUE THREAD

**Issue by champseo2017** [WalletConnect/web3modal#860]
**SDK Version**
 - "@web3modal/react": "2.1.1",
 - "next": "13.1.6",
 -  "react": "18.2.0",
 -  "react-dom": "18.2.0",

**To Reproduce**
1. add Web3Modal in project
`<Web3Modal
                  projectId={projectId}
                  ethereumClient={ethereumClient}
                  // Custom Linking Mobile Wallets
                  mobileWallets={mobileWallets}
                  // Custom Linking Desktop Wallets
                  desktopWallets={desktopWallets}
                  // Custom Wallet Images
                  walletImages={walletImages}
                  // Custom Chain Images
                  chainImages={chainImages}
                />`

**Screenshots**

<img width="696" alt="Screen Shot 2566-02-06 at 14 14 02" src="https://user-images.githubusercontent.com/32265715/216908196-73711c85-9998-4d48-aec0-2b8a127c0f75.png">

**Comment by 0xAsimetriq** [comment]
What does the actual error say? And at first glance this looks like an error thrown by an image tag, possibly due to a broken or restricted image usage. Could you post which custom images are you using for wallet and chain fields?

**Comment by findtoni** [comment]
It appears even without any custom image props set. Here's what I get.

<img width="300" alt="Screenshot 2023-02-07 at 14 00 56" src="https://user-images.githubusercontent.com/35571969/217252186-bb5dc833-cd5a-4688-ba33-8b498dbca305.png">

**Comment by champseo2017** [comment]
This is the custom images walletImages that I use in component Web3Modal

`export const walletImages = {
  metaMask: "/assets/images/imageNewChain/wallet_metamask.webp",
  brave: "/assets/images/imageNewChain/wallet_brave.webp",
  ledger: "/assets/images/imageNewChain/wallet_ledger.webp",
  coinbaseWallet: "/assets/images/imageNewChain/wallet_coinbase.webp",
  zerion: "/assets/images/imageNewChain/wallet_zerion.webp",
  trust: "/assets/images/imageNewChain/wallet_trust.webp",
  rainbow: "/assets/images/imageNewChain/wallet_rainbow.webp",
  oreid: "/assets/images/imageNewChain/wallet_oreid.svg"
};`

This is the custom images chainImages that I use in component Web3Modal
`export const chainImages = {
  137: "/assets/images/imageNewChain/chain_polygon.webp",
  10: "/assets/images/imageNewChain/chain_optimism.webp",
  42161: "/assets/images/imageNewChain/chain_arbitrum.webp"
};`

@0xAsimetriq

**Comment by memochou1993** [comment]
@0xAsimetriq 

Hi

I got the same error.

This repo can reproduce the behavior.

https://github.com/memochou1993/web3modal-v2-example

**Comment by 0xAsimetriq** [comment]
@memochou1993 just pulled the repo and everything worked for me, which node / npm version are you on and what do you do to get the error?

My steps were
1. Download the repo
2. Delete package lock file (just in case)
3. `npm i` and `npm run dev`, everything worked

I'm on `node@19.5.0` and `npm@9.3.1`

**Comment by memochou1993** [comment]
@0xAsimetriq 

Node Version: v18.12.1
NPM Version: 8.19.2

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/38420282/217595946-3be78c41-6e40-4b9f-9e96-c2fd33f73cb8.png">

**Comment by 0xAsimetriq** [comment]
Found the issue (at least in your case @memochou1993 ), it is due to there being no image for `goerli` chain. Not a critical error, but I will look into making it silent 👍

**Comment by champseo2017** [comment]
I still got an error but most of the functions still work. @0xAsimetriq

**Comment by d1onys1us** [comment]
yeah @0xAsimetriq i also got this from adding sepolia testnet. would agree silencing it is a good path

**Comment by haidarabdillah** [comment]
anyone still get this issue?
node : v16.20.0
"vue": "^3.2.47"
"@walletconnect/modal": "^2.5.9",
"@web3modal/ethereum": "^2.6.2",
"@web3modal/html": "^2.6.2",


i can't custom the 
`chainImages` and `tokenImages` and `walletImages` too
![image](https://github.com/WalletConnect/web3modal/assets/113880800/4075a3cd-c7a2-4072-8e38-d867c00bfe58)

**Comment by 0xAsimetriq** [comment]
@haidarabdillah `walletImages` and other options should be placed in same options object where `projectId` is. Also `@walletconnect/modal` and `@web3modal/ethereum / @web3modal/html` are two different modal libraries, you likely want to remove walletconnect one. You can also place themeMode and themeVariables inside Web3Modal's options initially. `setTheme` is meant to be used when you want to "change theme" later on
