### ISSUE TITLE
export 'providers' (imported as 'providers') was not found in 'ethers' issues

### ISSUE THREAD

**Issue by shinwong97** [WalletConnect/web3modal#862]
**Describe the bug**
Seems like wagmi is deprecated some packages ie: json-rpc

**SDK Version**
"wagmi": "^0.11.4"

Trying to configure and setting up web3modal but when npm run start, will show the following errors:

![image](https://user-images.githubusercontent.com/59962717/217045222-8d3cde85-38b2-4af3-94b8-14ea0af03bf7.png)

**Comment by 0xAsimetriq** [comment]
Which version of ethers are you using? wagmi is not compatible with v6 yet

**Comment by shinwong97** [comment]
> Which version of ethers are you using? wagmi is not compatible with v6 yet

Ohh I see. Im using v6 at the moment. Guess ill downgrade it to 5 first. Thanks
