### ISSUE TITLE
add harmony one network

### ISSUE THREAD

**Issue by marsidorowicz** [WalletConnect/web3modal#868]
**Is your feature request related to a problem? Please describe.**
Adding Harmony one Shard1

**Describe the solution you'd like**
Add chain harmony as follows or similar:

```
export const harmony: Chain = {
	id: 1666600000,
	name: 'Harmony One',
	network: 'harmony',
	nativeCurrency: {
		decimals: 18,
		name: 'Harmony',
		symbol: 'ONE'
	},
	rpcUrls: {
		public: { http: ['https://rpc.ankr.com/harmony'] },
		default: { http: ['https://rpc.ankr.com/harmony'] }
	},
	blockExplorers: {
		etherscan: { name: 'Ankr', url: 'https://rpc.ankr.com/harmony' },
		default: { name: 'Ankr', url: 'https://rpc.ankr.com/harmony' }
	},
	contracts: {
		multicall3: {
			address: '0xca11bde05977b3631167028862be2a173976ca11',
			blockCreated: ??? needs blockCreated !!!!!!!!!!!
		}
	}
}
```

**Comment by 0xAsimetriq** [comment]
We are currently exposing only those chains that are available in wagmi, but as you demonstrated anyone can add any evm chain. To have harmony as a preset, I'd suggest opening similar issue but within wagmi repo.

**Comment by marsidorowicz** [comment]
sure!

**Comment by marsidorowicz** [comment]
Done, waiting for accepting merge from wagmi team! Can I get some help if any questions arise about web3modal? I did implement it into my project cyberwealth.pro with cross chain swaps :) for now few chains, plus harmony soon...
