### ISSUE TITLE
Modal not picking up metamask

### ISSUE THREAD

**Issue by fachryadhitya** [WalletConnect/web3modal#870]
**Describe the bug**
first of all, thank you so much for building this lib. It helps me as a dev a **lot**. I have one question, sometimes, the modal is not picking up my metamask connection, is there a way to make this not happen?

**SDK Version**
 - web3modal/html version 2.1.1

**Expected behavior**
the modal should pick up metamask right after I choose metamask, but sometimes it is not and I have to refresh to make it connect successfully

**Screenshots**
<img width="405" alt="image" src="https://user-images.githubusercontent.com/58819726/218237100-6cf1fa3b-edc4-4f52-a494-928ec5694b3d.png">

**Comment by 0xAsimetriq** [comment]
Could you please provide a video for this flow. If metamask is under password lock / was opened and hidden (lost focus) before, it will not pop up in those cases and unfortunately there isn't much we can do about this.

**Comment by 0xAsimetriq** [comment]
closing as stale, please ping me when more details are available
