### ISSUE TITLE
Webpack babel pluggin issue

### ISSUE THREAD

**Issue by AndonMitev** [WalletConnect/web3modal#876]
Hello, I'm using following packages:

```
"@web3modal/standalone": "^2.1.1",
"react": "^16.9.0",
"react-scripts": "^4.0.3",
```

But when i try to compile the project i face this issue:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/32274987/218297455-07a5f8be-5f23-443a-b895-4280923e19ca.png">

I have installed these babel pluggins:

```
"@babel/plugin-proposal-nullish-coalescing-operator": "^7.18.6",
"@babel/plugin-syntax-optional-chaining": "^7.8.3",
"@babel/plugin-transform-runtime": "^7.19.6",
```

and plug them as expected:

```
  "babel": {
    "plugins": [
      [
        "@babel/plugin-proposal-decorators",
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-syntax-optional-chaining",
        "@babel/plugin-transform-runtime",
        {
          "legacy": true
        }
      ]
    ],
    "presets": [
      "react-app"
    ]
  },
```

But still can't manage to find the right loader looks like, any suggestions?

**Comment by 0xAsimetriq** [comment]
Not too familiar with how babel plugins need to be set up with react-scripts, but everyone who came across this issue resolved it via upgrading to latest version of react-scripts (it has newer babel that supports all of this by default without any plugins). We also have an example based on this here https://github.com/WalletConnect/web3modal/tree/V2/examples/create-react-app

As to how to do it on earlier versions, I think it's best to ask within create react app community.
