### ISSUE TITLE
Using wagmi MetaMask connector conflicts with InjectedConnector

### ISSUE THREAD

**Issue by Cristi6** [WalletConnect/web3modal#879]
**Describe the bug**
So I'm already using MetaMask inside my Dapp and I want to integrate WalletConnect but the React implementation because of it's easiness to implement but I have the following issue:

When I have the MetaMask extension and any other wallet extension (like CoinBase, TokenPocket, etc.), in the WalletConnect modal when I click on MetaMask the extension is not recognized as installed.

As a solution to the above I added the MetaMask connector manually in the wagmi client config, but then:
1. When I have only MetaMask installed, MetaMask appears twice in the WalletConnect modal.
2. If I have MetaMask and another wallet extension, all appears good (the wallet extension and MetaMask appear as Installed in the WalletConnect modal) but when I click on MetaMask it still opens the other wallet extension.

Are there any solutions for this on my side? Or will there be a version soon that will take care of situations like this?

**SDK Version**
"@web3modal/ethereum": "^2.1.1",
"@web3modal/react": "^2.1.1",
"wagmi": "^0.11.4",

**Expected behavior**
I'd expect to see all the wallet extensions I've added to my browser in WalletConnect separately by default.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version Latest

**Comment by 2facedsquid** [comment]
Same problem happening to me, exactly the same environment scenario, the only work around I found is using the coinbase wallet and on the first pop up you can actually choose metamask and then use metamask through the coinbase wallet

**Comment by 0xAsimetriq** [comment]
In essence you want custom connectors, so will need to remove `modalConnectors` and replace it with array of connectors that you need. Make sure to include `WalletConnectConnector`, this is the only one that is required.

**Comment by Cristi6** [comment]
That still doesn't work correctly.

1. I have the MetaMask and Coinbase wallet extensions installed and I've replaced modalConnectors with 
`    connectors: [
        new WalletConnectConnector({
            chains,
            options: { qrcode: false, version: '2', projectId: Config.WALLET_CONNECT_KEY },
        }),
        new InjectedConnector({
            chains,
            options: { shimDisconnect: true, shimChainChangedDisconnect: true },
        }),
        new MetaMaskConnector({ chains }),
    ],`
and now when I open the WalletConnect modal and I click on MetaMask the active connector returned by useAccount from wagmi shows that the active connector is `id: "injected", name: "Coinbase Wallet"`. It should be MetaMask.

2. Removing the InjectedConnector from the connectors array resolves in the error from the image when I click MetaMask in the WalletConnect modal.

![image](https://user-images.githubusercontent.com/60075655/218776476-2fc23559-df56-4450-8953-db67461cebc4.png)

**Comment by 0xAsimetriq** [comment]
Hmm, looks like internally it tries to treat metamask connector as injected, causing the error. Will reopen this issue to dive deeper and see if it is resolvable 👍
