### ISSUE TITLE
Package size seems larger than it should be

### ISSUE THREAD

**Issue by Mahan-F** [WalletConnect/web3modal#883]
**Describe the bug**
I'm using the `/ethereum` and `/html` packages and just wondering about the package size. On the web3modal website, I see this:
![image](https://user-images.githubusercontent.com/6375360/218788589-181a201a-d046-4fff-afb4-a914f7d8b099.png)

But on the VSCode package cost, the sizes shown are much larger. 

![image](https://user-images.githubusercontent.com/6375360/218788261-b9c6148e-aca5-4070-817c-19151e2631f0.png)

Am I doing something wrong causing the larger package size?

**SDK Version**
 - Version 2.1.1

**Comment by 0xAsimetriq** [comment]
Use npm registry or tools like [bundlephobia](https://bundlephobia.com) could help here. Calculate for

@web3modal/html
  - @web3modal/ui
  - @web3modal/core
@web3modal/ethereum

There is also tree shaking involved when you build and other factors, so in reality you'll get even smaller bundle size than what we mention on web3modal.com website when using modern build tools like vite / esbuild.

I'm not sure how / which tool is used in vscode to calculate those sizes and what it includes in calculation. Best way to check all of this is to build your bundle.

Will be closing this issue as it does not fall under bug, rather a discussion maybe?
