### ISSUE TITLE
Lit is in dev mode. Not recommended for production!

### ISSUE THREAD

**Issue by aalmada** [WalletConnect/web3modal#887]
**Describe the bug**
When using `@web3modal/react` the message `Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.` appears in the browser console.

**SDK Version**
 - 2.1.1

**To Reproduce**
I followed the installation instruction from https://docs.walletconnect.com/2.0/web3modal/react/installation

**Expected behavior**
Lit in dev mode should not be used as stated in the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/534533/219329886-912b6a52-827d-4ebb-b899-3c108d1503b4.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.1 (22C65)
 - Browser: Microsoft Edge 
 - Version: 110.0.1587.41 (Official build) (arm64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xAsimetriq** [comment]
This message will be present in development, but not when you build a production bundle i.e. inspect our prod deployments and you shouldn't see it there.

https://lab.web3modal.com/v1Base
https://web3modal.com

If you are seeing this in production, it's likely something is misconfigured within build tool you are using (maybe it doesn't set `NODE_ENV` to production or something similar?)

**Comment by songkeys** [comment]
Is there a way to disable this warning? It's polluting my console.
