### ISSUE TITLE
explorerDenyList / explorerAllowList issue

### ISSUE THREAD

**Issue by clrhc** [WalletConnect/web3modal#895]
just using the IDs given on wallet connect to allow certain wallets or remove some give the following issues

using explorerAllowList for IDs like trust wallet using the walletid "trust" doesnt add it to the list

using explorerDenyList for too many IDs removes the show all button when choosing a wallet
some of the IDs do not remove the options from the list
using IDs like "phantom" to remove phantom wallet doesnt actually work

**Comment by 0xAsimetriq** [comment]
"trust" and "phantom" are invalid id's for these fields, you need to copy them from https://explorer.walletconnect.com
