### ISSUE TITLE
ethers `provider.send("personal_sign", ...)` doesn't work on mobile

### ISSUE THREAD

**Issue by 0xSwego** [WalletConnect/web3modal#896]
**Describe the bug**
when the ethers `signer.signMessage` method is invoked on mobile, nothing happens (correctly working on desktop).
Under the hood, `provider.send("personal_sign", ...);` is called.

I've tried by connecting with Brave wallet, MetaMask and Rainbow.

**SDK Version**
 - 2.1.1

**Expected behavior**
The wallet app should be triggered, a message should be signed.

**Smartphone:**
 - OS: both iOS & Android
 - Browser: Brave, chrome

**Comment by 0xAsimetriq** [comment]
Could you provide more details around your implementation please

**Comment by AlvinAtDotty** [comment]
@0xAsimetriq sure!

Initialization:
```JavaScript
const wcProvider = walletConnectProvider({ projectId: "xxx" });
const { provider } = configureChains(chains, [wcProvider]);
const wagmiClient = createClient({
    autoConnect: true,
    connectors: modalConnectors({
        projectId: "xxx",
        version: "1",
        appName: "web3Modal",
        chains
    }),
    provider
});
const ethereumClient = new EthereumClient(wagmiClient, chains);
```

React code:
```JavaScript
<WagmiConfig client={wagmiClient}>
    <Web3Modal projectId="xxx" ethereumClient={ethereumClient} />
    {/* Header */}
    <div className="header">
         <Web3Button />
    </div>

    {/* Other stuff.... */}
</WagmiConfig>
```

When the wallet is connected, a modal appears prompting the user to authenticate through a button. When the button is pressed, the following code is executed:
```JavaScript
const triggerLogin = async () => {
    const message = ...; // retrieve message from backend
    
    const provider = new ethers.providers.Web3Provider((window as any).ethereum);    // <<<-- could the problem be here?
    const signer = provider.getSigner();
    const signedMessage = await signer.signMessage(message); 
    
    // send signed message to backend 
};
```

Is `window.ethereum` also supposed to work on mobile? Is there another way I should get it?

**Comment by 0xAsimetriq** [comment]
I see, I think issue here is separate usage of ethereum provider (your own one and one wagmi uses internally).

There can be 2 solutions to this

1. You can stick to using wagmi, thus sign message via https://wagmi.sh/docs/hooks/useSignMessage
2. Instead of creating your own provider and getting signer from it, get signer from wagmi via https://wagmi.sh/react/hooks/useSigner (this is also ethers signer)

**Comment by AlvinAtDotty** [comment]
@0xAsimetriq it worked! Thanks a lot!
