### ISSUE TITLE
on using Phantom wallet it doesn't recognize it is is already installed, no solana chain 

### ISSUE THREAD

**Issue by marsidorowicz** [WalletConnect/web3modal#898]
**Describe the bug**
on using Phantom wallet it doesn't recognize it is is already installed in a browser, no solana chain 

**SDK Version**
2.1.1

**To Reproduce**
1. Go to connect button
2. Click on chain
3. select phantom wallet
4. See error it asks to install although other sites see it

**Expected behavior**
Should see it even if solana chain is not available

**Screenshots**
![image](https://user-images.githubusercontent.com/36972693/220138082-39d0942a-69b8-4a07-88e6-24d4983bd46a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Wersja 110.0.5481.104 (Oficjalna wersja) (64-bitowa)

**Comment by 0xAsimetriq** [comment]
I think you forgot to add link to the dapp?

**Comment by marsidorowicz** [comment]
you mean my platform using web3modal? it is cyberwealth.pro/app

**Comment by marsidorowicz** [comment]
after commit on references in wagmi, how long it takes to get minor update into new release? I added Harmony One chain

**Comment by 0xAsimetriq** [comment]
Just tested your use-case, does phantom already support evm chains? We added it into the modal a while ago, but perhaps they didn't release this version yet.

I am looking at `window.ethereum` and it seems like phantom is not injecting it, only `window.phantom` for solana.

**Comment by marsidorowicz** [comment]
I would like to contribute more for web3modal and wagmi :) so will web3modal work with window.solana?

**Comment by 0xAsimetriq** [comment]
So, if `@web3modal/standalone` and `@walletconnect/sign-client` are used together as per this example https://docs.walletconnect.com/2.0/web3modal/standalone/installation then yes, you can already use any chain or combination of them, however only with walletconnect specific functionality.

To manage injected extensions / getting balances etc. we rely on wagmi for eip155 chains (evm chains). We started solib for this purpose for solana, but team is currently busy with protocol v2 updates. We will, however, return back to solana integration soon.

Feel free to play around with solib and see if you can bring it to a state where it supports similar api as `@web3modal/ethereum` package (https://github.com/WalletConnect/web3modal/tree/V2/chains/ethereum)

But we might need to tweak things in web3modal as well to support proper multichain.

For now I will close this issue, I'm pretty sure phantom's evm support is not rolled out yet (or maybe it is behind some feature flag?) so it won't work at the moment.

**Comment by marsidorowicz** [comment]
Thanks very much ill stick to web3modal and will help if possible, cheers!
