### ISSUE TITLE
Support browser compatible AMD/UMD standalone js for V2

### ISSUE THREAD

**Issue by jaan** [WalletConnect/web3modal#904]
### Link to minimal reproducible example

NA

### Summary

Web3modal v2 has issues with generating standalone js. Could you please provide support for the feature?

Web3modal v1 supports standalone js for browsers
https://unpkg.com/web3modal@1.9.0/dist/index.js

### List of related npm package versions

web3modal@v2.0.0

**Comment by 0xAsimetriq** [comment]
Closing as a duplicate of #678
