### ISSUE TITLE
[task] Trigger auto-connect if modal is in mobile and has injected connector (in-wallet browsers)

### ISSUE THREAD

**Issue by 0xAsimetriq** [WalletConnect/web3modal#909]
### Summary

Upon detecting mobile and injected provider, trigger auto-connection prompt as we are in a "in-wallet" browser.

However with ios safari extensions now making appearance, we might need to expand on this to somehow allow in-wallet browsers to indicate which injected connector they use.

**Comment by da748** [comment]
Wallet connect finally here on web3 network

**Comment by da748** [comment]
I'm still and always here

**Comment by 0xAsimetriq** [comment]
We added this in, but unfortunately can't reliably detect whether dapp is in a mobile wallet webview or normal mobile browser. With support for web wallets and new mobile extension wallets now in place, we'll be opening modal all the time, but injected wallet will always be there at the front if it is installed.
