### ISSUE TITLE
[bug] Respect chain switching and update listings according to curently selected defaultChain

### ISSUE THREAD

**Issue by crypto-services** [WalletConnect/web3modal#912]
### Link to example

https://react-app.walletconnect.com/

### Summary

There are a couple of issues with the explorer list stemming from the core package as far as I can tell.

core/src/controllers/ExplorerCtrl.ts does not take in to consideration the chain when calling previewWalletsTemplate. This results in the first wallets being shown to the user often not supporting the selected chain. 

Additionally the list of wallets does not update when you change the standalone chain, except when there are no items in the list. If on desktop you select Cosmos, the desktop list is empty as expected.. same for Near. If you then click on Ethereum the list will update but then not again after. If you go back to Cosmos it will now show all the Ethereum wallets. The state is updated as search still reveals the correct results however the list shown is what ever was loaded first. Same for mobile.

I noticed this in my own project and confirmed by testing the example standalone app (both locally and on the project url).

Using chrome on MacOS and tried an iOS simulator with Safari with the same result.  

### List of related npm package versions

core + standalone (current versions)

**Comment by crypto-services** [comment]
Small update. I think the issue is it's attempting use state as it's being, in the same way you'd get random behaviour in react when attempting to set state and use it in the same method. 

I set an allow list for each chain/render and used a different instance of the modal for each load but you still have to click twice to update the list (after the first load) which leads me to believe the issue is in core and coming from state being set and used in the same chain of methods.

**Comment by 0xAsimetriq** [comment]
Closing this as wallet display has changed in v3, we will show all wallets by default with options to override. Per chain wallet display will not work correctly as of now as there are many factors that need to be considered like if wallet supports wallet_addEthereumChain method / added this data in our cloud dashboard. Unfortunately data is not too reliable on this at the moment.
