### ISSUE TITLE
[feature] Packages deprecated

### ISSUE THREAD

**Issue by jcardenes-via** [WalletConnect/web3modal#915]
### What problem does this new feature solve?

the installation of walletconnect modal depends on several outdated dependencies as:

`npm WARN deprecated @json-rpc-tools/provider@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm WARN deprecated @json-rpc-tools/utils@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm WARN deprecated @json-rpc-tools/types@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
`

### Describe the solution you'd like

update dependencies not to rely on legacy packages

**Comment by 0xAsimetriq** [comment]
Looked over these and I don't think there is a way for us to resolve the warnings on web3modal level. We don't actually use any of these directly and keep our dependencies updated with every new release.
