### ISSUE TITLE
Connecting to an installed desktop extension opens blank page [bug] 

### ISSUE THREAD

**Issue by Alexandra-Popa** [WalletConnect/web3modal#916]
### Link to minimal reproducible example

https://wagmi.sh/examples/connect-wallet

### Summary

I have installed the following Chrome browser extensions: MetaMask, Exodus, Crypto.com, OneKey.

When I open WalletConnect and select Desktop, OneKey appears 3 times, and on click of one of the above (installed extensions) I get for each errors like:
Failed to launch 'cryptowallet://wc?uri=wc%3A420a9173-567d-47c2-96ee-092d4d128107%401%3Fbridge%3Dhttps%253A%252F%252Ff.bridge.walletconnect.org%26key%3D2fda74876a8aac70a239f9b4119f238a0423909684623422049199c7fc963819' because the scheme does not have a registered handler.

And instead of opening the browser extension wallet, a blank page opens in a new tab.

Also, I get similar behaviour and errors as above for other wallets like: Ledger, Wallet3, Bobablocks.

### List of related npm package versions

https://wagmi.sh/examples/connect-wallet

**Comment by 0xAsimetriq** [comment]
Invalid minimal reproduction and package versions, please re-create the issue with details that can help us identify the issue better.
