### ISSUE TITLE
[bug] QR Code connection issue after updating to version 2 and setting chains to `crossbell`

### ISSUE THREAD

**Issue by runjuu** [WalletConnect/web3modal#922]
### Link to minimal reproducible example

https://github.com/runjuu/crossbell-wallet-connect-v2-example

### Summary

Hi, I encountered an issue when updating to version 2 and setting the chains to `[crossbell]` (import from @wagmi/core/chains). Unfortunately, I am unable to connect using QR Code. I attempted to use both Trust Wallet and Spot Wallet, but neither were successful. Interestingly, version 1 worked without any issues.

### Trust Wallet
![IMG_7557](https://user-images.githubusercontent.com/12002941/223306068-3d84c991-0f2f-4551-bd45-a40679355e2f.jpg)

### Spot Wallet
![IMG_7556](https://user-images.githubusercontent.com/12002941/223306123-b4854a47-f83d-4d8f-a70c-4f0b0943b03e.jpg)

### List of related npm package versions

"@wagmi/core": "0.9.6",
"@web3modal/ethereum": "2.1.3",
"@web3modal/html": "2.1.3",
"ethers": "5.7.2"

**Comment by 0xAsimetriq** [comment]
Does v2 work with our wallet example? https://react-wallet-eip155.vercel.app

**Comment by runjuu** [comment]
Hi @0xAsimetriq , I'm unsure of how to change the network to `crossbell` on [https://react-wallet-eip155.vercel.app](https://react-wallet-eip155.vercel.app). Additionally, I was wondering if there are any Git repositories that I could clone to test the `crossbell` network? 

Thank you for your help!

**Comment by 0xAsimetriq** [comment]
@runjuu Could you deploy your app to somewhere like vercel so we can test it (dapp) against our wallet https://react-wallet-eip155.vercel.app

My hunch is that Trust is not handling combo of v2 / crossbell properly, so I want to test against our demo wallet which allows connection with any chain. If it works out there, issue is likely with trust wallet.

**Comment by 0xAsimetriq** [comment]
Closing due to innactivity
