### ISSUE TITLE
[bug] balance displays _._ ETH when account has exactly 1 ETH

### ISSUE THREAD

**Issue by d1onys1us** [WalletConnect/web3modal#923]
### Link to minimal reproducible example

https://dapp-slaps.vercel.app

### Summary

If you have exactly 1 ETH on any chain (for example baseGoerli), then the balance will show "__.__ ETH" instead of "1 ETH" or "1.000 ETH". I tested this thoroughly, I'm very confident it's a bug (compared against other wallets like rainbowkit, tried eth.getBalance calls, compared against metamask etc.)

Hope this can get fixed, and thank you! Please let me know if this is not reproducible, but should be fairly straightforward. 

### List of related npm package versions

"@wagmi/core": "0.9.6",
"@web3modal/ethereum": "^2.1.3",
"@web3modal/html": "^2.1.3",

**Comment by 0xAsimetriq** [comment]
Possibly related https://github.com/WalletConnect/web3modal/pull/885
