### ISSUE TITLE
[docs] Invalid Discord invite link

### ISSUE THREAD

**Issue by 70nyIT** [WalletConnect/web3modal#929]
### Summary

In the docs, the Discord invitation link in the footer of the page is `invalid`

![image](https://user-images.githubusercontent.com/12898752/224164420-5dbdc62f-ddb3-40a6-a7b4-d914c3cf692f.png)

This is the link: https://discord.com/invite/cB54BwPGru

If you try to access, it says is invalid or expired. This is the line of the file in docs where the link should be replaced:

https://github.com/WalletConnect/walletconnect-docs/blob/6f8c54f0126488854e12615e1b867c3c4bda7acd/docusaurus.config.js#L133

### Link to the related docs page

https://docs.walletconnect.com/2.0/web3modal/react/installation

**Comment by 0xAsimetriq** [comment]
Thank you 🙏
