### ISSUE TITLE
[bug] Using Native Browser + Trust Wallet -> Trust Wallet is not opening on the write smart contract function

### ISSUE THREAD

**Issue by Trynight** [WalletConnect/web3modal#937]
### Link to minimal reproducible example

https://deelance.com/

### Summary

Hi!

The connection works perfectly, I'm able to connect from chrome on Android perfectly .. the dapp automatically opens my Trust Wallet and then connects me on the native browser.

But this thing does not happen when I try to call a write function of the smart contract, I am not redirected to the wallet but the write function is opened on the trust wallet if I manually go to the wallet.

Code of the write function:
```

 const buyNFT = async (e) => {
    e.preventDefault();

    if (!account) {
      return;
    }

    const token = selectedToken;
    const nftAmount = nftAmountElement.current.value;

    try {
      let transaction = null;
      const xx = await contracts.Main.salePrice();
      const xxx = ethers.utils.formatEther(xx);
      console.log(nftAmount * xxx);
      if (nftAmount * xxx < 9.8) {
        console.log("Amount is", nftAmount * xxx);
        alert("Please insert more than 10$ to buy!");
        return;
      }
      if (token == "ETH") {
        const ETHAmount = await contracts.Main.getETHAmount(
          ethers.utils.parseUnits(nftAmount.toString(), "wei").toString()
        );
        console.log(ETHAmount.toString());
        
        transaction = await contracts.Main.buyWithETH(nftAmount, {
          value: ETHAmount.toString(),
        });
      } else {
        const tokenAmount = await contracts.Main.getTokenAmount(
          nftAmount.toString(),
          0
        );
        const b = parseInt(
          await contracts["USDT"].allowance(account, contracts.Main.address),
          10
        );

        if (b <= 0) {
          console.log("sono qui");
          transaction = await contracts["USDT"].approve(
            contracts.Main.address,
            "10000000000000000000000000000000000000000000000000000000000"
          );
        } else {
          console.log("SIIII", nftAmount.toString());
          transaction = await contracts.Main.buyWithUSD(
            nftAmount.toString(),
            0
          );
        }
      }
      const tx_result = await transaction.wait();
      alert(`Successfully transaction! TX: ${tx_result.transactionHash}`);
      console.log("transaction", tx_result.transactionHash);
      setSomeState(!somestate);
    } catch (error) {
      alert(
        "Error occured during transaction. Please check the browser console.\n" +
          error.reason
      );
      console.error("Transaction Error:", error.reason);
      setSomeState(!somestate);
    }
  };
```

### List of related npm package versions

"@web3modal/ethereum": "2.1.2",
"@web3modal/react": "2.1.2",
"wagmi": "^0.11.7",

**Comment by 0xAsimetriq** [comment]
Could you please try with latest versions of web3modal and wagmi packages. We added missing deeplinking functionality there which was missing when using version `2`

**Comment by 0xAsimetriq** [comment]
Yep, that vercel link will be useful 👍 just trust wallet, or any others you can confirm this with?

**Comment by 0xAsimetriq** [comment]
Ty for the repros, I'll have a deeper look 👍 

1. Metamask is not supported on mobile when you use version `2`
2. Looks like Trust Wallet is mishandling universal links, will reach out to them

**Comment by 0xAsimetriq** [comment]
We are working on solution that will prioritise older deeplinks for mobile vs. newer universal link approach. While they are an older approach, they are much more stable. Unfortunately most wallets on version `2` seem to have their universal links not supported properly. For me walelts like Trust and Zerion don't work, while alpha wallet and spot worked.

For time being I recommend using version `1`, however you'll still encounter issues until we deploy version of web3modak that uses deeplinks over universal links. (some time next week is the target)

**Comment by Romeo23ty** [comment]
Do you need help

**Comment by 0xAsimetriq** [comment]
As I mentioned above, work on resolving this is already underway, will land in `2.3` release
