### ISSUE TITLE
[feature] Option to not switch the default chain upon connecting

### ISSUE THREAD

**Issue by oconnorjoseph** [WalletConnect/web3modal#956]
### What problem does this new feature solve?

Our platform is cross-chain. When the user connects their wallet, we don't need them to be on one specific chain. We only need them to switch chains later on in the user journey. Right now, Web3Modal requires them to switch chains to Ethereum, which annoys the cohort of users who a few seconds later have to switch back to Polygon.

### Describe the solution you'd like

We would benefit greatly from not requiring the user to switch chains after authenticating. Perhaps this can be a `defaultChain={null}` property passed to the React `<Web3Modal />` component?

**Comment by shaffy9633** [comment]
This is a great suggestion. Could possibly use this in a app im building

**Comment by 0xAsimetriq** [comment]
I like the proposal of `defaultChain={null}` I think we can check for this and underneath call wagmi's `connect` method without passing chain argument. This should do the trick 👍 Will try to squeeze this into next version as well.
