### ISSUE TITLE
[bug] Cannot find module ... or its corresponding type declarations

### ISSUE THREAD

**Issue by smelnikov** [WalletConnect/web3modal#960]
### Link to minimal reproducible example

https://github.com/smelnikov/walletconnect-sample/tree/web3modal-tsc-errors

### Summary

**To Reproduce:**
Checkout branch `web3modal-tsc-errors` of repo:
https://github.com/smelnikov/walletconnect-sample

```sh
yarn install
tsc
```
This produces many errors of same type:
```sh
node_modules/@web3modal/core/dist/_types/src/controllers/ClientCtrl.d.ts:5:22 - error TS2307: Cannot find module '@web3modal/ethereum' or its corresponding type declarations.

5     client(): import("@web3modal/ethereum").EthereumClient;
                       ~~~~~~~~~~~~~~~~~~~~~

node_modules/@web3modal/core/dist/_types/src/controllers/OptionsCtrl.d.ts:8:32 - error TS2307: Cannot find module '@wagmi/chains' or its corresponding type declarations.

8     getSelectedChain(): import("@wagmi/chains").Chain | undefined;
                                 ~~~~~~~~~~~~~~~

node_modules/@web3modal/core/dist/_types/src/types/controllerTypes.d.ts:1:44 - error TS2307: Cannot find module '@web3modal/ethereum' or its corresponding type declarations.

1 import type { Chain, EthereumClient } from '@web3modal/ethereum';
                                             ~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in 3 files.
```

Adding `yarn add -D @web3modal/ethereum` to dependencies causes more type declaration errors.

**Expected behavior**
There are no errors.

### List of related npm package versions

"@walletconnect/sign-client": "2.5.2",
"@web3modal/standalone": "^2.2.2",
"typescript": "^4.9.3"

**Comment by 0xAsimetriq** [comment]
You need to add `"skipLibCheck": true` to your tsconfig

**Comment by smelnikov** [comment]
> You need to add `"skipLibCheck": true` to your tsconfig

But why? Aren't library types supposed to be correct?

**Comment by 0xAsimetriq** [comment]
Code that is being checked is for optional dependencies that are never used / built for what you have set up in your package json. Since you don't have these (nor need) optional deps typecheck fail. In your case it is sufficient to confirm your own app types are correct as well as it also checks all used functions
