### ISSUE TITLE
bug in connecting walletconnect 

### ISSUE THREAD

**Issue by Basimkm369** [WalletConnect/web3modal#966]
### Link to minimal reproducible example

k

### Summary

i have use web3Modal for wallet connect and it give qr scanner and desktop wallets to connect and if only metamask its show first and we can connect to it but if there is coinbase wallet also while taking metamask it shows to install metamask extension

### List of related npm package versions

web3Modal

**Comment by 0xAsimetriq** [comment]
Missing minimal reproducible example
