### ISSUE TITLE
[bug] Phantom Wallet Extension is not detected. Web3Modal prompts to "Install Phantom"

### ISSUE THREAD

**Issue by oconnorjoseph** [WalletConnect/web3modal#970]
### Link to minimal reproducible example

https://www.blumint.com/

### Summary

Install the latest version of the Phantom Extension (v23.3.6 at the time of writing) into a v111 or later version of a Chromium. Open an application that uses the Web3Modal. When you select the Phantom wallet option inside of the Web3Modal, you will be prompted to "Install Phantom." It doesn't appear that the Phantom Wallet extension is being detected.

Our Web3Modal instance is customized as follows:
```
<Web3Modal
    projectId={
      process.env
        .NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID!
    }
    ethereumClient={ethereumClient}
    themeVariables={{
      '--w3m-z-index': '2000',
    }}
/>
```
given
```
const { provider } = configureChains(defaultChains, [
  w3mProvider({
    projectId: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID!,
  }),
]);

const wagmiClient = createClient({
  provider,
  autoConnect: true,
  connectors: w3mConnectors({
    projectId: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID!,
    version: 1,
    chains: defaultChains,
  }),
});

const ethereumClient = new EthereumClient(wagmiClient, defaultChains);
```

### List of related npm package versions

"wagmi": "0.12.2"
"@web3modal/ethereum": "2.2.2"
"@web3modal/react": "2.2.2"

**Comment by 0xAsimetriq** [comment]
Ty for the report, was able to partially reproduce i.e. it detected phantom, but didn't apply "Installed" label. Logic around this is changing in next release, just tested locally and everything looks ok, so will close this issue as it will soon be fixed.
