### ISSUE TITLE
[feature] Integrate web3modal with HTML app

### ISSUE THREAD

**Issue by levanigongadze** [WalletConnect/web3modal#973]
### What problem does this new feature solve?

Hello.
My project backend written in php and frontend in html, I use nginx server.
So, I want to integrate web3modal with html application.
I tried  Html and Standaolone methods from walletconnect documentation step by step but finally I get the error in my console.

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
`

### Describe the solution you'd like

Do you have any suggestion how can I integrate and use web3modal with html application?

**Comment by 0xAsimetriq** [comment]
Error is not related toweb3modal, looks like files served from your server have incompatible mime types. As for better html support we have this feature for building and deploying to cdn that will be addressed shortly after we deliver some missing modal features https://github.com/WalletConnect/web3modal/issues/678

**Comment by levanigongadze** [comment]
I solved this problem using Webpack.
