### ISSUE TITLE
[bug] using themeVariables in setTheme cause page to load infinitely

### ISSUE THREAD

**Issue by clrhc** [WalletConnect/web3modal#975]
### Link to minimal reproducible example

a

### Summary

themeVariables added to setTheme will make page load infinitely and not respond in nextjs react app

### List of related npm package versions

@web3modal/ethereum@2.2.2
├─ @web3modal/react@2.2.2
└─ wagmi@0.12.9

**Comment by 0xAsimetriq** [comment]
`setTheme` is used in our lab examples (the coral button) https://lab.web3modal.com/v2Base so issue is likely with specific implementation (some sort of loop you have in react that triggers re-renders when theme changes and then changes theme again perhaps?)

Unable to help out without reproduction.
