### ISSUE TITLE
Brave wallet is missing on mobile

### ISSUE THREAD

**Issue by vivanzar** [WalletConnect/web3modal#977]
### Link to minimal reproducible example

https://sandbox.ethereumico.io/wp-login.php?redirect_to=https%3A%2F%2Fsandbox.ethereumico.io

### Summary

I have a Brave wallet installed on my phone (Android 11), but when I call the WalletConnect dialog from the Brave browser and click the "select wallet" button in the list of available wallets, I see MetaMask and TrastWallet installed but Brave is missing.

### List of related npm package versions

    "@wagmi/core": "0.9.3",
    "@walletconnect/auth-client": "^2.0.3",
    "@web3modal/ethereum": "2.1.1",
    "@web3modal/html": "2.1.1",

**Comment by 0xAsimetriq** [comment]
There was addition in later versions of web3modal `2.2.2` that should add new "other" option on android. This is where you will see brave wallet, as it is not walletconnect one, but injected.

Let me know if you have further comments, closing this for now.
