### ISSUE TITLE
[bug] Dapps in SafePal not worked

### ISSUE THREAD

**Issue by phanthai12** [WalletConnect/web3modal#982]
### Link to minimal reproducible example

https://lab.web3modal.com/v2Standalone

### Summary

Case 1:
- I open the SafePal app, open the dapps and navigate to the link https://lab.web3modal.com/v2Standalone
- press "Connect Wallet" button, modal opens, I search for SafePal and click but the loading icon is spinning and not working.
![image](https://user-images.githubusercontent.com/5457016/232234846-3e93cefd-8fa6-42f7-a849-318ecfa573e9.png)

Case 2:
- I go back and go to https://lab.web3modal.com/v2Base, click "Connect Wallet" now there's a Trust Wallet icon saying "installed", I try to click on it, the connection is successful.
  + but actually this connection comes from safepal, not trust wallet. safepal's modal opens and I confirm them and log in.
  + I also tried clicking the safepal icon in this case, but I can't connect like the above case.
![image](https://user-images.githubusercontent.com/5457016/232234873-2103548d-bc64-47fa-8754-a0438f03058c.png)

Machine information:
iOS 16.3.1 (iphone 12)
Safepal 3.8.3

### List of related npm package versions

I using demo in lab.web3modal.com

**Comment by phanthai12** [comment]
@0xAsimetriq Some of my users on Safepal say that since I upgraded to version `2.3.0` they can no longer connect. Before that I used version `2.2.2`

**Comment by 0xAsimetriq** [comment]
@phanthai12 will test this out this week, but few ideas I have that you could relay to safepal are

1. For mobile linking, we switched to using deeplinks (safepalwallet://) over universal ones (https://...). As far as I can see in [cloud](https://cloud.walletconnect.com) safepal has their deeplink set, so question is, are they handling it properly? If not, we should ask them to delete it from their cloud project.

2. When you see TrustWallet as "installed" option it means safe pal is injecting `window.ethereum`, if trust data is shown, maybe they are setting extra flags which are not their own? i.e. `isMetaMask` or `isTrust`. Many wallets do this for better compatibility with dapps and its hard for us to determine which wallet they actually are.

3. The fact that you are sometimes seeing installed option and sometimes not leads me to think that safepal might not be injecting it right away (i.e. there is wait time) so we don't pick it up sometimes if it takes a bit longer.

Would be good to chat to them, but I'll also update you on what I can find once I deepdive into the issue as well 👍

**Comment by phanthai12** [comment]
@0xAsimetriq Some more information for you:
Trust with "installed" option not showing with https://lab.web3modal.com/v2Standalone
but it shows up with https://lab.web3modal.com/v2Base

**Comment by 0xAsimetriq** [comment]
Ah, that's actually expected. Standalone mode doesn't handle injected (extension) connections, it's a simple WalletConnect only experience. It shows up in v2Base as we use wagmi there for a "Managed" modal experience with a lot of extra features (but it needs wagmi).

**Comment by phanthai12** [comment]
Update version 2.3.7
I can click buttons of two apps, and it worked both
![image](https://user-images.githubusercontent.com/5457016/235043924-7559b1b1-30a8-43c5-8eb8-03e2ff0e20e1.png)

**Comment by 0xAsimetriq** [comment]
Awesome! Ty for the update.

**Comment by AdemKao** [comment]
> Awesome! Ty for the update.

Hi 0xAsimetriq, 
I tried  to connect SafePal in https://lab.web3modal.com/
on iPhone, but currently when SafePal been opened, nothing show on SafePal App.
I need to go back to the web, and click backup button. Then it show connect screen successfully, but when I click Agree, it did not redirect to the web.
But other wallets could redirect to web after click connect button(like MetaMask or TrustWallet).
Not sure it's web3modal issues or SafePal App's issue?

Machine information:
iOS 16.3.1 (iPhone SE)
Safepal 3.8.3
