### ISSUE TITLE
[feature] Creating a "What is a wallet?" page

### ISSUE THREAD

**Issue by svenvoskamp** [WalletConnect/web3modal#993]
### What problem does this new feature solve?

Last week, I spoke to some of my friends and family about web3 and wallets. Most of them don’t know much about it, so I showed them this page (https://ethereum.org/en/wallets/) which is the page we redirect to in web3modal if they don’t know what a wallet is. However, this didn't help them understand it better, and they also didn't get excited.

### Describe the solution you'd like

The idea is to create our own page that explains what a wallet is in a cool and creative way. I found some examples of how such an experience could look like:

https://silencio.es/
https://flecto.io/
https://en.manayerbamate.com/
https://kprverse.com/
https://www.deso.com/

The goal is to bring more excitement and joy in onboarding new users. I think this could contribute to "Towards Crypto's 1st Billion Users".

Questions we need to ask to get the best result: 

* How easy or difficult is it to use a wallet? What are the common usability issues that users face?
* What are some of the most common misconceptions about wallets that we need to address?
* How can we educate users about the importance of securing their wallet and taking appropriate security measures
* How can we explain the benefits of using a wallet in simple, easy-to-understand language?
* How can we help users understand the landscape for web3 and blockchain technology
* What resources can we provide to help users stay up-to-date with the evolving environment

**Comment by 0xAsimetriq** [comment]
Yep, this is definitely on our radar with revamp of "I don't have a wallet" flow that we are finalising. Might take some time, but something like this will be added in eventually 👍 We'll colab on this with you as well.

**Comment by 0xAsimetriq** [comment]
Implemented in v3
