### ISSUE TITLE
[feature] Expose selected chain

### ISSUE THREAD

**Issue by timefordroids** [WalletConnect/web3modal#997]
### What problem does this new feature solve?

Currently, when a user selects a different network in the network selector without being connected to their wallet, there is no way to determine which network they have selected. This can lead to a situation where the network in the network selector is Ethereum, but data is showing for BSC (Binance Smart Chain).

### Describe the solution you'd like

To solve this issue, I propose exposing the selectedChain property. This will enable developers to determine the currently selected network even when the wallet is not connected, allowing them to handle network-specific data and interactions more effectively.

I've created a PR but not sure the solution is elegant
https://github.com/WalletConnect/web3modal/pull/961

**Comment by 0xAsimetriq** [comment]
Closing this one in favor of #871 which will expose this information
